### ISSUE TITLE
Add support for Visual Studio 2015

### ISSUE THREAD

**Issue by kosinsky** [Microsoft/PowerBI-visuals#1]
Add support for Visual Studio 2015 that has TypeScript 1.5 be default

**Comment by spatney** [comment]
Makes sense, we'll add it to our backlog. Thanks!

**Comment by pedramrezaei** [comment]
VS 2015 is not fully released yet. We will add support for it as soon as it is released.

**Comment by sgrebnov** [comment]
as per quick test everything (build, playground app, tests) works fine if I use VS2015 RC Community to open solution file (the following still must be updated: docs and *.cmd files as they rely to specific VS version when doing `call "%VS120COMNTOOLS%vsvars32.bat"`)

**Comment by pedramrezaei** [comment]
Hey, I have the vs 2015 rtm build. Don't use rc

Sent from my iPhone

On Jul 16, 2015, at 6:36 AM, Sergey Grebnov <notifications@github.com<mailto:notifications@github.com>> wrote:


as per quick test everything (build, playground app, tests) works fine if I use VS2015 RC Community to open solution file (the following still must be updated: docs and *.cmd files as they rely to specific VS version when doing call "%VS120COMNTOOLS%vsvars32.bat")

-

**Comment by kosinsky** [comment]
I'm on RTM. I install TypeScript 1.4 for VS 2013. After that npm run build succeeded. 

However, when I'm trying samples folder to run in VS 2015, I'm getting:

Severity	Code	Description	Project	File	Line
Your project file uses a different version of the TypeScript compiler and tools than is currently installed on this machine.  No compiler was found at C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\1.4\tsc.exe.  You may be able to fix this problem by changing the <TypeScriptToolsVersion> element in your project file.

**Comment by spatney** [comment]
Support for VS 2015 has been added. Refer to [v0.2.0](https://github.com/Microsoft/PowerBI-visuals/releases/tag/v0.2.0) for details. Please note, once you sync, you will be unable to use VS 2013 for development. Thanks.
