### ISSUE TITLE
gulp test - errors

### ISSUE THREAD

**Issue by AndyCross** [Microsoft/PowerBI-visuals#10]
I did an update of the repo this afternoon and now experience many errors. 

**1984 specs, 1116 failures**

*Example*
TypeError: undefined is not a constructor (evaluating 'expect($('.columnChart')).toBeInDOM()')

**Comment by spatney** [comment]
are you missing jasmine JQuery? Refer to this instruction in the ReadMe.

"Copy the jasmine-jquery.js Jasmine Extension Library file from GitHub into the following folder on your local machine "[PowerBIVisuals folder]\src\Clients\Externals\ThirdPartyIP\JasmineJQuery\"  "
