### ISSUE TITLE
Is it possible to group values by multiple fields in DataViewMapping.categorical.values?

### ISSUE THREAD

**Issue by xiecong** [Microsoft/PowerBI-visuals#101]
For example, in the following dataview mapping, the values are grouped by 'series'.
<img width="595" alt="screen shot 2015-09-19 at 4 12 48 pm" src="https://cloud.githubusercontent.com/assets/2120510/9977979/8ccb42ae-5ee9-11e5-8665-ac1f1bf7ae0b.png">

Can I add another fields, such as 'type', so the values are grouped by 'series' and 'type' together?
Thanks

**Comment by spatney** [comment]
No, what are you trying to achieve? If you tell us your scenario instead, maybe we could figure out an alternative.
