### ISSUE TITLE
Word Cloud is hanging the browser

### ISSUE THREAD

**Issue by rhuanbarreto** [microsoft/PowerBI-visuals#102]
Have a look at [this link](http://sys.petromonitor.com.br/#/transpetro/servicos). All browsers are hanging, including Edge.

**Comment by AviSander** [comment]
Hi Rhuan, 
   We're investigating this issue and will update. Please be aware that we're aware that the WordCloud visual has performance issues when data gets big. 
thx, Avi

**Comment by ignatvilesov** [comment]
@rhuanbarreto Thanks for your feedback.
We’ve already fixed the performance problem of WordCloud. We’re going to publish it to the Power BI DEV environment today.
The new version will be available in PROD in two weeks.
