### ISSUE TITLE
Not able to run StreamGraph example in Dev Tools preview of PowerBI

### ISSUE THREAD

**Issue by sourav2090** [Microsoft/PowerBI-visuals#102]
Hi All,

I followed the steps provided in tutorial video. 

Used the code given in 
https://github.com/Microsoft/PowerBI-visuals/blob/master/src/Clients/Visuals/visuals/samples/streamGraph.ts

But on clicking Compile+Run, the plugin section is getting populated in the end and it says 
"Cannot find name StreamGraph" . When I replaced it with powerbi.visuals.samples.StreamGraph, the error is not showing but i am not able to see the graph in the data preview. 

module powerbi.visuals.plugins {
	export var _StreamGraph: IVisualPlugin = {
		name: '_StreamGraph',
		class: '_StreamGraph',
		capabilities: StreamGraph.capabilities,
		create: () => new StreamGraph()
	};

![image](https://cloud.githubusercontent.com/assets/14358184/9979186/07e9be9c-5f7c-11e5-9961-900d01e16b01.png)

Could you please let me know where I am going wrong.

Kind Regards,

Sourav

**Comment by spatney** [comment]
Remove the samples word from the module name. Should be module powerbi.visuals vs powerbi.visuals.samples

**Comment by sourav2090** [comment]
Thanks a lot Sachin. That error is gone. But to run this do I need to set up any additional configuration. I am going for Compile+Run, but nothing is getting displayed in the data preview.

![image](https://cloud.githubusercontent.com/assets/14358184/9979278/346ea03a-5f82-11e5-9eda-0b96a830def9.png)

**Comment by sourav2090** [comment]
removed /// <reference path="../../_references.ts"/> and it is working correctly.

**Comment by MuhilaRangaraj** [comment]
![image](https://cloud.githubusercontent.com/assets/15796190/11088583/736af114-8889-11e5-8705-c4e2403e3cf5.png)

Hi,

I followed the steps in the video..https://channel9.msdn.com/Blogs/Seth-Juarez/Creating-a-Custom-PowerBI-Visualization-from-Scratch-with-Sachin-Patney

I am just trying the very basic sample "Hey 0" but I am not getting it...

Could anyone please say what I actually missed??

Thanks,
Muhi

**Comment by NicolaeGP** [comment]
This is the code I used which is basically the same and it works for me. Maybe you can try formatting the code, see if that helps. If not, copy paste this and it should work.

module powerbi.visuals {
    import ClassAndSelector = jsCommon.CssConstants.ClassAndSelector;

    export class StreamGraph implements IVisual {

        public static capabilities: VisualCapabilities = {

        }

        private static VisualClassName = 'streamGraph'
        private static Layer: ClassAndSelector = {
            class: 'layer',
            selector: '.layer'
        };

        private element: JQuery;
        private svg: D3.Selection;
        private axis: D3.Selection;
        private colors: IDataColorPalette;
        private selectionManager: utility.SelectionManager;
        private legend: ILegend;

        private static converter(dataView: DataView, colors: IDataColorPalette) {

        }
        public init(options: VisualInitOptions): void {
            this.element = options.element;
            this.element.text('Hey 0').css('font-size', '40px');
        }
    }
}

**Comment by pnarendrai1** [comment]
Can we show custom images along with charts while creating visualizations

**Comment by MuhilaRangaraj** [comment]
Hi Nicolae,

Thanks. It worked after Formatting the code.:)

**Comment by MuhilaRangaraj** [comment]
Hi,

I got the code for Map.ts from PowerBIVisuals GitHub. https://github.com/Microsoft/PowerBI-visuals/blob/master/src/Clients/Visuals/visuals/map.ts 

But, its not working and showing Compilation Errors. We tried clearing it but still there are so many that we couldn't figure out what the error exactly is...

![image](https://cloud.githubusercontent.com/assets/15796190/11924550/78b128d2-a7d8-11e5-826b-4ddd678ebae2.png)

Can anyone please say where I need to make the changes in the code to get the result for Map.ts ??

Do anyone have the working code of Map.ts in PowerBI Devtools??, if so please update it 

As well, to add any new coding or features to the existing Map.ts file is feasible or not ??

Thanks,
Muhi

**Comment by riksof-asim** [comment]
@spatney I need to add some changes in line chart. Can you tell me from where I will get power bi line chart code.
