### ISSUE TITLE
Image refererence in pbviz file

### ISSUE THREAD

**Issue by berida10** [microsoft/PowerBI-visuals#104]
Hi, I need to find out the best way provide images in Power BI custom visuals to generate textures on for instance a 3d model. Is it possible to package these images up within the custom visual? Currently the pbiviz.json file has an “assets” reference where the icon.png is stored.  Can I do the same with other images and reference this in the code?  If so, I need to know how I reference this. Alternatively a URL reference approach may work.

**Comment by srzmldl** [comment]
I want to do the same thing but can not found any related document or example.

**Comment by Knagis** [comment]
See https://github.com/Microsoft/PowerBI-visuals/issues/41

To my understanding, currently there are two options:
1. Deploy the images on a CDN server and load the images from there.
2. Embed the images as data-uri strings in your own JavaScript code or CSS files.

**Comment by CleberDSantos** [comment]
We solved concatenating our css in just one **style/visual.less** file and converting the images to base64.

https://www.base64-image.de/

**Comment by ignatvilesov** [comment]
Images might be embedded into CSS by using [data-uri](http://lesscss.org/functions/#misc-functions-data-uri) function of LESS CSS.

**Comment by MikeWise2718** [comment]
Hmm. So what is that assets directory for anyway?

**Comment by ignatvilesov** [comment]
Assets directory is for an icon. This is the main purpose.
Anyway, you can store any files in this directory but they will not be included in pbiviz package automatically.

**Comment by MikeWise2718** [comment]
Well, I guess I can hard-code an image (I am working in R and it is not too hard), but seems ugly and rather bloated. I tried to download it from an external server with RCurl, but it wouldn't connect. I suppose they won't let me out of the sandbox, right?

**Comment by grajamanickam** [comment]
@ignatvilesov can you please help with the documentation or any example of embedding image/icon on power bi custom visual

**Comment by ignatvilesov** [comment]
@uve Could you please help @grajamanickam ?

**Comment by zBritva** [comment]
@grajamanickam tools uses base64-inline-loader of webpack.

You can import images as base64 string:

```typescript
const icon = require("../assets/icon.png");
```

or specify another loader for the file:

https://github.com/microsoft/PowerBI-visuals-tools/issues/303#issuecomment-601401473

**Comment by grajamanickam** [comment]
@ignatvilesov, @zBritva I really appreciate your help.  Sorry iam a newbie to the custom visual development.  Do you have a sample .ts code?

**Comment by zBritva** [comment]
@grajamanickam you find here: https://github.com/zBritva/powerbi-visuals-webpack-loader-test/blob/master/src/visual.ts#L41

But in the sample, csv file and custom loader is used.

**Comment by grajamanickam** [comment]
thanks @zBritva !
I just ended up using the below code

I ended up using the below code
this.svg
            .append("svg:image")
            .attr("xlink:href","https://.../512.png")
            .attr("x", "50%")
            .attr("y", "30%")
            .attr("width", "130")
            .attr("height", "130");
