### ISSUE TITLE
Changes not showing up in the Visualizer

### ISSUE THREAD

**Issue by ClarkDan** [Microsoft/PowerBI-visuals#104]
When I make changes and view them through the playground web page they are not showing up. Is there caching I need to turn off?
Dan

**Comment by ebunt** [comment]
Same here.  Added my visual to the playground and added my visual to to references, plugins, and capabilities and not showing in the playground.

**Comment by uve** [comment]
Did you try to call createPlugin function for your custom visual here?https://github.com/Microsoft/PowerBI-visuals/blob/master/src/Clients/Visuals/services/visualPluginService.ts#L257

**Comment by spatney** [comment]
You shouldn't even need to do that. Eddie, what you did sounds correct. You might be missing a fix we recently did. be sure your code includes this [commit](https://github.com/Microsoft/PowerBI-visuals/commit/c26db5747d18411cf16096fbbc1694d6ac6285e7) if not, you could either cherry pick it or sync to latest.

**Comment by ebunt** [comment]
@spatney that worked great, thank you.
