### ISSUE TITLE
Can't contact visual server

### ISSUE THREAD

**Issue by twastvedt** [Microsoft/PowerBI-visuals#107]
1. Successfully created new pbiviz project
2. Successfully installed certificate (i.e. it closed without error. Is there a way to check that the certificate is working other than instantiating the Developer Visual inside Power BI?
3. Restarted computer.
4. Successfully built and ran visual with `pbiviz start`.
5. Instantiated Developer Visual, and get "Can't contact visual server". Tried with Firefox, Chrome, and IE.
6. In the Network tab of Developer Tools there's an OPTIONS request to `https://localhost:8080/assets/status` which never gets a response.

What can I try next?

**Comment by r1sc** [comment]
Same issue here with Firefox. Works for both Edge and Chrome.

**Comment by uve** [comment]
Here is a workaround for Firefox:
1. Open https://localhost:8080/assets/status in Firefox manually.
2. You will get an error message: Your connection is not secure.
3. Click advanced button.
4. Click Add exception button and add this url to exception list.
Try to refresh the page with your report, visual should be loaded correctly.

**Comment by Leo450** [comment]
Working, thanks a lot !
