### ISSUE TITLE
https://app.powerbi.com/devtools - the default visual's Dataset Details link is broken

### ISSUE THREAD

**Issue by AviPi** [microsoft/PowerBI-visuals#109]
Clicking the link “Dataset Details” redirects to a 404 page on github @ https://github.com/Microsoft/PowerBI-visuals/blob/master/src/Clients/PowerBIVisualsPlayground/sampleDataViews/SalesByCountryData.ts

**Comment by uve** [comment]
the old PowerBIVisualsPlayground project is deprecated
