### ISSUE TITLE
Dev tools API not up to date??

### ISSUE THREAD

**Issue by TonyGaul** [Microsoft/PowerBI-visuals#110]
The following do not compile for me in the Dev Tools, but do in VS.  Error example: Cannot find name 'IInteractiveVisual'

IInteractiveVisual
VisualInteractivityFactory
InteractivityVisitor

These are used in the breakdownTree visual https://github.com/fredrikheden/PowerBI-visuals

**Comment by spatney** [comment]
Yes, correct. This is intentional. These APIs are private, and will not be supported (and could possibly be deprecated). Instead you should use the SelectionManager class to perform selection operations.

**Comment by TonyGaul** [comment]
Hi, thanks for the update.  I am still learning about all this.

But how do I get this visual to work / compile in the Dev Tools:
https://github.com/fredrikheden/PowerBI-visuals/blob/master/src/Clients/Visuals/visuals/breakdownTree.ts

Are you saying that I need to modify the original code to use the SelectionManager class?  I've generally been copying the code from the .ts file and pasting into the Dev Tools.  What is the correct way to get this to work?

**Comment by spatney** [comment]
you can just paste the code + css in and it should just work.. even though it gives you error lines. You won't see it in the preview window but since those APIs exist in the actual service, when you switch to the report you will be able to use the visual.

**Comment by spatney** [comment]
Though yes. the "right way" would be to use the selection manager class, since these APIs can change without notice.

**Comment by TonyGaul** [comment]
Thanks again!
