### ISSUE TITLE
Understanding the dataViewMappings property

### ISSUE THREAD

**Issue by mgam1** [Microsoft/PowerBI-visuals#111]
Hello, 

I've read and watched the explanations in the wiki pages and video tutorial (https://channel9.msdn.com/Blogs/Seth-Juarez/Creating-a-Custom-PowerBI-Visualization-from-Scratch-with-Sachin-Patney) respectively about dataViewMappings. They gave me an understanding of the general purpose of this property but not the specifics so that I can make use of it. 

Is anyone able to provide a more detailed explanation of the DataViewMappings property of the VisualCapabilities object. So that I may understand why I'm experiencing the missing property described below in my Data View object. 

Issue: 
I've created a simple line chart which works with the sample data as shown below:
![image](https://cloud.githubusercontent.com/assets/13663012/10102365/ed4cf432-6395-11e5-9428-45a60f91fddb.png)

However it does not work inside Power BI. This is because of a missing property in the dataView object for this visualisation. I am using the categorical canonical DataView structure. The missing property is the values property circle in the below image: 
![image](https://cloud.githubusercontent.com/assets/13663012/10102683/b90edbfc-6397-11e5-8b84-57e08d598d45.png) 
![image](https://cloud.githubusercontent.com/assets/13663012/10102733/fd9690bc-6397-11e5-85ca-287cd3377b68.png)

The two fields I defined in my Data roles object were:
1. Category - Grouping (discrete) 
2. Values - Measure (continuous)  

In my dataViewMappings property I defined values like so: 
values: {
                      for: { in: 'Values' },
                      dataReductionAlgorithm: { bottom: {} }
                },
I thought this should iterate over whatever is in the Values field bucket? Any suggestions on why I'm missing this values property is appreciated. 

In addition, may you please provide an explanation on the following specific area: 
1. What does the condition property do, and how is it done? 
2.What does "max:0" for a given property  mean?

Thanks

**Comment by spatney** [comment]
could you paste both dataroles and mappings? I think you are missing on how to bind categories with values. The reason, this works in the playground is because there we provide pre-generated datasets that don't look at these bindings.

**Comment by spatney** [comment]
i suspect you need something like. 

```typescript
            dataRoles: [
                {
                    name: 'Category',
                    kind: powerbi.VisualDataRoleKind.Grouping,
                },
                {
                    name: 'Y',
                    kind: powerbi.VisualDataRoleKind.Measure,
                },
            ],
            dataViewMappings: [{
                categories: {
                    for: { in: 'Category' },
                    dataReductionAlgorithm: { top: {} }
                },
                values: {
                    select: [{ bind: { to: 'Y' } }]
                },
            }],
```

**Comment by mgam1** [comment]
Hi Spantney, 

Here's the code, I was able to resolve the issue myself soon after I posted the request. It was simply a missing bracket in my data mapping. However I am still unsure on the purpose of the conditions object and that's why I've left it blanked in my code below. Also I was wondering if you could tell me how select: [{ bind: { to: 'Values' } }] works. 

![image](https://cloud.githubusercontent.com/assets/13663012/10160334/b3b77ce0-6694-11e5-8e21-522a42cc77be.png)

Thanks for the help :)

**Comment by mgam1** [comment]
Thanks for replying Sachin,

I solved my issue shortly after I posted my question, it was simply a
missing bracket in my dataViewMappings object. However I've noticed
you use select:
[{ bind: { to: 'Y'* } }] *instead of what I use *for*: { in: 'Y'* }*. Could
you explain how select-bind works? and what are its advantages over the
for-in?

Kind regards,
