### ISSUE TITLE
Facing issue when trying to add Typings to my custom visual

### ISSUE THREAD

**Issue by sau752** [Microsoft/PowerBI-visuals#113]
I ran `npm install typings -g` to successfully install Typings CLI

After this when I am  trying to add Typings to my custom visual using below command I am facing issue
`typings install --save --global dt~d3`

 Below error pops up, I need help on how to fix the same

> typings ERR! message Attempted to compile "d3" as a global module, but it looks like an external module. You'll need to remove the global option to continue.
> typings ERR!
> typings ERR! cwd C:\Users\sau75
> typings ERR! system Windows_NT 10.0.14393
> typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sau75\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "--save" "--global" "dt~d3"
> typings ERR! node -v v6.9.2
> typings ERR! typings -v 2.1.0
> typings ERR!
> typings ERR! If you need help, you may report this error at:
> typings ERR!   <https://github.com/typings/typings/issues>

![image](https://cloud.githubusercontent.com/assets/5901255/21485211/568ba842-cbc5-11e6-9da8-74b2a29ef0f6.png)

**Comment by ignatvilesov** [comment]
@sau752 Could you please try to use the following command: ```typings install --save --global dt~d3#0.0.0+20160907005744```.  This command won't install the latest version of the types from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by sau752** [comment]
Thanks!

**Comment by djpirra** [comment]
Is this something that we should find ourselves? How about improving documentation? After all it is not working like its described :)
