### ISSUE TITLE
Required documentation for Legend Builder

### ISSUE THREAD

**Issue by sau752** [Microsoft/PowerBI-visuals#114]
On page [Roadmap - Visuals API ](https://github.com/Microsoft/PowerBI-visuals/tree/master/Roadmap) for Version 1.3 API it says that Legend Builder control has been added. But when I navigate to the [link](https://github.com/Microsoft/PowerBI-visuals/issues/35) provided I could not find any documentation or information on how to implement the same. I need documentation for Legend implementation or if documentation is not present can a detailed documentation be created and shared so that it is helpful. (Attached screenshot of Roadmap page below)

![screenshot_2016-12-28-00-43-24_com android chrome_1482866816982](https://cloud.githubusercontent.com/assets/5901255/21506757/a81d0736-cc98-11e6-88bf-8c6ea2b9ae37.jpg)

**Comment by nicksav** [comment]
If you look at the helper:
https://github.com/Microsoft/powerbi-visuals-utils-chartutils/blob/master/src/legend/legendInterfaces.ts

You can check what you need to be able to use with 
    export interface ILegend {
        getMargins(): IViewport;

        isVisible(): boolean;
        changeOrientation(orientation: LegendPosition): void;
        getOrientation(): LegendPosition;
        drawLegend(data: LegendData, viewport: IViewport);
        /**
         * Reset the legend by clearing it
         */
        reset(): void;
    }


Havent played with it yet, but will try this week.

**Comment by danieleperilli** [comment]
The Legend Builder library doesn't work for me. I've just tried (and spent time to implement it) just to discover that the drawLegend() function doesn't render anything :(
Can Power BI team provide some examples?

**Comment by nicksav** [comment]
Check Microsoft GitHub for already built visuals. Everything is there.

**Comment by danieleperilli** [comment]
Thanks @nicksav. You're right, it was my fault. I ignored that Microsoft has migrated those components to the new API.
