### ISSUE TITLE
where to get the source code in new dev tool for the built-in visuals in Power BI desktop

### ISSUE THREAD

**Issue by zhll2046** [Microsoft/PowerBI-visuals#118]
Any idea?

**Comment by Mike-Honey** [comment]
I'm also stalled on multiple projects until this is updated.

**Comment by zhll2046** [comment]
any update？

**Comment by rneven** [comment]
I have heard that Microsoft has retracted the open source code for their standard visuals, I'm curious if this is true.

**Comment by ignatvilesov** [comment]
Source code of build-in Power BI visuals isn't open anymore. we don't have any plans to open source it again.

**Comment by zhll2046** [comment]
@ignatvilesov 
Is there any official declaration?

**Comment by vsymguysung** [comment]
So could I say that there is no way to extend the built-in visuals officially ?  Could anybody confirm this ?

**Comment by AviSander** [comment]
yes - correct. This is not supported any more.
