### ISSUE TITLE
Need more info on how InteractivityService works with selection

### ISSUE THREAD

**Issue by bigac** [Microsoft/PowerBI-visuals#120]
While building new IVisual, I'm struggling to understand exactly how InteractivityService works with selection, especially on how the selection of one IVisual would drive the update of one or more IVisuals.  The playground project uses only the DefaultVisualHostService and it doesn't show how IVisualHostServices.onSelect() is being handled.

I have been studying how Slicer works but I can only find WebInteractivityService.sendSelectToHost() being called but I can't figure out how the host service is supposed to handle the select event and drive other related IVisuals to be updated.

Are there E2E example of how one IVisual's selection interacts with other IVisuals?  Any more details doc on this topic?

**Comment by deldersveld** [comment]
Use Selection Manager instead of Interactivity Service. There may be compatibility issues with Interactivity Service. Many of the newer sample visuals showcase how the Selection Manager can be used.

**Comment by UncleDolan** [comment]
Hi @deldersveld,

I am also having questions about how selection works in the framework, and I am using SelectionManager. My confusion is mainly on "onSelect" of DefaultVisualHostServices and how the selection of one IVisual can affect another.

I tried to figure out how DefaultVisualHostServices handles the selection by walking through the code of "AreaRangeChart" in the playground app. However, at the very end, SelectionManager will call "onSelect" of DefaultVisualHostServices, which seems to be an empty function:
DefaultVisualHostServices.prototype.onSelect = function () { };

According to the "Hello IVisual" page, it seems like it is the host that takes care of notifying other IVisuals when a selection is made to one of them. 

So could you please shed some light on both DefaultVisualHostServices and how the selection of one IVisual can affect another.


Thank you.

**Comment by spatney** [comment]
@UncleDolan, answered it here #139
