### ISSUE TITLE
Source code for built-in visuals (like Donut)

### ISSUE THREAD

**Issue by kraftwer1** [Microsoft/PowerBI-visuals#120]
What about the source code of the built-in visuals - that used to be on the [PowerBI-visuals-core](https://github.com/Microsoft/PowerBI-visuals-core) repo?

Are the current versions no longer open source?

**Comment by Mike-Honey** [comment]
I'm also stalled on multiple projects until this is updated.

**Comment by mukuldroid3** [comment]
@kraftwer1  The current versions are no longer open source.

**Comment by ignatvilesov** [comment]
Power BI native visuals are no longer open source.

**Comment by kraftwer1** [comment]
Thanks for the official reply.
