### ISSUE TITLE
Click and drag data selection 

### ISSUE THREAD

**Issue by gabs17** [microsoft/PowerBI-visuals#122]
I'm building a new visual using typescript.
And I need to use click and drag data selection that exists on the Windows desktop for example.
 
 

 
The visual I'm building is a matrix , and I need this click and drag function to select the data that will be highlighted.
 
Any idea how to implement this in the visual I'm building?

**Comment by gabs17** [comment]
![example](https://cloud.githubusercontent.com/assets/25078593/21891567/6da8e560-d8ba-11e6-902c-acb5b647dac6.png)

**Comment by helen508light** [comment]
@gabs17
You can use this visual as example
https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381703?src=office&tab=Reviews
https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381825?src=office&tab=Overview

There are source code https://github.com/akvelon/PowerBI-Scatter-Chart

Logic related to drag and drop is here src/selectionUtil.ts
