### ISSUE TITLE
Scale factor for visual or fix tooltip service

### ISSUE THREAD

**Issue by Futhark** [Microsoft/PowerBI-visuals#128]
There is a need to pass information about current scale of the sandbox to the visual, probably as another property in update descriptor or fix tooltip service.

This is needed because tooltip service accepts tooltip coordinates in host scale (1.0) and most of the time our visuals are scaled on the reports. Since visuals are sandboxed, there is no way to find an actual scale through css/js tricks. 

I've noticed that some custom visual vendors like Esri just implements their own tooltip system to overcome that issue, but of course custom tooltips are always cut to visual sandbox viewport.

**Comment by oleg-vasilyev** [comment]
I confirm that in 1.4.0 version there is a bug.
![image](https://cloud.githubusercontent.com/assets/24278912/22729482/fc0e3a14-edf3-11e6-92ef-be2e2ae23050.png)
![image](https://cloud.githubusercontent.com/assets/24278912/22729556/50aeccb4-edf4-11e6-97b1-9f56734275b0.png)
When Microsoft plan to fix it?

**Comment by Ozymandy** [comment]
Yes, I ran into exactly the same bug

**Comment by AviSander** [comment]
The scale issue has been fixed for tooltips. thx.
