### ISSUE TITLE
shiftKey property is not present in D3Event

### ISSUE THREAD

**Issue by Kasianand** [Microsoft/PowerBI-visuals#130]
In D3Event interface(src\Clients\Typedefs\d3\d3.d.ts), shiftKey property is not present. 
To make continuous selection of items in a visual, we need to hold shift key and click the items. As the shiftKey property is not present, we are unable to determine shiftKey is pressed or not.

In the orginal d3.js event object, shiftKey is present but we couldn't use it as there is compilation error in typescript.

Are there any specific reasons, why this property is not included?

Pls let me know if there any other ways to override the D3Event in the visual.

**Comment by spatney** [comment]
they typedefs file is out of date, you should still be able to use it by casting to <any>
