### ISSUE TITLE
You are probably wasting your time posting here - no-one from Microsoft is listening

### ISSUE THREAD

**Issue by Mike-Honey** [Microsoft/PowerBI-visuals#131]
It seems no-one from Microsoft is paying any attention to the Issues for this repository - they have not made any comments or responses for months.  The most recent comment I could find was on Dec 2, 2016.

I'd be happy to be proved wrong - the lack of support/involvement by Microsoft in this area is a huge missed opportunity to improve their product, and thereby improve their revenue.

**Comment by Tameshiwari** [comment]
Indeed I'm afraid you may be totally right on that issue. I wouldn't be surprised to hear some former team headers are no longer in charge and may even have been shifted on another project a while ago - which could explain why they haven't given any sign of life...I may be wrong though lack of support and responses raised a bit of skepticism. Hellooooo anybody home?
