### ISSUE TITLE
visual map in playground could not display

### ISSUE THREAD

**Issue by hytang-nancy** [Microsoft/PowerBI-visuals#134]
I update code in ubuntu and use "gulp build" to run playground. all visuals work except map. console print following errors:
Uncaught TypeError: Cannot read property 'MaxAllowedLongitude' of undefinedo.resetBounds @ powerbi-visuals.js:23o.init @ powerbi-visuals.js:23t.initVisual @ PowerBIVisualsPlayground.js:3t.createVisualElement @ PowerBIVisualsPlayground.js:3$.fn.visual @ PowerBIVisualsPlayground.js:3t.createVisualPlugin @ PowerBIVisualsPlayground.js:3t.onVisualTypeSelection @ PowerBIVisualsPlayground.js:3(anonymous function) @ PowerBIVisualsPlayground.js:3n.event.dispatch @ externals.min.js:3r.handle @ externals.min.js:3

**Comment by joostshao** [comment]
same to me
