### ISSUE TITLE
When I debugged, cannot find the sampleVisual.ts

### ISSUE THREAD

**Issue by pingshuibing** [Microsoft/PowerBI-visuals#136]
when I debugged, I cannot find the sampleVisual.ts showing as example. 

I only found the file:
src/Clients
--Visual/obj
----Visual.js

It is mini file of all visual in JavaScript rather than original TypeScript.
Where I can find the file and debug?

Regards,
Alex

**Comment by spatney** [comment]
@dmitriy-tarasov, could you look into this?  We should have source maps that allow you to debug into TS.

**Comment by sgrebnov** [comment]
friendly ping @v-kazaki as Dmitry is on vacation and I know that Kamil planned to refactor this logic so should be aware of this..

**Comment by ignatvilesov** [comment]
@pingshuibing This problem is fixed in #441
