### ISSUE TITLE
Maximum Call Stack Exceeded

### ISSUE THREAD

**Issue by peterk123** [Microsoft/PowerBI-visuals#136]
We are receiving attached error when trying to build the provided bar chart demo. We have followed every step on multiple computers. We have also tried changing to older versions.
![callstackerror](https://cloud.githubusercontent.com/assets/25915044/23146846/420ce5c0-f78f-11e6-93a5-143f6290fa0b.png)

**Comment by rneven** [comment]
Same problem here!

![image](https://cloud.githubusercontent.com/assets/24790371/23299090/78f5edfe-fa80-11e6-998f-57d135907606.png)

**Comment by ignatvilesov** [comment]
Do you have any ```.js``` (JavaScript) files in your ```tsconfig.json```? If so, please move them to the ```externalJS``` property of the ```pbiviz.json```. Please take a look at [this](https://github.com/Microsoft/PowerBI-visuals-WordCloud/blob/master/pbiviz.json#L20) example.

**Comment by rneven** [comment]
Thanks, that solved it!

**Comment by joergplewe** [comment]
see also: https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/issues/14

**Comment by AviSander** [comment]
thx for the inpu. fixed in https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/pull/18/commits
