### ISSUE TITLE
Got error listen EADDRNOTAVAIL without visual studio

### ISSUE THREAD

**Issue by Gabriel0402** [Microsoft/PowerBI-visuals#141]
I'm running the playground without visual studio, and I set up gulp run:playground but get the error: listen EADDRNOTAVAIL fe80::1:3000. And I change the port name in gulp.js to some other port still didn't work. Is there step I'm missing? Thanks.

**Comment by sgrebnov** [comment]
Just tested and don't see such problem - @Gabriel0402 this looks like to be workspace issue, please re-open if you otherwise; also try running `gulp build` before `gulp run:playground` as it it only runs playground w/o build

**Comment by Gabriel0402** [comment]
@sgrebnov Sorry for the spam. It turned out that in the hosts file the localhost was direct to some other ip. After changing back to 127.0.0.1, everything works perfectly. Thanks
