### ISSUE TITLE
How to localize capabilities

### ISSUE THREAD

**Issue by BerndtHamboeck** [microsoft/PowerBI-visuals#144]
If I try to add  "displayNameKey": "dataRoleCategory" to my capabilities.json I get the error:  JSON  capabilities.json :  instance.dataRoles[0] additionalProperty "displayNameKey" exists in instance when not allowed. I am using API 1.4, did anyone get this up and running?

**Comment by nikhilkabbin** [comment]
I am getting same error as @BerndtHamboeck. i am using API 1.5.0

**Comment by AviSander** [comment]
Hello  - this is supported from API 1.6. Please try and update to 1.6.
thx

**Comment by nikhilkabbin** [comment]
@AviSander Thanks that helped to fix the error, But I am still unable to see locale strings in capability panel,  I followed this [example](https://github.com/Microsoft/PowerBI-visuals/blob/master/Visual/Locale.md)

**Comment by nikhilkabbin** [comment]
@AviSander This is working only after packing but not in debug mode

**Comment by AviSander** [comment]
Hi - Are you trying this in PBI desktop or in PBI service (browser)? So 1.6 API will only reach the PBI Desktop in the April release (next week). Until then please use the web client.
We apologize for the confusion.

**Comment by nikhilkabbin** [comment]
@AviSander I am using PBI service and until I package my visual I am unable to see localizations.

**Comment by AviSander** [comment]
yes - known issue. Doesn't work for the debug visual.
