### ISSUE TITLE
How to add my own visual to the playground?

### ISSUE THREAD

**Issue by NicolaeGP** [Microsoft/PowerBI-visuals#145]
I'm trying to learn how to create a new visual for power bi. I know I need a visualName.ts in visuals and visualNameCapabilities.ts in the capabilities folder.
I did not manage to understand the whole architecture so I'm having problems with adding it to the playground.
Could you explain, a tutorial maybe, on how to add your custom visual to the playground and how to get it into a pbiviz file afterwards for use in PowerBI desktop?

**Comment by yapaxi** [comment]
As far as I understand, you should add your visual to "src\Clients\Visuals\plugins.ts" as plugin, then this plugin must be added to "src\Clients\Visuals\services\visualPluginService.ts" and that's all.

Easiest way to make a simple custom visualization it to copy-paste any from "src\Clients\Visuals\visuals\samples\*.ts", because they are not splitted between many ts files.

**Comment by NicolaeGP** [comment]
I didn't know about visualPluginService and could not understand why the table and some other visuals weren't among the visuals in the playground, but it works now so Thank you!
I've also learned that, at the moment the project does not export the visuals as pbiviz files but this improvement it is in the backlog.

**Comment by yapaxi** [comment]
> I've also learned that, at the moment the project does not export the visuals as pbiviz files but this improvement it is in the backlog.

You can use https://app.powerbi.com/devTools to generate pbiviz. Just copy paste your code there with minor changes. Actually I use VS2015 only for complex debugging. DevTools are much faster (instant vs 10 sec. compilation) and easier to use.

**Comment by NicolaeGP** [comment]
I'm trying to use it but I'm also getting inspired from the git project and sometimes things don't match. I'm trying to modify the table so I can allow the user to select the background for the header but I can't get it to work in the dev tool.
I copy-pasted the code from visual studio from the table and table.capabilities, made some modifications to make it work in the dev tool but when I try to use it in power bi, nothing is displayed.

module powerbi.visuals {

    import DataViewVisualTable = powerbi.visuals.DataViewVisualTable;
    import DataViewVisualTableRow = powerbi.visuals.DataViewVisualTableRow;
    import TableDataAdapter = powerbi.visuals.TableDataAdapter;
    import TableCell = powerbi.visuals.TableCell;
    import TableTotal = powerbi.visuals.TableTotal;
    import TableHierarchyNavigator = powerbi.visuals.TableHierarchyNavigator;
    import TableBinderOptions = powerbi.visuals.TableBinderOptions;
    import TableBinder = powerbi.visuals.TableBinder;
    import TableDataViewObjects = powerbi.visuals.TableDataViewObjects;
    import TableDataViewObject = powerbi.visuals.TableDataViewObject;
    import ColumnWidthCallbackType = powerbi.visuals.ColumnWidthCallbackType;


    export class myCustom_Table implements IVisual {

        public static formatStringProp: DataViewObjectPropertyIdentifier = { objectName: 'general', propertyName: 'formatString' };
        public static totalsProp: DataViewObjectPropertyIdentifier = { objectName: 'general', propertyName: 'totals' };
        public static autoSizeProp: DataViewObjectPropertyIdentifier = { objectName: 'general', propertyName: 'autoSizeColumnWidth' };
        public static textSizeProp: DataViewObjectPropertyIdentifier = { objectName: 'general', propertyName: 'textSize' };

        private static preferredLoadMoreThreshold: number = 0.8;

        public static capabilities: VisualCapabilities = {
            dataRoles: [{
                name: 'Values',
                kind: VisualDataRoleKind.GroupingOrMeasure
            }],
            objects: {
                general: {
                    displayName: data.createDisplayNameGetter('Visual_General'),
                    properties: {
                        formatString: {
                            type: { formatting: { formatString: true } },
                        },
                        columnWidth: {
                            type: { numeric: true }
                        },
                        totals: {
                            type: { bool: true },
                            displayName: data.createDisplayNameGetter('Visual_Totals')
                        },
                        autoSizeColumnWidth: {
                            type: { bool: true },
                            displayName: data.createDisplayNameGetter('Visual_Adjust_Column_Width')
                        },
                        textSize: {
                            displayName: data.createDisplayNameGetter('Visual_TextSize'),
                            type: { numeric: true }
                        },
                    },
                },
            },
            dataViewMappings: [{
                table: {
                    rows: {
                        for: { in: 'Values' },
                        dataReductionAlgorithm: { window: { count: 100 } }
                    },
                    rowCount: { preferred: { min: 1 } }
                },
            }],
            sorting: {
                custom: {},
            },
            suppressDefaultTitle: true,
        }

        private element: JQuery;
        private currentViewport: IViewport;
        private style: IVisualStyle;
        private formatter: ICustomValueColumnFormatter;
        private isInteractive: boolean;
        private getLocalizedString: (stringId: string) => string;
        private dataView: DataView;
        private hostServices: IVisualHostServices;

        private tablixControl: controls.TablixControl;
        private hierarchyNavigator: TableHierarchyNavigator;
        private waitingForData: boolean;
        private lastAllowHeaderResize: boolean;
        private waitingForSort: boolean;
        private visualTable: DataViewVisualTable;
        private columnWidthManager: controls.TablixColumnWidthManager;

        public static customizeQuery(options: CustomizeQueryOptions): void {
            var dataViewMapping = options.dataViewMappings[0];
            if (!dataViewMapping || !dataViewMapping.table || !dataViewMapping.metadata)
                return;

            var dataViewTableRows: data.CompiledDataViewRoleForMapping = <data.CompiledDataViewRoleForMapping>dataViewMapping.table.rows;

            var objects: TableDataViewObjects = <TableDataViewObjects>dataViewMapping.metadata.objects;
            dataViewTableRows.for.in.subtotalType = myCustom_Table.shouldShowTotals(objects) ? data.CompiledSubtotalType.Before : data.CompiledSubtotalType.None;
        }

        public static getSortableRoles(): string[] {
            return ['Values'];
        }

        public init(options: VisualInitOptions): void {
            this.element = options.element;
            this.style = options.style;
            this.updateViewport(options.viewport);
            this.formatter = valueFormatter.formatValueColumn;
            this.isInteractive = options.interactivity && options.interactivity.selection != null;
            this.getLocalizedString = options.host.getLocalizedString;
            this.hostServices = options.host;

            this.waitingForData = false;
            this.lastAllowHeaderResize = true;
            this.waitingForSort = false;
        }
        
        /**
         * Note: Public for testability.
         */
        public static converter(table: DataViewTable): DataViewVisualTable {
            debug.assertValue(table, 'table');
            debug.assertValue(table.rows, 'table.rows');

            var visualTable = Prototype.inherit<DataViewVisualTable>(table);
            visualTable.visualRows = [];

            for (var i: number = 0; i < table.rows.length; i++) {
                var visualRow: DataViewVisualTableRow = {
                    index: i,
                    values: table.rows[i]
                };
                visualTable.visualRows.push(visualRow);
            }

            return visualTable;
        }

        public onResizing(finalViewport: IViewport): void {
            this.updateViewport(finalViewport);
        }

        // Public for testability
        public getColumnWidthManager(): controls.TablixColumnWidthManager {
            return this.columnWidthManager;
        }

        public onDataChanged(options: VisualDataChangedOptions): void {
            debug.assertValue(options, 'options');
            // To avoid OnDataChanged being called every time resize occurs or the auto-size property switch is flipped.
            if (this.columnWidthManager && this.columnWidthManager.suppressOnDataChangedNotification) {
                // Reset flag for cases when cross-filter/cross-higlight happens right after. We do need onDataChanged call to go through
                this.columnWidthManager.suppressOnDataChangedNotification = false;
                return;
            }

            var previousDataView = this.dataView;
            var dataViews = options.dataViews;

            if (dataViews && dataViews.length > 0) {
                this.dataView = dataViews[0];
                if (options.operationKind === VisualDataChangeOperationKind.Append) {
                    var visualTable = Table.converter(this.dataView.table);
                    this.hierarchyNavigator.update(visualTable);
                    this.tablixControl.updateModels(/*resetScrollOffsets*/false, visualTable.visualRows);
                    this.refreshControl(false);
                } else {
                    this.createOrUpdateHierarchyNavigator();
                    this.createColumnWidthManager();
                    this.createTablixControl();
                    this.populateColumnWidths();
                    this.updateInternal(this.dataView, previousDataView);
                }
            }

            this.waitingForData = false;
            this.waitingForSort = false;
        }

        private populateColumnWidths(): void {
            if (this.columnWidthManager) {
                this.columnWidthManager.deserializeTablixColumnWidths();
                if (this.columnWidthManager.persistColumnWidthsOnHost())
                    this.persistColumnWidths(this.columnWidthManager.getVisualObjectInstancesToPersist());
            }
        }

        public columnWidthChanged(index: number, width: number): void {
            this.columnWidthManager.columnWidthChanged(index, width);
            this.persistColumnWidths(this.columnWidthManager.getVisualObjectInstancesToPersist());
        }

        private persistColumnWidths(objectInstances: VisualObjectInstance[]): void {
            this.hostServices.persistProperties({
                merge: objectInstances
            });
        }

        private updateViewport(newViewport: IViewport) {
            this.currentViewport = newViewport;

            if (this.tablixControl) {
                this.tablixControl.viewport = this.currentViewport;
                this.verifyHeaderResize();
                this.refreshControl(false);
            }
        }

        private refreshControl(clear: boolean) {
            if (visibilityHelper.partiallyVisible(this.element) || this.getLayoutKind() === controls.TablixLayoutKind.DashboardTile) {
                this.tablixControl.refresh(clear);
            }
        }

        private getLayoutKind() {
            return this.isInteractive ? controls.TablixLayoutKind.Canvas : controls.TablixLayoutKind.DashboardTile;
        }

        private createOrUpdateHierarchyNavigator(): void {
            this.visualTable = Table.converter(this.dataView.table);
            if (!this.tablixControl) {
                var dataNavigator = new TableHierarchyNavigator(this.visualTable, this.formatter);
                this.hierarchyNavigator = dataNavigator;
            }
            else {
                this.hierarchyNavigator.update(this.visualTable);
            }
        }

        private createTablixControl(): void {
            if (!this.tablixControl) {
                // Create the control
                this.tablixControl = this.createControl(this.hierarchyNavigator);
            }
        }

        private createColumnWidthManager(): void {
            if (!this.columnWidthManager) {
                this.columnWidthManager = new controls.TablixColumnWidthManager(this.dataView, false /* isMatrix */);
                this.columnWidthManager.columnWidthResizeCallback = (i, w) => this.columnWidthChanged(i, w);
            }
            else {
                this.columnWidthManager.updateDataView(this.dataView);
            }
        }

        private createControl(dataNavigator: TableHierarchyNavigator): controls.TablixControl {
            var layoutKind = this.getLayoutKind();

            var tableBinderOptions: TableBinderOptions = {
                onBindRowHeader: (item: any) => this.onBindRowHeader(item),
                onColumnHeaderClick: (queryName: string) => this.onColumnHeaderClick(queryName),
            };
            var tableBinder = new TableBinder(tableBinderOptions);

            var layoutManager: controls.internal.TablixLayoutManager = layoutKind === controls.TablixLayoutKind.DashboardTile
                ? controls.internal.DashboardTablixLayoutManager.createLayoutManager(tableBinder)
                : controls.internal.CanvasTablixLayoutManager.createLayoutManager(tableBinder, this.columnWidthManager);

            // Create Host element
            var tablixContainer = document.createElement('div');
            this.element.append(tablixContainer);

            var tablixOptions: controls.TablixOptions = {
                interactive: this.isInteractive,
                enableTouchSupport: false,
                layoutKind: layoutKind,
                fontSize: this.getFontSize(),
            };

            return new controls.TablixControl(dataNavigator, layoutManager, tableBinder, tablixContainer, tablixOptions);
        }

        private updateInternal(dataView: DataView, previousDataView: DataView) {
            if (this.getLayoutKind() === controls.TablixLayoutKind.DashboardTile) {
                this.tablixControl.layoutManager.adjustContentSize(UrlHelper.hasImageColumn(dataView));
            }

            this.tablixControl.fontSize = this.getFontSize();

            this.verifyHeaderResize();

            // Update models before the viewport to make sure column widths are computed correctly
            this.tablixControl.updateModels(/*resetScrollOffsets*/true, this.visualTable.visualRows, this.visualTable.columns);

            var totals = this.createTotalsRow(dataView);
            this.tablixControl.rowDimension.setFooter(totals);

            this.tablixControl.viewport = this.currentViewport;
            var shouldClearControl = this.shouldClearControl(previousDataView, dataView);

            // Render
            // We need the layout for the DIV to be done so that the control can measure items correctly.
            setTimeout(() => {
                // Render
                this.refreshControl(shouldClearControl);
                this.columnWidthManager.persistAllColumnWidths(this.tablixControl.layoutManager.columnWidthsToPersist);
                if (this.columnWidthManager.persistColumnWidthsOnHost())
                    this.persistColumnWidths(this.columnWidthManager.getVisualObjectInstancesToPersist());
            }, 0);
        }

        private shouldClearControl(previousDataView: DataView, newDataView: DataView) {
            if (!this.waitingForSort || !previousDataView || !newDataView)
                return true;

            return !DataViewAnalysis.isMetadataEquivalent(previousDataView.metadata, newDataView.metadata);
        }

        private createTotalsRow(dataView: DataView): TableTotal {
            if (!this.shouldShowTotals(dataView))
                return null;

            var totals = dataView.table.totals;
            if (!totals || totals.length === 0)
                return null;

            var totalRow: any[] = [];
            var columns = dataView.table.columns;

            // Add totals for measure columns, blank for non-measure columns unless it's the first column
            for (var i = 0, len = columns.length; i < len; ++i) {
                var column = columns[i];

                var totalValue = totals[column.index];
                if (totalValue != null) {
                    totalRow.push(totalValue);
                }
                else {
                    // If the first column is a non-measure column, we put 'Total' as the text similar to PV.
                    // Note that if the first column is a measure column we don't render any Total text at
                    // all, once again similar to PV.
                    totalRow.push((i === 0) ? this.getLocalizedString('TableTotalLabel') : '');
                }
            }

            return <TableTotal>{ totalCells: totalRow };
        }

        private shouldShowTotals(dataView: DataView): boolean {
            var objects = <TableDataViewObjects>dataView.metadata.objects;
            return myCustom_Table.shouldShowTotals(objects);
        }

        private static shouldShowTotals(objects: TableDataViewObjects): boolean {
            if (objects && objects.general)
                return objects.general.totals !== false;

            // Totals are enabled by default
            return true;
        }

        private shouldAutoSizeColumnWidth(objects: TableDataViewObjects): boolean {
            if (objects && objects.general) {
                return objects.general.autoSizeColumnWidth !== false;
            }

            // Auto adjust is turned on by default
            return controls.AutoSizeColumnWidthDefault;
        }

        private static getTextSize(objects: TableDataViewObjects): number {
            // By default, let tablixControl set default font size
            return DataViewObjects.getValue<number>(objects, Table.textSizeProp, controls.TablixDefaultTextSize);
        }

        private getFontSize(): string {
            var objects = this.getTableDataViewObjects();
            return jsCommon.PixelConverter.fromPoint(myCustom_Table.getTextSize(objects));
        }

        private onBindRowHeader(item: any): void {
            if (this.needsMoreData(item)) {
                this.hostServices.loadMoreData();
                this.waitingForData = true;
            }
        }

        private onColumnHeaderClick(queryName: string) {
            var sortDescriptors: SortableFieldDescriptor[] = [{
                queryName: queryName,
            }];
            var args: CustomSortEventArgs = {
                sortDescriptors: sortDescriptors
            };
            this.waitingForSort = true;
            this.hostServices.onCustomSort(args);
        }
        
        /**
         * Note: Public for testability.
         */
        public needsMoreData(item: any): boolean {
            if (this.waitingForData || !this.dataView.metadata || !this.dataView.metadata.segment)
                return false;

            var leafCount = this.tablixControl.rowDimension.getItemsCount();
            var loadMoreThreshold = leafCount * myCustom_Table.preferredLoadMoreThreshold;

            return this.hierarchyNavigator.getIndex(item) >= loadMoreThreshold;
        }

        private getTableDataViewObjects(): TableDataViewObjects {
            if (this.dataView && this.dataView.metadata && this.dataView.metadata.objects)
                return <TableDataViewObjects>this.dataView.metadata.objects;
        }

        public enumerateObjectInstances(options: EnumerateVisualObjectInstancesOptions): VisualObjectInstance[] {
            var instances: VisualObjectInstance[] = [];
            
            // Visuals are initialized with an empty data view before queries are run, therefore we need to make sure that
            // we are resilient here when we do not have data view.
            if (this.dataView && options.objectName === 'general') {
                var objects = this.getTableDataViewObjects();
                instances.push({
                    selector: null,
                    properties: {
                        totals: myCustom_Table.shouldShowTotals(objects),
                        autoSizeColumnWidth: this.shouldAutoSizeColumnWidth(objects),
                        textSize: myCustom_Table.getTextSize(objects),
                    },
                    objectName: options.objectName
                });
            }
            return instances;
        }

        private shouldAllowHeaderResize(): boolean {
            return this.hostServices.getViewMode() === ViewMode.Edit;
        }

        private verifyHeaderResize() {
            var currentAllowHeaderResize = this.shouldAllowHeaderResize();
            if (currentAllowHeaderResize !== this.lastAllowHeaderResize) {
                this.lastAllowHeaderResize = currentAllowHeaderResize;
                this.tablixControl.layoutManager.setAllowHeaderResize(currentAllowHeaderResize);
            }
        }
    }
}

Can you see where the mistake is? or why it's working in the tool but not the app? 
I still haven't figured out on how to modify the header color so if you have some input on that I'd appreciate.

**Comment by yapaxi** [comment]
This visual uses deprecated api - onDataChanged and onResizing. I am not sure if it can run in Power BI Desktop. 
You can add js alerts to public methods (except "test" public ones) in order to find if they are executed in desktop (or debug it in clould version), but i think it's better to rewrite this to init+update+destory way or try to "extend" original visual, instead of copy-pasting it (but that does not work for me too).

**Comment by NicolaeGP** [comment]
I will try and rewrite it in a init-update-destroy fashion. But shouldn't the code for the working table be out somewhere since the table is available and working in powerbi.com?

**Comment by venkateshappala** [comment]
I have followed these steps. 
Added to "src\Clients\Visuals\plugins.ts" as plugin and added to "src\Clients\Visuals\services\visualPluginService.ts". My visual is not appearing in dropdown. What other changes I need to do if I want to integrate my visual to solution. Any documentation helps!!

**Comment by mirceapirv** [comment]
Did you manage to rewrite the custom table visual ? I am trying to modify the current table visual to be able to display a custom text instead of the whole hyperlink. And I can't get it to work in the dev tools. I tried to get the code from the existing table files and merge it into one but could not get it to work.

**Comment by noorahmad01** [comment]
@mirceapirv I am also try to modify the existing table visual. I need image columns in table could you please suggest some solution.

**Comment by mirceapirv** [comment]
@noorahmad01 I did not pursue the building of a custom visual, since we decided to go with another solution, besides Power BI.

**Comment by ignatvilesov** [comment]
@NicolaeGP You should define your visual in “plugins.ts” (see example below) and rebuild the solution using command “gulp build”. After that your visual should be available in Playground.

    export let yourVisualName: IVisualPlugin = {
        name: 'yourVisualName',
        capabilities: YourVisualClassName.capabilities,
        create: () => new YourVisualClassName()
    };
