### ISSUE TITLE
Scroll bar on the visual

### ISSUE THREAD

**Issue by jrhalasz** [microsoft/PowerBI-visuals#145]
A gray scroll bar is showing up on the right side of the visual in a Report when the Title is turned off. 
A gray scroll bar is showing up on the right side of the visual after you pin the visual to a Dashboard, regardless of the Title setting. 

Would you please figure out a way to remove this gray scroll bar?

**Comment by AviSander** [comment]
Hi @jrhalasz -
   does this happen to all visuals? is there a sample you can share?
thx, avi

**Comment by helen508light** [comment]
outdated
