### ISSUE TITLE
Dropdown in Object

### ISSUE THREAD

**Issue by SamuraiApocalypse** [microsoft/PowerBI-visuals#147]
I've seen the ability to put a custom dropdown in your objects list to select from a number of different options. It's in the standard KPI visual.

Unfortunately, the [documentation](https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Objects.md) only mentions primitive types and colors.

Does anyone have details on what your capabilities and enumeration would look like? I can't find documentation anywhere.

Thanks!

**Comment by nikhilkabbin** [comment]
@SamuraiApocalypse see issue #39
