### ISSUE TITLE
Use local file capability in capabilities panel

### ISSUE THREAD

**Issue by nikhilkabbin** [microsoft/PowerBI-visuals#157]
I can see in Shape map visual component, users are allowed to use local topojson file to render maps. How do I allow the same capability in my custom visual? any reference or Example?

**Comment by AviSander** [comment]
Hi Nikhil,
    If you are trying to access a local file (localstorage) from the visual, then you will not be able to do so in the current API. this is purposely blocked. We are working on an API for local access per visual - there is no ETA for such support yet.

**Comment by nikhilkabbin** [comment]
@AviSander Thanks for the clarification. But may I know if the [shapemap](https://powerbi.microsoft.com/en-us/documentation/powerbi-desktop-shape-map/) visual capability of using/uploading a topojson file in format panel "+ Add Map" is not part of current API?

**Comment by AviSander** [comment]
Hi @nikhilkabbin - so this is not part of the Custom Visuals API. This is a specific implementation of the shapemap visual. The "+Add Map" is also not yet available in the API...

**Comment by danieljroy** [comment]
I have a business case where I have been requested to display horopleth data for our proprietary internal poly layers. I have created topojsons of the target polys and have worked with our IT group to host them on a github-like server with the required https:// path. Unfortunately, we've had no success and continue to get the "invalid json file" despite everything we try.

Are there plans to better document the process of using our own poly layers, or as the above suggests, add a way to grab local (or sharepoint or WFS) data? A timeline would be extremely helpful. I have been battling this issue for 6 months now so any progress would be awesome.

**Comment by nikhilkabbin** [comment]
@danieljroy Have you enabled CORS on your Server (Where you have hosted TopoJSON's)?

**Comment by danieljroy** [comment]
@nikhilkabbin I honestly do not know - our IT dept handled the server setup based on the requirements that I was able to find in this forum and others. Is there a site which documents the required services and host configuration? If so, I am game to try again! Thank you

**Comment by nikhilkabbin** [comment]
@danieljroy You just need to ask your IT team if they have enabled [CORS](https://www.w3.org/wiki/CORS_Enabled) on the server. Alternatively, if you can share the link to the topojson maps we can figure out the issue and help you resolve it.

**Comment by danieljroy** [comment]
@nikhilkabbin  thank you, I have passed this along to our IT and will try hosting again.

**Comment by danieljroy** [comment]
I saw on another thread that the hosted topojson data needs to be hosted "publicly" (external to a private network and open for all to view?) for custom visuals to be able to utilize it. Is this true? I see no reason why internally-hosted reports on an internal Report Server setup could not access internally-hosted topojson data, but of course there could be something in the way the visual works...

**Comment by danieljroy** [comment]
Sorry for the delay in response. Our IT dept has been slow about responding to my repeated requests for clarification on how the current system is set up. 

Can anyone tell me if updating the choropleth API to use local topojsons is on the roadmap at all?

**Comment by nikhilkabbin** [comment]
@danieljroy it is on our roadmap but only if Power-BI API allows us to do so.

**Comment by danieljroy** [comment]
Our IT group has finally come back, saying that they cannot enable CORS on bitbucket. So I'm in limbo on this for the moment.
