### ISSUE TITLE
What is the .pbiviz file size limit?

### ISSUE THREAD

**Issue by youranupama** [Microsoft/PowerBI-visuals#159]
We have a visual file that is around 3 MB in size because of embedded images in CSS file. What is the size limit of visual file? It works fine in Desktop but we are unable to import it to the Power BI App.

**Comment by ignatvilesov** [comment]
@youranupama As far as I know, the size limit is about 2MB. You might reduce size of the package by using compression:
1. Unpack your package by using any zip tool
2. Pack the unpacked package with another compression level (7-zip supports different compression levels)
3. Try to import your package to Power BI web and Power BI Desktop to make sure that the package is correct

**Comment by youranupama** [comment]
@ignatvilesov So if i bring it under 2MB using another compression level, it will still work. 
Thanks.
