### ISSUE TITLE
dotplot visual sample doesn't work in devtools

### ISSUE THREAD

**Issue by LukaszPawlowski-MS** [Microsoft/PowerBI-visuals#159]
Again there are "let" statements that need to be converted to "var".

But also this:
private static round10(value: number, digits: number = 2) {
            const scale = Math.pow(10, digits);
            return (Math.round(scale * value) / scale);
        }

DevTools complains that "const" is only valid when targeting EMCAScript 6.

**Comment by sgrebnov** [comment]
Fixed
