### ISSUE TITLE
Illegal invocation error with openlayer.js

### ISSUE THREAD

**Issue by xyw101** [Microsoft/PowerBI-visuals#163]
I'm using openlayer library in my custom visual.  The default 'update count' visual works fine, but as soon as I include openlayer.js, it allows me to build, however, when I drag the visual in power BI service, it has the following error:

Uncaught TypeError: Illegal invocation
    at <anonymous>:84:1469
    at OPENLAYERS (<anonymous>:23:15)
    at Window.<anonymous> (<anonymous>:25:2)
    at <anonymous>:1098:20
    at Object.r [as injectJsCode] (visualhostcore.min.js:2)
    at i.loadWithoutResourcePackage (visualsandbox.min.js:1)
    at i.executeMessage (visualsandbox.min.js:1)
    at i.onMessageReceived (visualsandbox.min.js:1)
    at visualsandbox.min.js:1
    at e.invokeHandler (visualhostcore.min.js:2)

Also, the visual is working fine in power BI desktop, but not on power BI service

**Comment by kksevta** [comment]
I am facing same but with some other external lib,

**Comment by pawelfus** [comment]
The same issue here.

After some debugging, found the reason, this is how visual is loaded:

                (function(powerbi) {
                    var window = this;

                    //These 2 lines are needed to trick lodash into using this as global scope
                    var self = this;
                    self.Object = Object;

                    //de-reference powerbi loaded modules
                    var $, jQuery, _;
                    window.jQuery = window.$ = undefined;
                    window._ = undefined;

// External libraries go here
...
// Then our visual
...
// Then we have culprit:

                    //overwrite global variables with window values for PowerBI libraries
                    $ = jQuery = window.$;
                    _ = window._
                }).call(
                    //generate isolated clone of window object
                    (function(w) {
                        var wKeys = Object.getOwnPropertyNames(w);
                        var nextW = w;
                        while ((nextW = Object.getPrototypeOf(nextW))) {
                            wKeys = wKeys.concat(Object.getOwnPropertyNames(nextW));
                        }
                        var newWindow = Object.create(w);
                        //rebuild some of the window properties so they work correctly
                        for (var i = 0; i < wKeys.length; i++) {
                            try {
                                var key = wKeys[i];
                                var item = w[key];
                                //rebind native functions to proper window context
                                if (typeof item === 'function') {
                                    if ((/\{\s*\[native code\]\s*\}/).test('' + Function.prototype.toString.call(item))) {
                                        newWindow[key] = item.bind(w);
                                        //remap prototype
                                        newWindow[key].prototype = item.prototype;
                                        //remap own properties
                                        var fKeys = Object.getOwnPropertyNames(item);
                                        for (var j = 0; j < fKeys.length; j++) {
                                            var fKey = fKeys[j];
                                            if(fKey === 'arguments' || fKey === 'caller') continue;
                                            try {
                                                newWindow[key][fKey] = item[fKey];
                                            } catch (e) { /* catch protected function properties */} 
                                        }                                        
                                    }
                                //map getters to proper context (needed for firefox only)
                                } else if (typeof item === 'object') {
                                    Object.defineProperty(newWindow, key, {
                                        get: (function(item) {
                                            return function() {
                                                return item;
                                            }
                                        })(item),
                                        set: function() { }
                                    });
                                }
                            } catch (e) { /* catch sandbox security exceptions */ }
                        }
                        return newWindow;
                    })(window),
                    powerbi || (powerbi = {})
                );

As we can see, it creates a cloned window object. However, referencing simple `window.pageXOffset` generates error: `Uncaught TypeError: Illegal invocation`

This is standalone issue in jsFiddle: http://jsfiddle.net/rzf6e56L/ (consider 17th line -> error).

Possible workaround: overwrite `window = document.defaultView;` before rendering any of the files.
