### ISSUE TITLE
Not able to load Playground page from Visual Studio

### ISSUE THREAD

**Issue by venkateshappala** [Microsoft/PowerBI-visuals#165]
I have cloned the repo and opened the index html page present in Visuals PlayGround folder. Set as start page and changed build properties as mentioned in home page. When I run the application, $ undefined error and many references externals.min.js, VisualsPlayGround.js etc., files refereed in index page are not available in solution. Please help me. I am blocked.

**Comment by sgrebnov** [comment]
@venkateshappala did you follow instructions in repo home (`npm install`, etc)?

**Comment by venkateshappala** [comment]
Yes. I have installed node.js and ran npm install command as well in Visual Studio

**Comment by sgrebnov** [comment]
Could you try running `gulp build` from command line (root folder) and see if there is any error?

Looks like you don't have the following files which are produced during build:
```
PowerBI-visuals\src\Clients\PowerBIVisualsPlayground\PowerBIVisualsPlayground.js 
PowerBI-visuals\src\Clients\PowerBIVisualsPlayground\externals.min.js 
PowerBI-visuals\src\Clients\PowerBIVisualsPlayground\powerbi-visuals.js 
```


PS. I've just tested master branch and it works for me

**Comment by venkateshappala** [comment]
thnx a lot!! working now.
