### ISSUE TITLE
Power BI creates a fake copy of the window object

### ISSUE THREAD

**Issue by ignatvilesov** [microsoft/PowerBI-visuals#165]
# Power BI creates a fake copy of the ```window``` object.

### Description:

Looks like Power BI creates a copy of ```window``` object for security reasons and module isolation. However, it produces issues that are related to external library injection and using some properties of the ```window``` object.

### Related issues:
- #164 
- #158
- [PowerBI-visuals-tools#81](https://github.com/Microsoft/PowerBI-visuals-tools/issues/81)

### Current workaround:

Use ```window.window``` instead of ```window```.

**Comment by domoritz** [comment]
@ignatvilesov What if I cannot easily modify my library? Is there a way to inject `window = window.window` or something like that?

**Comment by ignatvilesov** [comment]
Is this library public? I suppose that you might use window.window before including the library.

**Comment by ryanbaumann** [comment]
@ignatvilesov The public library I'm using is `mapboxgl`.  It uses the `window` object in the library for many function in the library code.  EX: `window.getDevicePixelRatio`.

I tried creating an overwrite variable for window -> `var window = window.window` before importing the `mapboxgl` library, but that didn't seem to work.  Do you have any other ideas on how to get access to the parent window variable?  Thanks in advance!

**Comment by ignatvilesov** [comment]
@ryanbaumann Can you share source code vie GitHib?
I'd like to investigate this issue deeper.

**Comment by ryanbaumann** [comment]
@ignatvlesov absolutely - please see the public repo with all code for the Custom Visual here -> https://github.com/ryanbaumann/mapboxgl-powerBI

**Comment by ryanbaumann** [comment]
@ignatvilesov absolutely - please see the public repo with all code for the Custom Visual here -> https://github.com/ryanbaumann/mapboxgl-powerBI

**Comment by ignatvilesov** [comment]
@ryanbaumann 

`chroma.limits` throws this unexpected exception:
```
VM6120:1 Uncaught TypeError: Cannot read property 'push' of undefined
    at eval (eval at chroma.limits (:2995:9), <anonymous>:1:19)
    at Function.chroma.limits (<anonymous>:2995:9)
    at Function.converter (<anonymous>:3898:45)
    at Function.value (<anonymous>:3841:61)
    at MapboxMap.update (<anonymous>:3926:56)
    at MapboxMap.value (<anonymous>:3841:61)
    at r.update (https://msit.powerbi.com/13.0.2278.113/scripts/visualhostcore.min.js:3:24895)
    at https://msit.powerbi.com/13.0.2278.113/scripts/visualhostcore.min.js:3:10264
    at t.executeSafely (https://msit.powerbi.com/13.0.2278.113/scripts/visualhostcore.min.js:3:12838)
    at t.update (https://msit.powerbi.com/13.0.2278.113/scripts/visualhostcore.min.js:3:10220)VM6120:1 Uncaught TypeError: Cannot read property 'push' of undefined
    at eval (eval at chroma.limits (:2995:9), <anonymous>:1:19)
    at Function.chroma.limits (<anonymous>:2995:9)
    at Function.converter (<anonymous>:3898:45)
    at Function.value (<anonymous>:3841:61)
    at MapboxMap.update (<anonymous>:3926:56)
    at MapboxMap.value (<anonymous>:3841:61)
    at r.update (https://msit.powerbi.com/13.0.2278.113/scripts/visualhostcore.min.js:3:24895)
    at https://msit.powerbi.com/13.0.2278.113/scripts/visualhostcore.min.js:3:10264
    at t.executeSafely (https://msit.powerbi.com/13.0.2278.113/scripts/visualhostcore.min.js:3:12838)
    at t.update (https://msit.powerbi.com/13.0.2278.113/scripts/visualhostcore.min.js:3:10220)
```
I suppose that this issue is related to the fact that `domain` contains only [string values](https://github.com/ryanbaumann/mapboxgl-powerBI/blob/e7cb1bf8f7e854bc6649d12da5214ad1c2aad6f4/src/ts/mapboxMap.ts#L71).

I suppose that you should update this condition something like this:
```TypeScript
if (role !== 'category') {
    domain.push(v)
}
```

**Comment by ryanbaumann** [comment]
Thanks @ignatvilesov!  Moved to an issue in the repo => https://github.com/ryanbaumann/mapboxgl-powerBI/issues/1 to keep this issue focused on the parent window object copy.

Any thoughts on the `window.window` solution?  My workaround is here -> https://github.com/ryanbaumann/mapboxgl-powerBI/blob/master/src/js/mapboxglAdaptor.js and in the mapboxgl library, which needs access to the browser window object outside of the narrow example I created.

**Comment by sureshamathew** [comment]
Yes, thank you. FIgured out the issue.

**Comment by ignatvilesov** [comment]
@ryanbaumann

No concerns about your workaround. There's no another way to work with libraries that use the global context (window).

**Comment by ryanbaumann** [comment]
Thanks @ignatvilesov.  The nested window solution ended up working out ok with a few small changes to the core `mapboxgl` library - I replaced references to `window.devicePixelRatio` with `window.window.devicePixelRatio`. 

The [fully packaged version](https://cdn.rawgit.com/ryanbaumann/mapboxgl-powerBI/672fb6f4/dist/mapboxGLMap.pbiviz) worked too by removing uglification via `pbiviz package --no-minification`.

**Comment by uve** [comment]
powerbi-visuals-api@3.2.0 and above don't use Fake window anymore
