### ISSUE TITLE
Custom Visuals not displaying in PowerBi Desktop after import but displays in Power Bi Web

### ISSUE THREAD

**Issue by BigBrahma** [Microsoft/PowerBI-visuals#166]
I have created a custom visual using Visual code and tested in App.Powerbi.com. It is working fine. 

Created a package and  successfully imported to power bi desktop.

After adding fields it is not showing chart in power bi desktop.

If i publish the same to web it is showing the charts. 

Can you please let me what is the issue?

**Comment by PerttiFI** [comment]
I do have the same experience with my visual but also with the Microsoft sample custom visual (https://github.com/Microsoft/PowerBI-visuals) - even after the step 1 of the sample visual development.

I have the free version of Power BI Desktop. Is paid Pro version required to get the private custom visuals working in the Desktop?

**Comment by AviSander** [comment]
Hello - what API version did you use in this case - can you share a stub of the visual so we can reproduce this?

**Comment by PerttiFI** [comment]
Version 1.6.
Visual was the one from the sample case I refer to in my first post.I created the visual using the pbiviz new (pbiviz version 1.6.1).
 Terveisin, Pertti

      Lähettäjä: Avi Sander <notifications@github.com>
 Vastaanottaja: Microsoft/PowerBI-visuals <PowerBI-visuals@noreply.github.com> 
Kopio: PerttiFI <pertti.silen@yahoo.com>; Comment <comment@noreply.github.com>
 Lähetetty: maanantai 24. huhtikuuta 2017 8.54
 Aihe: Re: [Microsoft/PowerBI-visuals] Custom Visuals not displaying in PowerBi Desktop after import but displays in Power Bi Web (#166)
   
Hello - what API version did you use in this case - can you share a stub of the visual so we can reproduce this?—

**Comment by PerttiFI** [comment]
I updated the Power BI Desktop. Now my custom visual is visible also in the Desktop.

**Comment by BigBrahma** [comment]
SOLVED.  Please upgrade to latest PowerBi Desktop version.
