### ISSUE TITLE
Playground does no work

### ISSUE THREAD

**Issue by tomsoir** [Microsoft/PowerBI-visuals#169]
Project build success but not initialize. 
![2015-12-07 15 50 23](https://cloud.githubusercontent.com/assets/301881/11643647/4e0043f4-9cfa-11e5-884d-2224bcd1b021.png)

**Comment by sgrebnov** [comment]
:+1: same issue

**Comment by proll** [comment]
7edf86f3f32a54b179497fefa70f84b50c179dd1 by @IgnatVilesov broke it down

**Comment by proll** [comment]
And it appears only on macOS

**Comment by joostshao** [comment]
And it appears  on Ubuntu.

**Comment by sgrebnov** [comment]
Fixed in master by the following commit
https://github.com/Microsoft/PowerBI-visuals/commit/eb11270809c152b8698c43795cd4c7d3df70aa4c

Please feel free to re-open if it still does not work for you.
