### ISSUE TITLE
Get user's name from custom viz

### ISSUE THREAD

**Issue by fredrikheden** [Microsoft/PowerBI-visuals#170]
I need to get the user's name/email in a custom viz. Outside the sandbox this is available through the "powerbi.session.userInfo" object. However, this is not available inside the sandbox. Is there any way to get this information? Are you planning to make this available inside the sandbox in the future?

**Comment by youranupama** [comment]
Yes. We also need user email id inside custom visual. Please help.

**Comment by ignatvilesov** [comment]
There's no way get user information right now.
Power BI API doesn't support this feature.

**Comment by nikhilkabbin** [comment]
@AviSander Is this feature in your roadmap?

**Comment by wpfdev** [comment]
This is a valuable feature, why we have no this before these time?

**Comment by srikanthnd** [comment]
Any updates on this feature implementation?  We see a big use case for this to be implemented for our product. It totally makes sense to build this feature ASAP 👍 

Regards,
Srikanth
