### ISSUE TITLE
Tooltips of custom visuals are not displayed in dashboard

### ISSUE THREAD

**Issue by alexmeia** [microsoft/PowerBI-visuals#172]
When a custom visual is pinned to a dashboard tooltips are not displayed on mouse over, while native visuals can display their tooltips correctly.
In all other contexts (included dashboard in focus mode) tooltips work as expected.
We noticed this issue testing our custom visuals and also pinning to a dashboard the [sampleBarChart](https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/issues/21) visual provided by Microsoft.
Debugging the code we noticed that the method `visualHostTooltipService.show()` is called as usual in `tooltipServiceWrapper.ts`, but nothing is shown.

**Comment by AviSander** [comment]
Hello - we a re working to fix this issue.
thx.

**Comment by helen508light** [comment]
fixed
