### ISSUE TITLE
Custom R Visual - CreateRHTML.md

### ISSUE THREAD

**Issue by kamipatel** [microsoft/PowerBI-visuals#173]
This works in Power BI online. When I package and try to use in PowerBI desktop it fails loading because of the packages... Is this expected?
Feedback Type:
Frown (Error)

Timestamp:
2017-04-20T21:39:04.1708551Z

Local Time:
2017-04-20T16:39:04.1708551-05:00

Product Version:
2.45.4704.442 (PBIDesktop) (x64)

Release:
April 2017

IE Version:
11.1066.14393.0

OS Version:
Microsoft Windows NT 10.0.14393.0 (x64 en-US)

CLR Version:
4.6.2. or later [Release Number = 394802]

Workbook Package Info:
1* - en-US, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Peak Working Set:
585 MB

Private Memory:
449 MB

Peak Virtual Memory:
34.1 GB

Error Message:
R script error.
Loading required package: XML
Loading required package: methods
Warning message:
package 'XML' was built under R version 3.3.3 
Loading required package: htmlwidgets
Loading required package: ggplot2
Warning message:
package 'ggplot2' was built under R version 3.3.3 
Loading required package: plotly

Attaching package: 'plotly'

The following object is masked from 'package:ggplot2':

    last_plot

The following object is masked from 'package:stats':

    filter

The following object is masked from 'package:graphics':

    layout

Error in gg2list(p, width = width, height = height, tooltip = tooltip,  : 
  attempt to apply non-function
Calls: ggplotly -> ggplotly.ggplot -> gg2list
Execution halted

User ID:
e58759e7-8b47-4aae-952b-0c3981937fc7

Session ID:
b7f67106-6ec6-4a98-b571-23ad63fa0736

Telemetry Enabled:
True

Model Default Mode:
DirectQuery

Snapshot Trace Logs:
C:\Users\Kam\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot598454533.zip

Performance Trace Logs:
C:\Users\Kam\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Enabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_EnableReportTheme
PBI_allowBiDiCrossFilterInDirectQuery
PBI_pivotTableVisualEnabled
PBI_numericSlicerEnabled
PBI_PbiServiceLiveConnect
PBI_daxTemplatesEnabled

Disabled Preview Features:
PBI_Impala
PBI_Snowflake
PBI_esriEnabled
PBI_SpanishLinguisticsEnabled

Enabled DirectQuery Options:
PBI_DirectQuery_Unrestricted

Cloud:
GlobalCloud

Activity ID:
e9d46333-6f0a-7522-d6a3-62e9338aea7a

Time:
Thu Apr 20 2017 16:38:58 GMT-0500 (Central Daylight Time)

Version:
2.45.4704.442 (PBIDesktop)

Client Error Code:
ServiceErrorToClientError

Error Details:
R script error.
Loading required package: XML
Loading required package: methods
Warning message:
package 'XML' was built under R version 3.3.3 
Loading required package: htmlwidgets
Loading required package: ggplot2
Warning message:
package 'ggplot2' was built under R version 3.3.3 
Loading required package: plotly

Attaching package: 'plotly'

The following object is masked from 'package:ggplot2':

    last_plot

The following object is masked from 'package:stats':

    filter

The following object is masked from 'package:graphics':

    layout

Error in gg2list(p, width = width, height = height, tooltip = tooltip,  : 
  attempt to apply non-function
Calls: ggplotly -> ggplotly.ggplot -> gg2list
Execution halted

Stack Trace:
Microsoft.PowerBI.ExploreServiceCommon.ScriptHandlerException: R script error.
Loading required package: XML
Loading required package: methods
Warning message:
package 'XML' was built under R version 3.3.3 
Loading required package: htmlwidgets
Loading required package: ggplot2
Warning message:
package 'ggplot2' was built under R version 3.3.3 
Loading required package: plotly

Attaching package: 'plotly'

The following object is masked from 'package:ggplot2':

    last_plot

The following object is masked from 'package:stats':

    filter

The following object is masked from 'package:graphics':

    layout

Error in gg2list(p, width = width, height = height, tooltip = tooltip,  : 
  attempt to apply non-function
Calls: ggplotly -> ggplotly.ggplot -> gg2list
Execution halted
 ---> Microsoft.PowerBI.Radio.RScriptRuntimeException: R script error.
Loading required package: XML
Loading required package: methods
Warning message:
package 'XML' was built under R version 3.3.3 
Loading required package: htmlwidgets
Loading required package: ggplot2
Warning message:
package 'ggplot2' was built under R version 3.3.3 
Loading required package: plotly

Attaching package: 'plotly'

The following object is masked from 'package:ggplot2':

    last_plot

The following object is masked from 'package:stats':

    filter

The following object is masked from 'package:graphics':

    layout

Error in gg2list(p, width = width, height = height, tooltip = tooltip,  : 
  attempt to apply non-function
Calls: ggplotly -> ggplotly.ggplot -> gg2list
Execution halted

   at Microsoft.PowerBI.Radio.RScriptWrapper.RunScript(String originalScript, Int32 timeoutMs)
   at Microsoft.PowerBI.Client.Windows.R.RScriptHandler.GenerateVisual(ScriptHandlerOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.PowerBI.Client.Windows.R.RScriptHandler.GenerateVisual(ScriptHandlerOptions options)
   at Microsoft.PowerBI.ExploreServiceCommon.ScriptVisualCommandFlow.RunInternal(Stream dataShapeResultStream, QueryBindingDescriptor& bindingDescriptor)
   at Microsoft.PowerBI.ExploreServiceCommon.ScriptVisualCommandFlow.Run(Stream dataShapeResultStream, QueryBindingDescriptor& bindingDescriptor)
   at Microsoft.PowerBI.ExploreHost.SemanticQuery.ExecuteSemanticQueryFlow.TransformDataShapeResult(QueryCommand transformCommand, String dataShapeId, SemanticQueryDataShapeCommand command, Stream dataShapeResultStream, QueryBindingDescriptor& bindingDescriptor)
   at Microsoft.PowerBI.ExploreHost.SemanticQuery.ExecuteSemanticQueryFlow.ProcessAndWriteDataQuery(IQueryResultDataWriter queryResultDataWriter, DataShapeGenerationContext dsqGenContext, EntityDataModel model, DataQuery query, ServiceErrorStatusCode& serviceErrorStatusCode)
   at Microsoft.PowerBI.ExploreHost.SemanticQuery.ExecuteSemanticQueryFlow.ProcessAndWriteSemanticQueryCommands(IQueryResultsWriter queryResultsWriter, ExecuteSemanticQueryRequest request, IConceptualSchema conceptualSchema, EntityDataModel model)

DPI Scale:
100%

Supported Services:
Power BI

Formulas:

section Section1;

shared VSTables = let
    Source = Sql.Database("ctserver.database.windows.net", "ctdemo"),
    dbo_VSTables = Source{[Schema="dbo",Item="VSTables"]}[Data]
in
    dbo_VSTables;

shared Incident = let
    Source = Sql.Database("ctserver.database.windows.net", "ctdemo"),
    dbo_Incident = Source{[Schema="dbo",Item="Incident"]}[Data]
in
    dbo_Incident;

**Comment by boefraty74** [comment]
1) Did you do any changes, or it is just template? 
2) Do you have latest PBI desktop? 
3) Did you try: 
>pbiviz new myName -t rhtml
>cd myName
>npm install
>pbiviz package

**Comment by helen508light** [comment]
outdated
