### ISSUE TITLE
data set row counts

### ISSUE THREAD

**Issue by mipugh** [microsoft/PowerBI-visuals#179]
Is it possible to have 2 different `dataRoles ` in a custom visual that accept different numbers of row? I have them set to "Do not summarize".

I've tried creating this but when I drag a column with 'n' rows into one and a column with 'm' rows into the other, I get an error.

Update: I tried creating 2 different "table" mappings in the `dataViewMappings` section of the capabilities.json, but then no data at all was passed to the visual's `update` method.

**Comment by helen508light** [comment]
Now there is no way because by design dataRoles dimension should be the same to reduce errors and complicated binding

**Comment by emmasaunders** [comment]
PLEASE take me off this list! I have tried GitHub unsubscribe multiple times but it doesn’t work
