### ISSUE TITLE
How to upload new visualization to PowerBI?

### ISSUE THREAD

**Issue by webinfographer** [Microsoft/PowerBI-visuals#18]
Hi,
I have created a new visualization and would like to use it in powerbi. What is the possible way to upload it on powerbi.

Regards

**Comment by spatney** [comment]
There are two ways your visualization can end up in Power BI. 

1. You contribute it to this repository, and if we accept it, it will be available for every user of Power BI.
2. In the near future, we will provide details + tools that will allow you to add visuals for personal use, or on your organization's Power BI tenant.

**Comment by webinfographer** [comment]
Thanks spatney for your prompt response.
