### ISSUE TITLE
Category values are being parsed as dates when they should not be.

### ISSUE THREAD

**Issue by verneroberts** [Microsoft/PowerBI-visuals#181]
Recently something has changed in Power BI and the dataview that is provided in the updateModel function has attempted to create date objects out of text objects so things come through as "Invalid Date" or "Epoch" for nulls.

This is affecting pre-existing custom visuals that have had no code changes and are already released and live so ideally this should be fixed in Power BI.

Currently it does not seem possible to retrieve a text value from the category.

Here you can see the object recieved into the updateModel method:
![object recieved from api](https://cloud.githubusercontent.com/assets/1232285/25827843/4230c23e-34a1-11e7-9460-ec36adeef560.PNG)
Here you can see the data view as show using the developer visual in Power BI online:
![show dataview in online dev tool](https://cloud.githubusercontent.com/assets/1232285/25827873/5d8d76ee-34a1-11e7-87cd-2c94c70eeb8c.PNG)

![capabilities](https://cloud.githubusercontent.com/assets/1232285/25827929/a354dda2-34a1-11e7-98f2-94c4c638de2c.PNG)

**Comment by verneroberts** [comment]
Further to this, this appears to only exibit itself if the FIRST category value is NULL.
Datasets with NULL in the middle or no NULL value at all seem come through ok.

**Comment by ignatvilesov** [comment]
Hello @verneroberts 

It is a known issue. The fix will be shipped soon.

**Comment by nickeeromo** [comment]
I am still having the problem when using the online version.  The only way around it this point that I can find is to give values to the blank/null values in the dataset before import.

**Comment by tosta1989** [comment]
Hi verneroberts , 
this issue is already fixed please update to the latest version of power bi desktop.
