### ISSUE TITLE
GET https://localhost:8080/assets/status net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by kiewic** [Microsoft/PowerBI-visuals#184]
Even I successfully ran `pbiviz --install-cert` and `pbiviz start`, I keep getting the following error in the developer tools console:

```bash
GET https://localhost:8080/assets/status net::ERR_INSECURE_RESPONSE
```

And at the same time, the *Developer Visual* shows the following error:

> Can't contact visual server
> Please make sure the visual server is running and configured correctly. [Learn more](https://aka.ms/powerbideveloperpbivizservererror)

As a work around, I navigate to `https://localhost:8080/assets/status`, click on *ADVANCED* and then click on *Proceed to localhost (unsafe)*. Then, I reload the *Developer Visual*  and it works. However, after some time, the error always comes back and I have to apply the workaround again.

What is the right way to fix this error?

Thanks,
Gilberto

P.S. When I navigate to `https://localhost:8080/assets/status` using Chrome, I see this additional information:

> This server could not prove that it is localhost; its security certificate is from [missing_subjectAltName]. This may be caused by a misconfiguration or an attacker intercepting your connection. Learn more.

**Comment by pawelfus** [comment]
Thanks for the workaround!

**Comment by MitjaBezensek** [comment]
I'm having this same issue. The proposed solution seems to work for me. A couple of days everything worked just fine, then suddenly this problem appeared.

**Comment by scharly3** [comment]
Same problem here ...

**Comment by GarySweeting** [comment]
Same issue here - didn't have this the first 6 months.

**Comment by AviSander** [comment]
Hello - please install latest version of the toolset. The certificate has been updated and fixes this issue.
thx.
