### ISSUE TITLE
Cannot add another Capability

### ISSUE THREAD

**Issue by KangJiYoung** [Microsoft/PowerBI-visuals#189]
I tried to add a tooltip capability in order to select what columns to add to the tooltip and I get this errpr:

> instance.dataViewMappings[0].categorical additionalProperty "tooltip" exists in instance when not allowed

My capabilities.json is: 
`"dataRoles": [
        {
            "displayName": "Category Data",
            "name": "category",
            "kind": "Grouping"
        },
        {
            "displayName": "Measure Data",
            "name": "measure",
            "kind": "Measure"
        },
        {
            "displayName": "Tooltips",
            "name": "tooltip",
            "kind": "Grouping"
        }
    ],
    "dataViewMappings": [
        {
            "conditions": [
                {
                    "category": {
                        "max": 1
                    },
                    "measure": {
                        "max": 1
                    },
                    "tooltip": {
                        "min": 0,
                        "max": 3
                    }
                }
            ],
            "categorical": {
                "categories": {
                    "for": {
                        "in": "category"
                    }
                },
                "tooltips": {
                    "for": {
                        "in": "tooltip"
                    }
                },
                "values": {
                    "select": [
                        {
                            "bind": {
                                "to": "measure"
                            }
                        }
                    ]
                }
            }
        }
    ]`

**Comment by AviSander** [comment]
Hello -
     was this what you meant? you had a schema violation.
thx, avi

            "categorical": {
                "categories": {
                    "select": [
                        {
                            "for": {
                                "in": "category"
                            }
                        },
                        {
                            "for": {
                                "in": "tooltip"
                            }
                        }
                    ]
                },
                "values": {
                    "select": [
                        {
                            "bind": {
                                "to": "measure"
                            }
                        }
                    ]
                }
            }
