### ISSUE TITLE
is there a tutorial  for ubuntu or othere linux version to use this repo and open the Start Page and build it ?

### ISSUE THREAD

**Issue by joostshao** [Microsoft/PowerBI-visuals#189]
- First

```
ubuntu@ubt:~/PowerBI-visuals/src/Clients/PowerBIVisualsPlayground$ http-server 
Starting up http-server, serving ./
Available on:
  http:127.0.0.1:8080
  http:192.168.1.101:8080
Hit CTRL-C to stop the server
```

but it lack of some files:

```
powerbi-visuals.js:3067 Uncaught TypeError: Cannot read property 'createClassAndSelector' of undefined
DistrictSalesData.ts:29 Uncaught TypeError: Cannot read property 'DataViewTransform' of undefined
(index):53 Uncaught TypeError: Cannot read property 'initialize' of undefined
```

- Second 

and at the build Directory, it also occurs.

```
textMeasurementService.ts:62 Uncaught TypeError: Cannot read property 'createClassAndSelector' of undefinedpowerbi.TextMeasurementService.powerbi.TextMeasurementService @ textMeasurementService.ts:62powerbi @ textMeasurementService.ts:370(anonymous function) @ 
textMeasurementService.ts:371
(index):112 Uncaught TypeError: Cannot read property 'visualPluginFactory' of undefined
```
the index.html file is from 
https://github.com/Microsoft/PowerBI-visuals/wiki/Displaying-visuals-in-a-single-html-page

ubuntu@ubt:~/PowerBI-visuals/build$ tree
.
├── index.html
├── scripts
│   ├── externals.min.js
│   └── powerbi-visuals.js
└── styles
    └── visuals.css

2 directories, 4 files

some one can help me ?

**Comment by sgrebnov** [comment]
Fixed in master branch by the following commit, @joostshao could you please see if it works for you now
https://github.com/Microsoft/PowerBI-visuals/commit/eb11270809c152b8698c43795cd4c7d3df70aa4c

**Comment by joostshao** [comment]
thank you very much , it works now.
