### ISSUE TITLE
Subtotals for matrix

### ISSUE THREAD

**Issue by fredrikheden** [microsoft/PowerBI-visuals#196]
How can I get access to total rows for a matrix type dataviewmapping? Is there any way to define a customizeQuery for instance?

**Comment by liprec** [comment]
In the matrix `dataviewmapping` you are not getting a special row for (sub)totals. You need to calculate those by yourself in the visual.

In the end all visuals will get the same columns and rows based on the field assignment. The dataviewmapping will organize those records differently and expose to the visual. Also I have noticed that the table and matrix type can be used with larger datasets that the categorical type.
