### ISSUE TITLE
Please fix the fonts in the playground sample app

### ISSUE THREAD

**Issue by pedramrezaei** [Microsoft/PowerBI-visuals#20]

**Comment by spatney** [comment]
Appropriate fall backs added

**Comment by pedramrezaei** [comment]
Not fixed!

**Comment by spatney** [comment]
closing out this issues, since the general issue has been fixed(ie, the fall back for the app itself). I have assigned other bugs to tackle the font issues with individual visuals that are not using the regular fallbacks.
