### ISSUE TITLE
Window.Open() blocked by iframe not having "allow-top-navigation" flag

### ISSUE THREAD

**Issue by mcowley5** [Microsoft/PowerBI-visuals#201]
**Use case:**
A user clicks a chart bar and is navigated to another report view with a custom filter set via query string parameters based on the bar they clicked.

**Problem:**
The iframe that contains the visual doesn't have the flag "allow-top-navigation" and blocks the navigation.
Access Denied

**Reproduction steps:**

1. Add a click handler to the chart bar.  bars.on('click', function(d) {}
2. Variable "d.Category" is the value required.
3. Window.Open("UrlOfReport" + "?filter=Table/Column eq d.Category", "_blank");

**Comment by AviSander** [comment]
Hello mcowley5 -
    This is done on purpose presently for security\isolation reasons. We are currently working on adding Url navigation APIs from the custom visual.
Hopefully this will reach SU09 which is the Sept release.
thx.

**Comment by mcowley5** [comment]
Thanks for the response AviSander
