### ISSUE TITLE
Visual tool Query 

### ISSUE THREAD

**Issue by ritz301** [microsoft/PowerBI-visuals#202]
![outlookstoreuserflown](https://user-images.githubusercontent.com/10402990/27386649-1adab98a-56b4-11e7-95b3-e4ff0b0ade9f.png)
Hi,
I want to create this kind of visualization in powerBI. The edges represents the number of users moving along that path which I want to display alongside the edge. These numbers may vary when for a particular date and client (which are the dimensions). Is there an existing visual/tool similar to this? 
Thanks.

**Comment by helen508light** [comment]
you can find edges and links in ForceGraph visual
