### ISSUE TITLE
Document dataReductionAlgorithm

### ISSUE THREAD

**Issue by ABKimmel** [Microsoft/PowerBI-visuals#207]
There is literally no documentation about the `dataReductionAlgorithm` property of the `dataViewMappings`. The only place I've seen it mentioned in this repo is issue #44, and that is just a single example. Is it the only way you can configure it or are there more ways? 

This is just another example of the poor documentation of this repo and the whole process for creating custom visualizations.

**Comment by liprec** [comment]
If it helps you (for the time being):

## Syntax
`"dataReductionAlgorithm" : { "<algorithm>" : { "count": "<count>" } }`

The *`algorithm`* values:
-  **top** - Reduce the data to the Top count items
- **bottom** - Reduce the data to the Bottom count items
- **sample** - Reduce the data using a simple Sample of count items
- **window** - Allow the data to be loaded one window, containing count items, at a time

The *`count`* value is the approximate maximum items available for the visual.

If no `dataReductionAlgorithm` is provided, a *top 1000* is used as reduction algorithm.

## Samples
Bottom 4,000 items of a dataset: 
`"dataReductionAlgorithm": { "bottom": { "count": 4000 } }`

Top 50,000 items of a dataset:
`"dataReductionAlgorithm": { "top": { "count": 50000 } }`

**Comment by ABKimmel** [comment]
Thank you! This is really helpful. A follow-up question: Your example shows getting the top 50,000 items, but Issue #44 indicates that there is a hard limit of 30,000 items. Have you gotten 50,000 items into a visual before? I've been trying to get a dataset that is ~45,000 into a visual with no luck so far.

**Comment by liprec** [comment]
I don't have some actual test with this size of datasets, but I recall that the SandDance visual had a limit of 50,000 items. But I could be wrong about the limit or it is changed in the time and it is set to 30,000.

**Comment by liprec** [comment]
Created a PR (#208) to add it to the current documentation.

**Comment by ignatvilesov** [comment]
The current limitation is 30,000.
We suppose that it's more than enough for custom visuals.

**Comment by ABKimmel** [comment]
@ignatvilesov Is there a reason you guys picked 30,000 as opposed to a higher number? It just seems like a very arbitrary cut off point.

**Comment by jamescorey** [comment]
How does the window algorithm work? Can it get past the 30 000 row limit?

**Comment by ABKimmel** [comment]
Closed by #226
