### ISSUE TITLE
Increase or remove the limit on the number of rows that can be brought into a custom visual.

### ISSUE THREAD

**Issue by ABKimmel** [microsoft/PowerBI-visuals#209]
As listed in Issues #44 and #207 , there is a cap of 30,000 rows of data that get brought into the visual when update is called. This is very limiting for many enterprise visuals and the limit should be removed or increased dramatically.

It should be on the visual creator to keep the performance of the visual at an acceptable level, and the visuals should not be artificially limited by the data they are handed.

**Comment by erapade** [comment]
For quality reasons, I would strongly recommend to not show any data (or even better, show a standard image saying there's to much data). 
Will this be something that every visual shall handle, or is this a change for the Power BI tools and services. If each visual, is there a code pattern for this?

**Comment by jamescorey** [comment]
Is there a way to allow more than 30 000 rows if you dont visualize them?  I have written a custom visualization that needs to iterate through each record, but i cant get past this data reduction algorithm.

**Comment by ryanbaumann** [comment]
I'm running into this issue as well developing a map visual where data volume is the key to a great visual.  A user needs to create a heat map from up to 500k individual records -> currently we cannot achieve this with PowerBI.

**Comment by ignatvilesov** [comment]
There's no way to get more than 30000 data-rows.

**Comment by ABKimmel** [comment]
@ignatvilesov But why is there an arbitrary limit at 30,000? Why not 50,000? 200,000? Why limit it at all?

**Comment by jamescorey** [comment]
I've come a cross articles saying Pro users can export 150 000 rows. Is this valid for custom visualizations? 

You could potentially do a lot with power bi and custom visualizations, much more than just visualize data. But this 30 000 row limit puts a stop everything.

**Comment by ABKimmel** [comment]
That 150,000 row limit is for exporting from Power BI to a `.xlsx` file, unfortunately.

**Comment by AviSander** [comment]
Also -if  you use R visuals or Custom visuals based on R then you can use up to 150000 rows.

**Comment by ABKimmel** [comment]
@AviSander Do you have an explanation for why visuals are limited to 30,000 rows?

**Comment by chetan2309** [comment]
@AviSander - Could you please reply @ABKimmel answer why there is 30K limit if you represent PBi team. We are also running into the same issue.

Thanks,
Chetan

**Comment by vitaly-livshits** [comment]
@AviSander , can you please comment on the above? 

This is an increasingly significant limitation within the custom visual ecosystem. 30,000 rows is a low limit for some custom visualizations, including the Mapbox visualization that @ryanbaumann 's team is developing.

If this limit is in place primarily for historical reasons perhaps it can be increased, eliminated, or made overridable by the visualization itself?

**Comment by meng1313** [comment]
This record limit is a significant limitation for us as we are required to plot all records on the map - we were attracted to Mapbox because it COULD handle large volumes of data and plot many records on a map (I was told by the Mapbox team that they could plot all census blocks across the U.S.), however this record limit in Power BI makes the Mapbox functionality much less valuable.  

Can this limitation be removed?

**Comment by rconjaerts** [comment]
Is there any update on this? 

I don't get why custom visuals get this limit when you expect users to use this as their number one visualisation tool. Is it because you can't control the performance, and you don't want users to use a shitty visualisation and blame Microsoft for it when it crashes due to the amount of data?

**Comment by liprec** [comment]
You can take a look at the `fetchMoreData` method: https://microsoft.github.io/PowerBI-visuals/api/references/fetchmoredata/ which is introduced with API v1.12.
With this method you can overcome the limit of 30.000 data points and load until the hard limit of 100MB is reached.

My experience is that the support with the development visual is a bit strange: only one 'page' is loaded as the method is returning `false`, but the `options` are telling there is more data to load...

**Comment by arriad2tkapilap** [comment]
Has anyone tried out @liprec's workaround. Can you overcome 30,000 row limit using fetchmoredata option?

**Comment by maximnl** [comment]
When a size field is used it seems that powerbi map cuts points , without it i could see all my points (i have <16000 points with lat lon.

**Comment by maheshabhi** [comment]
@arriad2tkapilap Yes, I have tried out @liprec  solution. Using fetchmoredata API, we can bypass 30k rows of data

**Comment by maheshabhi** [comment]
// indicates this is the first segment of new data.
    if (options.operationKind == VisualDataChangeOperationKind.Create) {    
            dataView = options.dataViews[0]; // Get Data from the Dateview array
            console.log("dataview ", dataView.table.rows);
        }   
        // on second or subesquent segments:
        if (options.operationKind == VisualDataChangeOperationKind.Append) { 
            dataView = options.dataViews[0]; // Get Data from the Dateview array

            console.log("dataview", dataView); 
        } 
        if (dataView.metadata.segment) {
            //request for more data if available
            let request_accepted = this.host.fetchMoreData();
            // handle rejection
            // for example when the 100MB limit has been reached
            if (!request_accepted) {
                console.log("error");  
            }  
        }

**Comment by djouallah** [comment]
please, does anyone have a fork we can use with this workaround, i am not a developer, so I can't do it myself.

**Comment by otravers** [comment]
@helen508light can you please shed more light on what it means that you closed this issue. Does this mean the 30K datapoint limitation stays and won't be revisited?

**Comment by Zahma** [comment]
@maheshabhi have tried the fetchMoreData() but it doesn't work ... can you share the complete code with us ?
