### ISSUE TITLE
DataRoleHelper

### ISSUE THREAD

**Issue by deldersveld** [Microsoft/PowerBI-visuals#21]
I really like this new dev experience!

Is DataRoleHelper or an equivalent module available?

**Comment by wesyao** [comment]
Awesome!!

Do you mean a section in the documentation where it talks about dataroles? If so, it's here (i also added it in the table of contents).

https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/Capabilities/Capabilities.md#define-the-data-fields-your-visual-expects---dataroles

**Comment by deldersveld** [comment]
Related, but not quite what is in the documentation. 

In the old code, we could define capabilities and then import DataRoleHelper like so.
`import DataRoleHelper = powerbi.data.DataRoleHelper;`

Later on, we could get the index of roles regardless of which order they were dragged into the field well. For example, if multiple measures were defined for Latitude, Longitude, Measure, and Description; we could easily get the index for each in the following manner:
`lngIndex = DataRoleHelper.getMeasureIndexOfRole(dataViews[0].categorical.values.grouped(), "Longitude");   
latIndex = DataRoleHelper.getMeasureIndexOfRole(dataViews[0].categorical.values.grouped(), "Latitude");   
measureIndex = DataRoleHelper.getMeasureIndexOfRole(dataViews[0].categorical.values.grouped(), "Measure");   
descriptionIndex = DataRoleHelper.getMeasureIndexOfRole(dataViews[0].categorical.values.grouped(), "Description");`

**Comment by spatney** [comment]
Correct, that isn't available as yet. We will be adding more helper libraries to the mix soon that will allow you to read information out of the DataView in a systematic fashion.  I'll attach this issue to a milestone in the next couple of days so you'll be able to track when it get delivered.

**Comment by deldersveld** [comment]
Perfect, thanks

**Comment by wesyao** [comment]
Hopefully we've answered your questions, let us know if you have more issues.

**Comment by sso7159** [comment]
#21

**Comment by AviSander** [comment]
completed
