### ISSUE TITLE
Document Data Binding to Capabilities object

### ISSUE THREAD

**Issue by tkawchak** [Microsoft/PowerBI-visuals#212]
I'm looking for more documentation on how to bind properties in a capabilities file (it looks like only color pickers are currently available) to a datapoint.  There is very basic information on this [here](https://github.com/Microsoft/PowerBI-visuals-core/wiki/Capabilities#partial-highlights-sort--drill), but I haven't found anything that describes how I can access the data when it is updated in the dataview (where is the updated color).  Also, I am not able to add the necessary properties described in the link to the capabilities file, as I get the error "Property fillRule is not allowed."

**Comment by ABKimmel** [comment]
[This](https://github.com/ABKimmel/Power-BI-Visualization-Development-Tutorial/blob/master/docs/advanced/SettingsDefinitions.md) should cover what you want. Disclaimer: I wrote it.

**Comment by tkawchak** [comment]
Thanks @ABKimmel.  Great resource!  I also found documentation [here](https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Objects.md).  I was confused because I was only finding the [older version](https://github.com/Microsoft/PowerBI-visuals-core/wiki/Capabilities) of the api.
