### ISSUE TITLE
Don't understand how to connect, error is can't contact visual server

### ISSUE THREAD

**Issue by wil40484** [microsoft/PowerBI-visuals#213]
Not sure where I need to make edits to the code. How do I test a visual? Tutorials are terrible for all of this. I don't even know where to input code to create. Someone help? Do I use visual studio? What?

**Comment by ABKimmel** [comment]
Hi Josh,

If you are trying to use the live reloading, be sure you have [installed SSL certificates for localhost](https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/CertificateSetup.md), and [enabled developer tools](https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/DebugVisualSetup.md). It's also worth noting that you can only do live preview with the online service, not with desktop. 

You don't have to use VS, though VS Code is pretty good. You can use any text editor you want.

There are two main places where you will want to change code, [capabilities.json](https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Capabilities.md) and [visual.ts](https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/DataBinding.md#defining-and-using-visualtransform). Capabilities is where you will set what data you take in, and visual is where you actually render the visualization. (Sorry those are the only links I have to offer you, I know they are pretty unhelpful)

I would suggest looking at a [couple](https://github.com/Microsoft/powerbi-visuals-sankey) [of the](https://github.com/Microsoft/powerbi-visuals-enhancedscatter) [visuals](https://github.com/Microsoft/powerbi-visuals-gantt) that are out there to get an idea of what they look like.

If you have any questions, leave them here and I'll try to answer them.
