### ISSUE TITLE
Can't import many libraries

### ISSUE THREAD

**Issue by domoritz** [microsoft/PowerBI-visuals#217]
Right now importing D3v4 doesn't work as described in https://github.com/Microsoft/PowerBI-visuals/issues/98. The problem is that PowerBI seems to be overwriting global variables. The error messages are also not very useful right now. 

Is there a workaround for external libraries?

**Comment by domoritz** [comment]
Another example: https://github.com/Microsoft/PowerBI-visuals/issues/99

**Comment by domoritz** [comment]
And https://github.com/Microsoft/PowerBI-visuals/issues/142

**Comment by ryanbaumann** [comment]
I'm running into this issue creating a mapbox-gl based custom visual as well.  The `mapboxgl` object is recognized as a type in my PowerBI IVisual class extension, but the `mapboxgl` object is not scoped to be accessable in the IVisual class.
