### ISSUE TITLE
Errors are silenced

### ISSUE THREAD

**Issue by domoritz** [microsoft/PowerBI-visuals#221]
How do I make sure that errors in my custom visual are visible on the console?

**Comment by ABKimmel** [comment]
A really terrible workaround would be to wrap everything in `update()` in a `try ... catch` that manually sends the errors to the console, then returns. We really shouldn't be forced to do that though if we want error messages.

**Comment by domoritz** [comment]
Here is what I did:

```ts
try {
} catch (e) {
  this.target.innerHTML = `${e.message} ${e.stack}`;
  console.error(e.message, e.stack);
}
```

While this at least shows errors, it doesn't correctly link to the sourcecode.

**Comment by ryanbaumann** [comment]
@domoritz I had the same issue.  Following the debug instructions here helped -> https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/debugging.md

One note is that all errors are silenced BEFORE your functions like update() (such as in the constructor).  Make sure your source of an error is not in those functions.

**Comment by domoritz** [comment]
@ryanbaumann Thank you for the link. Unfortunately the code from that page does not compile and I get the following error

```
[ts]
Type '<T>(target: Object, propertyKey: string, descriptor: TypedPropertyDescriptor<Function>) => TypedP...' is not assignable to type 'MethodDecorator'.
  Types of parameters 'descriptor' and 'descriptor' are incompatible.
    Type 'TypedPropertyDescriptor<T>' is not assignable to type 'TypedPropertyDescriptor<Function>'.
      Type 'T' is not assignable to type 'Function'.
(parameter) target: Object
```

**Comment by CleberDSantos** [comment]
```export function logExceptions(): MethodDecorator {

        return function (target: Object, propertyKey: string, descriptor: TypedPropertyDescriptor<any>): TypedPropertyDescriptor<any> {

            return {
                value: function () {

                    try {
                        return descriptor.value.apply(this, arguments);
                    } catch (e) {
                        console.error(e);
                        throw e;
                    }
                }
            }
        }

    }
```
![image](https://user-images.githubusercontent.com/1626423/31356456-717cc830-ad14-11e7-9bb0-ce10624106d9.png)

**Comment by LinqLover** [comment]
The type declarations produce lots of errors as stated by @domoritz. Using @CleberDSantos' approach works well for me! (Still, you cannot use the decorator for constructors, but that appears to be a general TypeScript problem.)
