### ISSUE TITLE
Timeline slicer - unable to select single date

### ISSUE THREAD

**Issue by tonytha** [microsoft/PowerBI-visuals#225]
Timeline slicer is selecting the next day in addition to the currently selected date.

**Comment by ABKimmel** [comment]
I think you are reporting this in the wrong place. You would have better luck on the [forums](http://community.powerbi.com/t5/Desktop/bd-p/power-bi-designer) and it looks like it has already been [covered](http://community.powerbi.com/t5/Desktop/Timeline-Issue/m-p/56918/highlight/true#M23199) there.
