### ISSUE TITLE
Blank Boxes - custom visual only

### ISSUE THREAD

**Issue by isabeli-m** [Microsoft/PowerBI-visuals#229]
The sample bar graph example doesn't work on my Desktop Power BI. However, the built in visuals work. The CLI is downloaded and installed, that's how I created the new visualization directory. I typed in pbiviz new [folder name] -t rhtml, then cd [folder name], and pbiviz package. This created the pbiviz file, which I opened using power BI. It loads, but then does not show an image. What could I be doing wrong?

**Comment by ABKimmel** [comment]
Hi isabeli,

Are you trying to load up the sample bar chart they provide, or are you trying to create a new R visual? 

If you want to load up the sample bar chart, you should clone [this repo](https://github.com/Microsoft/PowerBI-visuals-sampleBarChart), then run `npm install` followed by `pbiviz start` in the root of the directory.  Once you do that, you have to put data into the chart before it will show anything. If you want documentation beyond what is available in this repo, check out [this tutorial](https://github.com/ABKimmel/Power-BI-Visualization-Development-Tutorial) I wrote.

If you are trying to create a new R visual, you are on the right track with the -t rhtml, which will set up the project directory to have all the things you need for an R visual.

**Comment by ignatvilesov** [comment]
Hello @isabeli-m ,

What version of Power BI Desktop do you use?
I suppose that PBI Desktop is out dated and doesn't support API that is used in sample-bar-chart.

**Comment by ABKimmel** [comment]
I'm on `2.47.4766.542` and it works fine for me.

**Comment by isabeli-m** [comment]
Hi, 

I was trying to create a new custom visual, and I got it to show by turning off the proxy on my work computer. 

Thanks for the help
