### ISSUE TITLE
Slider Objects

### ISSUE THREAD

**Issue by domoritz** [Microsoft/PowerBI-visuals#230]
How do I create a slider object like

![image](https://user-images.githubusercontent.com/589034/28889693-a90d31de-7779-11e7-8bfb-ffbc0675cc79.png)?

The documentation at https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/StaticObjects.md doesn't explain how to specify the range of valid values.

**Comment by ignatvilesov** [comment]
There's no way to specify a range of values.
The current range is 8pt - 40pt.

**Comment by ABKimmel** [comment]
@domoritz You could use an [enumeration](https://github.com/ABKimmel/Power-BI-Visualization-Development-Tutorial/blob/master/docs/advanced/SettingsDefinitions.md#enumerations) instead of a slider. It's not as elegant, but it gets the job done.

**Comment by akash273** [comment]
Hii Kimmel,
can you please reply here for this issue 228
https://github.com/Microsoft/PowerBI-visuals/issues/228

**Comment by domoritz** [comment]
@ignatvilesov I found a way in the tutorial: https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/SliderControl.md. What did you mean is not possible?
