### ISSUE TITLE
What can we do to help update the roadmap?

### ISSUE THREAD

**Issue by whitneyland** [microsoft/PowerBI-visuals#235]
Hello @ABKimmel et al,

The roadmap is out of date, and also factually incorrect.  Can help be offered to improve this situation?

Having this kind of document out of date (while being referenced many times) hurts Microsoft's strategic efforts to continue the momentum and success of Power BI, by putting speed bumps in the way of 3rd parties trying to build solutions that provide value-add to the ecosystem.

It may not be quite as easy for an outsider to do, but maybe googling whatever is available from all Microsoft sources and the Internet in general could yield some improvements.  Would such a PR be accepted?

Or if it should be done internally, but you are overloaded at the moment, that's no problem, what if we start by setting expectations on when a roadmap update could realistically be made available?

Whatever the action, what would it take to improve the situation?

https://github.com/Microsoft/PowerBI-visuals/blob/master/Roadmap/README.md

**Comment by helen508light** [comment]
We are in documentation replacements process. Roadmap is up-do-date on MSDocs
