### ISSUE TITLE
Formatting in modelling tab not working in custom table visual 

### ISSUE THREAD

**Issue by akash273** [Microsoft/PowerBI-visuals#236]
Hi,
 
I have created new simple custom table visual but i am unable to use the formatting % feature in modelling tab in desktop.
 
Please check below image
![modelling tab1](https://user-images.githubusercontent.com/23463341/29218081-a44e7892-7e81-11e7-9249-78535bb5de71.PNG)

**Comment by ignatvilesov** [comment]
You should select a column in `Fields` pane. After you you might apply formats.

**Comment by akash273** [comment]
@ignatvilesov   I already selected fields in pane even still it is not showing up. 
**Note: This is my own custom table visual not power bi table visual**

**Comment by liprec** [comment]
You have to format the values yourself in your custom visual. Via the dataview object the unformatted numbers and used format is provided to the visual. Take a look at these powerbi utils for easy formatting the numbers: https://www.npmjs.com/package/powerbi-visuals-utils-formattingutils
