### ISSUE TITLE
External library: Telerik KendoUI throws exception in PowerBI's sandbox

### ISSUE THREAD

**Issue by whileoneloop** [Microsoft/PowerBI-visuals#239]
There is an incompatibility between PowerBI's sandbox and the Kendo UI component library.  The following exception is raised by the library:

```
Uncaught TypeError: Illegal invocation
    at <anonymous>:562:21817
    at <anonymous>:562:27218
    at <anonymous>:563:18554
    at <anonymous>:563:18651
    at t.kendo.t.kendo.cultures (<anonymous>:562:21)
    at Window.<anonymous> (<anonymous>:562:59)
    at <anonymous>:841:20
    at Object.r [as injectJsCode] (visualhostcore.min.js:2)
    at i.loadWithoutResourcePackage (visualsandbox.min.js:1)
    at i.executeMessage (visualsandbox.min.js:1)
```

Difficult to explore further without the non-minified source for the library.  A repo demonstrating the problem:

https://github.com/whileoneloop/kendo-ui-power-bi-visual

Also posted in the developer forum:

http://community.powerbi.com/t5/Developer/Exception-raised-when-using-Telerik-Kendo-UI-components-in/m-p/231248#M7292

Anyone had success using this library in the custom visual sandbox?

**Comment by ignatvilesov** [comment]
You have to include these code lines into your code:
```JavaScript
Object.defineProperties(window, {
    'devicePixelRatio': {
        get: function () {
            return window.window.devicePixelRatio;
        }
    },
    'innerWidth': {
        get: function () {
            return window.window.innerWidth;
        }
    }
});

var kendo = { cultures: {} };
window.kendo = kendo;
window.window.kendo = kendo;
```

Please note that these code lines should included before other code.

Please take a look at [this pull request](https://github.com/whileoneloop/kendo-ui-power-bi-visual/pull/2) to find out more.

**Comment by whileoneloop** [comment]
Thanks ignatvilesov, that has fixed the issue.  I will try the same approach with the DevExpress component that is throwing a different (but perhaps related) error re a prop missing from window object.
