### ISSUE TITLE
Power BI desktop custom visuals

### ISSUE THREAD

**Issue by sureshamathew** [Microsoft/PowerBI-visuals#242]
All the documentation here seems to refer to developing custom visuals for Power BI cloud service. Can the custom visual be used on the Power BI desktop as well? If so, is there some documentation on that? I've created the pbiviz package on my local machine and I've imported the same into my Power BI desktop. But the visual isn't running... it comes up as a blank plane.

**Comment by ABKimmel** [comment]
Custom visuals should be cross compatible across desktop and web clients. Is it working on web?

**Comment by sureshamathew** [comment]
I don't have a web account. I only have the power BI desktop. The visual
that I am trying to use is the sample visual that's on the group - the one
with the update count changing as I resize the window.

On Aug 21, 2017 10:37 AM, "Ben Kimmel" <notifications@github.com> wrote:

Custom visuals should be cross compatible across desktop and web clients.
Is it working on web?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/PowerBI-visuals/issues/242#issuecomment-323759524>,
or mute the thread

**Comment by sureshamathew** [comment]
Issue was fixed. I just had to pull some random data into the visual and the visual updated itself.
