### ISSUE TITLE
D3 V3 integration into Microsoft Power BI

### ISSUE THREAD

**Issue by sureshamathew** [microsoft/PowerBI-visuals#243]
I am new user of Power BI and I am looking to create some custom visualizations using D3.js. 
So I'd like to start with this visualization : http://bl.ocks.org/d3noob/8375092

Is there a good place that provides guidance on how to convert the example code shown on the D3 webpages into code that's compatible for Power BI visual?

**Comment by ABKimmel** [comment]
Provided the sandboxing in Power BI doesn't break D3, you should be able to basically copy-paste the D3 and then adapt it for your use case.

**Comment by sureshamathew** [comment]
Thanks. So, in the particular example that I shown, should all of the code that's in between <script> and </script> should go into the "update" function.... or should the code be placed in some other fashion.

**Comment by ABKimmel** [comment]
You can do it that way, with the exception of the `update` function in the code you've given. You'll want to pull that out and rename it. You probably also want to look at rewriting the code in TypeScript.

**Comment by prakhar112** [comment]
I have absolutely the same problem sureshamathew. If I just copy paste the code given then it does not get integrated properly into PowerBi. How do you solve the issue?

**Comment by uve** [comment]
Hello @prakhar112, please follow this tutorial to build your visual with d3 support:
https://github.com/Microsoft/PowerBI-visuals-sampleBarChart
