### ISSUE TITLE
DataReductionAlgorithm window type

### ISSUE THREAD

**Issue by ghost** [microsoft/PowerBI-visuals#244]
I've read the documentation but still I do not understand how the window algorithm works.
Is it possible to set multiple windows with 30 000 rows each , or is the sum of all windows capped at 30 000? If it is the latter; can you access each window from typescript?

**Comment by ABKimmel** [comment]
As far as I know, each window maxes out at 30,000 rows each. That said, there's never been any documentation on how to get a window beyond the first one, and looking at the typing file for the Power BI framework, there is no currently supported way to read beyond the first window. I would love to be proven wrong though...
