### ISSUE TITLE
Distinguish update() calls that come from a selection?

### ISSUE THREAD

**Issue by joergplewe** [Microsoft/PowerBI-visuals#247]
Hi all!

Whenever somewhere in a report a selection is performed, my visual gets an update() call with a reduced set of data corresponding with the selection. 
I saw other visuals like the common charts react on the selection by highlighting parts of their content in constrast to replacing their complete data content. How do they do it? How do they know the data provided in update() comes from a selection?

Do I miss something completely?

Thanks in advance,

. Jörg

**Comment by uve** [comment]
hello @joergplewe,
 To use highlighting in your visual, just define the following parameter in capabilities.json, e.g.:
https://github.com/Microsoft/PowerBI-visuals-ChicletSlicer/blob/master/capabilities.json#L447

**Comment by joergplewe** [comment]
Thank you @uve for the hint.

From there on, how is the visual notified and how does it notify about the highligthing?

**Comment by uve** [comment]
@joergplewe **update** method will be triggered in all visuals in the report.
Special **[highlights](https://github.com/Microsoft/PowerBI-visuals-ChicletSlicer/blob/master/src/converter.ts#L154-L156)** object in dateviews will include all highlighted elements.

**Comment by joergplewe** [comment]
Ah great @uve , see it.

Finally, how does my visual trigger a highlighting itself?

**Comment by uve** [comment]
@joergplewe, Visuals don't highlight anything, they use selection only. Visuals choose type of selection/highlight themselves.
