### ISSUE TITLE
Selection from 'table' data

### ISSUE THREAD

**Issue by joergplewe** [Microsoft/PowerBI-visuals#248]
Hi all!

Is there a HOWTO for creation of selections on 'table' data? I failed with everything I tried so far.

Thank you very much,

. Jörg

**Comment by ABKimmel** [comment]
It is currently impossible to create selections with anything other than `categorical` mappings. See: Issue #77 and #48.

**Comment by uve** [comment]
Hello @joergplewe,
 Try to use the following workaround:
https://github.com/Microsoft/PowerBI-visuals/issues/77#issuecomment-321750225

**Comment by joergplewe** [comment]
Hello @uve, I tried that but failed. It delivers good amounts of selectionIds which are all empty.

**Comment by uve** [comment]
@joergplewe,
please send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>, we'll check it.

**Comment by domoritz** [comment]
@ABKimmel @uve Is it true that highlighting also only works for categorical mappings? It would be great if this was documented.

**Comment by joergplewe** [comment]
@uve, 
please disregard my objection, I finally could bring it to work. 
Sample project is attached. Thank you very much! 

[tableSelection.zip](https://github.com/Microsoft/PowerBI-visuals/files/1287156/tableSelection.zip)

**Comment by uve** [comment]
@joergplewe, great!
