### ISSUE TITLE
developer visual - cannot test

### ISSUE THREAD

**Issue by g4ege** [microsoft/PowerBI-visuals#252]
I have created the cert, rebooted, etc. and still see "Can't contact visual server"  in any browser - Firefox, Chrome, IE, Edge.  

http://localhost:8080/assets/status 
This site can’t provide a secure connection

localhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

Please advise.

C:\Users\gensminger\CustomVisual\d3joy>pbiviz info
 info   visual.name.................. d3joy
 info   visual.displayName........... d3joy
 info   visual.guid.................. d3joy837542688F614557827642DA7EB05EDC
 info   visual.visualClassName....... Visual
 info   visual.version............... 1.0.0
 info   visual.description...........
 info   visual.supportUrl............
 info   visual.gitHubUrl.............
 info   apiVersion................... 1.7.0
 info   author.name..................
 info   author.email.................
 info   assets.icon.................. assets/icon.png
 info   externalJS................... [ 'node_modules/powerbi-visuals-utils-dataviewutils/lib/index.js' ]
 info   style........................ style/visual.less
 info   capabilities................. capabilities.json
 info   dependencies................. dependencies.json
 info   stringResources.............. []

**Comment by uve** [comment]
@g4ege,
Use HTTPS protocol:
https://localhost:8080/assets/status
