### ISSUE TITLE
R HTML visual showing blank

### ISSUE THREAD

**Issue by William-Ch** [Microsoft/PowerBI-visuals#255]
Hi all,

I created an R HTML visual from template "rhtml" follow the tutorial (https://github.com/Microsoft/PowerBI-visuals/blob/master/RVisualTutorial/CreateRHTML.md). I tried to test on server and package it then import to Power BI desktop, without any change.

Either way it showed a blank box as screenshot below (not return error, which looks R scrip is fine). 
![blank pbi r custom visual](https://user-images.githubusercontent.com/29701039/30728556-2c66f66a-9f9c-11e7-8e07-a9d914eee3ce.JPG)

Thank in advance

**Comment by ignatvilesov** [comment]
Hello @William-Ch 

Thank you for your feedback.
We'll investigate this issue.

**Comment by boefraty74** [comment]
Hi @William-Ch, 
If I understand correctly, it does not work in Power BI desktop.  
Please update your Desktop for recent version. If it still does not work, please send me your PBIX file for investigation.

**Comment by William-Ch** [comment]
Hi @boefraty74, thanks for reply
My Power BI desktop is up-to-date version (2017 September).
It didn't work in both developer testing on Power BI Service and import custom visual on Power BI desktop after packaged.
I will send you PBIX file.
Thanks

**Comment by boefraty74** [comment]
Hi @William-Ch , 
Let's focus only on Power BI desktop.  Only these: 

```
> pbiviz new someName -t rhtml
> cd someName
> npm install 
> pbiviz package

```
Let me know

**Comment by William-Ch** [comment]
Hi @boefraty74, 
I tried the code, but didn't work, still blank. Any recommendation for next?
Thanks

**Comment by boefraty74** [comment]
Hi @William-Ch, 
Is it possible to get from you the whole your custom visual folder for further investigation?

**Comment by William-Ch** [comment]
Hi @boefraty74, 
I have sent you the whole folder, please check.

**Comment by boefraty74** [comment]
Hi @William-Ch , 
Please replace line 
 `el.appendChild(document.createTextNode(window.atob(payloadBase64)));`
By 
` el.innerHTML = window.atob(payloadBase64);`
Inside **_src\visual.ts_**

We are still investigating why it is wrong in your version of pbiviz 
Let me know if it helped

**Comment by William-Ch** [comment]
Hi @boefraty74, 
It works perfectly now. Please let me know if you can figure out why the template generates wrong code.
Thanks!

**Comment by boefraty74** [comment]
My team is preparing a fix for it.  Thanks to you,  we found this issue in powerbi-visuals-tools 1.7.4

**Comment by uve** [comment]
Hi @William-Ch, @boefraty74 
powerbi-visuals-tools 1.7.5 has been published.

**Comment by boombranco** [comment]
Hey @boefraty74, I am having this exact same issue that William was having, however, the update to 1.7.5 did not helped. Not sure if you have found anything else that could be causing issues?
Thanks!

**Comment by boefraty74** [comment]
Hi @boombranco , 
I guess you tried all the proposed solutions from above. Is it possible to get from you the whole your custom visual folder for further investigation?

**Comment by boefraty74** [comment]
Hi @boombranco , 
Did you have any progress with your issue?

**Comment by boombranco** [comment]
Hey @boefraty74 I emailed you a copy of my pbix report and the test rhtml files that I was using for this example. Did you not receive that? I can send again if needed. Thanks.

**Comment by christinamarie13** [comment]
Having the same problem as well, with no luck from any of the above fixes. No errors pop up when the code runs, but the visual is completely blank.

**Comment by fparedesg** [comment]
I also had a blank visual showing up on the Desktop client (with the 1.7.5 pbiviz update), but I realized I had a July version of Power BI. Updating to the latest version now shows the visual.

**Comment by christinamarie13** [comment]
@fparedesg Updating it worked perfectly, thanks so much!

**Comment by boefraty74** [comment]
Hi @boombranco, 
I did not get anything :( 
You can share it with github/onedrive/dropbox/google drive etc.,  but don't sent ZIP. 
My email is boefraty @ microsoft . com
