### ISSUE TITLE
Illegal invocation error with leaflet

### ISSUE THREAD

**Issue by CleberDSantos** [Microsoft/PowerBI-visuals#256]
pbiviz.json

"apiVersion": "1.7.0",
  "externalJS": [
    "node_modules/powerbi-visuals-utils-dataviewutils/lib/index.js",
    "node_modules/jquery/dist/jquery.min.js",
    "node_modules/geojson/geojson.min.js",
    "node_modules/leaflet/dist/leaflet.js"
  ],

----------------------
typings.json

{
  "globalDependencies": {
    "geojson": "registry:dt/geojson#1.0.0+20170130182553",
    "jquery": "registry:dt/jquery#1.10.0+20170310222111",
    "leaflet": "registry:dt/leaflet#1.0.0+20170324151803"
  }
}

-------------------------------------------
tsconfig.json

"files": [
      ".api/v1.7.0/PowerBI-visuals.d.ts",
      "node_modules/powerbi-visuals-utils-dataviewutils/lib/index.d.ts",
      "node_modules/epe-pbiviz/src/pbiViz.ts",
      "typings/index.d.ts",
      "src/visual.ts" 
    ]

error:

![image](https://user-images.githubusercontent.com/1626423/31035747-7c070eaa-a53f-11e7-910a-0e0aab7079c1.png)

![image](https://user-images.githubusercontent.com/1626423/31035663-364a9cf6-a53f-11e7-8bb8-a92435a553ba.png)

Uncaught TypeError: Illegal invocation
    at <anonymous>:2398:22
    at version (<anonymous>:532:3)
    at Window.<anonymous> (<anonymous>:533:2)
    at <anonymous>:14274:20
    at Object.r [as injectJsCode] (VM10819 visualhostcore.min.js:2)
    at i.loadWithoutResourcePackage (VM10820 visualsandbox.min.js:1)
    at i.executeMessage (VM10820 visualsandbox.min.js:1)
    at i.onMessageReceived (VM10820 visualsandbox.min.js:1)
    at VM10820 visualsandbox.min.js:1
    at e.invokeHandler (VM10819 visualhostcore.min.js:2)

**Comment by uve** [comment]
@CleberDSantos, try to install latest powerbi-visuals-tools@1.7.5 and try it again.

**Comment by CleberDSantos** [comment]
I'm still having the same issue. :/

![image](https://user-images.githubusercontent.com/1626423/31074596-c3d7e9ca-a747-11e7-92bb-95423a89dfae.png)

![image](https://user-images.githubusercontent.com/1626423/31074624-e3ac32b0-a747-11e7-8d0a-beba827c7e74.png)

**Comment by uve** [comment]
@CleberDSantos please send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>

**Comment by CleberDSantos** [comment]
I sent the e-mail. Thanks

**Comment by CleberDSantos** [comment]
I used that approach: https://github.com/Microsoft/PowerBI-visuals/issues/163#issuecomment-304045990

![image](https://user-images.githubusercontent.com/1626423/31146536-7b9bedac-a85d-11e7-86e4-69b561873ca1.png)

**init.js**
```
(function () { 
    window = this; 
}()); 
```
It's working fine now:
![image](https://user-images.githubusercontent.com/1626423/31146588-a2891bce-a85d-11e7-8aa9-a72363b57b34.png)
