### ISSUE TITLE
After Starting Server through PowerShell, It is not Responding on Power Bi Service (Developer Mode Visual)

### ISSUE THREAD

**Issue by mgbhargava** [Microsoft/PowerBI-visuals#257]
Actually I am beginner , After Starting Server through PowerShell, It is not Responding on Power Bi Service (Developer Mode Visual) while changing logic in code .Can You suggest me how to manage this problem

![image](https://user-images.githubusercontent.com/19591746/31043151-d0528cc4-a5d4-11e7-91b6-ec592f36b180.png)

![image](https://user-images.githubusercontent.com/19591746/31043162-20aebb3e-a5d5-11e7-86ad-9459507338f0.png)

**Comment by uve** [comment]
Hello @mgbhargava,
 C:\windows\system32 is not a best place for keeping files during development, please choose another directory.  
Regarding not responding service, probably there are some mistakes in your code, please share your console logs.
