### ISSUE TITLE
How can I get organization chart visual working?

### ISSUE THREAD

**Issue by fsrodriguezm** [microsoft/PowerBI-visuals#258]
I'm trying to use this code but I can't find the pbiviz file anywere.

https://github.com/jianingyan/PowerBI-visuals/blob/master/src/Clients/Visuals/visuals/graph.ts

**Comment by uve** [comment]
Hello @fsrodriguezm, it's fork from https://github.com/Microsoft/PowerBI-visuals-core
This repository has been deprecated, so please follow the official guide:
https://github.com/Microsoft/PowerBI-visuals
