### ISSUE TITLE
Illegal invocation error with highcharts

### ISSUE THREAD

**Issue by SamuelRodriguesdosAnjos** [Microsoft/PowerBI-visuals#259]
**pbiviz.json**

`
"apiVersion": "1.7.0",
"externalJS": [
    "node_modules/powerbi-visuals-utils-dataviewutils/lib/index.js",
    "node_modules/jquery/dist/jquery.js",
    "node_modules/highcharts/highcharts.js",
    "externalJS/init.js"
  ]
`

**typings.json**

`
{
  "globalDependencies": {
    "highcharts": "registry:dt/highcharts#4.2.5+20161025153818",
    "jquery": "registry:dt/jquery#1.10.0+20170310222111"
  }
}
`

**tsconfig.json**

`
"files": [
    ".api/v1.7.0/PowerBI-visuals.d.ts",   
    "typings/index.d.ts",
    "src/visual.ts"
  ]
`

**Version:**
1.7.0 or 1.7.5

![image](https://user-images.githubusercontent.com/10775437/31130585-2fac8a8e-a82e-11e7-9176-25f092bae167.png)

**Server:**

![image](https://user-images.githubusercontent.com/10775437/31129650-99224290-a82b-11e7-9c65-7275a552a002.png)

![image](https://user-images.githubusercontent.com/10775437/31129738-cfa10b26-a82b-11e7-90fa-41bd84d620c8.png)

**Error:**

![image](https://user-images.githubusercontent.com/10775437/31129581-61ba0162-a82b-11e7-932a-9cd2aed9628c.png)

Uncaught TypeError: Illegal invocation
    at a.offset (<anonymous>:10797:148)
    at a.Pointer.normalize (<anonymous>:10974:294)
    at a.Pointer.onContainerMouseMove (<anonymous>:10986:228)
    at HTMLDivElement.e.onmousemove (<anonymous>:10988:342)
a.offset @ :sourcemap:10797
normalize @ :sourcemap:10974
onContainerMouseMove @ :sourcemap:10986
e.onmousemove @ :sourcemap:10988

**Comment by uve** [comment]
@SamuelRodriguesdosAnjos looks like code issue.
Please send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>, we'll check it.

**Comment by SamuelRodriguesdosAnjos** [comment]
I just sent the email.
Thank you

**Comment by SamuelRodriguesdosAnjos** [comment]
@Maksim Galiev and @uve 

Resolved

`window.pageYOffset = Object.defineProperty(window, "pageYOffset", {
    get: function() {
        return window.window.pageYOffset;
    }
});

window.pageXOffset = Object.defineProperty(window, "pageXOffset", {
    get: function() {
        return window.window.pageXOffset;
    }
});
`

I await version 1.8

Thank you
