### ISSUE TITLE
pbiviz start: error  UNKNOWN { Error: ENOENT: no such file or directory, open 'C:\repos\PowerBI-visuals\.api\v1.4.0\schema.stringResources.json'

### ISSUE THREAD

**Issue by kiewic** [microsoft/PowerBI-visuals#261]
Running `pbiviz start` in an existing visualizations results in the following error:

```bash
C:\repos\PowerBI-visuals>pbiviz start
 info   Building visual...
 error  UNKNOWN { Error: ENOENT: no such file or directory, open 'D:\repos\PowerBI-visuals\.api\v1.4.0\schema.stringResources.json'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\repos\\PowerBI-visuals\\.api\\v1.4.0\\schema.stringResources.json' }
```

Consider [this custom visual][repo] that was compiling fine for months, but when upgrading *powerbi-visuals-tools* from **1.7.1** to **1.7.5** started failing with the mentioned error.

Is this a known CLI bug?

Thanks,
Gilberto

[repo]: https://github.com/kiewic/PowerBI-WaffleChart

**Comment by CleberDSantos** [comment]
try to update your api: ` pbiviz update`

for example:

![image](https://user-images.githubusercontent.com/1626423/31260687-ef99b670-aa25-11e7-86e0-b04039ae9ae1.png)

![image](https://user-images.githubusercontent.com/1626423/31260715-2a67355c-aa26-11e7-873a-a2295ad0fb7b.png)

**Comment by KristofferBerge** [comment]
Trying to start a project using api v1.4.0, with CLI version 1.8.0 installed throws the same error.
Running pbiviz update does not change anything. The schema.stringResources.json is still missing in the v1.4.0 folder. 

The project starts after manually adding the missing file. Grabbed a copy from an empty v1.8.0 project that looks like this:

**schema.stringResources.json**
`{
    "PBI_API_VERSION": "v1.8.0",
    "type": "object",
    "properties": {
        "locale": {
            "$ref": "#/definitions/localeOptions"
        },
        "values": {
            "type": "object",
            "description": "translations for the display name keys in the capabilities",
            "additionalProperties": { "type": "string" }
        }
    },
    "required": [ "locale" ],
    "definitions": {
        "localeOptions": {
            "description": "Specifies the locale key from a list of supported locales",
            "type": "string",
            "enum": [
                "ar-SA",
                "bg-BG",
                "ca-ES",
                "cs-CZ",
                "da-DK",
                "de-DE",
                "el-GR",
                "en-US",
                "es-ES",
                "et-EE",
                "eu-ES",
                "fi-FI",
                "fr-FR",
                "gl-ES",
                "he-IL",
                "hi-IN",
                "hr-HR",
                "hu-HU",
                "id-ID",
                "it-IT",
                "ja-JP",
                "kk-KZ",
                "ko-KR",
                "lt-LT",
                "lv-LV",
                "ms-MY",
                "nb-NO",
                "nl-NL",
                "pl-PL",
                "pt-BR",
                "pt-PT",
                "ro-RO",
                "ru-RU",
                "sk-SK",
                "sl-SI",
                "sr-Cyrl-RS",
                "sr-Latn-RS",
                "sv-SE",
                "th-TH",
                "tr-TR",
                "uk-UA",
                "vi-VN",
                "zh-CN",
                "zh-TW"
            ]
        }
    }
}
`

**Comment by uve** [comment]
@KristofferBerge, why do you need api v1.4.0? localizations are not available on any version less than v1.7
Please use latest v1.8.0 version

**Comment by KristofferBerge** [comment]
It's not that I need v1.4.0, and I don't need localization either. The problem is that it seems the CLI is not able to run older projects because the api folder is missing the localization file, even though it is not supported by older versions of the api.

**Comment by kiewic** [comment]
I'm getting the same result as @KristofferBerge 

My custom visual was originally created with `.api/v1.4.0` and the CLI (which is installed globally) is not able to *start* or *update* the project.

IMO the CLI needs to be backward-compatible.

**Comment by uve** [comment]
@KristofferBerge, @kiewic, it seems that it's regression bug. I'll add it to pbiviz-tool roadmap.

**Comment by sugo-85** [comment]
![image](https://user-images.githubusercontent.com/64470929/84575706-d9f70680-adcc-11ea-92f2-5808ae943266.png)

Can anyone help me ?

**Comment by helen508light** [comment]
@sugo-85 
which version of API, tools and Node.js do you use?
