### ISSUE TITLE
VisualHost applyJsonFilter

### ISSUE THREAD

**Issue by jay-pillai** [Microsoft/PowerBI-visuals#263]
In a custom visual if we have to filter both the category and series (basically two different columns) at the same if we invoke applyJsonFilter sequentially the second column does not get filtered.

**Comment by jay-pillai** [comment]
Does applyJsonFilter send the query to the database if the data is coming through DirectQuery?

**Comment by uve** [comment]
Hello @jay-pillai,
Unfortunately, applyJsonFilter doesn't support filtering for more than one category.

**Comment by jay-pillai** [comment]
thanks @uve.

The API 1.8.1 has added FilterAction enum to applyJsonFilter which has both merge and remove. Could you please let me know the use of the same.

https://github.com/Microsoft/PowerBI-visuals-tools/blob/master/templates/visuals/.api/v1.8.0/PowerBI-visuals.d.ts#L1368

**Comment by AviSander** [comment]
merge is the default action: apply the filter.
remove is to effectively clear the current filter.
