### ISSUE TITLE
High CPU usage for interactive R visual

### ISSUE THREAD

**Issue by deldersveld** [Microsoft/PowerBI-visuals#266]
I have an RHTML visual that I am attempting to publish to AppSource. A failure on initial review states that "Your add-in sustained an increase in CPU usage", with CPU peaking at 100% each time a field change is made in Power BI Desktop. This occurs testing with both R and Microsoft R Open.

The CPU spike still occurs and reaches 100% even with data reduction down to *100* values.

Similar CPU usage occurs with other R visuals such as Clustering with Outliers, but those made it into the store with this defect. I'm assuming that's because they are from Microsoft. Are there suggestions or fixes for limiting CPU use with RHTML visuals so that they can pass this check?

[Sample CPU with my DT visual](https://i.imgur.com/qNS9dn2.png)
[Sample CPU with Clustering with Outliers visual](https://i.imgur.com/eEBygk5.png)

Code:
```
source('./r_files/flatten_HTML.r')

############### Library Declarations ###############
libraryRequireInstall("DT");
####################################################

################### Actual code ####################
if (!exists("settings_rdatatable_params_method"))
{
    settings_rdatatable_params_method = "5";
}

if (!exists("settings_rdatatable_params_showColumnFilters"))
{
    settings_rdatatable_params_showColumnFilters = "top";
}

p <- datatable(Values, 
		class = 'cell-border compact stripe hover', 
		rownames = FALSE, 
		filter = settings_rdatatable_params_showColumnFilters, 
		width = "100%", 
		extensions = list('Scroller'), 
		options = list(
			pageLength = settings_rdatatable_params_method,
			lengthMenu = c(5, 10, 25, 50, 100, 1000),
			autoWidth = FALSE,
			scrollX = "100%",
			scrollY = "50vh",
			scroller = TRUE
		)
	)
####################################################

############# Create and save widget ###############
internalSaveWidget(p, 'out.html');
####################################################
```

**Comment by ignatvilesov** [comment]
Hello David,

We're really sorry to heat that your visual has been rejected.

We'll investigate this issue deeper and back with suggestions.

**Comment by boefraty74** [comment]
Hello @deldersveld, 
Can you please share with me your project (for example via github)? 
Including sample PBIX. We will work together to make it happen, 

You can also contact me directly:   boefraty @ microsoft . com

**Comment by deldersveld** [comment]
Thank you for looking into it. My code is available [here](https://github.com/deldersveld/rDataTable) in the source directory. Sample PBIX is in the [packaged-versions](https://github.com/deldersveld/rDataTable/tree/master/packaged-versions) directory of that repo.

**Comment by boefraty74** [comment]
Hi @deldersveld , 
I forked your repository and did a very few changes (dependencies only). 
Here it is: 
https://github.com/boefraty74/rDataTable/tree/work/source

There was a fix to the validation VMs recently, it might impact the performance of RCVs.  
Once you resubmit, let me know and I’ll keep in touch with the validation team to make sure it is not rejected with strange reasons like before. 
Unfortunately, I can not submit it for you. 

In addition, please have a look at some metadata (short/long descriptions, icons, sample.pbix  etc), for example in:
https://github.com/Microsoft/powerbi-visuals-funnel/tree/master/assets

Please don't give up, we want your cool visual in the store. As an author of several R custom visuals I went through the process of re-submission many times and may assist you.

**Comment by deldersveld** [comment]
Thanks Boris. I've reviewed your changes and merged them into my branch. I'll try to resubmit in the next day or two, and I will let you know how it goes. Thank you for taking a look at this. I appreciate it.

**Comment by deldersveld** [comment]
@boefraty74, the visual was published to AppSource today. Thanks for all your help getting it through the process!
