### ISSUE TITLE
Cannot run project. 

### ISSUE THREAD

**Issue by skymanaditya1** [Microsoft/PowerBI-visuals#267]
I am trying to use Power BI - Visuals in a MVC based asp.net web application.

However, when I run the sample project with Internet Explorer I get the following exception -> 
![exception](https://cloud.githubusercontent.com/assets/9744692/12354271/cbd5414c-bbba-11e5-86f8-1fd53c6fb916.PNG)

When I run the project with Google Chrome, the project builds without any exception, I do not get a drop down on "Select a visual" and "Data View" (pretty much the web page does not display anything). 

![chrome_run](https://cloud.githubusercontent.com/assets/9744692/12354322/26d2a03a-bbbb-11e5-9caa-59399bf34825.PNG)

I have node.js v5.4.1 installed and npm 3.3.12 version installed. I am running the project on Visual Studio 2013 Ultimate edition. 

The messages displayed on the console while doing a npm install in PowerBI-Visuals directory are ->
![start_exception](https://cloud.githubusercontent.com/assets/9744692/12354375/85b21392-bbbb-11e5-9a0d-4c44e7c732a1.PNG)

**Comment by v-kazaki** [comment]
It seems to be that you have to add reference to jQuery library into your ASP.NET MVC page.

**Comment by skymanaditya1** [comment]
Thanks a lot. I will try it out.
