### ISSUE TITLE
The filter not working

### ISSUE THREAD

**Issue by CleberDSantos** [microsoft/PowerBI-visuals#267]
I'd like to filter the data on my custom visualization maps

![image](https://user-images.githubusercontent.com/1626423/31914927-6e3a6b2e-b82b-11e7-9c78-b07f3c09693a.png)

I created selectionId for each marker data, when I select I  call the function:

```  this.selectionManager.select(selectedIds).then((ids: ISelectionId[]) => { }) ;```

Result: 

![image](https://user-images.githubusercontent.com/1626423/31915188-4ac69bee-b82c-11e7-8652-f31a9236c285.png)

Is it possible to apply to filter on my visualization?

Because the inverse filter it's working fine, for example:

![image](https://user-images.githubusercontent.com/1626423/31915424-28477830-b82d-11e7-96b7-d395177014c4.png)

![image](https://user-images.githubusercontent.com/1626423/31915576-b5d5f8d4-b82d-11e7-9b81-d71cfd064b60.png)

**Comment by uve** [comment]
@CleberDSantos are you trying to filter the map visual itself?

**Comment by CleberDSantos** [comment]
Yes I'd like to filter the map visual itself.

I add the new properties on capabilities.json:

![image](https://user-images.githubusercontent.com/1626423/31947407-0367ff9a-b8b3-11e7-8b0a-cad30e21d463.png)

Is it required to set initial value? 

and there isn't properties on tab, is it ok? 

![image](https://user-images.githubusercontent.com/1626423/31947597-6e12976a-b8b3-11e7-992a-c230587c02a5.png)



@uve It's not working yet, now any filter is not working :/

![image](https://user-images.githubusercontent.com/1626423/31948262-2da3689c-b8b5-11e7-95f2-feff9dd4ec69.png)

1: now is not filtered, before was working
2: It's working
3: the map not filtered itself

Can I use the https://github.com/Microsoft/powerbi-visuals-utils-interactivityutils ? or I don't need it or Is there another project that uses this?

**Comment by joemensor** [comment]
It appears that SelectionManager is no longer working. This is a big problem for us as replacing with InteractivityUtils is not an option right now.

**Comment by uve** [comment]
@CleberDSantos, yes, please try to integrate https://github.com/Microsoft/powerbi-visuals-utils-interactivityutils to your project.

**Comment by uve** [comment]
Hello @joemensor,
 SelectionManager should work properly. Please send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>. 
We'll investigate the issue.
