### ISSUE TITLE
Error installing tools

### ISSUE THREAD

**Issue by deldersveld** [microsoft/PowerBI-visuals#268]
A number of users running Windows 7 get this error when running "npm install -g powerbi-visuals-tools" in the Node.js command prompt. Any insight as to why they're not able to install the tools on Win 7 x64?
![image](https://user-images.githubusercontent.com/11548654/32289130-45c18e60-bf0c-11e7-8346-b3ef134fe467.png)

**Comment by uve** [comment]
@deldersveld, could you please install the latest version of NodeJS and NPM and try it again.
