### ISSUE TITLE
Custom Visual not updating in realtime on dashboard

### ISSUE THREAD

**Issue by chriskabat** [Microsoft/PowerBI-visuals#27]
I am fairly new to custom visual development.  I have a pretty simple control that allows you to select a bunch of fields and it displays a number of values in the last/bottom record in some HTML.   It works fine on a report and brings in new data (from stream analytics into a Power BI data source) if I hit refresh.   However, when I pin to a dashboard, it doesn't update like other controls.   Is there something special I need to implement to get the update method called again with new data?   My capabilities.json is below, hopefully something simple.  Is there maybe some documentation I'm missing?

{
  "dataRoles": [
    {
      "displayName": "TextFields",
      "name": "textFields",
      "kind": 2
    }
  ],
  "dataViewMappings": [
    {
      "table": {
        "rows": {
          "for": { "in": "textFields" },
          "dataReductionAlgorithm": { "bottom": { } },
          "rowCount": { "preferred": { "min": 1 }, "supported": { "min": 1 } }
        }
      }
    }
  ]
 }

**Comment by spatney** [comment]
Is "textfield" a date? cos otherwise it won't get sorted right. The data in a DB is always considered unsorted, and we try to sort it by the role. Alternatively you can create a sort for a column while modelling the data in Power BI desktop.

**Comment by spatney** [comment]
I hope you got this to work, closing this issue, please reopen if you have an update or further questions.
