### ISSUE TITLE
plugin Does not show up in PowerBIVisualsPlayground plugins list

### ISSUE THREAD

**Issue by christoferhansen** [Microsoft/PowerBI-visuals#270]
i create a new iVisual item as the documentation says, named "CalenderView"

Now as per documentation it says it need to uncomment this code to be able to see my plugin in the 
PowerBIVisualsPlayground plugin list, i have done that. But it is not displaying in the PowerBIVisualsPlayground plugin list. I have also tried to put this code in the plugins.ts, but still no result.

How can i fix this problem, thanks a lot in advanced ...

/* Creating IVisualPlugin that is used to represent IVisual. */
//
// Uncomment it to see your plugin in "PowerBIVisualsPlayground" plugins list
// Remember to finally move it to plugins.ts
//
module powerbi.visuals.plugins {
    export var calenderview: ivisualplugin = {
        name: 'calenderview',
        capabilities: calenderview.capabilities,
        create: () => new calenderview()
    };
}

**Comment by istiakk** [comment]
there are couple of error in your code.

in the first line `ivisualplugin `it Should be `IVisualPlugin`

Change your class and capabilities name from `calenderview `to `Calenderview`

So the answer is :

```
export var calenderview: IVisualPlugin = {
    name: 'calenderview',
    capabilities: Calenderview.capabilities,
    create: () => new Calenderview()
};
```

Hope it will help you.

**Comment by mingjunfan** [comment]
I got a same issue

**Comment by getsetbro** [comment]
After you make several capitalization changes in your visual you will need to add your file ref to the list in tsconfig.json

**Comment by mashhype** [comment]
I did everything in Steps above and still do not see my new visual.

**Comment by mashhype** [comment]
Ok I now see my visual.  I needed to rebuild using Gulp.  For some reason the rebuild in VS2015 is not working.
