### ISSUE TITLE
Basic Filter/Advance Filter to Support Highlight Method Issue

### ISSUE THREAD

**Issue by capono** [Microsoft/PowerBI-visuals#271]
We shifted from selectionIds/selctionbuilder/selectionmanager method to the new basic filter method, since this method saves a lot of memory. 

But we realised that doing so, you cannot highlight other visuals in the dashboard, they all only get filtered. Is there a possibility to still use Highlight function on another visual and keeping the Basic Filter method?

A further question would be what does the selfFilter method in the capabilities.json do is there any documentation how to use it?

**Comment by uve** [comment]
Hello @capono,
 If you use basic filter, all data in the reports will be filtered. So it's not compatible with highlighting.

selfFilter is related to filter data inside of the visual. The documentation for selfFilter is not ready yet.
