### ISSUE TITLE
Custom visuals blank out when in dashboard

### ISSUE THREAD

**Issue by Rumsas** [microsoft/PowerBI-visuals#273]
I am experiencing an issue with custom visuals when they are pinned as a dashboard tile.
After a random period of time (less than 1hour) the contents of the custom visuals in the dashboard disappear.

Dashboard is build from various reports, using various types of connections:
Direct query to sql server;
Daily import from sql server;
Excel files from sharepoint;
Custom visuals are used with Direct query report.

We are having this dashboard displayed on a screen in our office and it's important that tiles stay visible at all times. I have tried loading data both ways - in DirectQuery and Import mode, in both instances the bug remains. Could you help, please?

**Comment by uve** [comment]
Hello @Rumsas, thank you for your feedback.
It's know issue and it will be fixed soon.

**Comment by helen508light** [comment]
already fixed
