### ISSUE TITLE
how to downgrade to older pbiviz version 

### ISSUE THREAD

**Issue by Mxesli** [Microsoft/PowerBI-visuals#277]
My company is using an older version for the powerbi report server but i only have the newest pbiviz api so my visual doesnt run in the Power Bi Desktop RS and dont run's on the Server, so how can i uninstall my pbiviz and how to install the pbiviz api version 1.5.0 ?

**Comment by uve** [comment]
@Mxesli, try to run the following command:
npm install -g powerbi-visuals-tools
pbiviz update 1.5.0
