### ISSUE TITLE
Bug: VisualUpdateType ResizeEnd 36 instead of 32

### ISSUE THREAD

**Issue by capono** [Microsoft/PowerBI-visuals#280]
enum VisualUpdateType {
        Data = 2,
        Resize = 4,
        ViewMode = 8,
        Style = 16,
        ResizeEnd = 32,
        All = 62,
    }
In Api 1.8.0 the ResizeEnd is enumed as 32.
But getting the options.type from an update in Power Bi the only value which appears on finishing the resizing is 36, which is not on the list. I assume it is the ResizeEnd enum. Would be nice, if you could fix that.
Further, I would like to know what update option.type Style is used for?

**Comment by uve** [comment]
@AviSander could you please check this bug?
