### ISSUE TITLE
TypeError: 'get length' called on an object that does not implement interface Window.

### ISSUE THREAD

**Issue by Mxesli** [Microsoft/PowerBI-visuals#281]
i am gettings this error on edge and firefox with my custom visual, any one know how to fix this cause my visual doesnt even show up in firefox/egde...

Error: 

> 11:24:54.844 TypeError: 'get length' called on an object that does not implement interface Window. VisualSandboxMinimal.htm:14:1039
	n

**Comment by Mxesli** [comment]
the strange thing is in the cloud my visual is working fine on firefox but when i publish my report with my visual to my own report server i am getting the error...

**Comment by uve** [comment]
@Mxesli please send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>, we'll check it.

**Comment by youranupama** [comment]
Were you able to solve this issue? We having same issue in our custom visual. Any guidance  will be helpful.

**Comment by uve** [comment]
@youranupama please your source code to pbicvsupport@microsoft.com also.

**Comment by youranupama** [comment]
@uve this is fixed with the help of Ignat.
