### ISSUE TITLE
could not connect to visual server

### ISSUE THREAD

**Issue by rabbanisyed** [Microsoft/PowerBI-visuals#283]
i am receiving an error "could not connect to visual server"  even after ran the command pbiviz start, is success running on port 80 and i have seen the </> icon in pbi

**Comment by uve** [comment]
@rabbanisyed, Here is a workaround:

Open https://localhost:8080/assets/status in broser manually.
You will get an error message: Your connection is not secure.
Click advanced button.
Click Add exception button and add this url to exception list.
Try to refresh the page with your report, visual should be loaded correctly.
