### ISSUE TITLE
Property Pane R Custom Visuals seems not to work

### ISSUE THREAD

**Issue by tomatminceddata** [microsoft/PowerBI-visuals#284]
Hey,
I'm following the instructions from the tutorial for the R Cusotm Visual "Funnel". 
I created a new rvisual and a new rhtml visual using the template from api version 1.9.0

I'm using the following final files from the tutorial 
capabilities.json
src/visual.ts
scrip.r
r_files/utils.r

and creating the pbiviz by using the command: pbiviz package 

The visual will be created, and works well, but without the possibility to use any of the configured properties.

I'm using Bower BI Desktop (Release November 2017)

Maybe I'm  missing a very simple thing, but I have no currently no idea.

Regards Tom

**Comment by uve** [comment]
Hello @tomatminceddata,
 please follow this documentation to add properties:
https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/StaticObjects.md

**Comment by tomatminceddata** [comment]
Hey @uve, please excuse the late response. I have been off for a couple of days, awkward experience. I will give it a try next week.
