### ISSUE TITLE
Is there documentation available for capabilities/objects/dataPoint/properties/defaultColor ?

### ISSUE THREAD

**Issue by kiewic** [Microsoft/PowerBI-visuals#284]
I am creating a custom visualization, and the only reference in the wiki for color settings I found is the [Objects (Formatting Objects)][formatting] section.

I have copied and pasted the `dataPoint` definition from the Funnel Chart into my chart, but I do not see the *Data Colors UI* when importing my visual into the Power BI client.

![Data Colors UI][colors_ui]

I am missing something, and I cannot figure it out what it is.

[formatting]: https://github.com/Microsoft/PowerBI-visuals/wiki/Capabilities#objects-formatting-objects
[colors_ui]: https://raw.githubusercontent.com/Microsoft/PowerBI-visuals/resources/capabilities/funnel_caps_objects_ui.PNG

Additionally, I would like to understand what other formatting options are available to integrate into my visualization.

Thank you,
Gilberto.

**Comment by spatney** [comment]
You also need to implement the enumerateObjectInstances function and return those objects with instance values as shown [here] (https://github.com/Microsoft/PowerBI-visuals/wiki/Hello-IVisual) in step five. 

Alternatively you can look at funnel charts implementation of enumerate. The reason for needing both is we use this mechanism to allow you to perform data validation on property values (say a 1000 was the max number you can input) or hide certain properties in some scenarios (by not returning them).

**Comment by kiewic** [comment]
Implementing `enumerateObjectInstances` worked perfectly.

Thank you!
