### ISSUE TITLE
Dynamically populated dropdown in property pane

### ISSUE THREAD

**Issue by szilardhuber** [microsoft/PowerBI-visuals#285]
I'm developing a custom visual in which the user should be able to select values from options coming from an API call. If I add an enumeration type object to `capabilities.json` I can only add predefined values there. I have also discovered that in `enumerateObjectInstances` there is a `validValues` property in the `objectEnumeration` and that I can pass an array to that but unfortunately this way I can only limit the options in the dropdown and can't add any options that was not predefined in `capabilities.json`. 

If I change the type of the object to `text` the `validValues` property works as expected but I have a text field on the property pane instead of a combobox.

My expectation would be to be able to either extend the options for `enumeration` type objects with `validValues` or if I set the `validValues` for `text` type objects then I would see a dropdown instead of a textbox on the property pane.

Is there a way to achieve what I need?

**Comment by uve** [comment]
@szilardhuber, dynamically populated dropdown is not supported yet.

**Comment by szilardhuber** [comment]
Thank you @uve . Could you give some hint on what timeframe can we expect this feature?

**Comment by uve** [comment]
@szilardhuber, unfortunately, there's no ETA for this feature yet.

**Comment by ryanbaumann** [comment]
@uve has there been any change in the status of this ticket?

**Comment by helen508light** [comment]
@ryanbaumann it still not supported
