### ISSUE TITLE
Difference between options for Measure in portal and desktop 

### ISSUE THREAD

**Issue by sjkp** [Microsoft/PowerBI-visuals#286]
I have a custom visual, with custom capabilities, one of them is a defined like this:
```
  {
                    name: 'Link',
                    kind: powerbi.VisualDataRoleKind.Measure,
                    displayName: 'Link'
                },
```
In the portal, the UI allows me to select Do not summerize (which is nice since the data is supposde to be a Uri I'm using to let the user navigate to different reports. 
![image](https://cloud.githubusercontent.com/assets/3397744/12450563/e6f4a878-bf84-11e5-9721-ba5c7ebd5842.png)

In the desktop client however, I can only select, Count or Count (Distinct)
![image](https://cloud.githubusercontent.com/assets/3397744/12450636/2b812cd2-bf85-11e5-9189-7f9a9f9ec998.png)

Is it a bug or just intended?

**Comment by DenisKudelin** [comment]
This is normal, because on the portal updates arrive faster than to the desktop version.
