### ISSUE TITLE
Update count when setting up visualisation in Power BI Service stays at 0

### ISSUE THREAD

**Issue by cbrawn** [Microsoft/PowerBI-visuals#287]
When creating a new visualisation in Power BI Service the count stays at 0, rather than refreshing.
![update-count](https://user-images.githubusercontent.com/34539524/33987733-d346f71a-e0b9-11e7-9835-3f79a890f8d4.jpg)

**Comment by Blumi** [comment]
When no data source is specified, the update() method will not be triggered.
Thus, the counter will not be increased in this example.
