### ISSUE TITLE
Trying to create new charts, leaves screen blank when refreshing

### ISSUE THREAD

**Issue by cbrawn** [microsoft/PowerBI-visuals#288]
When trying to update Typescript, the chart comes back as empty in Power BI Service.  There are no errors in the code either, it comes back as saying Typescript build is complete.

**Comment by uve** [comment]
@cbrawn, check your browser console logs.

**Comment by cbrawn** [comment]
@uve, thanks for getting back to me, It's telling me it's missing a visual.js.map file?  This is happening when I'm clicking on the visual customisation to show it.

**Comment by uve** [comment]
can you send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>?
