### ISSUE TITLE
Custom Visual does not render in Edge and Firefox - TypeError: 'get length' called on an object that does not implement interface Window

### ISSUE THREAD

**Issue by youranupama** [Microsoft/PowerBI-visuals#290]
We have custom visual which is based on javascript control library. It works fine in Chrome and IE but does not render at all in Edge and Firefox. 
In Firefox, the error logged in console is "TypeError: 'get length' called on an object that does not implement interface Window".

The control itself works fine in all the browsers but when added as part of visual gives problem. 

Any idea what could be the problem. Please help as it is blocking us for releasing it.

**Comment by ignatvilesov** [comment]
I think this is due to Power BI code isolation for custom visuals.
Could you please share libraries that you use or full stack trace?

**Comment by youranupama** [comment]
Yes, i also suspect that but do not exactly know where it could be failing. Can I share the entire visual code? Please provide email id, i will send it across.

**Comment by ignatvilesov** [comment]
Yes, sure. Please send code to `pbicvsupport@microsoft.com` and `v-viig@microsoft.com`.

**Comment by ignatvilesov** [comment]
The issue was related to calling jQuery's `isArrayLike` for `window` object.
The exception is thrown since `window` object is a copy of native one that PBI creates for isolation.

Current solution is to include this code before loading jQuery:

```javascript

Object.defineProperty(window, "length", {
    get: function () {
        return window.window.length;
    },
    configurable: true,
    enumerable: true,
});

```

**Comment by youranupama** [comment]
Thanks a ton. This solved the issue.
