### ISSUE TITLE
Why if I set values for to Grouping capabilities, DataView.categorical becomes null?

### ISSUE THREAD

**Issue by kiewic** [Microsoft/PowerBI-visuals#291]
Hello,

I have two `VisualDataRoleKind.Grouping` data roles in the capabilities of my measure:

    var waffleChartCapabilities: VisualCapabilities = {
        dataRoles: [{
            name: waffleChartRoleNames.category,
            kind: VisualDataRoleKind.Grouping,
            displayName: data.createDisplayNameGetter('Role_DisplayName_Group'),
            description: data.createDisplayNameGetter('Role_DisplayName_GroupFunnelDescription')
        }, {
            name: waffleChartRoleNames.paths,
            kind: VisualDataRoleKind.Grouping,
            displayName: 'Paths',
            description: 'The value used to customize the shape of the data points',
        }, {

When using Power BI Desktop, if I set values for only one of those, I get a nice `DataView.categorical` structure.

However, if I set values for both of them, then `DataView.categorical` becomes null.

I need to pass two columns of strings to my visualization, and if I define *paths* as `VisualDataRoleKind.Measure`, I do not get *paths* in the `DataView.categorical.values`.

Thank you,
Gilberto.

**Comment by ignatvilesov** [comment]
@kiewic You can use `Table` instead of `Categorical`.
You can see table capabilities [here](https://github.com/Microsoft/PowerBI-visuals/blob/master/src/Clients/Visuals/capabilities/table.capabilities.ts).
