### ISSUE TITLE
Data extraction issue from Adobe Analytics

### ISSUE THREAD

**Issue by narendrasoni1989** [Microsoft/PowerBI-visuals#294]
While extracting data from Adobe Analytics in Power BI using APIs not able to extract all the metrics and KPIs.
It would be great if you can help me to find some other way to connect Adobe Analytics and Power BI which actually works and will help to get all data from Adobe Analytics.

**Comment by uve** [comment]
Hello @narendrasoni1989, I support this issue isn't related to CustomVisuals Development.
Please post this topic to PowerBI community forum:
https://community.powerbi.com/t5/Integrations-with-Files-and/bd-p/power-bi-services
