### ISSUE TITLE
Build procedure documentation in README.md is misleading

### ISSUE THREAD

**Issue by nomnomdom** [Microsoft/PowerBI-visuals#295]
The documentation for custom visuals is so bad that it qualifies as a software defect.

The installation instructions in README.md are badly organized.  The "Additional Instructions" located on the bottom should be moved to below the "One Time Setup" section.

Many developers will stop reading when it gets to the "How to Engage, Contribute and Provide Feedback" section, will open the project, and then get frustrated when they can't get the project to run.

It is VERY UNCLEAR that the building the solution in Visual Studio will always fail, and the "Additional Instructions" are needed to allow the project to run with a failed build.

**Comment by v-kazaki** [comment]
Thanks for feedback. README.MD was updated.
