### ISSUE TITLE
Missing documentation on how to create an IVisual using the IVisual template

### ISSUE THREAD

**Issue by nomnomdom** [Microsoft/PowerBI-visuals#296]
The documentation for custom visuals is so bad that it qualifies as a software defect.

The wiki appears to contain a random set of information on how IVisuals work, but there isn't enough information there to enable someone to actually create an IVisual.

The following would be helpful:

A walkthrough showing how to create an IVisual using the IVisual template.  Where do you place the item in the hierachy?  Does it matter?

A walkthough on how to add the new IVisual to playground.  The "remember to finally move it to plugins.ts" comment is not very clear.  It could mean either "Visuals/plugins.ts" or "CustomVisuals/plugin.ts"

A walkthrough on how to actually add content to the IVisual.

**Comment by Mike-Honey** [comment]
+1 - I'm lost too.  Please put more effort into documentation of all areas of custom visuals to make them more accessible. For a brand-new component like this, walkthroughs are essential.  At present most visitors would be disheartened and give up.

**Comment by ignatvilesov** [comment]
@nomnomdom We’ve added documentation about CustomVisual template.
You can see documentation [here](https://github.com/Microsoft/PowerBI-visuals/wiki/Create-new-Power-BI-Visuals-using-template).
We’ll add documentation about Playground soon.
