### ISSUE TITLE
New items created by the IVisual template do not compile when the filename is pascalCase

### ISSUE THREAD

**Issue by nomnomdom** [Microsoft/PowerBI-visuals#297]
1. Install the IVisual template from https://raw.githubusercontent.com/Microsoft/PowerBI-visuals/master/tools/VSIXExtensions/VisualTemplate.vsix and run Visual Studio 2015
2. Create a new item using the IVisual template and choose the default filename "newVisual.ts"
3. Compile

You will get the following error:

line:33, char:27, message: name must be in pascal case

The issue is that the generate class name is the same as the file name, and the compiler requires that the class name be in CamelCase.

**Comment by DenisKudelin** [comment]
I see that this is the tslint error and there is special checking for class names, so it must be in PascalCase. I've added the comment to the template.

Thanks!
