### ISSUE TITLE
Sample IVisualPlugin code generated by the IVisual template does not compile

### ISSUE THREAD

**Issue by nomnomdom** [Microsoft/PowerBI-visuals#298]
1. Create a new item using the IVisual template.

The generated code is similar to the following:

/* Creating IVisualPlugin that is used to represent IVisual. */
//
// Uncomment it to see your plugin in "PowerBIVisualsPlayground" plugins list
// Remember to finally move it to plugins.ts
//
//module powerbi.visuals.plugins {
//    export var NewVisual: IVisualPlugin = {
//        name: 'NewVisual',
//        capabilities: NewVisual.capabilities,
//        create: () => new NewVisual()
//    };
//}

Note that the variable being declared (line 85 in the source) is the same name as the declared class.  This will not compile.

The correct sample code should be:

module powerbi.visuals.plugins {
    export var newVisual: IVisualPlugin = {
        name: 'newVisual',
        capabilities: NewVisual.capabilities,
        create: () => new NewVisual()
    };

**Comment by DenisKudelin** [comment]
That's right. But we cannot change a case of variables in the template. You should do it manually.
Resolved #297
