### ISSUE TITLE
Developer Visual is not working for Pro Version

### ISSUE THREAD

**Issue by MahadevVasista** [Microsoft/PowerBI-visuals#298]
Hi 

I have followed the standard process as per my instructor regarding developing the custom visual in Power BI Pro Developer Service.

![image](https://user-images.githubusercontent.com/35061323/35212412-0534c128-ff80-11e7-8d06-d0d0238d9353.png)

But nothing is getting loaded into the Visual, neither any issue is popping up in Visual Studio Code Window.

![image](https://user-images.githubusercontent.com/35061323/35212546-88b4bc2e-ff80-11e7-9c47-bc87fc471d7e.png)

Find the attached Code and suggest me what is the issue.
[barchart.zip](https://github.com/Microsoft/PowerBI-visuals/files/1651312/barchart.zip)

**Comment by uve** [comment]
@MahadevVasista, based on your screenshots I can guess that you haven't added any datasource to Visuals data buckets: **Category Data** and **Measure Data**. At least one field is strictly required.
