### ISSUE TITLE
Wrong to-do list in "Setting Up Environment"

### ISSUE THREAD

**Issue by Eyllaian** [Microsoft/PowerBI-visuals#303]
Hi,
maybe point 3. "Enable Developer Tools in PowerBI" should be reversed wih point 4. "Create New PowerBI Visual Project" otherwise you haven't "...https server that will serve your visual for testing in your favorite web browser...".

**Comment by uve** [comment]
these two options don't depend on each other. But if you want to run your visual in app.powerbi.com, you have to activate Enable Developer Tools in PowerBI option  first.

**Comment by Eyllaian** [comment]
You're right but step 4 in "Enable Developer Tools in PowerBI" will fail unless you have the servise running on your pc, isn't so?
Maybe is better a bulleted list instead of a numerical one...I tought I must do the step in order.

Bye

**Comment by uve** [comment]
@Eyllaian Actually you don't run the powerbi service on your local machine. It's all about app.powerbi.com. Pbiviz tools just launch local webserver that communicate with app.powerbi.com

**Comment by Eyllaian** [comment]
Hi @uve, I'm a newbie so sorry...but when I said "service running" I meant local webserver.
Setp 4 failed until I launched "pbiviz start" on my machine, then it started to work...that's all.
Bye
