### ISSUE TITLE
Roadmap and chagelog are not updated

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-visuals#304]
Guys, what is the current version of Power BI Custom Visuals framework?
What is coming and when?

Looks like CL and Roadmap haven't been updated for a while...

**Comment by uve** [comment]
@nicksav, thank you for your feedback, we'll update document soon. Here is a latest backlog:
https://github.com/Microsoft/PowerBI-visuals/blob/master/Roadmap/README.md#api-version-110
