### ISSUE TITLE
documentation and samples for RHTML custom visual

### ISSUE THREAD

**Issue by ghost** [microsoft/PowerBI-visuals#308]
Hi, I'm looking into the rhtml poject type because the standard project type suffers of a show stopper: it can only handle 30 000 data points.

In my rhtml-project I managed to create a GUI writing my own html,js and css wich renders fine once imported to power bi. 

 **But my major issue is that I dont know how to access the data which is provided from power bi.**

The example project uses the "Iris" example data wich is built in to R. But how can I, in the R-script, access  data that I drag from the fields pane?

**Comment by uve** [comment]
Hello @jamescorey, check the following repository:
https://github.com/Microsoft/powerbi-visuals-forcastingarima

**Comment by boefraty74** [comment]
Hi @jamescorey 
In addition, I'd recommend more detailed tutorial: 
[https://github.com/Microsoft/PowerBI-visuals/tree/master/RVisualTutorial/TutorialFunnelPlot](https://github.com/Microsoft/PowerBI-visuals/tree/master/RVisualTutorial/TutorialFunnelPlot)
