### ISSUE TITLE
Browser version and type used in Power BI desktop (WebGL software rendering support)

### ISSUE THREAD

**Issue by ryanbaumann** [Microsoft/PowerBI-visuals#310]
What default browser does Power BI Desktop use?  

I'm working on a customer that's using our custom visual (https://github.com/mapbox/mapboxgl-powerbi/issues/71) that relies in WebGL.  I'm wondering what specific browser is used in Power BI Desktop to determine if browser software rendering fallbacks are possible (such as SwiftShader on Chrome).

**Comment by uve** [comment]
@ryanbaumann, PBIDesktop uses Chromium Version 53 currently.
