### ISSUE TITLE
Shape Size of scatter chart bubble not decreasing in Desktop

### ISSUE THREAD

**Issue by hamza005** [Microsoft/PowerBI-visuals#315]
Hey, I used PowerBI Custom visual code of Enhanced scatter chart and decreased the size of shape by reducing the radius of the shape. It works well on the chrome verion, but when I package it and import it in desktop version, then it don't work. The shape size again remain the same as the presvious version had.

**Comment by uve** [comment]
hello @hamza005, Have you changed uniq GUID string in pbiviz.json file?

**Comment by hamza005** [comment]
nope. I really dont know what actually it does. Can you please tell me?

**Comment by uve** [comment]
Every visual uses it's own unique GUID number. So you must change it before you create a new package. Otherwise PBI uses stock version of the visual.

https://github.com/Microsoft/PowerBI-visuals/blob/17042fe7d5df81f5af07e85c4df441b5586a9f41/Tutorial/SubmissionCommonProblems.md

**Comment by hamza005** [comment]
Oh thanks @uve it worked! You made my day. It's working now... But can't we add a shape size changer? so that anyone can adjust by his/her choice like it is in the real visual of Power BI?
