### ISSUE TITLE
Load more data

### ISSUE THREAD

**Issue by spatney** [Microsoft/PowerBI-visuals#32]
Add the ability to request the host for more data. This applies to visuals that define a data reduction algorithm of type 'Window' to their data roles.

**Comment by nitinvrbhn** [comment]
Is this issue resolved?

If yes, please guide me how to use this feature. If no, can you please provide the date when this feature will be released?

**Comment by AviSander** [comment]
completed

**Comment by darthtrevino** [comment]
Can you link to the updated API?
