### ISSUE TITLE
Has anyone been able to get c3js running on this?

### ISSUE THREAD

**Issue by darewreck54** [microsoft/PowerBI-visuals#324]
Hi,

I'm trying to get c3js running on with a new custom visual, but i'm having the hardest time.  It compiles but exception is being thrown and it's not clear what the issue is:

```
VM2362:517 Uncaught SyntaxError: Unexpected token export
    at Object.i [as injectJsCode] (visualhostcore.min.js:2)
    at i.loadWithoutResourcePackage (visualsandbox.min.js:1)
    at i.executeMessage (visualsandbox.min.js:1)
    at i.onMessageReceived (visualsandbox.min.js:1)
    at visualsandbox.min.js:1
    at e.invokeHandler (visualhostcore.min.js:3)
    at e.dispatchMessage (visualhostcore.min.js:3)
    at e.onMessageReceived (visualhostcore.min.js:3)
    at windowMessageHandler (visualhostcore.min.js:3)
    at dispatch (visualsandbox.minimal.externals.js:16777)
```

Thanks,
Derek

**Comment by uve** [comment]
@darewreck54, what version of d3 and c3js do you use?

**Comment by darewreck54** [comment]
@uve I'm using https://github.com/c3js/c3/tree/v0.5.2 which i believe used d3v4.

**Comment by darewreck54** [comment]
I thought ideally you should be able to bring in any outside library and it would work.  However, that doesn't seem to be the case

**Comment by uve** [comment]
@darewreck54 Here is the current workaround:
1. npm install c3 @types/c3
2. create file src/c3Adapter.js with the following text:
```
var c3 = typeof c3 !== 'undefined'  ? c3 : window['c3'];
var d3 = typeof d3 !== 'undefined'  ? d3 : window['d3'];
```

3. add the following string to "externalJS"
```
"node_modules/d3/build/d3.min.js",
"node_modules/c3/c3.min.js",
"src/c3Adapter.js
```"

More info [here](https://github.com/Microsoft/PowerBI-visuals/issues/165) and [here](https://github.com/Microsoft/PowerBI-visuals/issues/158#issuecomment-291126732)

**Comment by darewreck54** [comment]
@uve This actually allows you to start the project but will throw an run time error.

![image](https://user-images.githubusercontent.com/16171726/40208600-6b8ae9ce-59ef-11e8-8bf2-94397b3c9dfc.png)

All i did was use the default template and did what you stated.  When you try to run it, it won't display the text in the default project (count)

Thanks,
Derek
