### ISSUE TITLE
Create certificate instructions for Windows 7 instructions not working

### ISSUE THREAD

**Issue by timtucker** [microsoft/PowerBI-visuals#325]
Getting the error below when attempting to run "pbiviz --create-cert".

As per the documentation, Openssl is installed and on the path.  (Tried both versions 1.0.2 and 1.1.0 of OpenSSL, but didn't see any difference).

`New-SelfSignedCertificate : The term 'New-SelfSignedCertificate' is not
recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:40
+ ... rt = ('Cert:\CurrentUser\My\' + (   New-SelfSignedCertificate         ...
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-SelfSignedCertificate:Strin
   g) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by zBritva** [comment]
Hello @timtucker ,

Could you execute the script 
`require('os').release()`
in node environment and say me the version of OS?

![image](https://user-images.githubusercontent.com/10897951/38367392-31859956-38eb-11e8-8057-f49de14fee65.png)

Thanks!

**Comment by zBritva** [comment]
@timtucker there is some error.
You can try to generate the cert manually:
Execute the following command
`openssl req -newkey rsa:2048 -nodes -keyout PowerBICustomVisualTest_public.key -x509 -days 180 -out PowerBICustomVisualTest_public.cer -subj "/CN=localhost"` 
in
`%appdata%\npm\node_modules\powerbi-visuals-tools\certs` location
for global installation of tools
or
`<PROJECT_ROOT>\node_modules\powerbi-visuals-tools\certs` location
for local installation of tools

**Comment by timtucker** [comment]
Created the manual certificate and placed in the appropriate directory, but can't connect to https://localhost:8080/assets/status via IE 10 or Chrome.

The more I read the docs on the limitations and hoops that I'd need to jump through to share anything I'd develop with others in our tenant, the less it seems worth the effort.

**Comment by uve** [comment]
@timtucker, have you tried this option?
https://github.com/Microsoft/PowerBI-visuals/issues/283#issuecomment-349712035

**Comment by timtucker** [comment]
Tried that, but here's what I get -- there is no "advanced" option that would allow me to add an exception:

Chrome:
"localhost uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH"

IE 11 (note that TLS 1.0, 1.1, and 1.2 are all enabled):
"Turn on TLS 1.0, TLS 1.1, and TLS 1.2 in Advanced settings and try connecting to https://localhost:8080  again. If this error persists, it is possible that this site uses an unsupported protocol or cipher suite such as RC4 (link for the details), which is not considered secure. Please contact your site administrator."

**Comment by Hugoberry** [comment]
Same problem as @timtucker 
Looked at the code and it seems that you don't setup to certificates correctly for Win7 64 bit environments where openssl is installed

**Comment by Hugoberry** [comment]
Got it working.
I might have used too many unnecessary setup, nevertheless this seems to have solved the problem.
Firstly this is my openssl.cfg
```
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no
[req_distinguished_name]
CN = localhost
[v3_req]
keyUsage = digitalSignature, keyEncipherment
subjectKeyIdentifier = hash
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost
```
Secondly make a note of the passphrase from the config.json in %AppData%\Roaming\npm\node_modules\powerbi-visuals-tools
and use it in the following openssl commands
navigate into 
%AppData%\Roaming\npm\node_modules\powerbi-visuals-tools\certs 
and type 
```
openssl req -newkey rsa:2048 -keyoutPowerBICustomVisualTest_private.key -x509 -days 180 -out PowerBICustomVisualTest_public.crt -passout pass:"whatever was in the config"
```
then generate a pfx
```
openssl pkcs12 -export -inkey PowerBICustomVisualTest_private.key -in PowerBICustomVisualTest_public.crt -out PowerBICustomVisualTest_public.pfx
```
make sure to type in the same passphrase.

You should be good to go.
In order to test it
1. Start the power BI visual server  `pbiviz start`
2. ` openssl s_client -connect localhost:8080` or navigate in a browser to https://localhost:8080/assets/status

**Comment by zBritva** [comment]
@Hugoberry, @timtucker The version 1.11.3 was released. Could you try to update the tools and try to generate cert again? Thanks!

**Comment by Hugoberry** [comment]
thanks @zBritva 
It works now 👍

**Comment by uve** [comment]
@timtucker, does it work for you?

**Comment by timtucker** [comment]
I updated to 1.11.3 and here's the basic summary:

"pbiviz --create-cert" still results in an error (see below)

The command does, however, result in a valid certificate being generated -- if I proceed to running --install-cert and start up the server, I can connect now to it now.



> info   Certificate generated. Location is C:\Users\username\AppData\Roaming\npm\n
> ode_modules\powerbi-visuals-tools\certs\PowerBICustomVisualTest_public.crt
> Invalid command '$cert = ('Cert:\CurrentUser\My\' + (   New-SelfSignedCertificat
> e        -DnsName localhost        -HashAlgorithm sha256        -Type Custom
>     -Subject localhost        -KeyAlgorithm RSA        -KeyLength 2048        -K
> eyExportPolicy Exportable        -CertStoreLocation Cert:\CurrentUser\My
> -NotAfter (get-date).AddDays(180)    | select Thumbprint |    ForEach-Object { $
> _.Thumbprint.ToString() }).toString());    Export-PfxCertificate -Cert $cert
>    -FilePath 'C:\Users\username\AppData\Roaming\npm\node_modules\powerbi-visuals-t
> ools\certs\PowerBICustomVisualTest_public.pfx'        -Password (ConvertTo-Secur
> eString -String '7067770005492398' -Force -AsPlainText)'; type "help" for a list
> .
>  error  Create certificate error: { Error: Command failed: openssl "$cert = ('Ce
> rt:\CurrentUser\My\' + (   New-SelfSignedCertificate        -DnsName localhost
>       -HashAlgorithm sha256        -Type Custom        -Subject localhost
>  -KeyAlgorithm RSA        -KeyLength 2048        -KeyExportPolicy Exportable
>     -CertStoreLocation Cert:\CurrentUser\My        -NotAfter (get-date).AddDays(
> 180)    | select Thumbprint |    ForEach-Object { $_.Thumbprint.ToString() }).to
> String());    Export-PfxCertificate -Cert $cert       -FilePath 'C:\Users\username
> \AppData\Roaming\npm\node_modules\powerbi-visuals-tools\certs\PowerBICustomVisua
> lTest_public.pfx'        -Password (ConvertTo-SecureString -String '706777000549
> 2398' -Force -AsPlainText)"
> Invalid command '$cert = ('Cert:\CurrentUser\My\' + (   New-SelfSignedCertificat
> e        -DnsName localhost        -HashAlgorithm sha256        -Type Custom
>     -Subject localhost        -KeyAlgorithm RSA        -KeyLength 2048        -K
> eyExportPolicy Exportable        -CertStoreLocation Cert:\CurrentUser\My
> -NotAfter (get-date).AddDays(180)    | select Thumbprint |    ForEach-Object { $
> _.Thumbprint.ToString() }).toString());    Export-PfxCertificate -Cert $cert
>    -FilePath 'C:\Users\username\AppData\Roaming\npm\node_modules\powerbi-visuals-t
> ools\certs\PowerBICustomVisualTest_public.pfx'        -Password (ConvertTo-Secur
> eString -String '7067770005492398' -Force -AsPlainText)'; type "help" for a list
> .
> 
>     at checkExecSyncError (child_process.js:601:13)
>     at execSync (child_process.js:641:13)
>     at createCertFile (C:\Users\username\AppData\Roaming\npm\node_modules\powerbi-
> visuals-tools\bin\pbiviz.js:209:25)
>     at Command.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\pow
> erbi-visuals-tools\node_modules\commander\index.js:395:35)
>     at emitNone (events.js:106:13)
>     at Command.emit (events.js:208:7)
>     at Command.parseOptions (C:\Users\username\AppData\Roaming\npm\node_modules\po
> werbi-visuals-tools\node_modules\commander\index.js:702:14)
>     at Command.parse (C:\Users\username\AppData\Roaming\npm\node_modules\powerbi-v
> isuals-tools\node_modules\commander\index.js:455:21)
>     at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\powe
> rbi-visuals-tools\bin\pbiviz.js:60:9)
>     at Module._compile (module.js:643:30)
>   error: null,
>   cmd: 'openssl "$cert = (\'Cert:\\CurrentUser\\My\\\' + (   New-SelfSignedCerti
> ficate        -DnsName localhost        -HashAlgorithm sha256        -Type Custo
> m        -Subject localhost        -KeyAlgorithm RSA        -KeyLength 2048
>    -KeyExportPolicy Exportable        -CertStoreLocation Cert:\\CurrentUser\\My
>        -NotAfter (get-date).AddDays(180)    | select Thumbprint |    ForEach-Obj
> ect { $_.Thumbprint.ToString() }).toString());    Export-PfxCertificate -Cert $c
> ert       -FilePath \'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\po
> werbi-visuals-tools\\certs\\PowerBICustomVisualTest_public.pfx\'        -Passwor
> d (ConvertTo-SecureString -String \'7067770005492398\' -Force -AsPlainText)"',
>   file: 'C:\\Windows\\system32\\cmd.exe',
>   args:
>    [ 'C:\\Windows\\system32\\cmd.exe',
>      '/d',
>      '/s',
>      '/c',
>      '"openssl "$cert = (\'Cert:\\CurrentUser\\My\\\' + (   New-SelfSignedCertif
> icate        -DnsName localhost        -HashAlgorithm sha256        -Type Custom
>         -Subject localhost        -KeyAlgorithm RSA        -KeyLength 2048
>   -KeyExportPolicy Exportable        -CertStoreLocation Cert:\\CurrentUser\\My
>       -NotAfter (get-date).AddDays(180)    | select Thumbprint |    ForEach-Obje
> ct { $_.Thumbprint.ToString() }).toString());    Export-PfxCertificate -Cert $ce
> rt       -FilePath \'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\pow
> erbi-visuals-tools\\certs\\PowerBICustomVisualTest_public.pfx\'        -Password
>  (ConvertTo-SecureString -String \'7067770005492398\' -Force -AsPlainText)""' ],

**Comment by 1q2q1q1q** [comment]
I have the same issue. I ran command "npm --create-cert" on Windows 7, error produced with the message "'$cert = ('Cert:\CurrentUser\My\' + ( New-SelfSignedCertif
icate -DnsName localhost -HashAlgorithm sha256 -Type Custom
-Subject localhost -KeyAlgorithm RSA -KeyLength 2048
-KeyExportPolicy Exportable -CertStoreLocation Cert:\CurrentUser\My
-NotAfter (get-date).AddDays(180) | select Thumbprint | ForEach-Obje
ct { $_.Thumbprint.ToString() }).toString()); Export-PfxCertificate -Cert $ce
rt -FilePath 'C:\Users\username\AppData\Roaming\npm\node_modules\pow
erbi-visuals-tools\certs\PowerBICustomVisualTest_public.pfx' -Password
(ConvertTo-SecureString -String '7921577074397836' -Force -AsPlainText)' is an invalid command'.  

The standard commands are suggested.

Should I use manually create the certificate, and what is command should I use?

Thanks a lot!

**Comment by LB913** [comment]
I am running into this same issue: "Can't connect to visual server". I believe my certificate is created and installed properly, However, I am unable to view the visual. 
1) Is there possibly a firewall issue that is blocking the connection to: https://localhost:8080?

2) Is there any other way to view a visual while you are developing it?

**Comment by zBritva** [comment]
@LB913 What happens or what do you see, when you open the link https://localhost:8080/assets/status in the browser?

**Comment by LB913** [comment]
When I try https://localhost:8080/assets/status int he browser it says:
This page can’t be displayed

•Make sure the web address https://localhost:8080 is correct.
•Look for the page with your search engine.
•Refresh the page in a few minutes.

I get the same thing in IE and Chrome.

**Comment by zBritva** [comment]
@LB913 Could you share the output after command `npm run start` or `pbiviz start`.

Do you see any output like?:
```
pbiviz-start.js:109:24
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {      
  code: 'EADDRINUSE',
  errno: -4091,
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 8080
}
```

**Comment by LB913** [comment]
Here is what I get when I run "pbiviz start":

PS W:\PowerBI\circleCard> pbiviz start

 info   Starting server...
 info   Start preparing plugin template
i ?wds?: Project is running at https://localhost:8080/webpack-dev-server/
i ?wds?: webpack output is served from /assets
i ?wds?: Content not from webpack is served from W:\PowerBI\circleCard\.tmp\drop
 info   Finish preparing plugin template
 info   Start packaging...
 info   Finish packaging
Webpack Bundle Analyzer saved report to W:\PowerBI\circleCard\webpack.statistics.dev.html


 DONE  Compiled successfully in 13192ms                                                   1:28:08 P

And it continues on with other lines and finally says: "i ?wdm?: Compiled successfully."

**Comment by zBritva** [comment]
It seems OK. 

Are you sure that nothing blocks incoming connections in port 8080? (Windows Defender Firewall, any antivirus)

**Comment by LB913** [comment]
I added an incoming firewall rule to allow port 8080, and that fixed the issue. @zBritva  Thank you for your help.
