### ISSUE TITLE
Power BI - Simple Striaght Table with Conditional Cell Back Ground Color.

### ISSUE THREAD

**Issue by Osamanu** [Microsoft/PowerBI-visuals#327]
I need help in making straight table in power BI with a Conditional Cell Back ground color. 

I already setup the Power BI visual via VS Community..

**Comment by abdsas** [comment]
Hi Osamanu, Please note Conditional Formatting is not yet available on PowerBi. You can however vote for it, Let's hope MS releases this functionality soon.

**Comment by jcbowyer** [comment]
Osamanu,

Not sure what conditions you want to change.  I have a reasonably simple example that alternates background color in css and changes background color on selection.   You can use attr and style methods to change background color as well as jquery.

My example is here:  https://gist.github.com/jcbowyer/8f92f8f343f775d7cd9251c5128c93a5

I am a newbie developer but you should be able to see concepts.
