### ISSUE TITLE
Persist Properties

### ISSUE THREAD

**Issue by spatney** [Microsoft/PowerBI-visuals#33]
Allow users to persist settings, and save them along with the visual definition so they are available on next reload. An example use-case would be if you wanted to allow user to adjust the width of a column on your table visual, and have it saved for the next reload of it.

**Comment by Futhark** [comment]
@spatney: Is there any way to persist some data with the visual at this moment? Maybe some static ID per visual per report to be able to save it on external services?

**Comment by spatney** [comment]
I am not on this team anymore, but I did a quick check, and it looks like this is already available. The docs don't seem to reflect it though. @tsikiksr (current owner) as FYI  to fix up docs.

**Comment by nicksav** [comment]
Example:
              let general: VisualObjectInstance[] = [{
                    objectName: "general",
                    displayName: "General",
                    selector: null,
                    properties: {
                        fillColor: this.settings.xAxisFillColor,
                        gridshow: this.settings.gridShow,
                        buckets: "Test"
                    }
                }];

                let propertToChange: VisualObjectInstancesToPersist = {
                    replace: general
                }

                this.host.persistProperties(propertToChange);

**Comment by AviSander** [comment]
completed
