### ISSUE TITLE
Incomplete documentation on ToolTip Services

### ISSUE THREAD

**Issue by Mike-Honey** [Microsoft/PowerBI-visuals#332]
I couldn't follow how to create a ToolTip using the information on the only wiki page: https://github.com/Microsoft/PowerBI-visuals/wiki/Tooltip-Services

What is meant by "each item of dataPoints array"? That object doesn't seem to be mentioned or referenced anywhere else.

For example I'm trying to contribute on Teo's Sparkline. His current code works and shows a Tooltip, but does not reference dataPoints at all?

Generally I'm discouraged by the level of documentation for Custom Visuals.

**Comment by v-kazaki** [comment]
Hello Mike. Thanks for your feedback. We also see this lack of documentation and are planning to improve it.

**Comment by Mike-Honey** [comment]
I keenly await those improvements.

I think the priority of resources needs to be adjusted for Power BI. It may be briefly exciting, but in the medium-long term it seems pointless to constantly churn out new features if they are not properly supported and documented.

**Comment by Mike-Honey** [comment]
I the meantime while we wait for your plans, I am stumped.

I'm trying to start from Teo's Sparkline contribution, and improve the Tooltips so they show specific data values.  The current code does show a Tooltip, but it seems to be a single value for the whole visual. It doesn't reference dataPoints at all? Should it? How?

**Comment by v-kazaki** [comment]
Sparkline has only one path object, and it means that we can show tooltip only for this one element. There are at least 2 options:
1.	To have one path element and display all values of sparkline in one tooltip.
2.	Add multiple path objects (and multiple datapoints) – in this case every path object will have its own tooltip.
