### ISSUE TITLE
custom visuals should be able to provide a font family formatting property

### ISSUE THREAD

**Issue by verneroberts** [microsoft/PowerBI-visuals#336]
custom visuals should be able to provide a font family formatting property as a nicely formatted drop down, much like the properties on the builtin visuals.

the following code actually already works if you hack the schema.capabilities.json file to allow it:
`                "fontFamily": {
                    "displayName": "Font Family",
                    "type": {
                        "formatting": {
                            "fontFamily": true
                        }
                    }
                },`

**Comment by helen508light** [comment]
https://github.com/microsoft/powerbi-visuals-api/blob/master/schema.capabilities.json
already done
