### ISSUE TITLE
Visualization Issue

### ISSUE THREAD

**Issue by powerbiquestions** [microsoft/PowerBI-visuals#353]
Hello,

I am trying to display revenue in a stacked column chart within Power BI desktop. The primary data set includes product, price, when it was sold, who sold it, and who bought it. I created a simple key that Power Bi should take the list of products and multiply it by the specific products' price to get the overall revenue for all of the products. I made all products' price equal 100 for now. I have 322 products listed. 

When I filter by product I get the correct revenue calculation, however when I have no slicer selected it is multiplying the total revenue per month by 322 (the number of products). 

What is causing Power BI to multiply the revenue by the number of products, but is not making it multiply the revenue by 322 when I slice on a specific product?

**Comment by helen508light** [comment]
Please check by right click on bucket field. There are may be chosen option "Summarize" and it would be cause of that behavior
