### ISSUE TITLE
launchUrl compatibility browsers

### ISSUE THREAD

**Issue by Laul0** [microsoft/PowerBI-visuals#357]
For one of my custom visual, we need to let the access at some links stored in database.
We had occurre that the link were don't work because the models of custom visual use an iFrame (really not a good idea for developing something great).

So, we had discover this solution host.launchUrl that work great on Microsoft Edge but on no other browser  !
We had tested on : chrome, firefox, safari, internet explorer.

Any idea ? Suggestion or solution ? It's possible that a improvement is scheduled from the roadmap ?

Thx

**Comment by ignatvilesov** [comment]
`launchUrl` supports all of modern browser including IE 11.
Are you still facing this issue? Can you share URL that did not work?

**Comment by Laul0** [comment]
Hi @ignatvilesov,

Thank you for you answer.

Of course, here some examples of URL that can be used by our custom visual :

```
https://ourdomain.sharepoint.com/sites/teamsite/pathtopdfile.pdf
http://intranet/entity/doc/pathofpdffile.pdf
```

Some other details about this behaviour. On Chrome and Firefox it works half but not with the same behavior. If we use Ctrl + Click the link works.

> We have an other issue with IE 11 that block external resource CDN files, so our custom visual is not completely loaded.

**Comment by ignatvilesov** [comment]
`launchUrl` does not support not HTTP/HTTPS links. We'll consider an ability to open non HTTP links.

**Comment by ignatvilesov** [comment]
We tested `http://intranet/entity/doc/pathofpdffile.pdf` from our side but it works well.

Can you share exact URL you used? How do you call `launchUrl` method?

**Comment by Laul0** [comment]
Hi @ignatvilesov, thx you for your investigations.

On which browser did you try ?

I can't share you the exact URLs, but it is mainly URLs of document stored on SharePoint Online.

**Comment by ignatvilesov** [comment]
@Laul0 Tested in all of browser. How do you call `launchUrl` method?

**Comment by Laul0** [comment]
Hi @ignatvilesov,

This is the function called to execute LaunchUrl :

> **Note** : `e` is useless, it is necessary for the event handler, `c` (c = context = this) is used to keep the context because my script is async and `u` is the target URL.

```javascript
public localLaunchURL(e, c, u) {
    c.host.launchUrl(u);
}
```

**Comment by dmfrazao** [comment]
When launchUrl will work for other protocols such as blob?

**Comment by pbicvsupport** [comment]
@dmfrazao 
now we aren't planning to support other protocols

**Comment by ScriptPup** [comment]
Not sure if anyone else is having this issue still, but I was able to get this working:
`// re-enable <a> links
      let ctx = this;
      $(this.contentDiv).on("click", "a", function(e) {
        e.preventDefault();
        ctx.host.launchUrl($(e.target).attr("href"));
      });`

I just dropped that code into the constructor using the documentation https://docs.microsoft.com/en-us/power-bi/developer/visuals/launch-url as a reference point to get started. It's super simple test, but hopefully this will help someone who found this same article when trying to figure out how to get this working with click events.
