### ISSUE TITLE
Displaying visuals in a single html page - Not Working 

### ISSUE THREAD

**Issue by alexgwolff** [Microsoft/PowerBI-visuals#360]
This wikipage example https://github.com/Microsoft/PowerBI-visuals/wiki/Displaying-visuals-in-a-single-html-page
It's doesn't work anymore, somebody can update?

![untitled](https://cloud.githubusercontent.com/assets/13754094/13075128/21733580-d490-11e5-9ed0-046fb26c3a62.png)

**Comment by ignatvilesov** [comment]
I've updated documentation [Displaying visuals in a single html page](https://github.com/Microsoft/PowerBI-visuals/wiki/Displaying-visuals-in-a-single-html-page).
Could you please try it again.

**Comment by alexgwolff** [comment]
Thanks :smile:
