### ISSUE TITLE
Date slider by month/year

### ISSUE THREAD

**Issue by CernaLuc** [Microsoft/PowerBI-visuals#365]
Hello, 

please, is there any solution how to have date slider (filter) by month and year (without day)? 

![date_filter](https://user-images.githubusercontent.com/41148826/42627239-f502e8d0-85bb-11e8-9cd7-e4cffb016101.JPG)

**Comment by ignatvilesov** [comment]
Not related to Custom Visuals. Please ask [Power BI Forum](https://community.powerbi.com/t5/Desktop/bd-p/power-bi-designer).
