### ISSUE TITLE
Value previous year

### ISSUE THREAD

**Issue by CernaLuc** [Microsoft/PowerBI-visuals#366]
Hello, 

please, can you help me. I have simple data table and I need to add Calculated coloum **Value previous year**: 
![data_table](https://user-images.githubusercontent.com/41148826/42628648-441d8872-85c0-11e8-8a66-179276a287c4.png)

Please, anyone does know DAX formula? 

Thank you

**Comment by ignatvilesov** [comment]
Not related to Custom Visuals. Please move this question to [Power BI Forum](https://community.powerbi.com/t5/Desktop/bd-p/power-bi-designer)
