### ISSUE TITLE
Optimization for KPI Indicator

### ISSUE THREAD

**Issue by janinehummel** [Microsoft/PowerBI-visuals#367]
Hey Fredrik, 

needless to say: our team here in Germany is totally psyched about your KPI Indicator Visual for Power BI. There's no report or dashboard without including your visual and so far, our clients love to see their data presented like that. Great job! 

I was wondering If you're open for some suggestions to add to the visual? We where thinking that it would be nice to have

- a date on the achse to make the time range clearer

- add a thousand decimeter to make big number better readable

- maybe  include an option to change the font size and character spacing

We believe these would be great additions to make the visual even more perfect.

Let me know what you think!

**Comment by v-kazaki** [comment]
@janinehummel your suggestions were addressed to Fredrik. You can always contact him by his email provided in description of [KPI Indicator](https://app.powerbi.com/visuals/show/KPIStatusWithHistory1446562283967) visual.
