### ISSUE TITLE
Light weight sandbox

### ISSUE THREAD

**Issue by spatney** [Microsoft/PowerBI-visuals#37]
The visual sandbox comes with libraries loaded by default (d3, lodash, JQuery). We'd like to trim the fat, so you can load your visuals faster, and also bring in different versions of the default libraries if you wish.

**Comment by TonyGaul** [comment]
Hey just wondering if the code is complete for v1.3 features can those features get release in v1.2? This light weight sandbox is a really important feature and it would be great to have it asap.

**Comment by spatney** [comment]
we want it to go out at the same time as the 'debug visual in an iFrame' feature to avoid strange issues like "i didn't need d3 for the debug visual, but when i packaged it, it broke".

**Comment by AviSander** [comment]
completed
