### ISSUE TITLE
Chiclet-Slicer displaying incorrect images

### ISSUE THREAD

**Issue by jonkelling** [Microsoft/PowerBI-visuals#371]
I first noticed this using the Chiclet-Slicer from https://app.powerbi.com/visuals. Several images do not display or display the image from the previous item. I cloned the repo from Github, and the demo shows the Ferrari image for all items—is this visual broken?

Thanks.

**Comment by ignatvilesov** [comment]
@jonkelling Thanks. I've fixed this issue.
