### ISSUE TITLE
how to add my custom visual to the playground

### ISSUE THREAD

**Issue by mingjunfan** [Microsoft/PowerBI-visuals#372]
I create a new iVisual item as the documentation says, but it can't be added to the playground.

Please help give me  a support, a tutorial maybe, on how to add your custom visual to the playground and how to get it into a pbiviz file afterwards for use in PowerBI desktop?

Thanks

**Comment by sheldonyss** [comment]
You need to declare your custom visual as plugin in plugins.ts that is in CustomVisuals solution.
