### ISSUE TITLE
Impossible to create custom properties

### ISSUE THREAD

**Issue by laurentpetit** [Microsoft/PowerBI-visuals#373]
Hi,

I'm trying to create a custom visualization.
I'm stuck when trying to create a custom property.

- I add it to the `General` Section of the `Capabilities.object` field.
- then I implement `enumerateObjectInstances` method

As a result, nothing appears in the UI. And the method `enumerateObjectInstances` is never called.

I also tried some other custom vizualizations available in the Gallery. None of them seemed to have any of their custom properties working.

Did something change recently?

FYI, my UI's language is `French`

Thanks

**Comment by vtkalek** [comment]
Hi, 
Checkout this example where you can find a bit more simplified method of properties setup:
(it could be run in DevTools)

// /// <reference path="../../_references.ts"/>
module powerbi.visuals.samples {
    import TablixFormattingPropertiesMatrix = powerbi.visuals.controls.TablixFormattingPropertiesMatrix;
    import TablixUtils = controls.internal.TablixUtils;
    import SelectionManager = utility.SelectionManager;
    import createClassAndSelector = jsCommon.CssConstants.createClassAndSelector;
    import ClassAndSelector = jsCommon.CssConstants.ClassAndSelector;

    export interface NumericSlicerData {
        maxValue: number;
        minValue: number;
        selectionColor: string;
        highValue: number;
        lowValue: number;
        fontSize: number;
        fontColor: string;
        lineColor: string;
        showMinMax: boolean;
        showRangeText: boolean;
        showAxisLabels: boolean;
        margin: number;
        lineHeight: number;
        handleWidth: number;
        handleHeight: number;
        linesY: number;
        selectionDxLow: number;
        selectionDxHigh: number;
        lineWidth: number;
        columnIdentity?: powerbi.data.SQExpr;
    }

    export class NumericSlicer implements IVisual {
        private static ClassName: string = "NumericSlicer";

        public static capabilities: VisualCapabilities = {
            dataRoles: [{
                name: 'Categories',
                kind: powerbi.VisualDataRoleKind.Grouping,
                displayName: 'Categories',
            }],
            dataViewMappings: [{
                conditions: [
                    { 'Categories': { max: 1 } }
                ],
                categorical: {
                    categories: {
                        for: { in: 'Categories' },
                        dataReductionAlgorithm: { sample: {} }
                    },
                    values: {
                        select: []
                    },
                }
            }],
            objects: {
                general: {
                    displayName: powerbi.data.createDisplayNameGetter('Visual_General'),
                    properties: {
                        highValue: {
                            type: { numeric: true },
                            displayName: 'High value selected'
                        },
                        lowValue: {
                            type: { numeric: true },
                            displayName: 'Low value selected'
                        },
                        maxValue: {
                            type: { numeric: true },
                            displayName: 'Maximum value'
                        },
                        minValue: {
                            type: { numeric: true },
                            displayName: 'Minimum value'
                        },
                        fontSize: {
                            displayName: 'Font size',
                            description: 'Font size',
                            type: { formatting: { fontSize: true } }
                        },
                        fontColor: {
                            displayName: 'Font color',
                            description: 'Font color',
                            type: { fill: { solid: { color: true } } }
                        },
                        lineColor: {
                            displayName: 'Line color',
                            description: 'Line color',
                            type: { fill: { solid: { color: true } } }
                        },
                        selectionColor: {
                            displayName: 'Selection color',
                            description: 'Selection color',
                            type: { fill: { solid: { color: true } } }
                        },
                        showMinMax: {
                            type: { bool: true },
                            displayName: 'Min/Max'
                        },
                        showRangeText: {
                            type: { bool: true },
                            displayName: 'RangeText'
                        },
                        showAxisLabels: {
                            type: { bool: true },
                            displayName: 'AxisLabels'
                        },
                    },
                },
            },
        };

        private svg: D3.Selection;
        private viewport: IViewport;
        private selectionManager: SelectionManager;
        private colors: IDataColorPalette;
        private NumericSlicerData: NumericSlicerData;
        private dataView: DataView;
        private coordinates = [0, 0];
        private defaultSelectionColor: string = '#ffd800';
        private defaultLineColor: string = '#a5a5a5';
        private hostServices: IVisualHostServices;
        private isJustDragged: boolean = false;
        private formatter: IValueFormatter;
        public init(visualsInitOptions: VisualInitOptions): void {
            this.hostServices = visualsInitOptions.host;
            this.formatter = valueFormatter.create({ format: "0", value: 0.1, value2: null });
            this.svg = d3.select(visualsInitOptions.element.get(0)).append("svg");
            this.svg.classed('NumericSlicerMainSVG', true);
            this.NumericSlicerData = <NumericSlicerData>{
                margin: 10,
                lineHeight: 10,
                handleWidth: 10,
                handleHeight: 14
            };
            var that = this;
            this.svg.on('mousemove', function() {
                that.coordinates[0] = d3.mouse(this)[0];
                that.coordinates[1] = d3.mouse(this)[1];
            })
                .on('mousedown', function() {
                    event.stopPropagation();
                });
        }

        private isDragging: boolean = false;
        public dragstarted(d, that: NumericSlicer): void {
            that.isDragging = true;
        }

        public dragged(d, that: NumericSlicer): void {
            if (that.isDragging === true) {
                //console.log(this.coordinates[0]);
                //TODO: scale mouse coordinates                
                switch (d) {
                    case 'low':
                        var pointX = this.findIndex(this.coordinates[0]);
                        this.NumericSlicerData.selectionDxLow = pointX;
                        if (this.NumericSlicerData.selectionDxLow + this.NumericSlicerData.handleWidth >= this.NumericSlicerData.selectionDxHigh)
                            this.NumericSlicerData.selectionDxLow = this.NumericSlicerData.selectionDxHigh - this.NumericSlicerData.handleWidth;
                        var selectionLowHandle = this.svg.selectAll('.selectionLowHandle');
                        selectionLowHandle
                            .attr('x', this.NumericSlicerData.selectionDxLow);
                        this.NumericSlicerData.lowValue = 1 + (this.NumericSlicerData.maxValue - this.NumericSlicerData.minValue) * (this.NumericSlicerData.selectionDxLow - this.NumericSlicerData.margin) / this.NumericSlicerData.lineWidth;
                        this.isJustDragged = true;
                        break;
                    case 'high':
                        var pointX = this.findIndex(this.coordinates[0]);
                        this.NumericSlicerData.selectionDxHigh = pointX;
                        if (this.NumericSlicerData.selectionDxHigh - this.NumericSlicerData.handleWidth <= this.NumericSlicerData.selectionDxLow)
                            this.NumericSlicerData.selectionDxHigh = this.NumericSlicerData.selectionDxLow + this.NumericSlicerData.handleWidth;
                        var selectionHighHandle = this.svg.selectAll('.selectionHighHandle');
                        selectionHighHandle
                            .attr('x', this.NumericSlicerData.selectionDxHigh);
                        this.NumericSlicerData.highValue = 1 + (this.NumericSlicerData.maxValue - this.NumericSlicerData.minValue) * (this.NumericSlicerData.selectionDxHigh - this.NumericSlicerData.margin) / this.NumericSlicerData.lineWidth;
                        this.isJustDragged = true;
                        break;
                }
                var selectionLine = this.svg.selectAll('.selectionLine');
                selectionLine.attr('x', this.NumericSlicerData.selectionDxLow + this.NumericSlicerData.handleWidth / 2)
                    .attr('width', this.NumericSlicerData.selectionDxHigh - this.NumericSlicerData.selectionDxLow);
                this.setSelectorValues(this.NumericSlicerData.lowValue, this.NumericSlicerData.highValue);
            }
            event.stopPropagation();
        }

        public dragended(d, that): void {
            this.isDragging = false;
            this.setSelection();
        }


        private drag = d3.behavior.drag()
            .origin(function(d) {
                return d;
            })
            .on("dragstart", (d) => { this.dragstarted(d, this); })
            .on("drag", (d) => { this.dragged(d, this); })
            .on("dragend", (d) => { this.dragended(d, this); });

        public update(options: VisualUpdateOptions): void {
            var dataView = options.dataViews[0];
            this.dataView = dataView;
            //this.isJustDragged ||
            if (!this.dataView
                || !this.dataView.categorical // Check if dataView contains real data
                || !this.dataView.metadata
                || !dataView.categorical.categories
                || dataView.categorical.categories.length !== 1
                || !dataView.categorical.categories[0].values
                || dataView.categorical.categories[0].values.length === 0
                || !options.dataViews[0].categorical.categories[0].source
                || !options.dataViews[0].categorical.categories[0].source.type) {
                this.isJustDragged = false;
                return;
            }
            this.viewport = options.viewport;
            // set settings and props
            var objects: DataViewObjects = dataView.metadata.objects;
            this.NumericSlicerData.selectionColor = DataViewObjects.getValue<Fill>(objects, { objectName: 'general', propertyName: 'selectionColor' }, { solid: { color: this.defaultSelectionColor } }).solid.color;
            this.NumericSlicerData.highValue = DataViewObjects.getValue<number>(objects, { objectName: 'general', propertyName: 'highValue' }, Number.MAX_VALUE);
            this.NumericSlicerData.lowValue = DataViewObjects.getValue<number>(objects, { objectName: 'general', propertyName: 'lowValue' }, Number.MIN_VALUE);
            this.NumericSlicerData.maxValue = DataViewObjects.getValue<number>(objects, { objectName: 'general', propertyName: 'maxValue' }, null);
            this.NumericSlicerData.minValue = DataViewObjects.getValue<number>(objects, { objectName: 'general', propertyName: 'minValue' }, null);
            var fontSize: string = '' + DataViewObjects.getValue<number>(objects, { objectName: 'general', propertyName: 'fontSize' }, 12);
            this.NumericSlicerData.fontSize = parseInt(fontSize);
            this.NumericSlicerData.fontColor = DataViewObjects.getValue<Fill>(objects, { objectName: 'general', propertyName: 'fontColor' }, { solid: { color: '#000000' } }).solid.color;
            this.NumericSlicerData.lineColor = DataViewObjects.getValue<Fill>(objects, { objectName: 'general', propertyName: 'lineColor' }, { solid: { color: this.defaultLineColor } }).solid.color;
            this.NumericSlicerData.showRangeText = DataViewObjects.getValue<boolean>(objects, { objectName: 'general', propertyName: 'showRangeText' }, true);
            this.NumericSlicerData.showMinMax = DataViewObjects.getValue<boolean>(objects, { objectName: 'general', propertyName: 'showMinMax' }, true);
            this.NumericSlicerData.showAxisLabels = DataViewObjects.getValue<boolean>(objects, { objectName: 'general', propertyName: 'showAxisLabels' }, false);

            this.converter(this.dataView);// setup data
            
            //Draw All here 
            this.svg.attr({
                height: options.viewport.height,
                width: options.viewport.width,
            });

            this.NumericSlicerData.lineWidth = options.viewport.width - this.NumericSlicerData.margin * 2;
            this.NumericSlicerData.linesY = (options.viewport.height - this.NumericSlicerData.lineHeight) / 2;

            if (this.NumericSlicerData.showRangeText) { // Range TEXT
                var rangeText = this.svg.selectAll('.rangeText').data([this.NumericSlicerData]);
                rangeText.enter()
                    .append('text')
                    .classed('rangeText', true);
                rangeText.attr("x", this.NumericSlicerData.margin)
                    .attr('y', this.NumericSlicerData.linesY - this.NumericSlicerData.fontSize)
                    .attr('height', this.NumericSlicerData.lineHeight)
                    .attr('width', this.NumericSlicerData.lineWidth);
                rangeText.attr("fill", this.NumericSlicerData.fontColor)
                    .style({ 'font-size': this.NumericSlicerData.fontSize + 'px' })
                    .text("Is between " + this.formatter.format(this.NumericSlicerData.lowValue) + " and " + this.formatter.format(this.NumericSlicerData.highValue));
                rangeText.exit().remove();
            } else {
                var wasSet = this.svg.selectAll('.rangeText');
                if (wasSet)
                    wasSet.text('');
            }

            if (this.NumericSlicerData.showMinMax) { // min max TEXT  powerbi.TextMeasurementService.measureSvgTextElementWidth
                var Y = this.NumericSlicerData.linesY + this.NumericSlicerData.lineHeight + this.NumericSlicerData.fontSize + 5;
                var minText = this.svg.selectAll('.minText').data([this.NumericSlicerData]);
                minText.enter()
                    .append('text')
                    .classed('minText', true);
                minText.attr("x", this.NumericSlicerData.margin)
                    .attr('y', Y)
                    .attr('height', this.NumericSlicerData.lineHeight)
                    .attr('width', this.NumericSlicerData.lineWidth);
                minText.attr("fill", this.NumericSlicerData.fontColor)
                    .style({ 'font-size': this.NumericSlicerData.fontSize + 'px' })
                    .text(this.formatter.format(this.NumericSlicerData.minValue));
                minText.exit().remove();

                var text = this.formatter.format(this.NumericSlicerData.maxValue);
                var maxText = this.svg.selectAll('.maxText').data([this.NumericSlicerData]);
                maxText.enter()
                    .append('text')
                    .classed('maxText', true);
                maxText.attr("x", this.NumericSlicerData.margin + this.NumericSlicerData.lineWidth - text.length * this.NumericSlicerData.fontSize * 0.7)
                    .attr('y', Y)
                    .attr('height', this.NumericSlicerData.lineHeight)
                    .attr('width', this.NumericSlicerData.lineWidth);
                maxText.attr("fill", this.NumericSlicerData.fontColor)
                    .style({ 'font-size': this.NumericSlicerData.fontSize + 'px' })
                    .text(this.formatter.format(this.NumericSlicerData.maxValue));
                maxText.exit().remove();
            } else {
                var wasSet = this.svg.selectAll('.maxText');
                if (wasSet)
                    wasSet.text('');
            }

            //render main line
            var mainLine = this.svg.selectAll('.mainLine').data([this.NumericSlicerData]);
            mainLine.enter()
                .append('rect')
                .classed('mainLine', true);
            mainLine.attr("x", this.NumericSlicerData.margin)
                .attr('y', this.NumericSlicerData.linesY)
                .attr('height', this.NumericSlicerData.lineHeight)
                .attr('width', this.NumericSlicerData.lineWidth);
            mainLine.attr("fill", this.NumericSlicerData.lineColor)
                .text((d) => { return ''; });
            mainLine.exit().remove();    
            
            //render selection line
            if (!this.isDragging) {
                var totalDiff = this.NumericSlicerData.maxValue - this.NumericSlicerData.minValue;
                //var selectionLineWidth = lineWidth*(this.NumericSlicerData.highValue - this.NumericSlicerData.lowValue)/totalDiff;
                this.NumericSlicerData.selectionDxLow = this.NumericSlicerData.lineWidth * (this.NumericSlicerData.lowValue - this.NumericSlicerData.minValue) / totalDiff;
                this.NumericSlicerData.selectionDxHigh = this.NumericSlicerData.lineWidth - this.NumericSlicerData.lineWidth * (this.NumericSlicerData.maxValue - this.NumericSlicerData.highValue) / totalDiff;
                var selectionLine = this.svg.selectAll('.selectionLine').data([this.NumericSlicerData]);
                selectionLine.enter()
                    .append('rect')
                    .classed('selectionLine', true);
                selectionLine.attr("x", this.NumericSlicerData.margin + this.NumericSlicerData.selectionDxLow)
                    .attr('y', this.NumericSlicerData.linesY)
                    .attr('height', this.NumericSlicerData.lineHeight)
                    .attr('width', this.NumericSlicerData.selectionDxHigh - this.NumericSlicerData.selectionDxLow);
                selectionLine.attr("fill", this.NumericSlicerData.selectionColor)
                    .text((d) => { return ''; });
                selectionLine.exit().remove();   
            
                //render selction low handle
                var selectionLowHandle = this.svg.selectAll('.selectionLowHandle').data(['low']);
                selectionLowHandle.enter()
                    .append('rect')
                    .classed('selectionLowHandle', true);
                selectionLowHandle.attr("x", this.NumericSlicerData.margin + this.NumericSlicerData.selectionDxLow - this.NumericSlicerData.handleWidth / 2)
                    .attr('y', this.NumericSlicerData.linesY - (this.NumericSlicerData.handleHeight - this.NumericSlicerData.lineHeight) / 2)
                    .attr('height', this.NumericSlicerData.handleHeight)
                    .attr('width', this.NumericSlicerData.handleWidth)
                    .style({ 'cursor': 'pointer' })
                    .call(this.drag);
                selectionLowHandle.attr("fill", this.NumericSlicerData.selectionColor)
                    .text((d) => { return ''; });
                selectionLowHandle.exit().remove();   
            
                //render selction high handle
                var selectionHighHandle = this.svg.selectAll('.selectionHighHandle').data(['high']);
                selectionHighHandle.enter()
                    .append('rect')
                    .classed('selectionHighHandle', true);
                selectionHighHandle.attr("x", this.NumericSlicerData.margin + this.NumericSlicerData.selectionDxHigh - this.NumericSlicerData.handleWidth / 2)
                    .attr('y', this.NumericSlicerData.linesY - (this.NumericSlicerData.handleHeight - this.NumericSlicerData.lineHeight) / 2)
                    .attr('height', this.NumericSlicerData.handleHeight)
                    .attr('width', this.NumericSlicerData.handleWidth)
                    .style({ 'cursor': 'pointer' })
                    .call(this.drag);
                selectionHighHandle.attr("fill", this.NumericSlicerData.selectionColor)
                    .text((d) => { return ''; });
                selectionHighHandle.exit().remove();
            }
        }

        public converter(dataView: DataView) {

            var numbers: number[] = dataView.categorical.categories[0].values;
            if (this.NumericSlicerData.maxValue === null)
                this.NumericSlicerData.maxValue = Math.max.apply(Math, numbers);
            if (this.NumericSlicerData.minValue === null)
                this.NumericSlicerData.minValue = Math.min.apply(Math, numbers);
            if (this.NumericSlicerData.highValue > this.NumericSlicerData.maxValue)
                this.NumericSlicerData.highValue = this.NumericSlicerData.maxValue;
            if (this.NumericSlicerData.lowValue < this.NumericSlicerData.minValue)
                this.NumericSlicerData.lowValue = this.NumericSlicerData.minValue;

            if (dataView.categorical.categories && dataView.categorical.categories[0].identityFields)
                this.NumericSlicerData.columnIdentity = <powerbi.data.SQExpr>dataView.categorical.categories[0].identityFields[0];

        }

        private isFormattingPropertiesEnabled: boolean = true;
        public enumerateObjectInstances(options: EnumerateVisualObjectInstancesOptions): VisualObjectInstanceEnumeration {
            var enumeration: ObjectEnumerationBuilder = new ObjectEnumerationBuilder();
            switch (options.objectName) {
                case 'general':
                    enumeration.pushInstance({
                        objectName: 'general',
                        displayName: 'General',
                        selector: null,
                        properties: {
                            highValue: NumericSlicer.getNumber(this.dataView, 'general', 'highValue', Number.MAX_VALUE),
                            lowValue: NumericSlicer.getNumber(this.dataView, 'general', 'lowValue', Number.MIN_VALUE),
                            maxValue: NumericSlicer.getNumber(this.dataView, 'general', 'maxValue', null),
                            minValue: NumericSlicer.getNumber(this.dataView, 'general', 'minValue', null),
                            fontSize: NumericSlicer.getNumber(this.dataView, 'general', 'fontSize', 12),
                            fontColor: NumericSlicer.getFill(this.dataView, 'general', 'fontColor', '#000000'),
                            lineColor: NumericSlicer.getFill(this.dataView, 'general', 'lineColor', this.defaultLineColor),
                            selectionColor: NumericSlicer.getFill(this.dataView, 'general', 'selectionColor', this.defaultSelectionColor),
                            showMinMax: NumericSlicer.getBoolean(this.dataView, 'general', 'showMinMax', true),
                            showRangeText: NumericSlicer.getBoolean(this.dataView, 'general', 'showRangeText', true),
                            showAxisLabels: NumericSlicer.getBoolean(this.dataView, 'general', 'showAxisLabels', false),
                        }
                    });
                    break;
            }
            return enumeration.complete();
        }

        public setSelection(): void {
            
            //     var sqExprLeft = powerbi.data.SQExprBuilder.compare(powerbi.data.QueryComparisonKind.GreaterThan, SQExprfortheField, powerbi.data.SQExprBuilder.integer(this.NumericSlicerData.lowValue));
            //     var sqExprRight = powerbi.data.SQExprBuilder.compare(powerbi.data.QueryComparisonKind.LessThan, SQExprfortheField, powerbi.data.SQExprBuilder.integer(this.NumericSlicerData.highValue));
            //     var result = powerbi.data.SQExprBuilder.and(sqExprLeft, sqExprRight);
            //     var filter = powerbi.data.SemanticFilter.fromSQExpr(result);


            // properties[filterPropertyIdentifier.propertyName] =filter;
            //         var instance = {
            //             objectName: filterPropertyIdentifier.objectName,
            //             selector: undefined,
            //             properties: properties
            //         };

            //         var changes: VisualObjectInstancesToPersist = {
            //             merge: [instance]
            //         };
            //         this.hostServices.persistProperties(changes);

            
            //this.requiresNoUpdate = true;
            // var lower: data.SQConstantExpr = powerbi.data.SQExprBuilder.integer(this.NumericSlicerData.lowValue);
            // var upper: data.SQConstantExpr = powerbi.data.SQExprBuilder.integer(this.NumericSlicerData.highValue);
            // var filterExpr = powerbi.data.SQExprBuilder.between(this.NumericSlicerData.columnIdentity, lower, upper);
            // var filter = powerbi.data.SemanticFilter.fromSQExpr(filterExpr);
            // var objects: VisualObjectInstancesToPersist = {
            //     merge: [
            //         <VisualObjectInstance>{
            //             objectName: "general",
            //             selector: undefined,
            //             properties: {
            //                 "filter": filter,
            //             }
            //         }
            //     ]
            // };
            // this.hostServices.persistProperties(objects);
            // this.hostServices.onSelect({ data: [] });
        }
        
        //Properties get set
        private setSelectorValues(lowValue: number, highValue: number): void {
            var objects: VisualObjectInstancesToPersist = {
                merge: [
                    <VisualObjectInstance>{
                        objectName: "general",
                        selector: undefined,
                        properties: {
                            lowValue: lowValue,
                            highValue: highValue
                        }
                    }
                ]
            };
            this.hostServices.persistProperties(objects);
            this.hostServices.onSelect({ data: [] });
        }

        private static getFill(dataView: DataView, field: string, property: string, defaultValue: string): Fill {
            if (dataView) {
                var objects = dataView.metadata.objects;
                if (objects) {
                    var f = objects[field];
                    if (f) {
                        var fill = <Fill>f[property];
                        if (fill)
                            return fill;
                    }
                }
            }
            return { solid: { color: defaultValue } };
        }

        private static getNumber(dataView: DataView, field: string, property: string, defaultValue: number): number {
            if (dataView) {
                var objects = dataView.metadata.objects;
                if (objects) {
                    var f = objects[field];
                    if (f) {
                        return <number>f[property];
                    }
                }
            }
            return defaultValue;
        }

        private static getcolPadding(dataView) {
            if (dataView) {
                var objects = dataView.metadata.objects;
                if (objects) {
                    var general = objects['general'];
                    if (general) {
                        var size = <number>general['colPadding'];
                        if (size)
                            return size;
                    }
                }
            }
            return 1;
        }

        private static getBoolean(dataView: DataView, field: string, property: string, defaultValue: boolean): boolean {
            if (dataView) {
                var objects = dataView.metadata.objects;
                if (objects) {
                    var b = objects[field];
                    if (b) {
                        var bool = <boolean>b[property];
                        if (bool != undefined && bool != null)
                            return bool;
                    }
                }
            }
            return defaultValue;
        }

        private findIndex(pointX: number, offsetX?: number): number {
            // we are using mouse coordinates that do not know about any potential CSS transform scale
            var svgNode = <SVGSVGElement>(this.svg.node());
            var ratios = SVGUtil.getTransformScaleRatios(svgNode);
            if (!Double.equalWithPrecision(ratios.x, 1.0, 0.00001)) {
                pointX = pointX / ratios.x;
            }
            if (offsetX) {
                pointX += offsetX;
            }

            // var scaleX = powerbi.visuals.AxisHelper.invertScale(this.xAxisProperties.scale, pointX);
            // if (this.data.isScalar) {
            //     scaleX = AxisHelper.findClosestXAxisIndex(scaleX, this.data.categoryData);
            // }

            return pointX;
        }

    }
	
	    export var NumericSlicerProps = {
        filterPropertyIdentifier: <DataViewObjectPropertyIdentifier>{ objectName: 'general', propertyName: 'filter' },
    };

	 export interface NumericSlicerDataPoint extends SelectableDataPoint {
        category?: string;
        value?: number;
        mouseOver?: boolean;
        mouseOut?: boolean;
        isSelectAllDataPoint?: boolean;
        imageURL?: string;
        selectable?: boolean;
    }
	
	 export interface NumericSlicerBehaviorOptions {
        slicerItemContainers: D3.Selection;
        slicerItemLabels: D3.Selection;
        slicerItemInputs: D3.Selection;
        slicerClear: D3.Selection;
        dataPoints: NumericSlicerDataPoint[];
        interactivityService: IInteractivityService;
        slicerSettings: NumericSlicerSettings;
    }
	
	export interface NumericSlicerSettings {
		 general: {
            orientation: string;
            columns: number;
            rows: number;
            multiselect: boolean;
            showDisabled: string;
        };
		 slicerText: {
            textSize: number;
            height: number;
            width: number;
            fontColor: string;
            hoverColor: string;
            selectedColor: string;
            unselectedColor: string;
            disabledColor: string;
            marginLeft: number;
            outline: string;
            background: string;
            transparency: number;
            outlineColor: string;
            outlineWeight: number;
            borderStyle: string;
        };
    }


    export class NumericSlicerWebBehavior implements IInteractiveBehavior {
        private slicers: D3.Selection;
        private slicerItemLabels: D3.Selection;
        private slicerItemInputs: D3.Selection;
        private dataPoints: NumericSlicerDataPoint[];
        private interactivityService: IInteractivityService;
        private slicerSettings: NumericSlicerSettings;

        public bindEvents(options: NumericSlicerBehaviorOptions, selectionHandler: ISelectionHandler): void {
            var filterPropertyId = NumericSlicerProps.filterPropertyIdentifier;
            var slicers = this.slicers = options.slicerItemContainers;
            this.slicerItemLabels = options.slicerItemLabels;
            this.slicerItemInputs = options.slicerItemInputs;
            var slicerClear = options.slicerClear;
            this.dataPoints = options.dataPoints;
            this.interactivityService = options.interactivityService;
            this.slicerSettings = options.slicerSettings;

            slicers.on("mouseover", (d: NumericSlicerDataPoint) => {
                if (d.selectable) {
                    d.mouseOver = true;
                    d.mouseOut = false;
                    this.renderMouseover();
                }
            });

            slicers.on("mouseout", (d: NumericSlicerDataPoint) => {
                if (d.selectable) {
                    d.mouseOver = false;
                    d.mouseOut = true;
                    this.renderMouseover();
                }
            });

            slicers.on("click", (d: NumericSlicerDataPoint, index) => {
                if (!d.selectable) {
                    return;
                }
                var settings: NumericSlicerSettings = this.slicerSettings;
                d3.event.preventDefault();
                if (d3.event.altKey && settings.general.multiselect) {
                    var selectedIndexes = jQuery.map(this.dataPoints, function (d, index) { if (d.selected) return index; });
                    var selIndex = selectedIndexes.length > 0 ? (selectedIndexes[selectedIndexes.length - 1]) : 0;
                    if (selIndex > index) {
                        var temp = index;
                        index = selIndex;
                        selIndex = temp;
                    }
                    selectionHandler.handleClearSelection();
                    for (var i = selIndex; i <= index; i++) {
                        selectionHandler.handleSelection(this.dataPoints[i], true /* isMultiSelect */);
                    }
                }
                else if (d3.event.ctrlKey && settings.general.multiselect) {
                    selectionHandler.handleSelection(d, true /* isMultiSelect */);
                }
                else {
                    selectionHandler.handleSelection(d, false /* isMultiSelect */);
                }
                selectionHandler.persistSelectionFilter(filterPropertyId);
            });

            slicerClear.on("click", (d: SelectableDataPoint) => {
                selectionHandler.handleClearSelection();
                selectionHandler.persistSelectionFilter(filterPropertyId);
            });
        }

        public renderSelection(hasSelection: boolean): void {
            if (!hasSelection && !this.interactivityService.isSelectionModeInverted()) {
                this.slicers.style('background', this.slicerSettings.slicerText.unselectedColor);
            }
            else {
                this.styleSlicerInputs(this.slicers, hasSelection);
            }
        }

        private renderMouseover(): void {
            this.slicerItemLabels.style({
                'color': (d: NumericSlicerDataPoint) => {
                    if (d.mouseOver)
                        return this.slicerSettings.slicerText.hoverColor;

                    if (d.mouseOut) {
                        if (d.selected)
                            return this.slicerSettings.slicerText.fontColor;
                        else
                            return this.slicerSettings.slicerText.fontColor;
                    }
                }
            });
        }

        public styleSlicerInputs(slicers: D3.Selection, hasSelection: boolean) {
            var settings = this.slicerSettings;
            slicers.each(function (d: NumericSlicerDataPoint) {
                d3.select(this).style({
                    'background': d.selectable ? (d.selected ? settings.slicerText.selectedColor : settings.slicerText.unselectedColor)
                        : settings.slicerText.disabledColor
                });
                d3.select(this).classed('slicerItem-disabled', !d.selectable);
            });
        }
    }

	
}

**Comment by laurentpetit** [comment]
Hi,Thanks for this quick answer. I tested that in the dev tools and I effectively got the expected parameters in the 'General' section. So I'll apply the necessary modification to my viz based on this example
