### ISSUE TITLE
custom visual online vs desktop

### ISSUE THREAD

**Issue by mhogeweg** [Microsoft/PowerBI-visuals#374]
I have a custom visual (small modification to the template resulting from `pbiviz new`) that I can load fine in app.powerbi.com. when loading the same .pbiviz package in Power BI desktop, it shows up in the visuals list, but adding it to a report results in:

`Your version of Power BI Desktop does not support this custom visual. Please update Power BI Desktop to the latest version.`

my version is: 2.59.5135.781 64-bit (June 2018)

are visuals compatible between desktop and online versions?

**Comment by ignatvilesov** [comment]
Please install the July version of Power BI Desktop because you use API 1.13.0.
