### ISSUE TITLE
PowerBI visuals code

### ISSUE THREAD

**Issue by blaz11** [Microsoft/PowerBI-visuals#377]
Hi,

Is code for Core PowerBI Visuals still open source? 
There is a version from 2 yrs ago in [repo](https://github.com/Microsoft/PowerBI-visuals-core) marked as DEPRECATED. I'm not sure if this code is up-to-date, and I would like to extend Matrix and stacked bar charts, moreover it looks like it is in an old project-structure and without much of documentation around. 

Thanks for any help,
Blazej

**Comment by ignatvilesov** [comment]
Source code of core visuals is no longer public. Currently we have no plans to open source it since it's hard to maintain.

**Comment by CyborgDroid** [comment]
Did anyone fork this before microsoft removed the code? The visuals have so many minor issues and not being able to fix them is really annoying. We are getting all of the drawbacks of open source (tons of bugs) but no benefits (visuals are not open source).
