### ISSUE TITLE
AM I the only one

### ISSUE THREAD

**Issue by justinlofley** [Microsoft/PowerBI-visuals#378]
Am I the only one that can not get this to work. I have followed all of the steps outlined several times and simply can not get the project to work for me. I have deleted everything and started over several times and have even tried at my house in case there was something happening with my firewall at work but nothing. All that I get when I build the project is this:

![image](https://cloud.githubusercontent.com/assets/17936414/14089774/ea99255e-f4f3-11e5-9784-0754a36be7a3.png)

I really only want to make some simple changes to the visuals and yet I am failing. 

Please someone tell me what I am doing wrong.

**Comment by istiakk** [comment]
try  to use the google chrome or firefox while you are running your project, i think it will solve your problem

**Comment by justinlofley** [comment]
Thanks for the reply, I was using Chrome and checked Firefox just to be sure. Same result.

**Comment by getsetbro** [comment]
It looks like it hasn't pulled in the css file. Do you see any errors in the browser devtools console?

**Comment by vtkalek** [comment]
Hi, Justin. By all signs you have forgotten to install gulp. 
When in root folder of PowerBI Try to run this command first : npm install -g gulp
Then npm install

It should solve your problem.

**Comment by justinlofley** [comment]
Thanks guys, turns out it was a network issue. It is working now.
