### ISSUE TITLE
TooltipManager functions in PowerBI desktop, fails on web

### ISSUE THREAD

**Issue by HunterOka** [Microsoft/PowerBI-visuals#379]
I am trying to implement tooltips for my custom visualization using the TooltipManager class. When the visualization is imported into PowerBI Desktop, the tooltip works as expected and my data is displayed. When the file from PowerBI Desktop is uploaded to PowerBI web, or the visualization is imported into a report on the web, the tooltip does not work at all. 

Is anyone aware of a reason this might be happening?

Update:
I looked at the about page for PowerBI Desktop, and I was using version 2.28. After upgrading to 2.33, tooltips no longer work in PowerBI desktop. Instead I receive an error saying 'toolTipInfo does not exist for undefined'. 

This probably explains why things were working on desktop but not online, if the web version was expecting things from 2.33, and my desktop version was 2.28. So now the question becomes, why do things work in 2.28, and not 2.33? Was there a change in how the toolTipManager was implemented? What changes do I need to make to my code for things to work in 2.33?

![screen shot 2016-03-28 at 6 19 24 pm](https://cloud.githubusercontent.com/assets/7736965/14092002/cefc87be-f511-11e5-9a62-24c93f325d96.png)
![screen shot 2016-03-28 at 6 20 15 pm](https://cloud.githubusercontent.com/assets/7736965/14092003/cf00c144-f511-11e5-8094-3df7056b0195.png)

**Comment by v-kazaki** [comment]
@HunterOka, I think you have code like this:

`return tooltipEvent.data[tooltipEvent.index].tooltipInfo;`

Recently "index" field was removed from TooltipEvent class, so that should be reason of your problem.
Get the latest version of infrastructure code from this repo to your fork and do required changes, something like this:

`return tooltipEvent.data[0].tooltipInfo;`

**Comment by HunterOka** [comment]
Hi, thanks for getting back to me.

Right now I am using the ToolTipManager class. In the update function, I have the line

`TooltipManager.addTooltip(ttSelect, (ttEvent: TooltipEvent) => ttEvent.data.toolTipInfo);`

Where ttSelect is a d3 selection, and tooTipInfo is a field of my data objects bound to that selection.

**Comment by v-kazaki** [comment]
@HunterOka, then you need to debug your code in web to find the reason.
Check [this article](https://github.com/Microsoft/PowerBI-visuals/blob/documents-misc/dev/browser_debug.md) describing how you can do that.
