### ISSUE TITLE
Parameterising PowerBI Visuals

### ISSUE THREAD

**Issue by radiiorg** [Microsoft/PowerBI-visuals#383]
Azure PowerBI API does not allow the parameters for a visual to be sent from outside PowerBI — if it did, we could design an interface that is customised for the user, and be able to generate specific visualisations without the user having to engage with the more technical Power BI UI.

Has anyone 'cracked' this problem?

**Comment by ignatvilesov** [comment]
@radiiorg I’m sorry, but we don’t have any information about it. Please, move your question to [Microsoft Power BI Community](http://community.powerbi.com/).
