### ISSUE TITLE
CartesianChart.getMinInterval valid only for sorted seriesList

### ISSUE THREAD

**Issue by joesatriani** [Microsoft/PowerBI-visuals#386]
This method will work perfectly if the input parameter `seriesList` already sorted, but not the otherwise. The problem is if the input `seriesList ` not sorted already the returned value `minInterval ` will be wrong.
Adding following line after `var series0data` will solve the problem:
`series0data.sort(function(a, b){
                    	return a.categoryValue - b.categoryValue;
                    });`

**Comment by ignatvilesov** [comment]
@joesatriani Thanks for your suggestion, we'll check it and implement your change if it looks good.
