### ISSUE TITLE
Power BI custom visuals code unable to build successfully

### ISSUE THREAD

**Issue by AmolD123** [Microsoft/PowerBI-visuals#39]
Trying to explore the custom visuals code. 
But getting error while building the solution as below -
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Comment by vtkalek** [comment]
If you are working in VS 2015 then do this (as described in instruction):
2.   Right click on the project root folder then select 'Property Pages'. In the window opened select 'Build' and then in 'Before running startup page' select 'No Build'.

**Comment by AmolD123** [comment]
Already done this as a part of the initial setup. But still facing this issue.
