### ISSUE TITLE
Add enum object type

### ISSUE THREAD

**Issue by wesyao** [Microsoft/PowerBI-visuals#39]
Add enum type for objects in capabilities. This will allow you to create property pane controls that show a list populated from enum values.

**Comment by ChamaraIC** [comment]
When is this feature getting available? What would code look like?

**Comment by ihud** [comment]
Hello, everyone!
As i know it's already available if you update you'r API to 1.2 version.
In capabilities -> objects adding something like this:

    "objects": {
        "first": {
            "displayName": "First",
            "properties": {
                "show": {
                    "displayName": "First",
                    "type": { "bool": true }
                },
                "enumNumber": {
                    "displayName": "Enum Number",
                    "suppressFormatPainterCopy": true,
                    "type": {
                        "enumeration": [
                            {"value": "10pt", "displayName": "10pt"},
                            {"value": "20pt", "displayName": "20pt"}
                        ]
                    }
                }
            }
        }
}

**Comment by nikhilkabbin** [comment]
@ihud Thanks for the example it was helpful, but can you show how do you use "enumNumber" in EnumerateVisualObjectInstancesOptions in Visual.ts file?

**Comment by AviSander** [comment]
completed
