### ISSUE TITLE
D3 EventDrops Library In PowerBI

### ISSUE THREAD

**Issue by ethanhunt4233** [Microsoft/PowerBI-visuals#393]
We have already developed some Charts with EventDrops Library. How can I add these libraries in Power BI Developer Tools. There is no way to add these EventDrops library URL's in Power BI Developer Tools.

Need help.

**Comment by ignatvilesov** [comment]
@ethanhunt4233 

You can add EventDrops Library using the following steps:
1.	Prepare a package (pbiviz) using Power BI Dev Tools ([Dev Tools](https://app.powerbi.com/devtools))
2.	Extract your package (pbiviz) using zip tool (7-zip, etc.)
3.	Add EventDrops Library to “YourVisual.js”
4.	Compress to “.zip” using zip tool (see package structure below)
5.	Change extension from “.zip” to “.pbiviz”

Package (pbiviz) structure:
- package.json
- resources
  - YourVisual.css
  - YourVisual.js
  - YourVisual.ts
