### ISSUE TITLE
DataRepetitionSelector interface is blank 

### ISSUE THREAD

**Issue by anushaj1** [microsoft/PowerBI-visuals#394]
We have updated the api of our visual to 2.1.0. 
We are getting the following error: 
 Property 'key' does not exist on type 'DataRepetitionSelector'.

**Comment by anushaj1** [comment]
The error is produced because of the following line 
const legendDataPoints: ILegendDataPoints[] = grouped.map((group: DataViewValueColumnGroup, index: number) => {
                const defaultColor: Fill = {
                    solid: {
                        color: colorPalette.getColor(group.identity ? group.identity.key : '').value
                    }
                };

**Comment by helen508light** [comment]
If you used key property of the DataViewScopeIdentity interface, you can replace it with JSON.stringify(identity)
