### ISSUE TITLE
The timeline fails to filter in the web

### ISSUE THREAD

**Issue by ilia-semenov** [Microsoft/PowerBI-visuals#395]
After the recent update (week dimension added), the visual is failing to cross-filter.

**Comment by danilorpneves** [comment]
I'm also having the same problem.

**Comment by v-kazaki** [comment]
@ilia-semenov This is known issue of the Timeline custom visual and we are working on fixes for it. After the fix will be ready, we will update this GitHub repo with the latest version of the visual source code.

**Comment by christianG23** [comment]
Hello,

Any update on when this will be fixed?  I have 2 clients that rely heavily on this timeline and are asking me for updates or a new slicer.  Please let us know timing?

Thanks.

**Comment by v-kazaki** [comment]
We have updated Timeline custom visual in [Power BI visuals gallery](http://visuals.powerbi.com), version 1.2.6. Please download it and check if you still have an issue. If so, please send description of your issue to pbicvsupport@microsoft.com

**Comment by ilia-semenov** [comment]
@v-kazaki Kamil, the visual still fails to perform cross-filtering both on desktop and in web. I have submitted the message to the pbicvsupport@microsoft.com.

**Comment by christianG23** [comment]
Hi - just to confirm, I tried over the weekend and had issues as well.  Should I submit an issue as well to the support email or is 1 submission enough.

Thanks.

**Comment by ilia-semenov** [comment]
@christianG23 looks like there is version 1.2.8 out there, and it seems to do the job

**Comment by v-kazaki** [comment]
@christianG23 Try updated version 1.2.8 and send email to pbicvsupport@microsoft.com if you have any issues (with some details). Sample pbix file will help a lot.

**Comment by ilia-semenov** [comment]
@v-kazaki Kamil, everything works as expected now. Thank you so much!
