### ISSUE TITLE
PowerBI cannot contact visual server when running pbiviz on different port 

### ISSUE THREAD

**Issue by Cpcrook** [microsoft/PowerBI-visuals#396]
I have a different utility running on port 8080, so I used the `-p` command line option when starting pbiviz to set the port to 8090.

I have already installed server certs, and verified I can reach https://localhost:8090/assets/status without issue on multiple browsers.

The issue is, once "Enable Developer visual for testing" is enabled and I add the visual to a report through app.powerbi.com, the site is still trying to hit https://localhost:8080 and there doesn't seem to be a way to configure this to look at the actual port on which the visual server is running.

I don't see how this is ever supposed to actually work the way it is currently setup, to be very honest, and there seems to be exactly zero documentation on running on a different port, making it *seem like* is should just work.

Here's the request going out from app.powerbi.com:

![image](https://user-images.githubusercontent.com/643732/45168663-d848e980-b1c9-11e8-95c6-94709c6e55fb.png)

Here's **pbiviz** running on 8090:

![image](https://user-images.githubusercontent.com/643732/45168700-eb5bb980-b1c9-11e8-888b-4b692f0c8eec.png)

pbiviz version: 2.1.0
nodejs version: 8.9.2

Can someone explain how the PowerBI site is supposed to know to look at a different port without explicitly configuring that somewhere (which doesn't appear to exist, despite pbiviz having the CLI option to change the port number)?

It also doesn't appear that PowerBI Desktop lets you test dev custom visuals without packaging and importing first (unlike running the visuals server), which is also extremely poorly documented in terms of making the distinction between the two interfaces which look nearly identical.

**Comment by Cpcrook** [comment]
Poking through the minified JS of powerbiportal.common.bundle on the site, it looks like the site is supposed to look at the value in local storage of DEVELOPMENT_SERVER_URL otherwise default to localhost:8080.

Setting this manually in my browser's dev tools does not appear to change the behavior either.

**Comment by Cpcrook** [comment]
Can I get an acknowledgement that this is at least a bug?

**Comment by Cpcrook** [comment]
@uve you seem to be all over the issues being tracked here...any help/clarity you could provide with respect to the issue about would be appreciated.

**Comment by Cpcrook** [comment]
Soooo....about this....

**Comment by mcjim** [comment]
I have also run into this issue. Connection is fine on port 8080 but fails if I use port 8081.

**Comment by helen508light** [comment]
Please try this way https://github.com/microsoft/PowerBI-visuals/issues/572
