### ISSUE TITLE
PowerBI-visuals returns HTTP Error 403.14 - Forbidden in VisualStudio 2015

### ISSUE THREAD

**Issue by maristhek** [Microsoft/PowerBI-visuals#396]
Using the cloned repo, set IIS permissions, set src\Clients\PowerBIVisualsPlayground\index.html  as default doc and start page, enable directory browsing, remove R/O flags on all files. 

Still get 403 response in VS 2015 in Chrome, IE browsers

**Comment by ignatvilesov** [comment]
@maristhek Did you set **PowerBIVisualsPlayground** as a StartUp project ?

You can set PowerBIVisualsPlayground as a StartUp project using the following steps:
1. Open src\PowerBIVisuals.sln
2. Navigate to Solution Explorer
3. Right click on PowerBIVisualsPlayground
4. Click on “Set as a StartUp project”

**Comment by maristhek** [comment]
Yes I did.

 

Also : ran the appcmd settings to enable directory browsing in IISExpress.

 

Finally created a web site in IIS (not Express, nor default site) at port 8080 (works with other ports as well) reconfigged VS2015 and got it to run.

 

Tnx,
