### ISSUE TITLE
Github.io comments: Overview

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#401]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/overview/

**Comment by uve** [comment]
test

**Comment by uve** [comment]
> test

thank you for solution!

**Comment by uve** [comment]
great

**Comment by ignatvilesov** [comment]
Hi guys,

Any updates on this?

**Comment by uve** [comment]
> Hi guys,
> 
> Any updates on this?

it's done already

**Comment by kthejoker** [comment]
The overview doesn't work on Android Chrome at all ... I get some initial text but all of the pages are truncated nane basically useless..

**Comment by uve** [comment]
> The overview doesn't work on Android Chrome at all ... I get some initial text but all of the pages are truncated nane basically useless..
Should work now. Try to click on hamburger button
