### ISSUE TITLE
Custom visuals broken in iOS and Android apps after sandbox feature 

### ISSUE THREAD

**Issue by sjkp** [Microsoft/PowerBI-visuals#402]
There a discussion on the powerbi community forum, that custom visuals doesn't work on the mobile powerbi apps after the introduction of the sandbox feature. I can confirm that I have the same problem. 

I'm opening a ticket here, to highlight the issues, as I did already spent a great deal of time trying to debug the issue before I found the post on the community, just to realize that it is no my visual that is broken.

http://community.powerbi.com/t5/Developer/Custom-Visuals-Sandbox-is-coming-Here-s-what-you-need-to-know/

**Comment by v-kazaki** [comment]
@sjkp mobile team is not reviewing this repo. If you address your issues to pbicvsupport@microsoft.com, I will add mobile team into discussion.

**Comment by sjkp** [comment]
@sjkp it was also to warn fellow custom visuals developers to not waste their time trying to get their stuff working when it is a problem with the platform. I believe the mobile team is aware of the problem, so spaming them is probably not gonna fix it faster ;)

**Comment by ignatvilesov** [comment]
@sjkp As I know, this problem was fixed.
Let us know if you have any problem.
