### ISSUE TITLE
Unresolved References when creating a new custom Visual using CustomVisualTemplate 

### ISSUE THREAD

**Issue by ChamaraIC** [Microsoft/PowerBI-visuals#403]
I followed instructions in https://github.com/Microsoft/PowerBI-visuals/wiki/Create-new-Power-BI-Visuals-using-template and created a custom visual.
1. in VS I see many "Cannot Find name" errors,
    eg. cannot find name "utility"
    cannot find name "DataViewObjectPropertyIdentifier"
sample code line is 
import SelectionManager = utility.SelectionManager;
2. The template has a reference to _references.ts which is unresolved (please see below) with a comment above that looks like
/* Please make sure that this path is correct */
/// <reference path="../_references.ts"/>
I searched the entire computer but I do not find a file named _references.ts (not even hidden files)

How do I resolve these?

**Comment by ignatvilesov** [comment]
@ChamaraIC, At first you should execute command “gulp build”. Then you should remove reference to “_references.ts” and add your visual to tsconfig.json.

**Comment by ChamaraIC** [comment]
@ignatvilesov, Added visual to tsconfig.json. Now "gulp build" throws duplicate identifier errors such as the ones shown below.
TypeScript error: visuals\MyCustomVisual.ts(45,9): error TS2300: Duplicate identifier 'name'.
TypeScript error: visuals\sampleVisual.ts(45,9): error TS2300: Duplicate identifier 'name'.

I commented out the following in MyCustomVisuals and got it compile without errors finally.
    export interface TeamData {
        name: string;
        value: number;
        color: string;
        identity: SelectionId;
    }
