### ISSUE TITLE
Github.io comments: Testing in Excel

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#408]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/building-for-excel/testing-in-excel/

**Comment by FrankFromGermany** [comment]
Example custom visual (Sankey) complains that Internet Explorer is deactivated !?

**Comment by rhershfield** [comment]
I followed the steps (on two computers) and the Insert Custom Visual command does not appear on the Insert Charts ribbon. I was able to add it to a custom group, but the Custom Visuals tab does not appear on the Insert Chart dialog. Anyone else experience this or have any suggestions to get it to appear? I have Excel version 1912 (Build 12325.20012 Click-to-Run) Office Insider.

**Comment by helen508light** [comment]
@rhershfield 
@AviSander  and Custom visuals in Excel team may know how to solve it
