### ISSUE TITLE
Adding additional assets for external libraries

### ISSUE THREAD

**Issue by Knagis** [microsoft/PowerBI-visuals#41]
The [Adding External Libraries](https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/Tutorial/ExternalLibraries.md) section mentions that the .js file should be included in the tsconfig.json file which would result in them being compiled within the visual.js file.

However our library needs not only a single .js file but it also dynamically loads additional resources such as stylesheets, images and other .js files that are not initially loaded.

Is it possible to include these files as assets in the visual and then at runtime to get the URL to the asset folder or individual asset files?

**Comment by spatney** [comment]
are these resources on a public facing endpoint somewhere? like a CDN?

**Comment by Knagis** [comment]
Yes, they can be downloaded from a CDN. However that would not work when the desktop app is used offline.

**Comment by spatney** [comment]
I see, yes that isn't possible, but an interesting feature we might consider adding.

**Comment by Knagis** [comment]
Would it be possible to post some guidelines how to handle loading libraries from external sources so that custom visuals are compatible with one another? Browsing the issues I noticed one example how this is worked around: https://github.com/woodbuffalo/powerbi-leaflet/blob/selection/src/visual.ts#L4-L5. 

However this approach populates the global namespace with a specific version of the library which might then break some other visual. For example, including leaflet.js (as in the code above) actually does this very easily if additional plugins are used since those extend the `L` global variable but including another `leaflet.js` overwrites the previous `L` with a fresh copy that no longer has the plugin.

In our visual I created a special loader (using simple XHR and `eval()`) so that the global namespace is not touched at all. I had to do this also because the powerbi web app already includes `moment.js` version 2.8.3 while our library only works with `2.9.0` or newer - so it also loads its own moment instance but leaves the global as is.

**Comment by spatney** [comment]
Makes sense, and we will. All visuals created with the new tools render in their own iframe, so don't have to worry about polluting the global namespace. Also in future versions we will be removing all of the default  external libraries, so to avoid collisions.

**Comment by Knagis** [comment]
> All visuals created with the new tools render in their own iframe

Does this happen only when the visual is packaged and used that way? I am asking because when using the debug visual I don't see an iframe for the visual.

**Comment by spatney** [comment]
correct. We are currently working on getting the debug visual to render in the sandbox as-well. I also added it to the [roadmap](https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/Roadmap/README.md) so you when to expect it.
