### ISSUE TITLE
playing with powerbi.session.userInfo in CustomVisual

### ISSUE THREAD

**Issue by johnnliu** [Microsoft/PowerBI-visuals#412]
Hi guys,

I've been doing some prototyping with custom visuals and wanting to detect the "current user" - which is available in powerbi.session.userInfo at the top frame level.  I only need to differentiate who is currently using the custom visual, e.g. powerbi.session.userInfo.name: "john.liu@sharepointgurus.net"

This disappears in the sandbox frame.  powerbi.session exists but no userInfo.  The utility methods powerbi.session.UserInfoUtils.getFullName etc exists but without context doesn't work.

So I'm just curious if there's a way to read the current user in the PowerBI service that's the officially supported way.  I feel powerbi.session.userInfo would be sufficient, but if I need to do a cross-frame message I'm ok with that too.

I tried also using formula USERNAME() but that's really rubbish on PowerBI Service.  (works well on desktop though).

**Comment by v-kazaki** [comment]
@johnnliu I'm just curious - why do you need user name in your visual?

**Comment by johnnliu** [comment]
There are several scenarios that we are prototyping, but they all pretty much tie around knowing the current user to then do some simple post requests.

- PowerBI reports has numerous projects - have a custom visual that allows different managers to select which projects they want to highlight - we store these separately in docdb, and the custom visual brings that back (via shiny Azure Functions).  Knowing who is the current user is useful for both setting the "favourite" and retrieving them.  - note, we are not looking for a row-level user security implemented via a visual - I expect PowerBI to support that in due time, we're just after a "return to your previous highlights".  

An alternative is to perhaps store a cookie, or map the user back to their IP address.

- I guess if we can see the user's name, we'd have analytics on when did they access the report.

- Allow users to apply tags against data entry, again, we store these elsewhere via a separate post request.

**Comment by jcbowyer** [comment]
We have this requirement to personalize the display for users as well

**Comment by v-kazaki** [comment]
Information about current user should not be used by custom visuals. As alternative you can use some additional field with list of all users in your dataset and allow users to select themselves from it.
