### ISSUE TITLE
Github.io comments: Adding Visual Elements

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#420]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/step-by-step-lab/adding-visual-elements/

**Comment by adarshmadrecha** [comment]
Which version of D3 does power BI use? Are we free to add the latest `v5.x`  of d3 which is mentioned in step 1?

**Comment by abelinoaleman** [comment]
after run pbiviz start i gatted this error
error  TYPESCRIPT  /visualPlugin.ts : (8,153) Property 'Visual' does not exist
on type 'typeof circleCardF2C38D1E5B754B19AE6E8D0C82100780'.

**Comment by uve** [comment]
> Which version of D3 does power BI use? Are we free to add the latest `v5.x` of d3 which is mentioned in step 1?

Currently, PowerBI-tools support d3 v3.x only. If you are looking for v5.x please read [this guide](https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/)

**Comment by uve** [comment]
> after run pbiviz start i gatted this error
> error TYPESCRIPT /visualPlugin.ts : (8,153) Property 'Visual' does not exist
> on type 'typeof circleCardF2C38D1E5B754B19AE6E8D0C82100780'.

@abelinoaleman please send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>

**Comment by chriskuech** [comment]
Can we just use standard typescript import semantics instead of adding to tsconfig.json and having the types automagically resolve?
