### ISSUE TITLE
Can't Figure out how to create settings for custom visual

### ISSUE THREAD

**Issue by jcbowyer** [Microsoft/PowerBI-visuals#427]
I currently can't get drilldown to work or custom settings.

For the drill down, I can't get it to work on any custom visual.
For the settings, it appears that I am not doing something obvious but I can't figure out what I am missing.  I implemented an object in capabilities.

The gist for my custom visual is below.

https://gist.github.com/jcbowyer/8f92f8f343f775d7cd9251c5128c93a5

**Comment by ignatvilesov** [comment]
@jcbowyer Property `this.model` is `undefined` in method `enumerateObjectInstances`. You should set `this.model`.

**Comment by jcbowyer** [comment]
Thank you.  That solved my problem!.    I am a newbie coder here and don't know proper rules for this forum.  It says to use stackoverflow for questions to powerbidev but I don't have enough points in stackoverflow to create/post to that tag.   If someone has enought points to establish the powerbidev topic that would be great.  Thanks again for the help.   I have a second question/example posted on stackoverflow here on multiselect with selectionmanager.

http://stackoverflow.com/questions/37388223/how-to-multiselect-with-selection-manager-in-power-bi-custom-visual
