### ISSUE TITLE
power Bi report show last hour

### ISSUE THREAD

**Issue by nitin16** [Microsoft/PowerBI-visuals#429]
Is there any way I can display streaming data for last hour or 30 minutes? I have stream analytics which sends request count by operation for every minute. In my dashboard/report I just need to show data for last hour, which refreshes every minute.

**Comment by ignatvilesov** [comment]
@nitin16 I’m sorry, but we don’t have any information about it. Please, move your question to [Power BI Community](http://community.powerbi.com/).
