### ISSUE TITLE
Github.io comments: Debugging

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#434]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/how-to-debug/

**Comment by jrichview** [comment]
FYI the code for "logExceptions()" is apparently obsolete. Pasting that into a typescript file creates a couple of errors in VSCode. Please review. Thanks.

**Comment by meerable** [comment]
> FYI the code for "logExceptions()" is apparently obsolete. Pasting that into a typescript file creates a couple of errors in VSCode. Please review. Thanks.

I found the solution here https://github.com/Microsoft/PowerBI-visuals/issues/221
