### ISSUE TITLE
Gulp Build: Visuals not showing up in Playground

### ISSUE THREAD

**Issue by rwedoff** [Microsoft/PowerBI-visuals#437]
When running the playground through Gulp, the visuals are not showing up in the playground.  After BuildAll, there are no errors that indicate that anything is wrong.
![play](https://cloud.githubusercontent.com/assets/6679636/15832459/ed7e50fc-2be7-11e6-8a4b-8543dfc026ae.PNG)

**Comment by rwedoff** [comment]
Here is the Chrome error log.

![chrome log](https://cloud.githubusercontent.com/assets/6679636/15833682/75a57b9a-2bed-11e6-802b-4e8dc208bd6f.PNG)

**Comment by ignatvilesov** [comment]
@rwedoff Thanks, we'll investigate this problem.

**Comment by ignatvilesov** [comment]
@rwedoff This problem is fixed. Please, let us know if you have any problem.

**Comment by thehetz** [comment]
I still have this issue after pulling latest today :(

**Comment by ignatvilesov** [comment]
@thehetz Could you please close Visual Studio and execute command “git clean –qdfix –e node_modules” in the project folder. After that try to run Playground again.

**Comment by thehetz** [comment]
After executing the command in the Git Bash in the project directory I get the following error in Visual Studio when attempting to run the project:
The operation could not be completed.  The system could not find the path specified.

**Comment by ignatvilesov** [comment]
@thehetz Could you please open Visual Studio in administrator mode.

**Comment by thehetz** [comment]
Running in Admin mode resolved the issue.
