### ISSUE TITLE
Github.io comments: Custom visuals unit test

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#438]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/unit-tests-introduction/

**Comment by Eric-Young194** [comment]
Is there updated documentation for this? It appears to be using older versions, and cannot be implemented into a project using a higher version of powerbi-visuals-tools

**Comment by zBritva** [comment]
@Eric-Young194 We are preparing the new documentation. But we don't have exact ETA
