### ISSUE TITLE
Github.io comments: Adding tooltips to custom visual

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#439]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/adding-report-page-tooltips/

**Comment by joanteixi** [comment]
Hi! I added in a custom visual a tooltip.. It works well when the "type" selector in powerbi.com is in "default". If I select "report" and select a report, it ignores this option and show the "normal" tooltip. I tried with other visuals like the ones of maqsoftware (https://github.com/maqsoftware/PowerBI-visuals/tree/master/src/CustomVisuals/Published/KPIColumn) and it works perfect, showing as a tooltip one page report...

My code just implements:
```typescript
 this.tooltipServiceWrapper = tooltip.createTooltipServiceWrapper(
                options.host.tooltipService,
                options.element);
```

and addTooltip:
```typescript
 this.tooltipServiceWrapper.addTooltip(
                this.slicerBody.selectAll(ChicletSlicer.ItemContainerSelector.selector),
                (tooltipEvent: TooltipEventArgs<any>) => this.getTooltipIndividualTargetData(),
                (tooltipEvent: TooltipEventArgs<any>) => tooltipEvent.data
```


In capabilites.json, added the supportedTypes default and canvas as True.

Some idea why it's not showing the report as tooltip?

**Comment by uve** [comment]
@joanteixi, what is tooltipEvent.data in your code? 
Based on our sample, you should pass tooltipEvent.data.selectionId object as 3rd argument.

**Comment by joanteixi** [comment]
Hi @uve, my tooltipEvent.data is big object with this keys:

context, coordinates, **data** and elementCoordinates. 

Where data, seems to be the data info that holds the selected zone where I'm mouseover. What is suposed to be the third argument? What is this selectionId? 

Thanks for your help!

**Comment by joanteixi** [comment]
Hi! 

I found the solution... in my case, the selectionId is an object named "identity", not selectionId. In the examples, seems that the selectionId should be a number, not an object. 

Should be very interesting to explain this in the documentation... If the doc is in github, I'll be glad to try to help other people with a PR over docs. 



Thanks to pointing me on the right solution!

Here is a capture of my tootipEvent.data object:
<img width="580" alt="Captura de Pantalla 2019-04-10 a les 22 28 22" src="https://user-images.githubusercontent.com/286098/55911005-0bc87800-5be0-11e9-94c7-0ce8ae19d802.png">

**Comment by rasmus1425** [comment]
Hi @joanteixi , 
Can you help me figure it out? I currently get this error: 
TYPESCRIPT  /src/visual.ts : (1189,43) Property 'showContextMenu' does not exist on type 'ISelectionManager'.

https://github.com/rasmus1425/CustomBulletChart/blob/master/src/visual.ts

**Comment by joanteixi** [comment]
Hi @rasmus1425 ... sorry I can't help... no idea... my comment was only about how implement tooltip showing a report page.

Good luck!

**Comment by helen508light** [comment]
Hi, @rasmusbrottwitt 
Is this issue still reproducable for you?
API version used in repo(2.2.0) support showContextMenu method
may be it needed to use typization like this on method call 
```
           let selectionId = dataPoint ? dataPoint.selectionId : {}
                    this.selectionManager.showContextMenu(selectionID as selectionId, {
                        x: mouseEvent.clientX,
                        y: mouseEvent.clientY
                    } as IPoint);
```

**Comment by 3000volt** [comment]
Hi, I'd like to implement the tooltips on an HTML table, but I do not know why it does not work. Here is the error I have:
![Capture](https://user-images.githubusercontent.com/44375832/60727387-c3cd9e80-9f0b-11e9-96b8-4611a7eefca4.PNG)

This is the code on update function
![image](https://user-images.githubusercontent.com/44375832/60727301-91bc3c80-9f0b-11e9-893a-7c6d3de5b686.png)
I use the version 3.1.1 of power bi tools
Please help me, anyone have and idea

**Comment by zBritva** [comment]
@3000volt Could you options of TooltipServiceWrapper?

It seems you didn't pass getEvent method to constructor

**Comment by 3000volt** [comment]
@zBritva  thank for reply, do you have an example because I can not find any documentation on how to implement it. when I look at the debugger, I notice that the"tooltipEvent is not defined" like you say
![image](https://user-images.githubusercontent.com/44375832/60811684-d17a6280-a15d-11e9-9a7a-07c2e2e7dfc0.png)
![image](https://user-images.githubusercontent.com/44375832/60811746-ea831380-a15d-11e9-8795-303489b1d1a4.png)

**Comment by zBritva** [comment]
@3000volt basic usage is here: https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/adding-tooltips/ - 

If you create wrapper by calling function `createTooltipServiceWrapper` it creates getEvent method.
Or you can pass your function to constructor:

https://github.com/microsoft/powerbi-visuals-utils-tooltiputils/blob/master/src/tooltipService.ts#L30
https://github.com/microsoft/powerbi-visuals-utils-tooltiputils/blob/master/src/tooltipService.ts#L66

**Comment by 3000volt** [comment]
@zBritva  yes, I create the tooltipservice wrapper with createTooltipServiceWrapper
![image](https://user-images.githubusercontent.com/44375832/60816589-07244900-a168-11e9-83a7-b85e30cc7842.png)
 but i don't understand what you want to say me

**Comment by danieleperilli** [comment]
I had the same problem with D3.js version < 5. After migrating to the latest version it started working.
