### ISSUE TITLE
Better debugging tools for powerbi desktop

### ISSUE THREAD

**Issue by sjkp** [Microsoft/PowerBI-visuals#446]
Firstly sorry if this is the wrong place to post this. But here goes. 

Is it possible to somehow attach a javascript debugger to powerbi desktop? Currently it is a royal pain in the ... to figure out errors in custom visuals that only come up in the PowerBI Desktop client. 

I have posted a similar question over at the powerbi community (https://community.powerbi.com/t5/Developer/Debugging-custom-visual-PowerBI-desktop-errors/m-p/43029), but I'm sure you have some internal way of testing powerbi desktop, which to me looks to be using chromium embedded so maybe there some remote way to connect to the browser running inside of powerbi desktop.

**Comment by ignatvilesov** [comment]
@sjkp As i know, we don't have any way to attach a remote debugger to Power BI Desktop for now.

**Comment by sjkp** [comment]
@ignatvilesov is it something that is planned? Or at least better error messages while we wait.
