### ISSUE TITLE
DateTime categories not working properly

### ISSUE THREAD

**Issue by tyjen** [Microsoft/PowerBI-visuals#45]
If I take the example posted in your [single page visuals tutorial](https://github.com/Microsoft/PowerBI-visuals/wiki/Displaying-visuals-in-a-single-html-page), change the countries to Date objects, and change the column type as well as category identity from text to dateTime, the last category label doesn't display, although its values do.

**Comment by MatthLee** [comment]
Can you share your datetime values so I can attempt to repro the issue?

**Comment by tyjen** [comment]
1. Replace the categoryValues with this array:
    `[new Date('2015-09-01T00:00:00'), new Date('2015-09-02T00:00:00'), new Date('2015-09-03T00:00:00'), new Date('2015-09-04T00:00:00'), new Date('2015-09-05T00:00:00'), new Date('2015-09-06T00:00:00')]`

2. Change the `SQExprBuilder` from `.text` to `.dateTime`
3. Change the column metadata `fromDescriptor` from `text` to `dateTime`

You'll notice the entry for 9/6 is missing. I realize this may be an artifact of having continuous vs discrete values for the categories, but it feels strange that 6 country labels can fit, while 6 short date strings cannot.

![image](https://cloud.githubusercontent.com/assets/643555/9921594/0719b34a-5c94-11e5-8303-18ea8f34ea5d.png)

**Comment by MatthLee** [comment]
You can change the axis type using metadata objects:
            var objects: DataViewObjects = {
                categoryAxis: {
                    axisType: 'Categorical',
                }
            };
            dataView.metadata.objects = objects;
DateTime category values will default to 'Scalar' axisType for column/bar and line charts.
That said, we have received a fair amount of feedback on Scalar vs. Categorical axis tick value behavior, and we are working on a new design to improve things.
There also appears to be about a 12-hour offset between the center of your columns and the tick values, this should not happen when you send in 00:00:00 for the time portion, I'll look into this.

**Comment by MatthLee** [comment]
Forgot to use markdown, sorry for the ugly formatting above:
```javascript
            var objects: DataViewObjects = {
                categoryAxis: {
                    axisType: 'Categorical',
                }
            };
            dataView.metadata.objects = objects;
```
