### ISSUE TITLE
Github.io comments: DataViewMappings

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#454]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/concepts/dataviewmappings/

**Comment by a10k** [comment]
Hi Uve,

Is there a plan to support multiple dataviews in the same custom visual in the future, if so can you please share additional details about the roadmap for this? This is currently the biggest issue for some complex custom visuals we want to create.

Thanks,
Alok

**Comment by djpirra** [comment]
Alok has a very good point. We need support to multiple dataviews. Is this already available?

Thank you

**Comment by helen508light** [comment]
Thanks for you feedback, it is not available and there is no ETA for now.
You can use DAX queries instead
