### ISSUE TITLE
Github.io comments: Using Capabilities

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#456]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/concepts/capabilities/

**Comment by jrichview** [comment]
How would you set default property values on something like Title which is a default property?  We'd like to set the default title text, font size, and color for example.

**Comment by MisterS** [comment]
Hi!
Currently I am trying to understand, why I have to define the capabilities.json in such detail, when I have to (re)build the property pane in _enumerateObjectInstances_ anyway? Why can't the capabilities.json just be simple array with property names?
Regards
Jonas
