### ISSUE TITLE
Github.io comments: Objects and properties

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#459]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/concepts/objects-and-properties/

**Comment by smndtrl** [comment]
Is there a way for a (solid) color to be configured with conditional formatting? Just like for some default elements 

![image](https://user-images.githubusercontent.com/9169479/59967748-15028900-952f-11e9-91e0-9a5070dcdc93.png)

**Comment by gica-gugui** [comment]
Can we change a custom visual property using a theme JSON?

I am trying to set a font size property but with no success:

The capabilities JSON config:
 "objects": {
	"textSettings": {
		"displayName": "Text settings",
		"properties": {
			"fontSize": {
				"displayName": "Text size",
				"description": "Change the size of text.",
				"type": {
					"formatting": {
						"fontSize": true
					}
				},
				"suppressFormatPainterCopy": true
			}
		}
	}
}

The theme JSON:
{
  "name": "Default Small Text",
  "dataColors": ["#074650", "#009292", "#fe6db6", "#feb5da", "#480091", "#b66dff", "#b5dafe", "#6db6ff", "#914800", "#23fd23"],
  "visualStyles": {
	"TextEnhancerByMAQ46ASG0293G65JY43S89DKJ9": {
      "*": {
        "textSettings": [
          {
            "fontSize": "10"
          }
        ]
      }
    }
  }
}

**Comment by zBritva** [comment]
@gica-gugui Value should be number:

` "fontSize": 10`

**Comment by gica-gugui** [comment]
Thanks for the feedback. 
I've tried setting the value as a number with no result.

**Comment by gica-gugui** [comment]
I tried setting the font size of an existing visual (card) and still cannot set the font size property.
This is the gist with the theme json:
https://gist.github.com/gica-gugui/a39f3bcf70128b37e0dbf9d50263cf29

However, changing the font family with the above theme JSON works. Should the font size be set in a different manner? Or this property cannot be set at all?

**Comment by zBritva** [comment]
@gica-gugui 
I checked with your sample:

```
{
  "name": "Default Small Text",
  "dataColors": ["#074650", "#009292", "#fe6db6", "#feb5da", "#480091", "#b66dff", "#b5dafe", "#6db6ff", "#914800", "#23fd23"],
  "visualStyles": {
	"TextEnhancerByMAQ46ASG0293G65JY43S89DKJ9": {
      "*": {
        "textSettings": [
          {
            "fontSize": 72
          }
        ]
      }
    }
  }
}
```

**If you change the font size in the visual properties, visual uses value from property instead theme. You need to remove the visual and put again to report.**

**Comment by gica-gugui** [comment]
@zBritva Thanks, that was the problem.
Is this the desired behavior or should this be considered as a bug?

**Comment by zBritva** [comment]
@gica-gugui I think, it's is expected. Because, theme provides global settings for all aspects (report pages, visuals, colors), and visual properties more concrete thinks.

**Comment by gica-gugui** [comment]
@zBritva Thanks! I managed to correctly apply theme styles and fix my issues with the information you provided.

**Comment by yelper** [comment]
@gica-gugui If you hit the "Revert to Default" link at the bottom of the property pane card, it should force the visual to use the theme-defined default.  Of course, remaking the visual will take the theme-default as well :)
