### ISSUE TITLE
Unclear where to post issues about different aspects of powerbi

### ISSUE THREAD

**Issue by Knagis** [Microsoft/PowerBI-visuals#46]
There are many different repositories related to powerbi - it would be useful to add guidelines where to post issues about what topics.

For example, if the docs are missing something, it is clear that the issue would be reported in this repo. However, this repo also contains issues regarding API changes that makes it feel like this is the goto repository for any issues.

I did post few issues on the `powerbi-visuals-tools` repository since those were directly related to the `pbiviz` tool itself. I assume that is the correct place.

However now I have a different issue - the powerbi web app is not calling `destroy()` on the debug visual when `Reload Visual Code` is clicked. Where should this issue be reported to?

**Comment by wesyao** [comment]
Hey @Knagis, I see your point, however the people who are working on the devtools are looking at both. I would say if there is an actual bug within the tools, it should be reported there. Questions about APIs or how to do something with the capabilities should be here.

Thanks for reporting this, we should probably be calling `destroy()`.

**Comment by Knagis** [comment]
I reported the issue about `destroy()` separately to https://github.com/Microsoft/PowerBI-visuals-tools/issues/18

I think the reason why I had the original question is that I assumed that the issues from the web application should be reported somewhere else for the web app and not in the `visual-tools` repository. However since then I clicked the `Feedback` button in the web app that brought me to the `visual-tools` repository thus somewhat clarifying the issue.

**Comment by spatney** [comment]
should be clear now, we rename the docs repo to be the powerbi-visuals, and point the link to here.
