### ISSUE TITLE
Github.io comments: Tutorials

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#471]
Comments to https://microsoft.github.io/PowerBI-visuals/tutorials/

**Comment by nezamtaheri** [comment]
hi
I Neesd run timer in power bi for countdown to refresh
can you help me?

**Comment by nezamtaheri** [comment]
hi
I Need run timer in power bi for countdown to refresh
can you help me?

**Comment by Geberson** [comment]
I have been looking for a course that has shown in detail how to customize visuals for power bi.
The documentation that Microsoft makes available, besides being very bad, is out of date in git.
When I get some video material that shows all the steps, it's in English.
Microsoft needs to provide local language customization courses, in this case, Portuguese Brazil.
Please urgently need good full materials in Portuguese Brazil to cost visuals for power bi.
