### ISSUE TITLE
Github.io comments: Custom Visual code structure

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#474]
Comments to https://microsoft.github.io/PowerBI-visuals/tutorials/building-slicer-visual/code-structure/

**Comment by kanhuangats** [comment]
wow, haven't seen this kind of 'Brilliant' step by step tutorial for a long long long time.

**Comment by z3c0** [comment]
If I could only cite one page to show how incomplete this documentation is overall, it would be this one.

**Comment by ErnieWhite** [comment]
For what its worth.
[Source Files Here](https://github.com/microsoft/powerbi-visuals-sampleslicer/tree/master/src) on the Github page

You also have to follow along down the left side of screen to get some of the step by step.
