### ISSUE TITLE
Github.io comments: Creating a new R Powered Custom Visual

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#482]
Comments to https://microsoft.github.io/PowerBI-visuals/tutorials/building-r-powered-custom-visual/creating-a-new-r-powered-custom-visual/

**Comment by DieselAnalytics** [comment]
Hello Uve,

The R HTML link in https://microsoft.github.io/PowerBI-visuals/tutorials/building-r-powered-custom-visual/creating-a-new-r-powered-custom-visual/ is broken. Can you please share the correct link?

Best Regards,

Ryan

**Comment by helen508light** [comment]
@DieselAnalytics 
It's working now.
Is this problem still actual for you?
May be you have some specific rules for connection

**Comment by DieselAnalytics** [comment]
I don't think we are talking about the same link. If you go to the last paragraph in the link the text "R HTML" is a hyperlink to this url: https://microsoft.github.io/PowerBI-visuals/tutorials/building-r-powered-custom-visual/creating-a-new-r-powered-custom-visual/CreateRHTML.md which returns a 404 error.

**Comment by rhershfield** [comment]
I believe this is the correct link for R HTML: https://github.com/microsoft/PowerBI-visuals/blob/master/RVisualTutorial/CreateRHTML.md
