### ISSUE TITLE
Github.io comments: Building a Visual with Static Data

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#483]
Comments to https://microsoft.github.io/PowerBI-visuals/tutorials/building-bar-chart/building-a-visual-with-static-data/

**Comment by OneidaAlmodovar** [comment]
Is it possible to show several barcharts in a single powerbi custom visual? 
I've a requirement that must show several graphs in the same visual custom, they are metrics connected to each other. 

Please let me know your comments. Thank You.

**Comment by helen508light** [comment]
You can use several visuals on one report page(which are related to dataset combined from several data) or use some existing solutions like this ones:
https://github.com/akvelon/PowerBI-100-Stacked-Bar-Chart
https://appsource.microsoft.com/en/product/power-bi-visuals/WA104381822?tab=Overview
https://appsource.microsoft.com/en/product/power-bi-visuals/WA104381823?tab=Overview

In general, the main difference for multi-visual solutions in this rows:
https://github.com/akvelon/PowerBI-100-Stacked-Bar-Chart/blob/master/capabilities.json#L1692-L1701
