### ISSUE TITLE
Github.io comments: Adding Selection and Interaction with Other Visuals

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#484]
Comments to https://microsoft.github.io/PowerBI-visuals/tutorials/building-bar-chart/adding-selection-and-interaction-with-other-visuals/

**Comment by twastvedt** [comment]
This document links [here ](https://github.com/Microsoft/PowerBI-visuals/blob/master/Visual/Selection.md#creating-selection-ids-selectionidbuilder) for more information. In that document a field, `private selectionIdBuilder: ISelectionIdBuilder;` is created to hold a single selectionIdBuilder. In this document it says that a new selectionIdBuilder should be created for every data point. Why store a single selectionIdBuilder in the visual then?

**Comment by zBritva** [comment]
@twastvedt it is old doc. the new documentation is here: https://docs.microsoft.com/power-bi/developer/visuals/selection-api

**Comment by twastvedt** [comment]
OK, thanks for the link. It's confusing that there's no indication of what's old and what's not.
