### ISSUE TITLE
Github.io comments: Adding Databound Objects to Property Pane

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#490]
Comments to https://microsoft.github.io/PowerBI-visuals/tutorials/building-bar-chart/adding-databound-objects-to-property-pane/

**Comment by twastvedt** [comment]
I think the [`dataViewObjects.getFillColor`](https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-dataview#getfillcolor) can be used instead of the custom `getCategoricalObjectValue` function here?

**Comment by helen508light** [comment]
@twastvedt 
The main difference in indexes usage in getCategoricalObjectValue -> it helps to make link with formatting color option and related datapoints, or for filtration
