### ISSUE TITLE
Incorrect JS file mentioned in SPA doc?

### ISSUE THREAD

**Issue by mmaitre314** [Microsoft/PowerBI-visuals#5]
The doc on [SPA](https://github.com/Microsoft/PowerBI-visuals/wiki/Displaying-visuals-in-a-single-html-page) mentions allInOne.js which does not seem to exist. 

```html
<script type="text/javascript" src="allInOne.js"></script>
```

Should it be powerbi-visuals.all.min.js instead? The latter shows up in the F12 network monitor when using the [playground](http://microsoft.github.io/PowerBI-visuals/playground/index.html)

**Comment by spatney** [comment]
Thanks! fixed.
