### ISSUE TITLE
Update Website section regarding whether stock visualizations are available

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/PowerBI-visuals#501]
Hello,

Currently when you search for PowerBI custom visuals you can find [this page](https://powerbi.microsoft.com/en-us/custom-visuals/). It states that the code for all visualizations has been published to Github. 

As per [this thread](https://community.powerbi.com/t5/Developer/Power-BI-Table-Visual-Source-Code/td-p/196185) these visualizations aren't available anymore.

Please can you update the text on the page to reflect this? 

Thank you!
-Craig

**Comment by helen508light** [comment]
updated
