### ISSUE TITLE
Dropdown cannot overlap as it would in normal web UI

### ISSUE THREAD

**Issue by jrichview** [microsoft/PowerBI-visuals#505]
At first it seems logical that the custom visual's frame would hide all content outside the visual's frame. However, when your custom visual contains a dropdown, or really anything that is intended to overlap the content below that control vertically, it cannot. 

The reason that dropdown controls exist is to avoid using up vertical screen layout that a listbox would occupy. The dropdown overlays whatever content is below it. 

This cannot be done with a custom visual. You have to fully occupy the amount of space that your dropdown might require. This means you gain absolutely no value from using a dropdown instead of a listbox.

I have tried setting the z-index to 1000 and it, as you would expect, had no effect despite the fact that the visual's container frame has z-index of 4.

**Comment by aakash1401** [comment]
@jrichview Any idea how to overlap the controls. Even in reading mode, I can see the default width and height of custom visual. For example, Please see my screenshot for reference.

![image](https://user-images.githubusercontent.com/31201591/57365558-eb6de800-71a2-11e9-9e54-1471193ae012.png)

The default width is only showing 4 options. You mean to say, while adding this widget in dashboard during final output, increase its height and overlap other modules by default.

**Comment by zBritva** [comment]
The visual loads inside iframe, and there is no any option to disable it. You can't draw any UI elements outside of iframe.
