### ISSUE TITLE
Navigation to URL

### ISSUE THREAD

**Issue by spatney** [Microsoft/PowerBI-visuals#52]
This will allow visuals to navigate the user to another URL.

**Comment by TonyGaul** [comment]
Hi, can you please give an update as to when this will be released?  The changelog and roadmap don't seem to be aligned.
https://github.com/Microsoft/PowerBI-visuals/blob/master/Roadmap/README.md
https://github.com/Microsoft/PowerBI-visuals/blob/master/ChangeLog.md

**Comment by TonyGaul** [comment]
@ignatvilesov Hi, do you have any idea when this feature will be released?  Thanks

**Comment by ignatvilesov** [comment]
@TonyGaul As far as I know, it will be available in May 2017. We'll update status of this issue as soon as we implement it.

**Comment by TonyGaul** [comment]
Thanks for the update!

**Comment by matthewfcarlson** [comment]
Really looking forward to this particular feature. Any updates?

**Comment by AviSander** [comment]
we're trying to push this to SU09 (beginning of Aug 2017)

**Comment by ryanpcali** [comment]
Any Updates? I would love to be able to link to other reports with more details utilizing my custom visualization. 
Thanks.

**Comment by nicksav** [comment]
Any update?

**Comment by TonyGaul** [comment]
Hi, I am still waiting for this update too.  Please provide an accurate implementation date.   This request has been on the backlog for well over a year.

**Comment by uve** [comment]
@nicksav, @TonyGaul Navigation URL API is postponed to API 1.9

**Comment by nicksav** [comment]
Hi @uve  ETA for 1.9? 
Thanks
Nick

**Comment by uve** [comment]
@nicksav, new API is coming later this year.

**Comment by ignatvilesov** [comment]
This feature has been delivered in API 1.9.0
