### ISSUE TITLE
Github.io comments: Filter API

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#520]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/concepts/filter-api/

**Comment by danieleperilli** [comment]
Hi, is it possible to apply multiple Tuple filters with different number of targets? For example, a filter with just one column and another with 3 columns. I tried to call applyJsonFilter() with FilterAction.Merge multiple times, but every call replaces the existing filter, not merge with it. Thanks!

**Comment by danieleperilli** [comment]
If it is not possible to really merge different filters, is it possible to define one of the values equal to *any*?
For example: 
```
let targets: ITupleFilterTarget = [
    {
        table: "Product Category",
        column: "Category"
    },
    {
        table: "Product Subcategory",
        column: "Subcategory"
    }
};
let values = [
    [
        { value: "Audio" },
        { value: "Bluetooth Headphones" }
    ],
    [
        { value: "Computers" },
        { value: "*" } //I need to say "any"
    ]
];
```

**Comment by a10k** [comment]
@danieleperilli  Regarding your question about merge: we can define multiple tuples/basic/advanced filters in an array and apply the array directly.

So, when you have only one column and you want to filter it you add only one column and apply (Its then equivalent to a basic filter, the host would translate it to a basic filter even if you define it with the tuple schema), and the other with two columns as a tuple filter. 

But all the filters in that array are applied with an AND operator, so we don't get the behaviour we desire as with an * operator. 

But I don't think its a problem with the custom visuals alone: when I added a filter for a column to the page and duplicated it and turned off interactions between both these slicers, and try selecting few values in one and few in another we get only an intersection of these filters (the same behaviour as the above apply JSON API) I think it's currently not possible to do it.

**Comment by a10k** [comment]
@uve If I'm trying to use the Date hierarchy in a filter, the query is like: <TABLE>.<COL>.Variation.Date Hierarchy.<YEAR/DAY etc.,> How would I use this in the filter target? which part is a table and which one is a column? If I use the actual table and column name the filter doesn't apply. Thanks!
