### ISSUE TITLE
What is the latest version of `powerbi-visual-tools` API supported by PBI Report Server?

### ISSUE THREAD

**Issue by ryanbaumann** [microsoft/PowerBI-visuals#526]
# Problem

Custom Visuals only function properly in PBI Report Server if they are built using the same or lower version of Powerbi-visual-tools in the PBI Report Server release.

# Question

For the latest release of PowerBI Report Server - https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service - what version of `powerbi-visuals-tools` ships with the latest version?

cc/ @uve

**Comment by sjlarkin** [comment]
I would like to know the answer to this question as well. We created a very simple visualization just to test it out, and it does not work on PBI Report Server (January 2019).

**Comment by helen508light** [comment]
Try to work with API 2.1.0 with PBI Report Server (January 2019)

**Comment by sjlarkin** [comment]
That worked! Thank you very much!

Sara Larkin
Technical Business Analyst III
Enterprise Data Solutions (Bank Data Warehouse)
BOK Financial
Business Technology Center
918-392-2726 – desk
slarkin@bokf.com<mailto:slarkin@bokf.com>

[cid:image001.png@01D52850.49537A80]
Services provided by BOKF, NA, Member FDIC. BOKF, NA is the banking subsidiary of BOK Financial Corporation.

**Comment by samusaran** [comment]
I'm developing a custom visual targeted for Power Bi Report Server (January 2020). It works on Powerbi.com and on the standard Power Bi Desktop, but it doesn't on Power Bi Desktop for Report Server (January 2020).

Here's my package.json:
```
{
  "name": "visual",
  "scripts": {
    "pbiviz": "pbiviz",
    "start": "pbiviz start",
    "package": "pbiviz package",
    "lint": "tslint -c tslint.json -p tsconfig.json"
  },
  "dependencies": {
    "@babel/runtime": "7.6.0",
    "@babel/runtime-corejs2": "7.6.0",
    "@types/d3": "^5.7.2",
    "core-js": "^3.6.5",
    "d3": "^5.16.0",
    "powerbi-visuals-utils-dataviewutils": "2.1.0",
    "powerbi-visuals-utils-formattingutils": "^4.6.0"
  },
  "devDependencies": {
    "powerbi-visuals-api": "2.1.0",
    "ts-loader": "6.1.0",
    "tslint": "^5.18.0",
    "tslint-microsoft-contrib": "^6.2.0",
    "typescript": "^3.8.3"
  }
}
```

**Comment by helen508light** [comment]
@samusaran
please write it on the forum topics related to Power Bi Desktop for Report Server and try new July version
