### ISSUE TITLE
You have exceeded the number of available v-cores in Premium Capcacity

### ISSUE THREAD

**Issue by reddysk18** [Microsoft/PowerBI-visuals#529]
i got this message in capacity settings. what does it mean? how can we exceed available cores.
we had 16 cores and we used all. and it shows 0 of 0 used. Earlier it was 16 of 16 used. ALl of our cores are gone? 
'You have exceeded the number of available v-cores. You can reduce your v-core usage by decreasing the size of one or more capacities, or you can purchase more v-cores. If you don't take action, capacities will be suspended soon"

**Comment by uve** [comment]
Hello @reddysk18,
This is a repository for Custom Visuals Development.
Please forward your question regarding Premiuim Capacity to our community forum.
It's best place to get answer to your question.
https://community.powerbi.com/t5/Get-Help-with-Power-BI/ct-p/PBI_GetHelp
