### ISSUE TITLE
Get unique id of the visual?

### ISSUE THREAD

**Issue by powerbilayeredmap** [Microsoft/PowerBI-visuals#530]
Is there any way to get a unique id of a visual that would change on copy/paste/new visual/etc?

**Comment by helen508light** [comment]
@powerbilayeredmap 
we support only unique quid for every visual. 
Always it is written in pbiviz.json visual project's file.
![image](https://user-images.githubusercontent.com/12563593/55718420-52fa1180-5a04-11e9-9481-196eda7b1fa8.png)
