### ISSUE TITLE
Visual User guide link

### ISSUE THREAD

**Issue by metinsevindik** [Microsoft/PowerBI-visuals#531]
Hi;

Is it possible to  visual user guide link show in visual properties.

Thanks

**Comment by helen508light** [comment]
@metinsevindik 
What do you mean? Please, describe in more details
If you want to show the link in formatting panel, use need to add string property to capabilities.json. But pay attention for security and purification entered link.
https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial-format-options  for string data using
```
 "type": {
                        "text": true
                    }
```

**Comment by metinsevindik** [comment]
Yes, I meant it. I will use format options.
Thanks.

**Comment by zBritva** [comment]
@metinsevindik you can also use a landing page in the visual to display short instructions or put the link into visual docs. Visual can display some info if user doesn't put data for the visual. 

Custom visual API should be 2.3.0.
Docs:
https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/landing-page/

There is a good sample in PowerApps Visual:
https://appsource.microsoft.com/en/product/power-bi-visuals/WA104381378

**Comment by metinsevindik** [comment]
> @metinsevindik you can also use a landing page in the visual to display short instructions or put the link into visual docs. Visual can display some info if user doesn't put data for the visual.
> 
> Custom visual API should be 2.3.0.
> Docs:
> https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/landing-page/
> 
> There is a good sample in PowerApps Visual:
> https://appsource.microsoft.com/en/product/power-bi-visuals/WA104381378

This perfect. That's exactly what I want. Thanks @zBritva
