### ISSUE TITLE
Special Treatment for some Visuals?

### ISSUE THREAD

**Issue by wysisoft** [Microsoft/PowerBI-visuals#532]
I am developing a custom visual and I need allow-same-origin in my sandbox iframe in IE11 / Edge, but I don't get that attribute. But the mapbox visual does. If I imitate the mapbox guid I get the attribute. When I change to any other guid I dont?

**Comment by uve** [comment]
@wysisoft, please forward your request to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>
