### ISSUE TITLE
Undo an applied filter?

### ISSUE THREAD

**Issue by vervatovskis** [microsoft/PowerBI-visuals#537]
I am using Filter Api to apply filter thru my custom visuals.
But I cannot find anywhere in the documentation how to clear/remove an already applied filter.
Any tips on how to do it?

**Comment by zBritva** [comment]
@vervatovskis just pass null instead filter object:

`visualHost.applyJsonFilter(null, "general", "filter", FilterAction.merge);`

Thanks for question, we will include into docs.

**Comment by vervatovskis** [comment]
@zBritva Thanks a lot

**Comment by zBritva** [comment]
[Documentation was updated](https://docs.microsoft.com/power-bi/developer/visuals/filter-api#clear-the-json-filter)
