### ISSUE TITLE
Power BI - Custom Visual - To implement Date Range Picker

### ISSUE THREAD

**Issue by aakash1401** [microsoft/PowerBI-visuals#543]
Hi,

I am making a Power BI custom visual with dropdown values like Today, Yesterday and Custom Dates. If I click custom dates, it should open a date range picker. All code is written using Typescript and Node (npm).

I am using jquery, moment and this date range picker library as instructed on the website.

To Note:- Current pbiviz version installed - 3.0.12

My package.json libraries entry look like this:

```
"dependencies": {
    "@babel/polyfill": "7.0.0",
    "@babel/runtime": "^7.2.0",
    "@babel/runtime-corejs2": "^7.2.0",
    "@types/bootstrap-datepicker": "0.0.11",
    "@types/d3": "^5.7.2",
    "@types/daterangepicker": "^2.1.17",
    "@types/jquery": "^2.0.41",
    "bootstrap": "^4.3.1",
    "bootstrap-datepicker": "^1.7.1",
    "d3": "^5.9.2",
    "daterangepicker": "^3.0.5",
    "jquery": "^3.2.1",
    "powerbi-models": "^1.1.0",
    "powerbi-visuals-api": "~2.2.0",
    "powerbi-visuals-utils-dataviewutils": "2.0.1",
    "powerbi-visuals-utils-typeutils": "^2.1.0",
    "require": "^2.4.20"
  },
```

Even jQuery is working fine in my visual.ts file. For example, this code works like magic:

```
import * as $ from "jquery";

private $root: JQuery;
private $searchHeader: JQuery;

update() {
this.$root = $("#sandbox-host").addClass("custom-jquery");
      this.$root.append('<form id="mySearch"></form>');
      this.$searchHeader = $('#mySearch').append('<input name="datefilter" type="text" 
      value="01/01/2018 - 01/15/2018" class="form-control" />');
}
```

But, at this line, it gives me the error.

```
$('input[name="datefilter"]').daterangepicker({
        opens: 'left'
      }, function(start, end, label) {
        console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
      });
```

Error in console is - **jquery__WEBPACK_IMPORTED_MODULE_124__(...).daterangepicker is not a function**

I know many have encountered this issue working with normal HTML, CSS and JavaScript flow and I am almost quite sure it is related to Versions mismatch.
Does anyone know how to fix this issue? Thanks in advance.

**Comment by zBritva** [comment]
Hello @aakash1401,

According the source code of daterangepicker:
https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L20
The plugin uses JQuery from global context (gets JQuery from window object).

And export function into window.JQuery.

And instance of JQuery from "import * as $ from "jquery";" doesn't have such function.

Power BI has JQuery in window context and uses for core functions. The configuration of webpack inside the new tools, injects window object for modules, to support old libs.

As workaround you can use custom webpack configuration to prevent injecting plugin into JQuery from global context.

You can find the sample here:
https://github.com/Microsoft/powerbi-visuals-webpack-plugin#webpack-configuration

**Comment by aakash1401** [comment]
@zBritva is there any way I can directly call window.jQuery in my visual.ts file? any workaround for that, like loading of js or window.jQuery directly? Or I would have to follow the mentioned steps in powerbi-visuals-webpack-plugin. Thanks

**Comment by zBritva** [comment]
@aakash1401 you can, but **we can't recommend. The visual can broken**, if Power BI updates the version of JQuery and version are incompatible.

**Comment by zBritva** [comment]
Try to use custom webpack config. Only one change it is need:
Remove `window: 'realWindow',` from
```
new webpack.ProvidePlugin({
    window: 'realWindow',
    define: 'fakeDefine',
    powerbi: 'corePowerbiObject'
}),
```
in the sample config at link above

**Comment by aakash1401** [comment]
@zBritva  Except that, any changes need to be done in my code files like visual.ts or package.json file related to jQuery?
Or only installing custom web pack config would be enough?

**Comment by zBritva** [comment]
@aakash1401 no, you need to import the package `import "daterangepicker";` in visual.ts

**Comment by aakash1401** [comment]
@zBritva  Just one help. ( Apologies as I am quite of entry-level guy when it comes to power BI configuration).
I just did **"npm i powerbi-visuals-webpack-plugin"** from npm website.
Next step I am not getting how to and where to add these configurations. I would be glad if you can provide me steps to follow in code. :)

**Comment by zBritva** [comment]
Just create `webpack.config.js` in root folder of the visual and copy sample config.
And also you need to install `npm i webpack  --save-dev`.

About webpack config: https://webpack.js.org/guides/getting-started/#using-a-configuration

**Comment by aakash1401** [comment]
I tried to follow the steps mentioned in the link. While running the command 

`npx webpack --config webpack.config.js`

after installing required libs ( it also installed webpack-cli which is for npx I think ), it is giving me this error 
```
C:\My Work\2019\05 May\finalDateRange\node_modules\powerbi-visuals-webpack-plugin\index.js
Cannot find module 'mini-css-extract-plugin'
```

If this command doesn't run successfully, changes won't reflect properly?

**Comment by zBritva** [comment]
Install all required packages:

`powerbi-visuals-webpack-plugin`,
`mini-css-extract-plugin`,
`webpack-visualizer-plugin`,
`extra-watch-webpack-plugin`

Probably other packages will be required. You will get same message `Cannot find module....`.
Just install package to resolve.

**Comment by aakash1401** [comment]
@zBritva Sure I will do that.

Second question. I would have to remove 

`import * as $ from "jquery";`  

from my visual.ts. But If i remove it, I will get error $ is not defined. Now from where to import this $.

**Comment by zBritva** [comment]
@aakash1401 why do you need to remove it?

**Comment by aakash1401** [comment]
As you said it will refer to jquery which doesn't have a .daterangepicker() function or my understanding is little odd/wrong.

Option 1: - 

1. Don't delete anything, add new import in visual.ts called  - import "daterangepicker";
2. Just follow power-bi webpack configuration steps and run command "npx webpack --config webpack.config.js"
3. It shoud work fine.

Option 2: If any, please suggest.

**Comment by aakash1401** [comment]
I have installed all package files mentioned during command run of npx webpack. Now Cannot module issue is gone but I am getting this error. instead.

```
ERROR in ./style/visual.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ref--8-2!./style/visual.less)
    Module build failed (from ./node_modules/less-loader/dist/cjs.js):
    Error: Cannot find module 'less'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
        at Function.Module._load (internal/modules/cjs/loader.js:508:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (C:\My Work\2019\05 May\finalDateRange\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
        at Object.<anonymous> (C:\My Work\2019\05 May\finalDateRange\node_modules\less-loader\dist\index.js:8:36)
        at Module._compile (C:\My Work\2019\05 May\finalDateRange\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
```
I have installed less, less-loader, css loader using npm i command  ex.  "npm i less-loader"

**Comment by zBritva** [comment]
Install 

    "@babel/core": "^7.4.3",
    "@babel/polyfill": "7.0.0",
    "@babel/preset-env": "^7.4.3",
    "@babel/runtime": "^7.1.5",
    "@babel/runtime-corejs2": "^7.1.5",
    "less": "3.8.0",
    "less-loader": "4.1.0",
    "ts-loader": "4.5.0",
    "typescript": "3.0.1",

or new versions. I just copied from powerbi-visuals-tools.

**Comment by aakash1401** [comment]
Hi. It got success now. It is creating directories in dist folder plus pbiviz package. How can I run it in compile mode or like pbiviz start to work along with jquery during development?

**Comment by aakash1401** [comment]
If I am running the package in the local PowerBI desktop, it is still not working. The present scenario in the visual.ts file.

```
import "daterangepicker";
import * as $ from "jquery";
```

```
update() {
if (selectValue === "Custom Range") {
      $(function() {
      console.log('Hello it is working');
      this.$root = $("#sandbox-host").addClass("custom-jquery");
      this.$root.append('<form id="mySearch"></form>');
      this.$searchHeader = $('#mySearch').append('<input name="datefilter" type="text" value="01/01/2018 - 01/15/2018" class="form-control" />');
      
      $('input[name="datefilter"]').daterangepicker({
        opens: 'left'
      }, function(start, end, label) {
        console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
      });
});
}
```

**Comment by aakash1401** [comment]
I also added these in package.json

```
"start": "pbiviz start",
    "package": "pbiviz package",
    "develop": "webpack --mode development --watch",
    "build": "webpack --mode production"
```
but how do I run this develop with pbiviz start

**Comment by zBritva** [comment]
@aakash1401 
I prepared update of docs, it's draft now:
https://github.com/zBritva/powerbi-visuals-webpack-plugin-1/blob/extend_docs/README.md

How to start dev server:
https://github.com/zBritva/powerbi-visuals-webpack-plugin-1/blob/extend_docs/README.md#run-webpack-dev-server-to-debug-custom-visual

**Comment by aakash1401** [comment]
On running npm run start command for webpack, it is giving this below error:

```
   throw err;
    ^

Error: mac verify failure
    at Object.createSecureContext (_tls_common.js:188:19)
    at Server (_tls_wrap.js:870:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at new Server (C:\My Work\2019\05 May\finalDateRange\node_modules\webpack-dev-server\lib\Server.js:702:35)
    at startDevServer (C:\My Work\2019\05 May\finalDateRange\node_modules\webpack-dev-server\bin\webpack-dev-server.js:168:14)
    at processOptions (C:\My Work\2019\05 May\finalDateRange\node_modules\webpack-dev-server\bin\webpack-dev-server.js:136:3)
    at Object.<anonymous> (C:\My Work\2019\05 May\finalDateRange\node_modules\webpack-dev-server\bin\webpack-dev-server.js:251:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

**Comment by aakash1401** [comment]
Thank god, the error is gone from console but nothing is happening on click on this line:

`$('input[name="datefilter"]').daterangepicker();`

Second in code if you add,

`debugger; `

doesn't work in case of web pack server. 

So this solution is like, with pbiviz start you will see the error again but in case of webpack, you don't.

Still. $().daterangepicker line do nothing.

**Comment by aakash1401** [comment]
It worked actually. :)

The issue was related to not adding all CSS of the daterangepicker library. 
You were literally god to me today who helped me resolve this issue. 

I also got to know how web pack works differently than pbiviz itself. 

Few takeaways:
1. If you are using third-party libraries, it's better to go for web pack version rather than pbiviz.
2. **debugger;** line in code only works with pbiviz not with web pack so you can't debug your code while development. Please let me know if we can debug our code with some command.
3. Creating Certs and passphrase is one of the crucial steps as mentioned on GitHub process.
4. Only Negative part is, your package.json is full of libraries thus your node_modules directory is quite bigger than you expected. ( Is there any resource/tools which show these are not usable libraries )
5. Custom visual in development mode hangs/stuck when you interact with it. After creating a package, it works smoothly.
6. Still need to learn, how to optimize overall generated package as it is quite big currently.

**Comment by zBritva** [comment]
1. yes, you need to use libs with es2015 modules, ex: https://www.npmjs.com/package/lodash-es
2. enable dev mode: https://webpack.js.org/guides/development/#root and disable minification 
    optimization : {
        concatenateModules: false,
        minimize: false
    },
3. you can skip, if you using webpack-dev-server
4. npm installs all required/used packages. powerbi-visuals-tools requires a lot of packages, but tools isn't part of the visual. you can remove the package, if you use webpack-dev-server and webpack-dev-server certs.
5. probably, browser blocks the custom ssl certificate. How to install certificate: https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/CertificateAddWindows.md
or open https://localhost:8080/status, you should see: 
![image](https://user-images.githubusercontent.com/10897951/57318820-daba6500-7103-11e9-9e01-768584486735.png)
and click to "Advanced" and "Proceed"
use the second one if you use dev-server-certificate.
For IE11 and Edge browsers you need to use the first approach.
6. result size of *.pbiviz is critical only (no more than 2MB), doesn't matter how much packages you used

**Comment by zBritva** [comment]
As option, you can try to use [base64-inline-loader](https://www.npmjs.com/package/base64-inline-loader)

To install:
`npm install --save-dev base64-inline-loader`
And apply config in webpack.config.json at rules section:

```
{
    test: /\.(woff|ttf|ico|woff2)$/i,
    use: [
      {
        loader: 'base64-inline-loader'
      }
    ]
}
```

webpack will put font files as base64 string in result css file

**Comment by Aryanmirza20** [comment]
can you explain how to implement such date picker along with custom date selection and pop up calendar. I am trying to code it for power BI visual but unable to do so
