### ISSUE TITLE
To show custom visual outside iframe container

### ISSUE THREAD

**Issue by Kumar-Aakash** [microsoft/PowerBI-visuals#544]
Hi,

At first, it seems logical that the custom visual's frame would hide all content outside the visual's frame. However, when your custom visual contains a dropdown or really anything that is intended to overlap the content below that control vertically, it cannot.

I am working on a custom date picker which shows dropdown and date picker based on selection. Currently my custom visual looks like this.

![image](https://user-images.githubusercontent.com/31201591/57443045-e3797b00-726a-11e9-9059-b35e3b9101cf.png)

If you can see, I have to increase the container's width manually by dragging it in Power BI. It's a problem in a scenario which has a dashboard and many containers widgets. if I keep increased height based on the date picker view, it will overlap other visuals in my reports/dashboard.

I recently also saw "Date" Slicer visual which perfectly show datepicker outside the container. Here is the image.

![image](https://user-images.githubusercontent.com/31201591/57443305-5be03c00-726b-11e9-999f-a49e300a0b47.png)

Even if the container height is very less, this visual is opening Datepicker on top of all.
Technical explanation - Somehow it is attaching this Datepicker div in the very top level Window object in the browser.

The same solution, I am not able to implement. I am using jQuery in my visual.ts and every time I try to access parent.document or top.document or similar origin issues/answers available on Internet/Stackoverflow. It can still access body of **iframe** in which my custom visual was loaded.

If you see Date slicer while inspecting it, it doesn't load it in an iframe, it just loads it normally under the <visual> tag.

How to achieve it. Does anyone know? I want to free my datepicker to be contained inside iframe code or is there any way I can remove iframe itself and can load it normally like date slicer?

**Comment by aakash1401** [comment]
@zBritva I know you must be knowing this in depth. Any inputs/suggestions?

**Comment by zBritva** [comment]
Hello @aakash1401,

Unfortunately custom visuals executes inside iframe by security reasons. And they also can break Power BI functionality.

**Comment by a10k** [comment]
I had the same issue with a complicated dropdown build, I considered opening a popup window opened from the iframe that I can use to display as a small window overlay with the menus I want to display, but this is also disabled. I think this is secure but would be great to have the ability to display another popup iframe like the report tooltip which we can position and manage the size of from the visual code. Can something like this be added to the roadmap?

**Comment by pbicvsupport** [comment]
For now it is complicated to provide such functionality (add iframe + iframe popups).
We'll discuss it with Power BI API command, maybe they will find the way how to implement it

**Comment by nodueck** [comment]
How about resizing the iframe on a click. Is it possible?

**Comment by helen508light** [comment]
@nodueck 
There are no such ability, only focus mode.
But focus mode is not allowed to be used automatically - it could be used by entering button "Edit"

**Comment by mujiannan** [comment]
For dropdown, I use HtmlSelectElement;
For calendar, I use HtmlInputElement with type='date'.
They both work well on desktop and iphone, but failed on Android phone.
