### ISSUE TITLE
Trying to use telerik with webpack in custom visual failing trying to load css / less

### ISSUE THREAD

**Issue by magnadrew** [microsoft/PowerBI-visuals#549]
I am new to powerbi custom visuals and we wanted to make some custom controls but leverage Kendo UI.  I had something working following an sample from 2 years ago but it uses on older version of tools and did not take advantage of npm install of kendo and web pack which is recommended approach for deploy kendo.

I upgraded to pbiviz version 3.0.13 got the js portions working with webpack in my custom visual.  I want to import the styles from the node_module but it fails when trying to import either less or css bindings.  I am not very familiar with using web pack and tried a number of suggestions from around the web.  Ideally it will pack it in but even if I could dynamically reference the css in the component by using jquery or something I would be ok with that solution.  

I put the sample in github - [https://github.com/magnadrew/powerbi-kendo]  If you uncomment the import described below errors happen during the build when issuing pbiviz start. 

When I import with:
   import "./../node_modules/@progress/kendo-ui/css/web/kendo.common.less";

I get a number of errors - here are some:

  ERROR in ./node_modules/@progress/kendo-ui/css/web/textures/transtexture.png 1:0
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.

    ERROR in ./node_modules/@progress/kendo-ui/css/web/kendo.default.less (C:/Users/dhaller.MAGNITUDE/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/css-loader!C:/Users/dhaller.MAGNITUDE/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/@progress/kendo-ui/css/web/kendo.default.less)
    Module build failed (from C:/Users/dhaller.MAGNITUDE/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/less-loader/dist/cjs.js):

**Comment by zBritva** [comment]
Hello @magnadrew, 

Thanks for feedback, we will add required loader in 3.1.1 version of tools.

**Comment by magnadrew** [comment]
Thank you.  In the meantime I was able to get something working by installing the webpack plugin (https://github.com/microsoft/powerbi-visuals-webpack-plugin) and customizing the webpack.config.js.  

I added "gif|eot|svg" to  
    test: /\.(woff|ttf|ico|woff2|jpg|jpeg|png|webp|gif|eot|svg)$/i,
    use: [
          {
            loader: 'base64-inline-loader'
           }
                ]

Is there an easy way to customize/override the webpack.config.js use in pbiviz start?  I tried changing it in directly in node_modules\powerbi-visuals-tools\lib\webpack.config.js but it did not seem to apply.  Maybe there is a step I am missing?  
If not already possibly I would like request feature /docs enabling override.

Thanks,
Drew

**Comment by zBritva** [comment]
No, you can't override config in tools. Use webpack directly as workaround

**Comment by zBritva** [comment]
@magnadrew the update was released:
https://www.npmjs.com/package/powerbi-visuals-tools/v/3.1.1

You can update tools to 3.1.1. It supports loading images.

**Comment by magnadrew** [comment]
Thanks but actually it still needs to support eot and svg to work.

As a work around I did:
  npm i powerbi-visuals-tools --save-dev
  added in package.npm scripts section 
      "start": "pbiviz start",
  make changes in node_modules\powerbi-visuals-tools\lib\webpack.config.js
  from terminal npm run start

**Comment by zBritva** [comment]
@magnadrew thanks! we will add in next version.

**Comment by beriwalt** [comment]
hi i am also working to develop powerbi custom visual and i am damn new to it. I also tried to run a sample from github but throws error like this.

**ERROR in ./style/visual.less
Module build failed (from C:/Users/tushar.beriwal/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from C:/Users/tushar.beriwal/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/less-loader/dist/cjs.js):


  padding-right: calc((1em + 0.75rem) * 3 / 4 + 1.75rem);
  background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3e%3cpath fill='%23343a40' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right 0.75rem center/8px 10px, url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3e%3cpath fill='%2328a745' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3e%3c/svg%3e") #fff no-repeat center right 1.75rem/calc(0.75em + 0.375rem) calc(0.75em + 0.375rem);
^
Cannot read property 'denominator' of undefined
      in node_modules\bootstrap\dist\css\bootstrap.css (line 2108, column 2)
    at runLoaders (C:\Users\tushar.beriwal\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\webpack\lib\NormalModule.js:302:20)
    at C:\Users\tushar.beriwal\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\tushar.beriwal\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\tushar.beriwal\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at <anonymous>
 @ ./src/visual.ts 162:0-32
 @ ./.tmp/precompile/visualPlugin.ts
 @ multi ./.tmp/precompile/visualPlugin.ts
Child mini-css-extract-plugin C:/Users/tushar.beriwal/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/css-loader/dist/cjs.js!C:/Users/tushar.beriwal/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/less-loader/dist/cjs.js??ref--6-2!style/visual.less:
    Entrypoint mini-css-extract-plugin = *
    [0] C:/Users/tushar.beriwal/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/css-loader/dist/cjs.js!C:/Users/tushar.beriwal/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/less-loader/dist/cjs.js??ref--6-2!./style/visual.less 906 bytes {0} [built] [failed] [1 error]**

if you can help me then it will be appreciable.

**Comment by zBritva** [comment]
Hello @beriwalt, it seems you try to use svg as background. But tools doesn't have configuration for loading svg for less.

**Comment by beriwalt** [comment]
> Hello @beriwalt, it seems you try to use svg as background. But tools doesn't have configuration for loading svg for less.

Hi @zBritva, can you suggest me a way to resolve the error.

**Comment by zBritva** [comment]
You can use plugin for webpack https://github.com/Microsoft/powerbi-visuals-webpack-plugin

**Comment by beriwalt** [comment]
> You can use plugin for webpack https://github.com/Microsoft/powerbi-visuals-webpack-plugin

Should I follow all the steps stated in the link you provided ?

**Comment by zBritva** [comment]
Do you mean DualKPI?:

https://github.com/Microsoft/powerbi-visuals-dualkpi

You can copy webpack.config.js from link into the root of any visual (converted to use new tools) and modify webpack config to match your requirements.

And yes, you will need to follow steps from link to install required packages and prepare `scripts` to launch dev server or prepare visual package.

**Comment by beriwalt** [comment]
No, not dual KPI. But, something that have bar charts, line charts,secondary axis for line chart. In which we can apply targets and comparison. something like that, and if possible bar can be made stacked.
