### ISSUE TITLE
 error: unknown option `--create-cert'

### ISSUE THREAD

**Issue by KEID07** [microsoft/PowerBI-visuals#550]
When I run the "pbiviz --create-cert" command on powershell following the documentation it shows this error message:
` error: unknown option '--create-cert'`

Then I run "pbiviz help"  I found the   "pbiviz --create-cert"  disappear in the option pane like:
`  Options:

    -V, --version     output the version number
    --install-cert    Install localhost certificate
    -h, --help        output usage information`
Is this option have been removed?
(Note:My visuals-tools version is 3.3.0)

**Comment by zBritva** [comment]
Use `--install-cert`, it's same.

**Comment by edwin500** [comment]
same issue --create-cert unknown option

**Comment by JavierEvaristo** [comment]
Hi, I had the same problem, and I tried directly running "pbiviz --install-cert"
A new certificate was created and installed. Hope you can solve it too :)

**Comment by luojiandan** [comment]
> Hi, I had the same problem, and I tried directly running "pbiviz --install-cert"
> A new certificate was created and installed. Hope you can solve it too :)

run pbiviz --install-cert again,it's ok!
