### ISSUE TITLE
pbiviz package does not work for newly added sampleRHTMLVisual

### ISSUE THREAD

**Issue by leilaetaatiprogram** [microsoft/PowerBI-visuals#554]
Hi  I use these features more than a year ago and it works very good, but today for a client I want to practice, in the first stage after pbiviz new sampleRHTMLVisual -t rhtml
when I navigate to the folder sampleRHTMLVisual and then I run pbiviz package I got some below message
 info Building visual...
 info   Start preparing plugin template
(node:5708) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 info   Finish preparing plugin template
 info   Start packaging...
 error  Author name is not specified
 error  Author e-mail is not specified
 error  The visual description is not specified
 error  supportUrl is not specified

I think something has been deprecated "tapable.plugin" which I am not sure how it is related 
really appreciate if you let me know

**Comment by zBritva** [comment]
You need to fill Author email, name, description, support URL

**Comment by leilaetaatiprogram** [comment]
Thanks it works now!
