### ISSUE TITLE
Zoomable Circle Packing

### ISSUE THREAD

**Issue by luojiandan** [microsoft/PowerBI-visuals#556]
power bi is a great product,I love it,and i want to develop custom visuals,i try two month,and feel very diffcult.
these are a lot of d3 example,i try to migrating to powerbi,can u give me a simple example.
eg:Zoomable Circle Packing  [https://bl.ocks.org/fdlk/076469462d00ba39960f854df9acda56](https://bl.ocks.org/fdlk/076469462d00ba39960f854df9acda56)
@uve @zBritva @helen508light

**Comment by zBritva** [comment]
@luojiandan The latest version of tools (3.1.x) supports D3 version 4. If you use old version of tools (version 2.6.0 or less) you can have difficults in including D3 library.

Could you explain what kind of difficults do you have?

**Comment by luojiandan** [comment]
@zBritva thanks for reply :)
I want to create a Zoomable Circle Packing Visuals in powerbi,it seems very easy,because the open source code.
but when I coding,I got two problems:
1) js to ts
2) the data structure design
can u help me to build the visual,then,i can following it.

**Comment by zBritva** [comment]
There is docs how to develop the simple visual:
https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial
But tutorial is outdated, we are preparing the new one. There is some difference in tools v3:
https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/

You can use typings for D3 library.
https://www.npmjs.com/package/@types/d3 (http://definitelytyped.org/)

You don't need to convert JS to TS. **Or you want to use your JS code?**

You can read about data structure/data view mapping in docs:
https://microsoft.github.io/PowerBI-visuals/docs/concepts/dataviewmappings/
