### ISSUE TITLE
Allow embedding assets via the "assets" directory

### ISSUE THREAD

**Issue by aschuhardt** [microsoft/PowerBI-visuals#557]
See #104 

We should be able to embed assets (images, 3D models, data, etc.) in visualizations via the "assets" directory.

Currently there are two ways to accomplish this:
- Keep the files in a CDN (incompatible with offline desktop mode)
- Store the files in a data string (causes issues with particularly large files)

Not being able to store assets in the "assets" folder is counter-intuitive.

**Comment by zBritva** [comment]
@aschuhardt  The new tools 3.x supports to embed assets for images, fonts, json. For other formats, you can configure custom webpack project of the visuals:
https://github.com/Microsoft/powerbi-visuals-webpack-plugin#how-to-build-a-visual-with-webpack
