### ISSUE TITLE
Property 'launchUrl' does not exist on type 'IVisualHost'.

### ISSUE THREAD

**Issue by kuehcj** [microsoft/PowerBI-visuals#558]
When I create a new Power BI Visual project, by default the **visual.ts**  file in **src** folder is not wrapped in 
```
module powerbi.extensibility.visual {
...
}
```
This is consistent with the recommendation in [Migrating to powerbi-visuals-tools 3.x](https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/#changes-inside-of-the-visuals-sources). 

However, without wrapping the code in module as mentioned above, when I tried 
```
import powerbi from "powerbi-visuals-api";
import IVisualHost = powerbi.extensibility.IVisualHost;
...
export class Visual implements IVisual {
    private visualHost: IVisualHost;

    constructor(options: VisualConstructorOptions) {
        this.visualHost = options.host;
        ...
    }
    private createHelpLinkElement(): Element {
        let linkElement = document.createElement("a");
        linkElement.textContent = "?";
        linkElement.setAttribute("title", "Open documentation");
        linkElement.setAttribute("class", "helpLink");
        linkElement.addEventListener("click", () => {
            this.visualHost.launchUrl("https://github.com/Microsoft/PowerBI-visuals/blob/master/Readme.md#developing-your-first-powerbi-visual");
        });
        return linkElement;
    };}
```
The line to call launchUrl is failing with an error message: **Property 'launchUrl' does not exist on type 'IVisualHost'**.
May I know if there is anything that I missed and how can I fix this issue?

**Comment by zBritva** [comment]
'import IVisualHost = powerbi.extensibility. visual.IVisualHost;'

**Comment by kuehcj** [comment]
Thank you, @zBritva! Sorry for that newbie question but it is working perfectly now after the import is corrected.
