### ISSUE TITLE
Tooltips in 2.6.1 of api

### ISSUE THREAD

**Issue by devwheel** [microsoft/PowerBI-visuals#561]
New to this and there is not much documentation for the API aside from older samples.  I've added the tooltipservicewrapper to my project and don't quite understand how to reference the VisualTooltipDataItem object.  It comes up with an error

**Comment by pbicvsupport** [comment]
Hi!
it comes from this namespace
import VisualTooltipDataItem = powerbi.extensibility.VisualTooltipDataItem;

You can provide tooltipInfo to your data used in smth likr this
`        this.tooltipServiceWrapper.addTooltip(
            selection,
            (tooltipEvent: TooltipEventArgs<TooltipEnabledDataPoint>) => {
                return tooltipEvent.data.tooltipInfo;
            });`

and add tooltipInfo: VisualTooltipDataItem [] somewhere in the code
`       
 tooltipDataArray.push({
            displayName: localizationManager.getDisplayName("Role_Task"),
            value: task.name
        });`
