### ISSUE TITLE
Error TS2741: forEach is missing in type 'HTMLCollectionOf<HTMLBodyElement>

### ISSUE THREAD

**Issue by Jujubug88** [microsoft/PowerBI-visuals#562]
Trying to create a R html for the first time.  Using the template in examples:

pbiviz new sampleRHTMLVisual -t rhtml

when I go to package the visual I get the following error:

[tsl] ERROR in C:\Users\hensleyj\sampleRHTMLVisual\src\visual.ts(148,17)
      TS2741: Property 'forEach' is missing in type 'HTMLCollectionOf<HTMLHeadElement>' but required in type 'NodeListOf<HTMLHeadElement>'.

 error  in C:\Users\hensleyj\sampleRHTMLVisual\src\visual.ts

[tsl] ERROR in C:\Users\hensleyj\sampleRHTMLVisual\src\visual.ts(160,13)
      TS2741: Property 'forEach' is missing in type 'HTMLCollectionOf<HTMLBodyElement>' but required in type 'NodeListOf<HTMLBodyElement>'.

Since it was a template file I assumed if I make no changes it should run?  Is there an issue or any guidance to get this to work?

#################### UPDATE ###########################

Not sure it is a proper fix, a work around or if something else is going on, but I added "// @ts-ignore" to the line above the errors in the visual.ts file and it let me package my visual and it works in power bi.

**Comment by yf569** [comment]
I am facing the same issue. It takes me ages but still cannot solve it.

**Comment by luancvs** [comment]
Can you tell exactly where you added "//@ts-ignore"? I can't make it work, same error.

**Comment by yf569** [comment]
So I got an answer from Microsoft support team. We need to replace NodeListOf<HTMLHeadElement> with HTMLCollectionOf<HTMLHeadElement> in visual.ts.

**Comment by timothysims** [comment]
I made these changes and still couldn't get it to work.

**Comment by zBritva** [comment]
@timothysims what happens? any errors in console, blank visual, or any error in browser console?

**Comment by timothysims** [comment]
Same exact error before replacing NodeListOf with HTMLCollectionOf.

**Comment by timothysims** [comment]
@zBritva I got it to work. I didn't close the visual.ts file.

Where is the best place to learn this through and through? I've been through a number of tutorials and few of them work. At this point, my brain is mush. Any plans to have a learning module put up on 'learn'? I love those things as it pertains to machine learning endeavors in Azure.

**Comment by zBritva** [comment]
@timothysims We are updating the documentation to match with the latest changes in tools 3.x.x, where API will be described with short samples, instead creating one big step by step guide.

Docs are here: https://docs.microsoft.com/power-bi/power-bi-custom-visuals
