### ISSUE TITLE
Encoding changes in PowerBI

### ISSUE THREAD

**Issue by luancvs** [microsoft/PowerBI-visuals#563]
Using the template in examples:
pbiviz new sampleRHTMLVisual -t rhtml
And changing R code

I have "ã" in the dataset I am using to create my PBI Custom Visual. In R Studio, I see it as "ã", however, when I import it to PowerBi, it becomes "Ã£". Also, I can't put ` , ´ , ^ or ~ in my code, If I do I get Error: unexpected numeric constat  right before the character.

For example:

source('./r_files/flatten_HTML.r')

############### Library Declarations ###############
libraryRequireInstall("ggplot2");
libraryRequireInstall("plotly");
####################################################

################### Actual code ####################
df = data.frame(x = c('ã','b','d'),y = c(1,2,3))
g=ggplot(df, aes( x=x,y=y,color = x)) +
  geom_point(size = 3 ) + 
  labs(x = "")
ggplotly(g)
####################################################

############# Create and save widget ###############
p = ggplotly(g);
internalSaveWidget(p, 'out.html');
####################################################

Should display:
![Rplot](https://user-images.githubusercontent.com/34325283/64271623-0152a600-cf14-11e9-9326-54c68c9a7f92.png)

However, I get an error message because of "~". If I dont define df in the code, but it is in the PBI table, the label changes to "Ã£", like this:

![Rplot](https://user-images.githubusercontent.com/34325283/64348446-95cc0f80-cfcb-11e9-8f1f-430ce5f63036.png)

**Comment by helen508light** [comment]
duplicate
