### ISSUE TITLE
Implementing custom scrollbar into custom visual 

### ISSUE THREAD

**Issue by HardRock4Life** [microsoft/PowerBI-visuals#565]
Hello everyone! Is there any way to implement an external custom scrollbar via Typescript, e.g. [OverlayScrollbars?](https://github.com/KingSora/OverlayScrollbars)

Using webkit is helpful when using Chrome, but Firefox or MS Edge slip back to default one.

**Comment by helen508light** [comment]
Thank u
we'll fix it

**Comment by helen508light** [comment]
Does your visual support webpack?(API 2.x.x and powerbi-visual-toos 3.x.x)
With webpack visual u can use any library.
But if it does not support webpack - in most cases no.

If u want to use typical scrollbar with tiny customisation in our visual - see powerbi-visuals-gantt or powerbi-visuals-timeline repos.

**Comment by HardRock4Life** [comment]
Ok, I will take a look
