### ISSUE TITLE
how can one get the DataViewScopeIdentity of a column'

### ISSUE THREAD

**Issue by jo-tham** [microsoft/PowerBI-visuals#57]
Hi,

I'm interested in trying the scope identity selector as describer [here](https://github.com/woodbuffalo/powerbi-crosschart/issues/4#issuecomment-240790195) 

it is not clear to me what a 'column' is

i see [many interfaces](https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/blob/c9f36161f7f7c0657f6e90979ac5fc537067c743/.api/v1.1.0/PowerBI-visuals.d.ts#L517) have an identity property of `DataViewScopeIdentity` type

I tried to get `identity` on `metadata.columns` and get:

```
 error  TYPESCRIPT  /src/visual.ts : (87,34) Property 'identity' does not exist on type 'DataViewMetadataColumn'.
```

if it's not from `metadata.columns`, what does "columns" refer to in the docs?

Thanks in advance!

**Comment by jo-tham** [comment]
I see that metadata columns do not have the identity prop...

https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/blob/c9f36161f7f7c0657f6e90979ac5fc537067c743/.api/v1.1.0/PowerBI-visuals.d.ts#L427

**Comment by itslenny** [comment]
I'm not totally clear what you're trying to achieve. The first link you provided is going to a 404 not found page (perhaps a private repo?). Please provide a working link or explain what you're trying to accomplish. thanks.

**Comment by jo-tham** [comment]
hi @itslenny 

thanks for checking in - sorry about the 404. I meant to link to this:

https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Objects.md#scope-identity

what I am asking is, how can I "get the DataViewScopeIdentity of [a] column"?

In light of that, I think the original message should make more sense.

Let me know if I can provide further clarification.

**Comment by helen508light** [comment]
outdated API
