### ISSUE TITLE
how can I re-direct my pbiviz server address and port?

### ISSUE THREAD

**Issue by Thomastw** [microsoft/PowerBI-visuals#572]
For permission reasons, I have to use a browser on one computer and build a nodejs server on the other. But I couldn't find a way to replace "localhost:8080" in my browser. Hope advices.
Regards.

**Comment by helen508light** [comment]
@Thomastw 
It can't be adjusted

**Comment by Thomastw** [comment]
> @Thomastw
> It can't be adjusted now

So in this case, is there any alternative for debugging? For example, is there an offline desktop application directly connected to the nodejs server?

Thanks!

**Comment by helen508light** [comment]
I think there only 1 workarond - you can build pbiviz file on admin machine(with debugger; sections), and then copy it to machine with internet access, run the visual with ?unmin=true in the url and then debug it. Ir you can catch pbiviz and other needed resources request from fiddler and replace it with it's file's destinations on you admin machine(it will be in dist folder of the visual and then you can share it on your server or etc)

**Comment by Thomastw** [comment]
Besides I was requesting permissions, I was always compiling it completely and debug it on another computer. It took me a lot of time in every compilation cycle, especially when I imported a bloated ECharts library.
I also tried to tamper with this address in the browser's developer tool, but it failed. I'm not very good at front-end design.

Thanks and Regards.

**Comment by helen508light** [comment]
@Thomastw
Also maybe that way:
-you need accessible localhost:8080
- another machine should be accessible by net
-you need to redirect requests from your localhost:8080 to another machine by proxy or similar app like fiddler

**Comment by helen508light** [comment]
@Thomastw
There are easy way!
You should create new record in your browser Local Storage
DEVELOPMENT_SERVER_URL="any address that replaces localhost:8080"

**Comment by Thomastw** [comment]
> @Thomastw
> There are easy way!
> You should create new record in your browser Local Storage
> DEVELOPMENT_SERVER_URL="any address that replaces localhost:8080"

It sounds great, but it doesn't work for me. I'm not sure what went wrong.
![localhost](https://user-images.githubusercontent.com/58240246/86339170-db0dac00-bc85-11ea-9e44-87a94bcc7677.JPG)

Thanks and Regards.

**Comment by helen508light** [comment]
@Thomastw 
do you use should use it with and slash like this
![Uploading image.png…]()

 else it couldn't be parsed and quotes returns default

**Comment by Thomastw** [comment]
> @Thomastw
> you should use it with quotes and slash like this
> ![image](https://user-images.githubusercontent.com/12563593/86779466-47145980-c064-11ea-8498-3c70f03064bd.png)
> 
> else it couldn't be parsed and quotes returns default

Strange as it may be, it has changed. Thank you very much for your efforts. I will continue to explore.

Best regards.

**Comment by uve** [comment]
PowerBI service loads the dev visual from 8080 port. If you change the port, PowerBI will not be able to load your dev visual.

**Comment by helen508light** [comment]
@Thomastw 
you should have localStorage key filled before Power BI Service load
So you should refresh you web page to have changes


@uve we can change this localStorage key(known from Power BI source code debugging)

**Comment by helen508light** [comment]
It changes address and host for me(i don't have any server on this address)

![image](https://user-images.githubusercontent.com/12563593/87043125-495deb80-c1fd-11ea-9388-eb40e66af935.png)

**Comment by Thomastw** [comment]
Hi folks,

I mean, the problem seems to be solved. Though it seems strange, at least from my personal point of view it is acceptable. Thank you all for your concern.

Best Regards.
