### ISSUE TITLE
Fetch more data not working on Power BI Desktop

### ISSUE THREAD

**Issue by lolijimenez** [microsoft/PowerBI-visuals#573]
I am using the fetchMoreData method to bypass the 30k rows limit. It works in app.powerbi.com when debugging and also when I generate the pbiviz package, but It does not work in Power BI Desktop. It seems like it only receives the first VisualDataChangeOperationKind.Create, but never the VisualDataChangeOperationKind.Append, so all data are not loaded.

Is there any problem in this scenario?

Thanks.

**Comment by helen508light** [comment]
@lolijimenez 
Which version of Desktop are you using?

**Comment by lolijimenez** [comment]
Version is 2.75.5649.961 64-bit (November 2019)

**Comment by helen508light** [comment]
It seems was fixed in Version: 2.76.5678.541 64-bit (December 2019).
It was confirmed bug

**Comment by lolijimenez** [comment]
Yes, it is working with the current version (December 2019).
Thanks.
