### ISSUE TITLE
Delete button not showed when there are many of them uploaded

### ISSUE THREAD

**Issue by sanederchik** [microsoft/PowerBI-visuals#574]
**Power BI Desktop Report Server (September 2019)**

I can't see a "Delete" button when clicking "Delete custom visual element":

![image](https://user-images.githubusercontent.com/30187683/69876560-f3bd7a00-12d0-11ea-95f2-59285fae6ed1.png)

However, I see it when there are no or few custom visuals:

![image](https://user-images.githubusercontent.com/30187683/69876703-50b93000-12d1-11ea-9aec-95628bc7b518.png)

**Comment by helen508light** [comment]
@sanederchik 
Please, write to PowerBI RS topic in MS community forum
This repo related to main concepts, schemas and API usage in general

**Comment by sanederchik** [comment]
Thanks!

пн, 29 июн. 2020 г., 19:06 Elena Rodionova <notifications@github.com>:
