### ISSUE TITLE
Exactly the same custom visuals files loaded multiple times to page

### ISSUE THREAD

**Issue by sanederchik** [microsoft/PowerBI-visuals#575]
**Power BI Report Server (September 2019)**

I use a report with dozens of external custom visuals. 

At some moment I found out that my report started loading slowly. I checked out my page load waterfall and saw that **several exactly the same (mostly, JS) files had been loading simultaneously**.

`customVisualsHost.bundle.js`

![image](https://user-images.githubusercontent.com/30187683/70121642-0ee90a80-1680-11ea-9e4e-6d5ce2fa28a3.png)

`data.js`

![image](https://user-images.githubusercontent.com/30187683/70121757-553e6980-1680-11ea-97a7-bbd981ea54d6.png)

`jQuery.js`

![image](https://user-images.githubusercontent.com/30187683/70121874-87e86200-1680-11ea-8c1c-20a88f2e34cb.png)

`PowrMDL2.woff`

![image](https://user-images.githubusercontent.com/30187683/70122056-f4fbf780-1680-11ea-8d64-47e3151352c2.png)

`utility.js`

![image](https://user-images.githubusercontent.com/30187683/70122109-12c95c80-1681-11ea-94a0-aba95b6e8786.png)

`visualHostCore.js`, `VisualResourceLoader.htm`, `visuals.js`

![image](https://user-images.githubusercontent.com/30187683/70122177-342a4880-1681-11ea-86f2-b584e1a3e5f4.png)

`visualsandbox.css`

![image](https://user-images.githubusercontent.com/30187683/70122332-7eabc500-1681-11ea-9389-68fbeeaf4803.png)

`visualSandbox.externals.js`, `visualSandbox.js`, `visualSandbox.minimal.externals.js`

![image](https://user-images.githubusercontent.com/30187683/70122389-9be09380-1681-11ea-9ac8-a0fd09b3b4e1.png)

`VisualsSandboxCore.bundle.js`

![image](https://user-images.githubusercontent.com/30187683/70122516-d5b19a00-1681-11ea-8d00-faa8ee7b070a.png)

If I disable cache, **it becomes worse 3-4x times**.

![image](https://user-images.githubusercontent.com/30187683/70122892-891a8e80-1682-11ea-8994-24590ece8c6a.png)

I personally think that **it would be better to load each resource one time, and then use them as sources**.

**Comment by zBritva** [comment]
@sanederchik 
except core visual, all visuals are loading inside iframe, and for each iframe browser should load the sources/styles and parse it. There is no options use one loaded JS script in several iframes.

The visuals loads inside iframe due to security reasons

**Comment by sanederchik** [comment]
@zBritva, I think it is possible to optimize. 

I am not a professional JS developer but I think there is a solution to achieve desired result.

1. Write a function that loads **all these exactly the same files** once to main page.
2. Write a function that simultaneously generates iframes with `src` not a link but entire HTML document (e.g. use `srcdoc` tag instead).

**Comment by zBritva** [comment]
You can see that network panel shows 304 code for request. It means they already cached.

`srcdoc` specifies the content of iframe. All visual looks different with different data. And browser have to parse it too.

And visuals aren't only HTML/SVG in iframe.  There are a lot of JS codes should be parsed and executed by browser inside each iframe.

**Comment by sanederchik** [comment]
@zBritva, I made snapshots before disabling cache. My customers usually cache out browser each time, so there will be no `304` code. As you can see from my `waterfall`, it increases time of load dramatically.

I understand that custom visuals have their own code and other elements. But elements which I mentioned **are standard for each visual, there are 100% the same**. 

There should be a solution how to optimize it.

**Comment by sanederchik** [comment]
Any officials comments, please?
As a workaround, I replaced most of custom visuals for in-app ones, it enhanced the loading process by more than 100%. It looks like using custom visuals in BI reports with requirements for speed of loading is impossible without solving the issue I have stated here...
