### ISSUE TITLE
pbiviz new [name] cost long time(>30 minutes)

### ISSUE THREAD

**Issue by luojiandan** [microsoft/PowerBI-visuals#579]
@uve 
I create a new project by:
    pbiviz new CircleCard
it costs more than 30 minutes.
info:
Windows 10 professional
PSVersion: 5.1.17763.771
Node.JS: 12.14.1

![image](https://user-images.githubusercontent.com/5663556/72737623-de7f1080-3bda-11ea-9f4c-33ba3f35e95a.png)
the CircleCard folder size is 51.5M
why cost so long time?
thanks:)

**Comment by uve** [comment]
@luojiandan, what is your version of powerbi-visuals-tools? 
Please install the latest version and try it again.
