### ISSUE TITLE
Issue : X-axis text is displayed on a diagonal.

### ISSUE THREAD

**Issue by ArpithaGMGowda** [microsoft/PowerBI-visuals#584]
![image](https://user-images.githubusercontent.com/40782788/75322331-85209600-5898-11ea-893d-7c7b0136210e.png)

Hi 
i uploaded slimier Issue image which i am getting
 
have 2 graphs as shown in the screenshot.  On one of them, the labels are horizontal (right to left)  The 2nd one is displayed on a diagonal, if it is long label its displayed with dot dot in diagonal( emplyee...)  Is there a way to get with horizontal (right to left ) ?? The charts are identical in size and I have made sure the x axis settings are exactly the same.

**Comment by helen508light** [comment]
Which custom visual do you use? This issue should be related to d3 library and it's bar and axis settings, not to power BI in general
