### ISSUE TITLE
how to transform d3 sample to pbi visuals?

### ISSUE THREAD

**Issue by luojiandan** [microsoft/PowerBI-visuals#586]
I'm a new power bi custom visual developer,I want to transform some d3 sample to pbi visuals,I cost long time,It's hard for me now,I was hoping for some help,Thanks:)
there is a d3 sample(time-series line chart):
![01](https://user-images.githubusercontent.com/5663556/76166852-bce2e400-619c-11ea-8ba9-247ea122d651.png)
[time-series line chart.zip](https://github.com/microsoft/PowerBI-visuals/files/4303503/time-series.line.chart.zip)
can u help me?@uve @zBritva thanks:)

**Comment by helen508light** [comment]
@luojiandan 
At first please see https://github.com/microsoft/PowerBI-visuals-sampleBarChart and it's documentation https://microsoft.github.io/PowerBI-visuals/tutorials/building-bar-chart/building-a-visual-with-static-data/ to understand general things.
Also, your chart very similar to pulseChart  https://github.com/microsoft/powerbi-visuals-pulsechart and line chart logic  https://github.com/microsoft/powerbi-visuals-linedotchart

**Comment by luojiandan** [comment]
@helen508light I got it,thanks very much......
