### ISSUE TITLE
Image Viewer

### ISSUE THREAD

**Issue by cmmunteanu** [microsoft/PowerBI-visuals#592]
Hello everybody,

I have a project that contains a Bing map with 20 items using on LatLong coordinates.
I have also an ImageViewer in relationship with the map, so every time I select an item from the map I get an image.

Question:
How to get an image by selecting 2 items on the map? What do I have to include in the table?

Thank you

**Comment by helen508light** [comment]
@cmmunteanu 
Could you please clarify on examples? Now it's seems like you want multiselect

**Comment by cmmunteanu** [comment]
Problem fixed.
Thank you.

Regards,
Michael

**Comment by helen508light** [comment]
q
