### ISSUE TITLE
What happens when you apply an action Include/Exclude using the context menu

### ISSUE THREAD

**Issue by djpirra** [microsoft/PowerBI-visuals#593]
Hello,

I am having a problem in my custom visual when I apply the filters using Include/Exclude. It does not appear to be a Power BI issue but I need to understand how I can capture what is filtered so that I can change the behavior of the data that is use in the visual.

How can I detect what is being filtered since I see all data still appearing in the Dataview.

Thank you

**Comment by helen508light** [comment]
@djpirra
please clarify your issue in details on your dataset and report
