### ISSUE TITLE
How to reduce size of custom visual?

### ISSUE THREAD

**Issue by djpirra** [microsoft/PowerBI-visuals#594]
When custom visual is compiling I can see information saying some of the files including visual.js is [BIG]. How can I reduce the size of this file?

It seems that I have a lot of folders on the node_modules but only one was actually installed by me. Others came with the new custom visual already.

Thank you

**Comment by helen508light** [comment]
@djpirra 
Power BI tools and API require additional packages - so you can see them on node_modules. Visual couldn't work without them. 
Our current visual packaging plugin may give you and information about size limit, but even with this warnings package should work. You can split visual.ts on lowest parts, if it's refactoring really needed and do another standart ways for minimization, but it is not really needed use it the way they are. 
If you noticed strange behavior during packaging process that blocks building, please describe it in details

**Comment by djpirra** [comment]
Hi Helen,

I was not referring to the packaging yet since the visual is still under build but when running the pbiviz start I am already getting those warnings on the filesize.
And even not having a lot of code, I find weird that visual.ts has already 3.5MB.

Thank you
