### ISSUE TITLE
How to create selection IDs based on a category group with several fields

### ISSUE THREAD

**Issue by djpirra** [microsoft/PowerBI-visuals#595]
Hi,
I have a custom visual that is using a category with a maximum of 4 fields.
How can I create the selection IDs for these combinations of items on these fields since I can only specify one category field/position.

Example:
All 4 fields are booleans so the value combinations in categories would be something like:
True False False False
True True False False
etc...
I need a selectionID for each of these combinations since they will be represented visually the same way.

Thank you

**Comment by helen508light** [comment]
@djpirra 
Do you mean several categories in one bucket or in different buckets? 
In general it would be smth like this
```
values.forEach((categoryValue: PrimitiveValue, index: number) => {      
  const selectionBuilder: ISelectionIdBuilder = host
                .createSelectionIdBuilder()
                .withCategory(dataView.categorical.categories[0], index);
}
```

**Comment by djpirra** [comment]
I mean that you have only one category and one measure role and in the mappings conditions you can have up to 4 categories and 1 measure.

**Comment by zBritva** [comment]
@djpirra it's same for several fields like for one field:
https://docs.microsoft.com/power-bi/developer/visuals/selection-api#create-selections-for-categories

Power BI considers it like:

| FIRST  |  SECOND | "selection" |
|---|---|---|
| F1  |  S1 | 0| 
| F1  |  S2 | 1|
| F2  |  S1 | 2|
| F2  |  S2 | 3|

And if you want to select two rows by the first column (select all rows with FIRST equal to F2), your visual have to pass two selections (with "id" 2 and 3) into `select` method of the `selectionManager`.

You can't generate the one selection id for two rows.

**Comment by djpirra** [comment]
Thanks for the explanation. I got it working. :)
