### ISSUE TITLE
MapBox not displaying all data

### ISSUE THREAD

**Issue by kfagerburg** [microsoft/PowerBI-visuals#596]
Don't know if this is the right place to share this. If not, maybe someone can point me in the right direction.

I'm building a heat map using MapBox with COVID-19 data. I confirmed that I have complete data in Excel by building a PowerMap tour:
![image](https://user-images.githubusercontent.com/62898569/78939919-fb610c80-7a82-11ea-8507-86c1d2d14ff0.png)

When I import that Excel file into Power BI and and build a MapBox visualization it only displays about half the data:
![image](https://user-images.githubusercontent.com/62898569/78940008-26e3f700-7a83-11ea-81f3-9deb64ccc04f.png)

I had a co-worker try the same thing and got the same result.

**Comment by helen508light** [comment]
@kfagerburg 
do you use grouping?
Please, attach your pbix to this issue, it will help to solve it

**Comment by kfagerburg** [comment]
I’m having trouble attaching the files to the thread.

Attached is a pbix file that shows the issue. I’ve also attached and Excel file with the data and a PowerMap visualization built on top of it.

**Comment by kfagerburg** [comment]
[3d Map Example File.xlsx](https://github.com/microsoft/PowerBI-visuals/files/4495260/3d.Map.Example.File.xlsx)

**Comment by kfagerburg** [comment]
Can't get the PBIX file to attach.

**Comment by zBritva** [comment]
@kfagerburg According the screenshot of Power BI, you use [Globe Map](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104380799) visual, not [Mapbox Visual](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381472) visual.

I don't see [exact limit for data](https://github.com/microsoft/powerbi-visuals-globemap/blob/master/capabilities.json#L184) in sources Globe Map visual. By default it's 1000. But in your data count of rows is 3500.

Power BI displays warning at the corner of the visual:

**Comment by kfagerburg** [comment]
Yep, sorry I've mixed up which visuals I'm using and missed the fact that it limits to 1000 rows of data. This can be closed.
