### ISSUE TITLE
pbiviz package does not work for newly added sampleRHTMLVisual 

### ISSUE THREAD

**Issue by oliviafield** [microsoft/PowerBI-visuals#598]
I am trying to build a r powered custom powerBI visual. When i tried to add the pbiviz to Windows PowerShell and I got the message below
PS C:\cv\sampleRHTMLVisual> pbiviz package
 info   Building visual...
 info   Start preparing plugin template
 info   Finish preparing plugin template
 info   Start packaging...
 error  Author name is not specified
 error  Author e-mail is not specified
 error  The visual description is not specified
 error  supportUrl is not specified

I know I need to fill Author email, name, description, support URL but I am unsure how to do so, any ideas?

**Comment by helen508light** [comment]
@oliviafield 
you should complete your pbiviz.json file in that way https://github.com/microsoft/powerbi-visuals-gantt/blob/master/pbiviz.json
