### ISSUE TITLE
Developer Visual Setup Step 4 Doesn't Match Actual

### ISSUE THREAD

**Issue by MerlinGrim** [microsoft/PowerBI-visuals#60]
When I select "Developer Visual" in the Visualizations pane, I get:
"Can't contact visual server 
Please make sure that visual server is running and configured 
correctly. Learn more"

and then I notice that "pbiviz start" must be run (almost as an after thought in the step-by-step guide) ... only to find that executing "pbiviz start" in a command window results in "error LOAD ERROR [Error: pbiviz.json not found.  You must be in the root of a visual project to run this command."

**Comment by gendalf7771** [comment]
I've had this message too until used Firefox. It works with Internet Explorer.

**Comment by spatney** [comment]
@MerlinGrim Thanks. I suppose the link should point here insteads. Thanks.  https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/usage.md#running-your-visual

**Comment by itslenny** [comment]
@MerlinGrim In the command window you must change directories to the root of your visual (the folder created using the `pbiviz new` command). Then you run `pbiviz start` and it will launch an http server that will serve up that visual so you can preview it live in PowerBI

**Comment by itslenny** [comment]
@spatney I updated the link to point to that url directly.

**Comment by helen508light** [comment]
outdated
