### ISSUE TITLE
Chinese and Japanese characters cannot be displayed correctly in custom-visual using R

### ISSUE THREAD

**Issue by MG-42-GO** [microsoft/PowerBI-visuals#600]
This may be a bug that has not been resolved for a long time. I found that almost all custom-visual developed using R, including [funnel plot](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381066?src=office&tab=Overview) and [forecasting TBATS](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381326?src=office&tab=Overview), cannot solve the problem of decoding errors of Chinese and Japanese characters. (as of today) ; I am also using r to develop custom-visual. The problem is I am not clear what the language encoding-decoding process is like after it is imported into PowerBI. I tried using the ["showtext"](https://cran.r-project.org/web/packages/showtext/vignettes/introduction.html) package but did not solve the problem. (hope it can be solved here)  

Any solution?
(I guess the cause of this error may be the same as [this issue](https://github.com/microsoft/PowerBI-visuals/issues/563))

**Comment by zBritva** [comment]
@MG-42-GO Did you try to apply the [steps from docs](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals#known-limitations)?

> Chinese, Japanese, and Korean fonts require all of the additional following steps to work properly in the Power BI service...

**Comment by MG-42-GO** [comment]
> @MG-42-GO Did you try to apply the [steps from docs](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals#known-limitations)?
> 
> > Chinese, Japanese, and Korean fonts require all of the additional following steps to work properly in the Power BI service...

Yes! I have installed and loaded the package 'showtext' and add "powerbi_rEnableShowTextForCJKLanguages =  1" at the beginning of "script.r" , but it doesn't seem to solve the problem. Maybe you can help me test it if it's possible.

**Comment by zBritva** [comment]
I just run the sample

```r
powerbi_rEnableShowTextForCJKLanguages =  1
powerbi_rEnableShowText =  1

plot(1, main = "\u4F60\u597D\uFF0C\u4E16\u754C")
```

![image](https://user-images.githubusercontent.com/10897951/80688358-53b08a80-8ad4-11ea-8604-660d55cfeb3d.png)

It works in Power BI Desktop and Services too. 

What version of R do you use locally? Power BI Service uses the [specified version](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support#requirements-and-limitations-of-r-packages)

**Comment by MG-42-GO** [comment]
> I just run the sample
> 
> ```r
> powerbi_rEnableShowTextForCJKLanguages =  1
> powerbi_rEnableShowText =  1
> 
> plot(1, main = "\u4F60\u597D\uFF0C\u4E16\u754C")
> ```
> 
> ![image](https://user-images.githubusercontent.com/10897951/80688358-53b08a80-8ad4-11ea-8604-660d55cfeb3d.png)
> 
> It works in Power BI Desktop and Services too.
> 
> What version of R do you use locally? Power BI Service uses the [specified version](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support#requirements-and-limitations-of-r-packages)

Yes!  It works in R Visual **but** it does not work in **custom visual** using R.  
(My R Version: 3.6.0)
Here is an example:
In R 3.6.0:
`g = qplot(`Petal.Length`, data = iris, fill = `Species`, main = Sys.time());    `
 `  g = g + xlab("你好") + ylab("世界")`

And then I got the right output:
![20200501093502](https://user-images.githubusercontent.com/62893767/80774501-c5014380-8b8f-11ea-9d37-34a100a0a607.png)
While in PowerBI Desktop:
I use following code in sript.r:
`source('./r_files/flatten_HTML.r')

############### Library Declarations ###############
libraryRequireInstall("ggplot2");
libraryRequireInstall("plotly");
libraryRequireInstall("showtext")
####################################################
powerbi_rEnableShowTextForCJKLanguages =  1
powerbi_rEnableShowText =  1
################### Actual code ####################
g = qplot(`Petal.Length`, data = iris, fill = `Species`, main = Sys.time());  
g = g + xlab("你好") + ylab("世界")
####################################################

############# Create and save widget ###############
p = ggplotly(g);
internalSaveWidget(p, 'out.html');`

And then I got the **wrong** output:
![20200501093556](https://user-images.githubusercontent.com/62893767/80774618-18739180-8b90-11ea-8805-ac7e760e3716.png)

Any ideas?

**Comment by zBritva** [comment]
@MG-42-GO Sorry, I though you talk about Rvisuals type (images), not RHTML.

I reproduced the issue and figure out the reason.
to fix find in the `visual.ts` the block of code in `injectCodeFromPayload` method: 

```typescript
// create 'virtual' HTML, so parsing is easier
let el: HTMLHtmlElement = document.createElement("html");
try {
      // tslint:disable-next-line
      el.innerHTML = window.atob(payloadBase64);
} catch (err) {
     return;
}
```

and change 

```typescript
el.innerHTML = window.atob(payloadBase64);
```

to 

```typescript
el.innerHTML = decodeURIComponent(escape(window.atob(payloadBase64)));
```

+@uve, @EugeneElkin
I think, templates of visual should be updated

**Comment by MG-42-GO** [comment]
@zBritva Thanks! It works. I really appreciate it!
