### ISSUE TITLE
Is it possible to DEVELOP custom visuals with the node stuff in power bi desktop?

### ISSUE THREAD

**Issue by nowherenearithaca** [microsoft/PowerBI-visuals#602]
I've seen how the custom viz development works against the web site, where it talks back to your machine on port 8080.

Is there a way for this workflow to work when you're in power bi desktop?

Thanks!

**Comment by dynamicapps** [comment]
No.  You develop using the developer visual in PBIS and then compile and package it to use in PBID.  The added benefit of working on PBIS is that you can debug using a web browser.

**Comment by nowherenearithaca** [comment]
thanks - that's what I figured but wanted to make sure you could only develop with PBIS
