### ISSUE TITLE
Remove lines like "console.debug"

### ISSUE THREAD

**Issue by mujiannan** [microsoft/PowerBI-visuals#603]
I want to remove code lines like "console.debug".
1. Add cover.js
```
var Debug=true;
function blankConsoleDebug(){
    return;
}
if(!Debug){
    console.debug=blankConsoleDebug;
}
```
2. Edit pbiviz.json, add "./src/cover.js" to externalJS
```
    "externalJS": [
        "./src/cover.js"
    ],
```

Now it works well. But every time I want to package my custom visual, I need to set the variable "Debug" to false.
I do want to know: 
Is there any way better to **Auto remove console.debug**?

**Comment by helen508light** [comment]
@mujiannan now it is not supported out-of-the-box

**Comment by helen508light** [comment]
@mujiannan  ExternalJS is not supported in modern Power BI API.
Also, debug usage is not recommended during compilation proccess
