### ISSUE TITLE
RolesIndex property seems to be missing from Power Bi Report Server January 2020

### ISSUE THREAD

**Issue by samusaran** [microsoft/PowerBI-visuals#604]
I have a report that currently works on Power BI Desktop and Powerbi.com, but it doesn't on Power BI Report Server January 2020 and the relative Power BI Desktop release.

The difference seems to be that while developing the custom visual on powerbi.com I had access to the property `metadata.columns.rolesIndex`, that I used to order values based on the order in the Visualization Pane.

This property doesn't seems to be present in Power BI Report Server, nor in typescript types.

Is it a deprecated property? Is it forbidden to use? How else can I know the order of columns inside a role?

Thanks

**Comment by uve** [comment]
@samusaran rolesIndex is not a public interface, so it can be absent in some configurations. 
You can find all available public interfaces here: https://github.com/microsoft/powerbi-visuals-api/blob/master/index.d.ts

**Comment by dynamicapps** [comment]
If we can't use rolesIndex, how can we know the order in which to display fields?  The "index" field is relative the the order in which the fields were added, not their position.

**Comment by samusaran** [comment]
> 
> 
> @uve , @samusaran, If we can't use rolesIndex, how can we know the order in which to display fields? The "index" field is relative the the order in which the fields were added, not their position.

I'm using the position in the array, like this:

`dataView.categorical.values.filter(c => c.source.roles[roleName] === true)?.[index]`

`roleName` is a parameter that contains the role name I'm looking for. 
`index` is the 0-based index of the field I'm looking for inside the role.

Basically items are already ordered correctly inside the `categorical` collection.

**Comment by dynamicapps** [comment]
@samusaran, Perfect, thanks.  I'm using the matrix dataview, but you're right that within the roles, the relative order is correct.

**Comment by danieluct** [comment]
I'm using the categorical dataview and the order is definitely not correct if one of the fields is used twice (e.g. if it used once as a measure on its own, and then as the second element in another measure based on two fields, the fields in the second measure are reversed). Going through the metadata, it seems that the only way to access the correct order for the second measure is by looking at the non-public rolesIndex attribute.
