### ISSUE TITLE
expand/collapse one row in a matrix dataview

### ISSUE THREAD

**Issue by dynamicapps** [microsoft/PowerBI-visuals#606]
Is there any way for a custom visual to expand/collapse a single row in a matrix dataview?  My client wants +/- expand as implemented in the stock matrix.

It looks like the visual is given data at whatever level is currently expanded and there is no indication of whether a leaf node has children, true?  Is there any way for a visual to request a level of data?

The hierarchy slicer source code available on git implements row expand/contract, but it does it by getting a table datasource, which includes all of the data needed for the tree, but does not include summary data for parent rows as provided by the matrix dataview.

Appreciate any assistance.
John

**Comment by helen508light** [comment]
@dynamicapps 
Expand/collapse is not supported now.
Data samples can be found [here](https://docs.microsoft.com/en-us/power-bi/developer/visuals/dataview-mappings#matrix-data-mapping)
