### ISSUE TITLE
Is it possible to enable an Action on a custom visual?

### ISSUE THREAD

**Issue by samusaran** [microsoft/PowerBI-visuals#607]
As title, I've created a custom widget for a client, and we wanted to enable an action on the widget so that we could link to a bookmark or an external link.

I can't see anything related on the [capabilities schema](https://github.com/microsoft/powerbi-visuals-api/blob/master/index.d.ts).

Thanks

**Comment by helen508light** [comment]
It is not provided now

**Comment by radiotalks** [comment]
It's always better to close than do something useful
