### ISSUE TITLE
Editing a .pbiviz ( custom visual file)

### ISSUE THREAD

**Issue by MonkAbhishek** [microsoft/PowerBI-visuals#608]
Hi All

I have a custom visual file .pbiviz. I want to make some changes in those that mean I need to open the same in some editor / some developer apps . Could you please suggest me how can I make the file in editable mode to make changes. 

*** FYI I have only .pbiviz file with me. 

Thanks for your precious time.
Regards

**Comment by helen508light** [comment]
@MonkAbhishek you should unzip .pbiviz - it has js and css files inside
Then change the code up to your needs and make new archive file with .pbiviz extension

**Comment by helen508light** [comment]
@MonkAbhishek if you have problems even after it, feel free to send pbiviz and questions to  pbicvsupport@microsoft.com
