### ISSUE TITLE
Refactor MS Visualizers to use new development model?

### ISSUE THREAD

**Issue by MerlinGrim** [microsoft/PowerBI-visuals#61]
Now that Microsoft has a new model for developing visualizers, shouldn't the existing visualizers (Source) be refactored to use the new model?  This would help developers new to the process if they can see/extend the existing visualizers in the same context which is being prescribed by Microsoft for new PBIVIZ dev model/tools.

**Comment by spatney** [comment]
@MerlinGrim, yes, correct, we will be moving the core (out-of-box) visuals to this format too. This won't be done anytime soon (next 6 mths) as migration would require man-hours that currently prioritized to build out other Power BI features. 

However, soon we will be migrating the visuals from the [gallery](https://app.powerbi.com/visuals/) to this as a first step.

**Comment by helen508light** [comment]
outdated
