### ISSUE TITLE
Add "allow-download" value to a "sandbox" attribute of iframe

### ISSUE THREAD

**Issue by sanederchik** [microsoft/PowerBI-visuals#610]
After the latest release of `Chrome 83`, there is no opportunity to download any files from `iframe` within a custom visual. The reason is an obligation to add a `allow-download` value to a `sandbox` attribute.

https://www.chromestatus.com/feature/5706745674465280

Currently, only `allow-scripts` tag is added.

![image](https://user-images.githubusercontent.com/30187683/86350927-1a2f0380-bc6c-11ea-891e-3dc4c657c289.png)

Please, fix it ASAP.

**Comment by uve** [comment]
Hi @sanederchik,
There are no plans to add allow-download support in Iframe at this moment. Also, Chromium dev team disabled this permission due to security aspects.

**Comment by sanederchik** [comment]
@uve , I hope you understand that **dozens of custom visuals** (including **commercial** ones) which allowed to download content in the past, now will become useless because of this decision.

"Also, Chromium dev team disabled this permission due to security aspects"

I don't know where you got this info, but folks from `whatwg` in [this topic](https://github.com/whatwg/html/issues/3236) **advise** to use an `allow-download` attribute.
