### ISSUE TITLE
Power bi visual api, refreshHostData not working after packaging

### ISSUE THREAD

**Issue by JipAccobat** [microsoft/PowerBI-visuals#619]
I'm trying to use the IVisualHost function refreshHostData.

In development it's working fine and dose as expected and updates my data.

But when i packege the visual and uploads it, nothing happens when refreshHostData is called.

**Comment by zBritva** [comment]
It's restricted API. Contact with support team for details. You can find E-mail here: https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-faq#how-to-get-support
