### ISSUE TITLE
Link to Roadmap gives 404 error in help page

### ISSUE THREAD

**Issue by ChamaraIC** [microsoft/PowerBI-visuals#63]
The link to Roadmap in this page issues 404 error
https://github.com/Microsoft/PowerBI-visuals/blob/master/ChangeLog.md

**Comment by spatney** [comment]
i can access the link.. is it still an issue?

**Comment by ChamaraIC** [comment]
Still have the same issue here is the link to RoadMap from the page https://github.com/Microsoft/PowerBI-visuals/blob/master/roadmap/README.md
