### ISSUE TITLE
cant add supportsHighlight as a capability

### ISSUE THREAD

**Issue by sagarvadodaria** [microsoft/PowerBI-visuals#65]
When i try to add "supportsHighlight", i get the below build error. But the docs say we can add this to capabilities. If so, how? 

![image](https://cloud.githubusercontent.com/assets/5859358/18133003/8adc12be-6fb6-11e6-921c-f17561c4e3b0.png)

**Comment by spatney** [comment]
correct, this will be enabled in the next bump of the API (1.2).
