### ISSUE TITLE
Fallback font for the legend is not consistant with the rest of the fonts in the visuals

### ISSUE THREAD

**Issue by pedramrezaei** [Microsoft/PowerBI-visuals#67]
![1](https://cloud.githubusercontent.com/assets/13262475/9643784/c0f4fd3c-5178-11e5-9134-cb25fb9d0bb8.png)

**Comment by spatney** [comment]
Legends don't have fall back fonts

**Comment by ignatvilesov** [comment]
This problem was fixed in #416.
