### ISSUE TITLE
Device location unavailable

### ISSUE THREAD

**Issue by DaveRuijter** [microsoft/PowerBI-visuals#67]
Hi team!
We would like to develop a custom visual (filter) that uses the current device location.
I believe that's now not possible, the right classes or API's are not visible for us..
But, the current Map visual makes use of it, so technically it should be possible, right?
Can you please help us with this issue?
Kind regards,
Dave

**Comment by helen508light** [comment]
Visuals API can't use browser location because of security reasons

**Comment by DaveRuijter** [comment]
Thanks for answering the question!
Haha, I asked it almost 4 years ago 😋
