### ISSUE TITLE
can't filter without highlighting other visuals

### ISSUE THREAD

**Issue by sagarvadodaria** [Microsoft/PowerBI-visuals#68]
i am working on custom slicer(dropdown) and want to filter the report data based on the selection in dropdown. I am using the code "selectionManager.select(d.selectionId)" but this doesnt seem to filter all the records and enables highlighting in Stacked Column charts and other such visuals.

Is there a way in the 1.1.0 api to filter data without highlighting..  i know some visuals like pie chart can be set to "filter" via Enable Interactions in PBI Desktop, but "Stacked charts" dont have that option.

**Comment by AviSander** [comment]
please see https://github.com/Microsoft/PowerBI-visuals#building-a-slicer-visual on advanced filtering options supported in API 1.8.
