### ISSUE TITLE
Aster Plot does not render in Microsoft Edge 

### ISSUE THREAD

**Issue by pedramrezaei** [Microsoft/PowerBI-visuals#68]
![image](https://cloud.githubusercontent.com/assets/13262475/9643799/d2aafe1e-5178-11e5-9592-341c76a585ac.png)
Error: 
![image](https://cloud.githubusercontent.com/assets/13262475/9643804/dbe186e2-5178-11e5-9a34-72d9476c531e.png)

**Comment by spatney** [comment]
Fixed!
