### ISSUE TITLE
Custom Visual no longer working in Power BI Online

### ISSUE THREAD

**Issue by calvin-pietersen** [microsoft/PowerBI-visuals#69]
Hi,

A custom visual we have created is no longer working in PowerBI Online. The visual was created initially using api v 1.0. All reports created using this visual display a blank boxes instead of the actual visual. Have tried to update the visual to api v1.1 with no luck. The visual works fine in desktop mode and also in PowerBI Online using the 'Developer Visual'.

**Comment by wesyao** [comment]
Hi Calvin, api version 1.0 is still supported. Are there any console errors occuring on the browser?
