### ISSUE TITLE
Can't start pbiviz to view SampleBarChart

### ISSUE THREAD

**Issue by umbalaxx** [microsoft/PowerBI-visuals#71]
I followed the tutorial step by step. I just finished the first code with static data.
How can I preview the graph after it says "listening on port 8080"?
Thank you.

**Comment by ChamaraIC** [comment]
This link should help with your question. https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/DebugVisualSetup.md

**Comment by zlaalami** [comment]
I did follow the link above but when i try to run 'pbiviz start' on either powershell or CMD i get the error that say s i need to run the command from the root project. when i get to the root project which is
"C:\Users\XXX\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\bin>" i get the following error:

PS C:\Users\zakarialaalami\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\bin> pbiviz start
pbiviz :  error  LOAD ERROR Error: pbiviz.json not found. You must be in the root of a visual 
project to run this command.
At line:1 char:1
+ pbiviz start
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ( error  LOAD ER...n this command.:String) [], RemoteE 
   xception
    + FullyQualifiedErrorId : NativeCommandError
 
    at e (C:\Users\zakarialaalami\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\Visual
Package.js:67:35)
    at Function.loadVisualPackage (C:\Users\zakarialaalami\AppData\Roaming\npm\node_modules\powerbi
-visuals-tools\lib\VisualPackage.js:62:16)
    at Object.<anonymous> (C:\Users\zakarialaalami\AppData\Roaming\npm\node_modules\powerbi-visuals
-tools\bin\pbiviz-start.js:43:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)

Please adivse

**Comment by umbalaxx** [comment]
I did everything in the link you've provided me, still, the visual wasn't loaded. I do not understand at all. I cloned the sampleBarChart using "git clone", cd into that folder, run "npm i" and "pbiviz start". All went fine, except the visual wasn't loaded.

**Comment by chayanupadhyay** [comment]
I got below error when run "pbiviz start" command, Can someone please guide me on this...
![capture](https://cloud.githubusercontent.com/assets/27407761/25062051/d3bc38c8-21e1-11e7-847f-225c98bbe15e.JPG)
Thanks !

**Comment by AyusmanBasu** [comment]
@chayanupadhyay I'm getting exactly the same error even after following all the steps in sequence starting from creating a local SSL till installing. I can see that there hasn't been an reply and it's been a year already!
