### ISSUE TITLE
Data labels for donut chart in Microsoft Edge don't render at all

### ISSUE THREAD

**Issue by pedramrezaei** [Microsoft/PowerBI-visuals#71]
![image](https://cloud.githubusercontent.com/assets/13262475/9643880/27cc641e-5179-11e5-9e17-2f43e29227e9.png)

**Comment by spatney** [comment]
Known bug with the Edge browser. Closing as can't fix :)

**Comment by pedramrezaei** [comment]
Let's keep the bug open until Edge fixes it.

**Comment by ignatvilesov** [comment]
Donut chart works fine in Edge 25 (see screenshot below).
![capture](https://cloud.githubusercontent.com/assets/4927804/15041312/be7fa996-12c3-11e6-924d-ca16ee4bbb4b.PNG)
