### ISSUE TITLE
CLI tool installed but I am unable to Sample bar chart visual.

### ISSUE THREAD

**Issue by ravi4chahal** [microsoft/PowerBI-visuals#72]
I installed CLI tool following all the steps mentioned at below URL.

PBIVIZ command works and I can see the Yellow ASCII figure. PBIVIZ start command also seems to work, however, I am not able to see the visual in powerbi online. I have tried re-installing the tool, still doesnt work. Please see the attached screenshot.

![cli error](https://cloud.githubusercontent.com/assets/4159661/18383452/4c45fd32-76a3-11e6-9c86-0f00f9cb9d72.PNG)

**Comment by wesyao** [comment]
Hi, did you try clicking the restart button on the debug visual?

**Comment by KingRider** [comment]
I think u need try add certificate to allow
https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/CertificateAddWindows.md

Before ur prompt or powershell is type **NET STOP HTTP**

**Comment by umbalaxx** [comment]
I'm having the same problem for so many days. Please helppppp.

**Comment by KingRider** [comment]
Allow Developer visual?
https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/DebugVisualSetup.md

**Comment by umbalaxx** [comment]
Yes of course I already checked that box. What else could be the problem?

**Comment by raananzvi** [comment]
Did you execute the "pbiviz --install-cert" command like KingRider suggested?

**Comment by umbalaxx** [comment]
Yessss, I did that as well. I cloned the sampleBarChart git using git clone. npm i and pbiviz start. Nothing happened.
I have:
- installed node, git
- installed pbiviz
- installed certificate using pbiviz install cert
- checked developer option in the web

I logged into my account and clicked one of my published reports, then I clicked on the debugging icon, did i do something wrong?

**Comment by KingRider** [comment]
i see, try this to change port, i think a port 8080 is conflict... powershell with admin

![image](https://cloud.githubusercontent.com/assets/4491180/18747131/d3a9a348-80a1-11e6-82c8-25df35730713.png)

**Comment by umbalaxx** [comment]
Thank you very much. I'll try as soon as I get home and will report back.
Thanks very much again!

**Comment by umbalaxx** [comment]
<img width="916" alt="screen shot 2016-09-22 at 22 03 50" src="https://cloud.githubusercontent.com/assets/22072917/18753775/8d326ea8-8110-11e6-8580-2ffa749e6090.png">

Here is the screenshot. The visual still doesn't show up.

**Comment by KingRider** [comment]
Hum... i see error ur network, used computer is mac? i not found documentation for mac and no have idea, i no know mac. sorry.

![image](https://cloud.githubusercontent.com/assets/4491180/18755664/7534c3f2-80c3-11e6-9a51-bd03e76d83e5.png)

**See communication requests:**
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/7546645-power-bi-tools-for-mac

**Comment by umbalaxx** [comment]
I used windows first and the visual didn't show up just like on my mac. But i remember that the version is not the same as yours, not sure, but thanks anyway.

**Comment by KingRider** [comment]
ok umbalaxx,

**Written Communication Report for NojeJS:**
https://github.com/nodejs/node/issues
