### ISSUE TITLE
Use the correct PBI logo as an image in the playground logo

### ISSUE THREAD

**Issue by pedramrezaei** [Microsoft/PowerBI-visuals#73]
![image](https://cloud.githubusercontent.com/assets/13262475/9643922/5a3f56e0-5179-11e5-8023-27d3ef85cd14.png)

**Comment by spatney** [comment]
Use [this](https://pbs.twimg.com/profile_images/604406061114634240/4CThwllO.png) instead

**Comment by uve** [comment]
Fixed.
