### ISSUE TITLE
All Readme.md links are redirected to the 404

### ISSUE THREAD

**Issue by tomsoir** [Microsoft/PowerBI-visuals#73]
Please fix the links on https://github.com/Microsoft/PowerBI-visuals/

**Comment by wesyao** [comment]
Which ones? I went through some of them. They seem fine.

**Comment by tomsoir** [comment]
Now, everything is fine. You can close this.

Yesterday all of the links in Readme.rm were without a  'blob/master/' part. 
Something like this: https://github.com/Microsoft/PowerBI-visuals/tools/README.md#installation -> 404
