### ISSUE TITLE
Problem with creating selection ids in table mapping

### ISSUE THREAD

**Issue by Bootta11** [microsoft/PowerBI-visuals#77]
I got problem with creating selection ids in table mapping. After calling command "createSelectionId()" my visual stuck. Here is github repo of my visual: https://github.com/Bootta11/pbiviz_help/blob/master/src/visual.ts

If we comment line 61 in file src/visual.ts program continue executing normally but if this line is executed program stuck(you can follow console output or follow visual rendering). 

Please can someone help me with this problem?

**Comment by nicksav** [comment]
I am actually having similar issue with Table. All my columns are categories. I am trying to add a Selection id by first Category. I can see that Selection is reated, but when I check, the Selector is null. 
What is the INDEX in this function?
withCategory(categoryColumn: DataViewCategoryColumn, index: number)?

Thanks
Nick

**Comment by nicksav** [comment]
One more finding:
From the power BI source, it is a .withCategorySource code:
`       var r = function() {
            function t() {}
            return t.prototype.withCategory = function(e, t) {
                return e && e.source && e.source.queryName && e.identity && (this.ensureDataMap()[e.source.queryName] = e.identity[t]), this
            }, t.prototype.withSeries = function(e, t) {
                return e && e.source && e.source.queryName && t && (this.ensureDataMap()[e.source.queryName] = t.identity), this
            }, t.prototype.withMeasure = function(e) {
                return this.measure = e, this
            }, t.prototype.createSelectionId = function() {
                return e.visuals.SelectionId.createWithSelectorForColumnAndMeasure(this.ensureDataMap(), this.measure)
            }, t.prototype.ensureDataMap = function() {
                return this.dataMap || (this.dataMap = {}), this.dataMap
            }, t
        }();`
As you can see, it is expecting e.source.queryName. However, in my case i have queryName = null for Table mapping... Not sure, may be for table, it different way to create a selection?

**Comment by rcjcooke** [comment]
Hi. I'm struggling with the same problem. My data mapping is tabular:
`    "dataViewMappings": [
        {
            "table": {
                "rows": {
                    "select": [
                        {"for": {"in": "datapoint1"}},
                        {"for": {"in": "datapoint2"}},
                        ...
`
I want to be about to use SelectionIDs to select individual data points but the SelectionIdBuilder only appears to support categorical data mappings (withCategory, withSeries, withMeasure). How do I create selectionIDs for a table data mapping?

This appears to be the same issue as the following open issues @soodik323 @Bootta11 @spatney @whyvez

- #48 
- [PowerBI-visuals-tools/#44](https://github.com/Microsoft/PowerBI-visuals-tools/issues/44)

This could be just a Documentation Request if the functionality is there, otherwise this is a feature request if we can't use selection with table data mappings.

**Comment by soodik323** [comment]
Any progress with this issue ? I still can't seem to find a way to use selection for table

**Comment by tnadkarni** [comment]
Has somebody figured this out yet? Please point me in the right direction.

**Comment by akash273** [comment]
Any results in this issue please help i need this

**Comment by ignatvilesov** [comment]
Please use this code as an example and current workaround:

```
getSelectionIds(dataView: DataView, host: IVisualHost): ISelectionId[] {
    return dataView.table.identity.map((identity: DataViewScopeIdentity) => {
        const categoryColumn: DataViewCategoryColumn = {
            source: dataView.table.columns[0],
            values: null,
            identity: [identity]
        };

        return host.createSelectionIdBuilder()
            .withCategory(categoryColumn, 0)
            .createSelectionId();
    });
}
```

**Comment by Zieg** [comment]
@ignatvilesov Is there by any chance a similar workaround for matrix data mapping? Thanks.

**Comment by ignatvilesov** [comment]
@Zieg Yes, there is. Workaround is the same. You can find a code sample [here](https://github.com/Microsoft/powerbi-visuals-sunburst/blob/f8eb4ee64cdfd43bc44c1270ed795452efe0f927/src/sunburst.ts#L503)

```typescript
const categoryColumn: DataViewCategoryColumn = {
                    source: {
                        displayName: null,
                        queryName: identity.key
                    },
                    values: null,
                    identity: [identity]
                };

                selectionIdBuilder.withCategory(categoryColumn, 0);
```
