### ISSUE TITLE
Question: Is there a place for licenseTerms, privacyTerms in package

### ISSUE THREAD

**Issue by proll** [microsoft/PowerBI-visuals#79]
Is there a place for licenseTerms, privacyTerms fields in the pbiviz
to point on rules of using current visual or it's galery metadata like screenshot and thumbnail?

**Comment by helen508light** [comment]
There is no unified way to do 
Every developer should write his own source code related to license inside a visual(by rules it should not send any http requests for license activation).
Gallery metadata is used pbiviz - there are the following section:
```json
  "assets": {
    "icon": "assets/icon.png"
  }
