### ISSUE TITLE
Add examples using Power BI Desktop

### ISSUE THREAD

**Issue by timewstr** [Microsoft/PowerBI-visuals#8]
After playing with the PowerBIVisualsPlayground project it's not clear how I could get these custom visuals to show up in the Power BI desktop application.  For example how would you get the "Cheer Meter" demo from the Wiki example to appear in Power BI Desktop?

**Comment by mgam1** [comment]
I too would love an explanation to this question

**Comment by pedramrezaei** [comment]
Using custom visuals will be coming to Power BI soon. Please stay tuned.

**Comment by javed77** [comment]
Is there any timeline available for this?

**Comment by spatney** [comment]
We do not have any official dates yet. We will provide more info here, and via the [PowerBI blog](http://blogs.msdn.com/b/powerbi/) in the coming weeks.
