### ISSUE TITLE
Unable to find logged in user name from a visual

### ISSUE THREAD

**Issue by diptarag** [Microsoft/PowerBI-visuals#80]
powerbi.session.userInfo is null inside a visual, is there any other way to get information regarding the user?

**Comment by nicksav** [comment]
Guys, any update on this?

**Comment by youranupama** [comment]
When will this issue is fixed? Is this working on V1.6

**Comment by pjagushte** [comment]
I am trying to get powerbi.session.userInfo but still getting null. By what release are you planning to have this fix?

**Comment by jcbowyer** [comment]
Hello, I am also interested in a solution to this.

**Comment by swaswati** [comment]
any update on this??

**Comment by uve** [comment]
Duplicated #170
