### ISSUE TITLE
Custom Slicers

### ISSUE THREAD

**Issue by vivibug** [Microsoft/PowerBI-visuals#84]
I need a solution to this resolved issue (which was resolved using the deprecated API): https://github.com/Microsoft/PowerBI-visuals-core/issues/154

How can we implement slicer behavior in custom visuals? 

I need to keep selection on Chart 1, when I select something on Chart 2. By default, only one visual can have a selection at a time, except for the slicers. 

Essentially, how can we implement this functionality below (which was available in the deprecated API). The function call needed is the call below. This function call came from: 

https://github.com/Microsoft/PowerBI-visuals-core/blob/550cc4b1a606cefc9d5e29c99255e994a3a79cb0/src/Clients/Visuals/behaviours/slicerBehaviors.ts

`selectionHandler.persistSelectionFilter(slicerProps.filterPropertyIdentifier);`

Please advise on possible approaches, and whether this functionality will be implemented.

**Comment by AviSander** [comment]
Hello,
     please see API 1.7 - it has slicer APIs and a sampleSlicer visual for reference. https://github.com/Microsoft/powerbi-visuals-sampleslicer 
thx.
