### ISSUE TITLE
Filter Issue

### ISSUE THREAD

**Issue by amolkare** [Microsoft/PowerBI-visuals#85]
Hi,
I am working on Breadcrumb custom visual but when no records selected in filter, I still get the default 0th index record in DataView object in update() function.

![image](https://cloud.githubusercontent.com/assets/3225249/18670668/a2633bc6-7f5e-11e6-8629-496b8e69df53.png)

is it issue with power BI core? 

Regards,
Amol

**Comment by raananzvi** [comment]
Hi,

Can you please elaborate about your issue.
What do you mean by 0th index?
I think that you can't get Power BI report to show no data. It seems from your screenshot that you unselected all elements in the slicer, but all visuals show all the data. So why do you expect your visual to get different values?

**Comment by amolkare** [comment]
Thanks for the prompt reply here, I am new to this custom visual and Power BI. I was not sure about the filter selection functionality in power BI, Please clarify, **If nothing is selected in filters that means all are selected, right?** in that case It's working fine. I am showing only the 
{ options.dataViews[0].categorical.categories[0].values[0]
options.dataViews[0].categorical.categories[1].values[0]
options.dataViews[0].categorical.categories[1].values[0]
.
.
options.dataViews[0].categorical.categories[1].values[n] }
data from categorical data which is hierarchical in nature like HierarchySlicer (https://app.powerbi.com/visuals/show/HierarchySlicer1458836712039)

![image](https://cloud.githubusercontent.com/assets/3225249/18775338/782cd21e-817e-11e6-9efb-0b93f17ee077.png)

**Comment by raananzvi** [comment]
Correct, if nothing is selected it means there is no filters.
