### ISSUE TITLE
Stars src availability

### ISSUE THREAD

**Issue by magtuto** [Microsoft/PowerBI-visuals#86]
Hello All,

I cannot find the src for the 'Stars' custom visual that's available on https://app.powerbi.com/visuals/ .

Am I just missing something simple?

Eric

**Comment by raananzvi** [comment]
This visual is developed by someone from the community.
The sources are located in GitHub: https://github.com/tisawyer/Stars-Custom-Visual
You can look here: https://app.powerbi.com/visuals/show/PBI_CV_9053509D_D461_463A_B485_CE9F6AB0F13C
there is a link to the github from there
