### ISSUE TITLE
Get error on jQuery $(document).ready() 

### ISSUE THREAD

**Issue by dmelling80** [Microsoft/PowerBI-visuals#89]
I'm getting error when running the Playground on the index.html page:
Line: 51
Error: '$' is undefined

I followed all prereq's etc.

**Comment by ClarkDan** [comment]
I am having the same issue.

**Comment by spatney** [comment]
I can't reproduce this. Could you pull the latest code (we made some fixes with regards to dependencies recently)? Then do an npm install + gulp build. Thanks.

**Comment by ClarkDan** [comment]
It has something to do with running on windows 8.1 with IIS express. I spun
up a windows 2012 server and it worked fine on it.
Thanks,
Dan
