### ISSUE TITLE
Scrollbars in visuals

### ISSUE THREAD

**Issue by danieleperilli** [microsoft/PowerBI-visuals#89]
How to show scrollbars for content out of the viewport? In the past I used overflow:auto technique, but it seems it doesn't work anymore. Moreover I've noted that built-in visuals use a special <rect> element to display scrollbars, how to be compliant with it?

**Comment by wbovela** [comment]
I have the exact same problem. 
Can anyone tell me how to introduce scroll bars when the contents overflows the view port?
