### ISSUE TITLE
How to control drilldown in visual

### ISSUE THREAD

**Issue by Knagis** [microsoft/PowerBI-visuals#90]
Once `drillDown` is defined in the capabilities.json file (see #76), the visual automatically displays additional buttons in its toolbar.

Is it possible to control these buttons? For example, if the visual does not support selection and only drilldown, the "Click to turn on Drill Down" button would have to disabled/removed.

If "Click to turn on Drill Down" is not enabled, can the visual still perform drilldown through the API - for example, if it contains separate interactions for selecting and drilling down?

**Comment by nikhilkabbin** [comment]
@Knagis Did you get any workaround for this?

**Comment by Knagis** [comment]
Nope. We ended up disabling the built-in drilldown and then performing the aggregation in the visual itself.

**Comment by nikhilkabbin** [comment]
@Knagis How do you aggregate the data for all options like: Standard deviation, mean. Do you usse normal JS functions to aggregate data or is there a way to use PowerBI query aggregatore in our code like query.Sum(column)? and also if I control drilldown in my own will this work well with cross filtering or highlight of data in other visuals in dashboard?

**Comment by Knagis** [comment]
Some of the aggregations (like Standard deviation) are not supported. We use our own code to aggregate, not anything PowerBI specific. 

Highlighting requires selecting every ISelectionId within the group (see #87).

**Comment by uve** [comment]
API 1.6.3 doesn't provide full support of 'drilldown' feature.
I recommend you to wait until this feature will be fully supported.
We'll update the documentation and open source code for new version of MekkoChart which uses drilldown.
