### ISSUE TITLE
Property pane not showing Static and Data Bound objects in Developer Visual

### ISSUE THREAD

**Issue by amolkare** [Microsoft/PowerBI-visuals#91]
Hi,

Th Property pane not showing static and Data bound objects when I am looking visual in developer tool(debugger mode), but once I packaged and import the same custom visual, I can see Static and Data bound objects in property Pane.

Regards,
Amol

**Comment by danieleperilli** [comment]
I confirm it. It started on last sunday.

**Comment by adamdavi3s** [comment]
I can't get any custom object to show in web or desktop, I have tried to create a simple switch.
It could be because I have only just started but I did follow a good guide online.

**Comment by raananzvi** [comment]
We are working on this issue now. Hope we have a fix ready soon.
In the mean time, the workaround is like OctoberRust2000 suggested, is to package your visual and import it manually

**Comment by raananzvi** [comment]
Bug was fixed, will take several weeks to get to production.
