### ISSUE TITLE
NodeJS installation failure

### ISSUE THREAD

**Issue by sampath530** [Microsoft/PowerBI-visuals#92]
Hi, while i am installing NodeJs in my desktop getting attached error .please suggest/help me on this issue.
![nodejs](https://cloud.githubusercontent.com/assets/22626159/19093675/e7507e46-8a40-11e6-8b57-31c834eca7c3.JPG)

log:
C:\Program Files\nodejs>npm install -g powerbi-visuals-tools
C:\Users\v-savara\AppData\Roaming\npm\pbiviz -> C:\Users\v-savara\AppData\Roamin
g\npm\node_modules\powerbi-visuals-tools\bin\pbiviz.js
powerbi-visuals-tools@1.1.0 C:\Users\v-savara\AppData\Roaming\npm\node_modules\p
owerbi-visuals-tools
├── jsonschema@1.1.0
├── node-uuid@1.4.7
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2
.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── source-map-concat@1.0.1 (urix@0.1.0, source-map@0.5.6)
├── connect@3.5.0 (parseurl@1.3.1, utils-merge@1.0.0, debug@2.2.0, finalhandler@
0.5.0)
├── serve-static@1.11.1 (escape-html@1.0.3, encodeurl@1.0.1, parseurl@1.3.1, sen
d@0.14.1)
├── fs-extra@0.28.0 (path-is-absolute@1.0.1, jsonfile@2.4.0, klaw@1.3.0, gracefu
l-fs@4.1.9, rimraf@2.5.4)
├── uglify-js@2.7.3 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6,
 yargs@3.10.0)
├── typescript@1.8.10
├── lodash@4.16.3
├── less@2.7.1 (graceful-fs@4.1.9, mime@1.3.4, image-size@0.5.0, source-map@0.5.
6, errno@0.1.4, promise@7.1.1, mkdirp@0.5.1)
└── jszip@3.1.2 (es6-promise@3.0.2, lie@3.1.0, pako@1.0.3, readable-stream@2.0.6
, core-js@2.3.0)

C:\Program Files\nodejs>pbiviz
'pbiviz' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\nodejs>npm install -g powerbi-visuals-tools >d:\log.txt
The device is not ready.

C:\Program Files\nodejs>

**Comment by raananzvi** [comment]
Please see if there is a file named: "C:\Users\v-savara\AppData\Roaming\npm\pbiviz.cmd" in your hard drive

**Comment by mjanalytics** [comment]
Same issue for me.   Yes, I have C:\Users\[username]\AppData\Roaming\npm\pbiviz.cmd on my hard drive.  Any thoughts?

**Comment by matthiasnielsen** [comment]
After installing powerbi-visuals-tools I couldn't run pbiviz from the command prompt either. I had to add the path to the pbiviz.cmd ("C:\Users\[username]\AppData\Roaming\npm\") file to my environment variables. 

I find the settings for editing environment variables by using the start menu search function in Windows 10 typing "environment variables" (I expect Windows 7 and 8 would work the same way).

This opens a small window with a "Environment Variables..." button at the bottom. Clicking this button opens another window where you have the choice of editing user variables (for your logged in user) or system variables (for all users). I edit my system variables because I am the only user on machine, but editing user variables would work as well.

The [user/system] variable you want to edit is the "Path" variable. In Windows 10 you add entries to the Path variable by clicking "Edit..." and adding the path to pbiviz.cmd by clicking "New" in the "Edit environment variable" window.
As far as I remember, Windows 7 and 8 is a bit different when editing environment variables. To the best of my recollection you need to append the path in question to a long text string consisting of a series of paths separated by ";". Two things to watch out for: Remember to separate by ";" and do not delete or edit existing paths (as it will likely break other commands executed from the command prompt).

**Comment by raananzvi** [comment]
Basically, when you install NodeJS the installation should add the npm folder to the path automatically.
This is strange that this folder was not added to your path. Maybe you need to open a new command line window after the installation.

**Comment by matthiasnielsen** [comment]
My NodeJS installation automatically added C:\Program Files\nodejs (where npm.cmd is located) to my system "path" variable, but not the global node_modules folder.

**Comment by MJZawacki** [comment]
I'm seeing the same issue. I can confirm that I have the npm global folder in may path and that I can call other cmd files in that folder. However pbivis will not work. Here's the output showing this in action:

`
E:\Scratch\reposFY18\Rockwell\AngularPBIVis>path
PATH=C:\RBuildTools\3.4\bin;C:\RBuildTools\3.4\mingw_32\bin;C:\Program Files\Docker\Docker\Resources\bin;D:\Program Files\Rtools\bin;D:\Program Files\Rtools\mingw_32\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\mikez\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;D:\Program Files (x86)\nodejs\;C:\Program Files\Java\jdk1.8.0_77\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Java\jdk1.8.0_112\bin;C:\Program Files (x86)\scala\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\mikez\AppData\Roaming\npm;C:\tools\apache-maven-3.3.3\bin;C:\Users\mikez\AppData\Local\Microsoft\WindowsApps;C:\tools\apache-maven-3.3.9\bin;;C:\Users\mikez\AppData\Local\Programs\Fiddler;C:\Program Files\Microsoft VS Code\bin

E:\Scratch\reposFY18\Rockwell\AngularPBIVis>dir C:\Users\mikez\AppData\Roaming\npm
 Volume in drive C has no label.
 Volume Serial Number is DAF9-57B5

 Directory of C:\Users\mikez\AppData\Roaming\npm

09/29/2017  12:53 PM    <DIR>          .
09/29/2017  12:53 PM    <DIR>          ..
08/18/2016  01:46 PM               290 bower
08/18/2016  01:46 PM               198 bower.cmd
12/29/2015  02:55 PM    <DIR>          etc
08/18/2016  01:46 PM               292 gulp
08/18/2016  01:46 PM               200 gulp.cmd
08/18/2016  01:30 PM               308 manifoldjs
08/18/2016  01:30 PM               216 manifoldjs.cmd
09/29/2017  12:53 PM    <DIR>          node_modules
09/29/2017  09:57 AM               330 pbiviz
09/29/2017  09:57 AM               238 pbiviz.cmd
09/29/2017  12:53 PM               296 tsc
09/29/2017  12:53 PM               204 tsc.cmd
09/29/2017  12:53 PM               306 tsserver
09/29/2017  12:53 PM               214 tsserver.cmd
08/18/2016  01:46 PM               298 typings
08/18/2016  01:46 PM               206 typings.cmd
05/24/2017  01:23 PM               330 validate-office-addin
05/24/2017  01:23 PM               238 validate-office-addin.cmd
08/18/2016  01:46 PM               286 yo
08/18/2016  01:46 PM               312 yo-complete
08/18/2016  01:46 PM               220 yo-complete.cmd
08/18/2016  01:46 PM               194 yo.cmd
              20 File(s)          5,176 bytes
               4 Dir(s)  26,299,219,968 bytes free

E:\Scratch\reposFY18\Rockwell\AngularPBIVis>where manifoldjs
C:\Users\mikez\AppData\Roaming\npm\manifoldjs
C:\Users\mikez\AppData\Roaming\npm\manifoldjs.cmd

E:\Scratch\reposFY18\Rockwell\AngularPBIVis>where pbivis
INFO: Could not find files for the given pattern(s).

E:\Scratch\reposFY18\Rockwell\AngularPBIVis>manifoldjs

  Usage: manifoldjs <website-url> [options]
         manifoldjs -m <manifest-location> [options]
           options:
             -d | --directory, -s | --short-name, -l | --loglevel,
             -p | --platforms, -m | --manifest, -f | --forceManifestFormat, -c | --crosswalk
 ...


E:\Scratch\reposFY18\Rockwell\AngularPBIVis>pbivis
'pbivis' is not recognized as an internal or external command,
operable program or batch file.
`

**Comment by uve** [comment]
@MJZawacki, please use **pbiviz** command instead.

**Comment by bjdeng** [comment]
Same problem as @MJZawacki  here. 

- C:\Users[username]\AppData\Roaming\npm is in my PATH
- C:\Users[username]\AppData\Roaming\npm\pbviz.cmd exists
- Windows 7 SP1
- node v8.10.0

`
C:\>pbviz
'pbviz' is not recognized as an internal or external command,
operable program or batch file.
`

**Comment by bjdeng** [comment]
Well disregard my comment. The command is pbiviz, not pbviz.

**Comment by gsweetwood** [comment]
I had the same error.  I added the path manually and it worked.  NOTE:  After you add it to the path, you MUST restart for the change to take place.
