### ISSUE TITLE
Getting error index.html at line powerbi.visuals.Playground.initialize();  

### ISSUE THREAD

**Issue by jayakanth459** [Microsoft/PowerBI-visuals#93]
Can't find PowerBIVisualsPlayground.js file in entire solution
<script type="text/javascript" src="PowerBIVisualsPlayground.js"></script>

Even index.html file doesn't show visuals / charts.

**Comment by spatney** [comment]
should be under src/Client/PowerBIVisualsPlayground. The js file only appears once you do a gulp build. Could you provide more details ?

**Comment by jakewava** [comment]
Same error for me here is my stack trace:

> cmd.exe /c gulp -b "C:\source\PowerBI-visuals" --color --gulpfile "C:\source\PowerBI-visuals\Gulpfile.js" continuous_build_debug
[15:45:03] Using gulpfile C:\source\PowerBI-visuals\Gulpfile.js
[15:45:03] Starting 'continuous_build_debug'...
[15:45:03] Starting 'continuous_build'...
[15:45:03] Starting 'build:projects'...
[15:45:03] Starting 'install:jquery-ui'...
[15:45:03] Starting 'install:jquery-ui:js'...
Dependency exists.
[15:45:03] Finished 'install:jquery-ui:js' after 631 μs
[15:45:03] Starting 'install:jquery-ui:css'...
Dependency exists.
[15:45:03] Finished 'install:jquery-ui:css' after 187 μs
[15:45:03] Finished 'install:jquery-ui' after 1.8 ms
[15:45:03] Starting 'build:visuals_common'...
[15:45:05] Finished 'build:visuals_common' after 1.86 s
[15:45:05] Starting 'build:visuals_data'...
[15:45:07] Finished 'build:visuals_data' after 1.76 s
[15:45:07] Starting 'build:visuals'...
[15:45:07] Starting 'build:visuals_project'...
src\Clients\Visuals\capabilities\basicShape.capabilities.ts(81,33): error TS2322: Type '{ objects: { [x: string]: { displayName: (IStringResourceProvider: any) => string; properties: { ...' is not assignable to type 'VisualCapabilities'.
  Types of property 'objects' are incompatible.
    Type '{ [x: string]: { displayName: (IStringResourceProvider: any) => string; properties: { [x: string]...' is not assignable to type 'DataViewObjectDescriptors'.
      Types of property 'general' are incompatible.
        Type '{ properties: { [x: string]: { type: { shapeType: boolean; }; }; shapeType: { type: { shapeType: ...' is not assignable to type 'DataViewObjectDescriptor'.
          Types of property 'properties' are incompatible.
            Type '{ [x: string]: { type: { shapeType: boolean; }; }; shapeType: { type: { shapeType: boolean; }; }; }' is not assignable to type 'DataViewObjectPropertyDescriptors'.
              Index signatures are incompatible.
                Type '{ type: { shapeType: boolean; }; }' is not assignable to type 'DataViewObjectPropertyDescriptor'.
                  Types of property 'type' are incompatible.
                    Type '{ shapeType: boolean; }' is not assignable to type 'ValueTypeDescriptor | StructuralTypeDescriptor'.
                      Object literal may only specify known properties, and 'shapeType' does not exist in type 'ValueTypeDescriptor | StructuralTypeDescriptor'.
[15:45:09] TypeScript: 21 semantic errors
src\Clients\Visuals\capabilities\comboChart.capabilities.ts(274,25): error TS2322: Type '{ dataRoles: { name: string; kind: VisualDataRoleKind; displayName: (IStringResourceProvider: any...' is not assignable to type 'VisualCapabilities'.
  Types of property 'dataViewMappings' are incompatible.
    Type '({ conditions: ({ [x: string]: { max: number; }; 'Category': { max: number; }; 'Series': { max: n...' is not assignable to type 'DataViewMapping[]'.
      Type '{ conditions: ({ [x: string]: { max: number; }; 'Category': { max: number; }; 'Series': { max: nu...' is not assignable to type 'DataViewMapping'.
        Type '{ conditions: ({ [x: string]: { max: number; } | { min: number; }; 'Category': { max: number; }; ...' is not assignable to type 'DataViewMapping'.
          Types of property 'categorical' are incompatible.
            Type '{ categories: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }; values: { select: ...' is not assignable to type 'DataViewCategoricalMapping'.
              Types of property 'values' are incompatible.
                Type '{ select: { for: { in: string; }; }[]; dataReductionAlgorithm: { top: {}; }; }' is not assignable to type 'DataViewRoleBindMapping | DataViewRoleForMapping | DataViewGroupedRoleMapping | DataViewListRoleM...'.
                  Object literal may only specify known properties, and 'dataReductionAlgorithm' does not exist in type 'DataViewRoleBindMapping | DataViewRoleForMapping | DataViewGroupedRoleMapping | DataViewListRoleM...'.
src\Clients\Visuals\capabilities\dataDotChart.capabilities.ts(63,25): error TS2322: Type '{ dataRoles: { name: string; kind: VisualDataRoleKind; }[]; objects: { [x: string]: { displayName...' is not assignable to type 'VisualCapabilities'.
  Types of property 'dataViewMappings' are incompatible.
    Type '{ conditions: { [x: string]: { max: number; }; 'Category': { max: number; }; 'Y': { max: number; ...' is not assignable to type 'DataViewMapping[]'.
      Type '{ conditions: { [x: string]: { max: number; }; 'Category': { max: number; }; 'Y': { max: number; ...' is not assignable to type 'DataViewMapping'.
        Types of property 'categorical' are incompatible.
          Type '{ categories: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }; values: { select: ...' is not assignable to type 'DataViewCategoricalMapping'.
            Types of property 'values' are incompatible.
              Type '{ select: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }[]; }' is not assignable to type 'DataViewRoleBindMapping | DataViewRoleForMapping | DataViewGroupedRoleMapping | DataViewListRoleM...'.
                Type '{ select: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }[]; }' is not assignable to type 'DataViewListRoleMapping'.
                  Types of property 'select' are incompatible.
                    Type '{ for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }[]' is not assignable to type '(DataViewRoleBindMapping | DataViewRoleForMapping)[]'.
                      Type '{ for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }' is not assignable to type 'DataViewRoleBindMapping | DataViewRoleForMapping'.
                        Object literal may only specify known properties, and 'dataReductionAlgorithm' does not exist in type 'DataViewRoleBindMapping | DataViewRoleForMapping'.
[15:45:09] TypeScript: emit failed
src\Clients\Visuals\capabilities\sampleVisual.capabilities.ts(48,9): error TS2322: Type '{ dataRoles: { name: string; kind: VisualDataRoleKind; }[]; dataViewMappings: { categorical: { ca...' is not assignable to type 'VisualCapabilities'.
  Object literal may only specify known properties, and 'dataPoint' does not exist in type 'VisualCapabilities'.
src\Clients\Visuals\capabilities\samples\consoleWriter.capabilities.ts(49,9): error TS2322: Type '{ dataRoles: { name: string; kind: VisualDataRoleKind; }[]; dataViewMappings: { categorical: { ca...' is not assignable to type 'VisualCapabilities'.
  Object literal may only specify known properties, and 'dataPoint' does not exist in type 'VisualCapabilities'.
src\Clients\Visuals\cartesian\columnChart.ts(963,17): error TS2322: Type '{ height: number; width: number; duration: number; hostService: IVisualHostServices; mainGraphics...' is not assignable to type 'ColumnChartContext'.
  Object literal may only specify known properties, and 'hostService' does not exist in type 'ColumnChartContext'.
[15:45:09] Finished 'build:visuals_project' after 2.52 s
src\Clients\Visuals\cartesian\lineChart.ts(523,17): error TS2345: Argument of type '{ pixelSpan: number; dataDomain: any[]; metaDataColumn: DataViewMetadataColumn; formatStringProp:...' is not assignable to parameter of type 'CreateAxisOptions'.
  Object literal may only specify known properties, and 'shouldClamp' does not exist in type 'CreateAxisOptions'.
src\Clients\Visuals\cartesian\lineChart.ts(782,21): error TS2322: Type '{ dataPoints: SelectableDataPoint[]; lines: UpdateSelection; interactivityLines: any; dots: Updat...' is not assignable to type 'LineChartBehaviorOptions'.
  Object literal may only specify known properties, and 'background' does not exist in type 'LineChartBehaviorOptions'.
[15:45:09] Starting 'build:visuals_sprite'...
src\Clients\Visuals\cartesian\scatterChart.ts(250,17): error TS2322: Type '{ xCol: DataViewMetadataColumn; yCol: DataViewMetadataColumn; dataPoints: ScatterChartDataPoint[]...' is not assignable to type 'ScatterChartData'.
  Object literal may only specify known properties, and 'hasSelection' does not exist in type 'ScatterChartData'.
src\Clients\Visuals\cartesian\scatterChart.ts(509,17): error TS2322: Type '{ xCol: undefined; yCol: undefined; dataPoints: undefined[]; legendData: { dataPoints: undefined[...' is not assignable to type 'ScatterChartData'.
  Object literal may only specify known properties, and 'selectedIds' does not exist in type 'ScatterChartData'.
src\Clients\Visuals\common\dataLabelUtils.ts(136,17): error TS2322: Type '{ show: boolean; position: PointLabelPosition; displayUnits: number; precision: number; labelColo...' is not assignable to type 'VisualDataLabelsSettings'.
  Object literal may only specify known properties, and 'formatterOptions' does not exist in type 'VisualDataLabelsSettings'.
src\Clients\Visuals\common\dataLabelUtils.ts(147,17): error TS2322: Type '{ show: boolean; displayUnits: number; precision: number; labelColor: string; showCategory: boole...' is not assignable to type 'VisualDataLabelsSettings'.
  Object literal may only specify known properties, and 'formatterOptions' does not exist in type 'VisualDataLabelsSettings'.
src\Clients\Visuals\common\dataLabelUtils.ts(165,17): error TS2322: Type '{ show: boolean; position: PointLabelPosition; displayUnits: number; precision: number; labelColo...' is not assignable to type 'PointDataLabelsSettings'.
  Object literal may only specify known properties, and 'formatterOptions' does not exist in type 'PointDataLabelsSettings'.
src\Clients\Visuals\common\dataLabelUtils.ts(177,17): error TS2322: Type '{ show: boolean; displayUnits: number; precision: number; labelColor: string; position: null; sho...' is not assignable to type 'VisualDataLabelsSettings'.
  Object literal may only specify known properties, and 'formatterOptions' does not exist in type 'VisualDataLabelsSettings'.
src\Clients\Visuals\common\dataLabelUtils.ts(814,17): error TS2322: Type '{ show: boolean; position: string; displayUnits: number; precision: number; labelColor: string; f...' is not assignable to type 'VisualDataLabelsSettings'.
  Object literal may only specify known properties, and 'formatterOptions' does not exist in type 'VisualDataLabelsSettings'.
src\Clients\Visuals\services\visualPluginService.ts(337,99): error TS2345: Argument of type '{ chartType: typeof Gauge; gaugeSmallViewPortProperties: any; }' is not assignable to parameter of type 'GaugeConstructorOptions'.
  Object literal may only specify known properties, and 'chartType' does not exist in type 'GaugeConstructorOptions'.
src\Clients\Visuals\visuals\funnelChart.ts(574,21): error TS2322: Type '{ viewModel: FunnelData; interactivityService: IInteractivityService; layout: IFunnelLayout; axis...' is not assignable to type 'FunnelAnimationOptions'.
  Object literal may only specify known properties, and 'colors' does not exist in type 'FunnelAnimationOptions'.
src\Clients\Visuals\visuals\owlGauge.ts(59,17): error TS2322: Type '{ dataRoles: { name: string; kind: VisualDataRoleKind; }[]; dataViewMappings: { categories: { for...' is not assignable to type 'VisualCapabilities'.
  Types of property 'dataViewMappings' are incompatible.
    Type '{ categories: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }; values: { select: ...' is not assignable to type 'DataViewMapping[]'.
      Type '{ categories: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }; values: { select: ...' is not assignable to type 'DataViewMapping'.
        Object literal may only specify known properties, and 'categories' does not exist in type 'DataViewMapping'.
src\Clients\Visuals\visuals\sampleVisual.ts(79,17): error TS2322: Type '{ dataRoles: ({ name: string; kind: VisualDataRoleKind; } | { displayName: string; name: string; ...' is not assignable to type 'VisualCapabilities'.
  Types of property 'dataViewMappings' are incompatible.
    Type '{ categories: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }; values: { select: ...' is not assignable to type 'DataViewMapping[]'.
      Type '{ categories: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }; values: { select: ...' is not assignable to type 'DataViewMapping'.
        Object literal may only specify known properties, and 'categories' does not exist in type 'DataViewMapping'.
src\Clients\Visuals\visuals\samples\asterPlot.ts(52,17): error TS2322: Type '{ dataRoles: { name: string; kind: VisualDataRoleKind; }[]; dataViewMappings: { categories: { for...' is not assignable to type 'VisualCapabilities'.
  Types of property 'dataViewMappings' are incompatible.
    Type '{ categories: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }; values: { select: ...' is not assignable to type 'DataViewMapping[]'.
      Type '{ categories: { for: { in: string; }; dataReductionAlgorithm: { top: {}; }; }; values: { select: ...' is not assignable to type 'DataViewMapping'.
        Object literal may only specify known properties, and 'categories' does not exist in type 'DataViewMapping'.
src\Clients\Visuals\visuals\table.ts(567,17): error TS2322: Type '{ interactive: boolean; enableTouchSupport: boolean; layoutKind: TablixLayoutKind; }' is not assignable to type 'TablixOptions'.
  Object literal may only specify known properties, and 'layoutKind' does not exist in type 'TablixOptions'.
[15:45:10] Finished 'build:visuals_sprite' after 518 ms
[15:45:10] Starting 'build:visuals_less'...
[15:45:10] Finished 'build:visuals_less' after 165 ms
[15:45:10] Finished 'build:visuals' after 3.2 s
[15:45:10] Starting 'combine:internal_js'...
[15:45:12] Finished 'combine:internal_js' after 1.74 s
[15:45:12] Starting 'combine:external_js'...
[15:45:12] Finished 'combine:external_js' after 154 ms
[15:45:12] Starting 'build:visuals_playground'...
[15:45:12] Starting 'build:visuals_playground_project'...
src\Clients\PowerBIVisualsPlayground\app.ts(36,56): error TS2305: Module 'powerbi.visuals' has no exported member 'defaultVisualHostServices'.
src\Clients\PowerBIVisualsPlayground\app.ts(36,56): error TS2339: Property 'defaultVisualHostServices' does not exist on type 'typeof visuals'.
[15:45:13] TypeScript: 21 semantic errors
src\Clients\PowerBIVisualsPlayground\app.ts(46,39): error TS2304: Cannot find name 'IVisualPluginService'.
src\Clients\PowerBIVisualsPlayground\app.ts(46,82): error TS2339: Property 'visualPluginFactory' does not exist on type 'typeof visuals'.
[15:45:13] TypeScript: emit failed
src\Clients\PowerBIVisualsPlayground\app.ts(47,39): error TS2304: Cannot find name 'IVisual'.
src\Clients\PowerBIVisualsPlayground\app.ts(54,37): error TS2304: Cannot find name 'IVisualStyle'.
[15:45:13] Finished 'build:visuals_playground_project' after 548 ms
src\Clients\PowerBIVisualsPlayground\app.ts(62,49): error TS2339: Property 'DataColorPalette' does not exist on type 'typeof visuals'.
src\Clients\PowerBIVisualsPlayground\app.ts(81,29): error TS2339: Property 'DefaultVisualHostServices' does not exist on type 'typeof visuals'.
[15:45:13] Starting 'copy:internal_dependencies_visuals_playground'...
src\Clients\PowerBIVisualsPlayground\app.ts(83,45): error TS2304: Cannot find name 'IVisualPlugin'.
src\Clients\PowerBIVisualsPlayground\app.ts(110,69): error TS2304: Cannot find name 'IVisualPlugin'.
[15:45:13] Finished 'copy:internal_dependencies_visuals_playground' after 1.07 ms
src\Clients\PowerBIVisualsPlayground\hostControls.ts(39,32): error TS2304: Cannot find name 'IVisual'.
src\Clients\PowerBIVisualsPlayground\hostControls.ts(50,27): error TS2304: Cannot find name 'IViewport'.
[15:45:13] Finished 'build:visuals_playground' after 549 ms
src\Clients\PowerBIVisualsPlayground\hostControls.ts(88,41): error TS2304: Cannot find name 'IVisual'.
src\Clients\PowerBIVisualsPlayground\hostControls.ts(92,32): error TS2304: Cannot find name 'IViewport'.
[15:45:13] Finished 'build:projects' after 9.27 s
src\Clients\PowerBIVisualsPlayground\hostControls.ts(111,31): error TS2304: Cannot find name 'IViewport'.
src\Clients\PowerBIVisualsPlayground\sampleDataViews\FileStorageData.ts(50,89): error TS2322: Type '{ columns: { displayName: string; queryName: string; isMeasure: boolean; properties: { "Y": boole...' is not assignable to type 'DataViewMetadata'.
  Types of property 'columns' are incompatible.
    Type '{ displayName: string; queryName: string; isMeasure: boolean; properties: { "Y": boolean; }; type...' is not assignable to type 'DataViewMetadataColumn[]'.
      Type '{ displayName: string; queryName: string; isMeasure: boolean; properties: { "Y": boolean; }; type...' is not assignable to type 'DataViewMetadataColumn'.
        Object literal may only specify known properties, and 'properties' does not exist in type 'DataViewMetadataColumn'.
[15:45:13] Starting 'start:watchers'...
src\Clients\PowerBIVisualsPlayground\sampleDataViews\RichtextData.ts(62,29): error TS2304: Cannot find name 'ParagraphContext'.
src\Clients\PowerBIVisualsPlayground\sampleDataViews\RichtextData.ts(75,69): error TS2305: Module 'powerbi.visuals' has no exported member 'ParagraphContext'.
[15:45:13]   Continuous build successfully started
src\Clients\PowerBIVisualsPlayground\sampleDataViews\SimpleGaugeData.ts(69,17): error TS2322: Type '{ columns: ({ displayName: string; roles: { [x: string]: boolean; 'MinValue': boolean; }; isMeasu...' is not assignable to type 'DataViewMetadata'.
  Object literal may only specify known properties, and 'groups' does not exist in type 'DataViewMetadata'.
[15:45:13]   Waiting for changes...
src\Clients\PowerBIVisualsPlayground\sampleDataViews\SimpleMatrixData.ts(58,33): error TS2322: Type '{ rows: { root: { children: { level: number; value: string; children: { level: number; value: str...' is not assignable to type 'DataViewMatrix'.
  Types of property 'rows' are incompatible.
    Type '{ root: { children: { level: number; value: string; children: { level: number; value: string; chi...' is not assignable to type 'DataViewHierarchy'.
      Types of property 'root' are incompatible.
        Type '{ children: { level: number; value: string; children: { level: number; value: string; children: {...' is not assignable to type 'DataViewMatrixNode'.
          Types of property 'children' are incompatible.
            Type '{ level: number; value: string; children: { level: number; value: string; children: { level: numb...' is not assignable to type 'DataViewTreeNode[]'.
              Type '{ level: number; value: string; children: { level: number; value: string; children: { level: numb...' is not assignable to type 'DataViewTreeNode'.
                Object literal may only specify known properties, and 'level' does not exist in type 'DataViewTreeNode'.
src\Clients\PowerBIVisualsPlayground\typedefs\typedefs.obj.ts(29,1): error TS6053: File 'C:/source/PowerBI-visuals/src/Clients/Visuals/obj/Visuals.d.ts' not found.

**Comment by ebunt** [comment]
1. cd into your PowerBI-visuals directory
2. run this git rev-parse HEAD                                                                           
3. should return this: *5a2bf5fd5f605a17661ed66ab4be337a726f4166*
4. run this: *gulp build:run:playground*
Are you still getting errors?

**Comment by jakewava** [comment]
Yes, got the playground to run locally.  Instead of running gulp from command prompt, I found the build:run:playground task in taskrunner and executed it in VS2015.

**Comment by spatney** [comment]
Awesome. closing this thread, since it appears your issue has been resolved.
