### ISSUE TITLE
I got an error trying to run the visuals example

### ISSUE THREAD

**Issue by GarySy** [Microsoft/PowerBI-visuals#94]
I followed the instructions up to running the example from Visual Studio. On running, I get the error:
Unhandled exception at line 53, column 13 in http://localhost:52242/src/Clients/PowerBIVisualsPlayground/index.html

0x800a1391 - JavaScript runtime error: 'powerbi' is undefined

**Comment by uve** [comment]
It seems that necessary powerbi-visuals.js file was not generated. Please try to run:
>npm install
>gulp build:run:playground

and copy output here if it won't work.

**Comment by GarySy** [comment]
It looks like the npm install worked, but there is a problem with the gulp
install:



C:\Users\v-gasyck\Documents\Power BI\visuals>npm install
> powerbi-visuals@0.2.1 preinstall C:\Users\v-gasyck\Documents\Power
BI\visuals
> npm install -g gulp
C:\Users\v-gasyck\AppData\Roaming\npm\gulp ->
C:\Users\v-gasyck\AppData\Roaming\
npm\node_modules\gulp\bin\gulp.js
gulp@3.9.0 C:\Users\v-gasyck\AppData\Roaming\npm\node_modules\gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0,
ansi-styles@2
.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0,
end-of-stream@0.
1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1,
resolve@1
.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0,
lodash.
_reescape@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0,
lodash._reinterp
olate@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, lodash.template@3.6.2,
through2@2.0
.0, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2,
vinyl@0
.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
C:\Users\v-gasyck\Documents\Power BI\visuals>gulp build:run:playground
[10:15:06] Local gulp not found in ~\Documents\Power BI\visuals
[10:15:06] Try running: npm install gulp
C:\Users\v-gasyck\Documents\Power BI\visuals>

**Comment by GarySy** [comment]
I tried the recommended install for gulp, then re-ran the build. Here is
the result:

C:\Users\v-gasyck\Documents\Power BI\visuals>gulp build:run:playground
module.js:338
    throw err;
    ^
Error: Cannot find module 'merge2'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\v-gasyck\Documents\Power
BI\visuals\gulpfile
.js:28:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
C:\Users\v-gasyck\Documents\Power BI\visuals>

**Comment by uve** [comment]
when you run *npm install*, it installs all dependencies from package.json
https://github.com/Microsoft/PowerBI-visuals/blob/master/package.json#L26
or you can install this module manually: 
>npm install merge2

**Comment by GarySy** [comment]
I copied the package.json to my directory. There were many differences
between what I got from git the other day and the file you pointed to. I
re-ran the npm install and then the build. Still no joy. Here is the result:

C:\Users\v-gasyck\Documents\Power BI\visuals>gulp build:run:playground
[11:01:42] Using gulpfile ~\Documents\Power BI\visuals\gulpfile.js
[11:01:42] Task 'build:run:playground' is not in your gulpfile
[11:01:42] Please check the documentation for proper gulpfile formatting
C:\Users\v-gasyck\Documents\Power BI\visuals>

**Comment by uve** [comment]
>[11:01:42] Task 'build:run:playground' is not in your gulpfile

It means that your source code is outdated.
Please try to pull the latest sources and launch task again.

**Comment by GarySy** [comment]
Thanks, that worked

**Comment by uve** [comment]
Great!
