### ISSUE TITLE
Cannot contact to visual server

### ISSUE THREAD

**Issue by gerdinve** [Microsoft/PowerBI-visuals#94]
I installed all prerequisites as the documentation describes me to get started with Power BI custom visuals. After that, I restarted my pc.

- successfully made a new visual project in C:/test by pbiviz new test
- started succesfully pbiviz by entering 'pbiviz start' using cmd in the root of the new made visual project. It returned:
info Building visual
done Building complete
info starting server
info Server listening on port 8080

Then I go to https://powerbi.microsoft.com/en-us/, go to my report, add the developer visual and still I get the warning 'Can't contact visual server ....' 

Please help me.

**Comment by gerdinve** [comment]
Update. It is working in Internet Explorer 11, but above error arises in Firefox

**Comment by raananzvi** [comment]
This is great you got it working.
Silly question, did you try to close firefox and open it again? Maybe firefox was opened when you installed the cert and it require to restart before it can accept this new certificate?

**Comment by demetrioi** [comment]
Hi,

Install certificates on machine https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/CertificateSetup.md
