### ISSUE TITLE
Static and Data Bound properties do not work with Table data mapping

### ISSUE THREAD

**Issue by DdanB** [microsoft/PowerBI-visuals#95]
Whilst we know the properties do not work within the debug visual in pbi service, they do not also work within power bi desktop for table data mappings.  When all of the data is bound the visual renders but never refreshes the properties box to show the new values.

**Comment by raananzvi** [comment]
Hi,

Can you please elaborate more about your issue. Maybe send screenshots or even your code so I will be able to debug it.

Thanks

**Comment by soodik323** [comment]
I have same issue.

I am using Table and
public enumerateObjectInstances(options: EnumerateVisualObjectInstancesOptions): VisualObjectInstanceEnumeration function is never executed

**Comment by dmitriysolovev** [comment]
I still have the same issue. Any chance to get response from MS?

**Comment by uve** [comment]
Please update to the latest API 3.2.0
