### ISSUE TITLE
Error when running playground

### ISSUE THREAD

**Issue by ebunt** [Microsoft/PowerBI-visuals#95]
I pulled the latest from the repo and did the following:

1. npm install
2. gulp build:run:playground

I consistently get this error in the console:  

*TypeError: a is not a constructor
...ainer=$("#container"),this.hostControls=new a($("#options")),this.hostControls.s...*

or this error

*Uncaught TypeError: HostControls is not a function*

I am building this on a Mac.  When I build this on Windows it works fine.

**Comment by uve** [comment]
It was fixed in this commit https://github.com/Microsoft/PowerBI-visuals/commit/15726a02d40c116da610dd92790f970a65b9272a
Please pull the latest sources or just rename file HostControls.ts to hostControls.ts 
and run again:
>gulp build:run:playground

**Comment by ebunt** [comment]
Thanks, I appreciate it. I figured it out last night.

**Comment by uve** [comment]
Great!
