### ISSUE TITLE
Drill down Issue

### ISSUE THREAD

**Issue by sudhachandrada** [Microsoft/PowerBI-visuals#96]
I'm getting the following error while adding drill down to the capabilities.json. 
**instance additionalProperty "drilldown" exists in instance when not allowed**.

My capabilities.json is as follows:

{
    "dataRoles": [
        {
            "displayName": "Category Data",
            "name": "category",
            "kind": 0
        },        
        {
            "displayName": "Measure",
            "name": "measure",
            "kind": 1
        }
        ,        
        {
            "displayName": "Measure",
            "name": "measure",
            "kind": 1
        }
    ],
    "dataViewMappings": [
        {
            "conditions": [
                {
                    "category": {
                        "max": 2
                    },
                    "measure": {
                        "max": 2,
                        "min": 1
                    }
                }
            ],
            "categorical": {
                "categories": {
                    "for": {
                        "in": "category"
                    },
                    "dataReductionAlgorithm": {
                        "top": {}
                    }
                },
                "values": {
                    "select": [
                        {
                            "bind": {
                                "to": "measure"
                            }
                        }
                    ]
                }
            }
        }
    ],
     "drilldown":{"roles":["category"]},
    "objects": {
        "general": {
            "displayName": "Enable Axis",
            "properties": {
                "show": {
                    "displayName": "Enable Axis",
                    "type": { "bool": true }
                }
            }
        },
        "colorSelector": {
            "displayName": "Data Colors",
            "properties": {
                "fill": {
                    "displayName": "Line 1",
                    "type": {
                        "fill": {
                            "solid": {
                                "color": true
                            }
                        }
                    }
                },
                "fill2": {
                    "displayName": "Line 2",
                    "type": {
                        "fill": {
                            "solid": {
                                "color": true
                            }
                        }
                    }
                },
                "line1dotcolor": {
                    "displayName": "line1 dotcolor",
                    "type": {
                        "fill": {
                            "solid": {
                                "color": true
                            }
                        }
                    }
                },
                "line2dotcolor": {
                    "displayName": "line2 dotcolor",
                    "type": {
                        "fill": {
                            "solid": {
                                "color": true
                            }
                        }
                    }
                }
            }
        }
    },
   
    
}

please help me to find where i'm getting it wrong .

Thanks,
Sudha

**Comment by raananzvi** [comment]
Please update the powerbi-visuals-tools to the new 1.2.0 version and this should get solved.
