### ISSUE TITLE
Trouble creating a new visualization

### ISSUE THREAD

**Issue by GarySy** [Microsoft/PowerBI-visuals#96]
What I did -
created a new file under src\Clients\Visuals\visuals\samples
Added code similar to helloIVisuals.ts
Added code to plugins.ts:

    export var landingIVisual: IVisualPlugin = {
        name: 'landingIVisual',
        capabilities: samples.LandingIVisual.capabilities,
        create: () => new samples.LandingIVisual()
    };

rebuilt the solution
ran in VS

An exception occurred in powerbi-visuals.js at this line:
            plugins.landingIVisual = {
                name: 'landingIVisual',
                capabilities: visuals.samples.LandingIVisual.capabilities,
                create: function () { return new visuals.samples.LandingIVisual(); }
            };
 
Examining visuals.samples shows that my new visualization is not in the methods array.

The declaration for my visualization is in powerbi-visuals.js, but it is later in the file. I suspect that I need to tell whatever builds powerbi-visuals.js to include my stuff sooner.

**Comment by spatney** [comment]
is your visual file declared before plugins.ts in _references.ts ?

**Comment by GarySy** [comment]
That fixed it.
Thanks.
