### ISSUE TITLE
External library

### ISSUE THREAD

**Issue by AntMassip** [microsoft/PowerBI-visuals#99]
Hello,

I would like to add an external library ( from [http://visjs.org/index.html#download_install](http://visjs.org/index.html#download_install) ) so i followed the tutorial : create new external folder, add the js file inside and update the tsconfig.json.

In visual.ts I declare a global variable, because there is no d.ts file in the library, with this line :
`declare var vis: any;`

Then I want to call a function : 

```
var items = new vis.DataSet([
                { id: 1, content: 'item 1', start: '2014-04-20' },
                { id: 2, content: 'item 2', start: '2014-04-14' },
                { id: 3, content: 'item 3', start: '2014-04-18' },
                { id: 5, content: 'item 5', start: '2014-04-25' }
            ]);
```
But if I go to the internet explorer's console i can see an error : 

> Permission denied

So what's wrong ?

**Comment by mmaitre314** [comment]
I also cannot get vis.js to work in custom visuals. I started defining types in a `vis.d.ts` file which seems to avoid the permission denied mentioned above:

```
declare namespace vis {
    export class DataSet {
        constructor(data: any);
    }
    export class Network {
        constructor(container: HTMLElement, data: any, options: any);
    }
}
```

When I call `new vis.DataSet()` in the visual, `vis` is undefined though. The problem seems to be that Power BI mucks with the `window` object so when vis.js tries to attach itself to it (`root` object below), it ends up in an object that is not available within the custom visual.

```
(function(powerbi) {
    var window = this;

    //These 2 lines are needed to trick lodash into using this as global scope
    var self = this;
    self.Object = Object;

    //de-reference powerbi loaded modules
    var $, jQuery, _;
    window.jQuery = window.$ = undefined;
    window._ = undefined;

(function webpackUniversalModuleDefinition(root, factory) {
    debugger;
    if (typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if (typeof define === 'function' && define.amd)
        define([], factory);
    else if (typeof exports === 'object')
        exports["vis"] = factory();
    else
        root["vis"] = factory();
})(this, function () {
```

**Comment by AntMassip** [comment]
Even with a ` vis.d.ts` file I have the same error, on the file `ReportSection`

```
var powerbi = {
        session : {
            userInfo: {
                name:  '',
                givenName: '',
                surname: '',
                puid: '',
                uoid: '',
                alternateEmail: ''
            }
        }
    };
```

It seems I have not the right but I don't know why..

**Comment by AntMassip** [comment]
The solution : 

[Power Bi community](http://community.powerbi.com/t5/Developer/External-libray-permission-refused/m-p/90304#U90304)

You let the vis.js without modification and you add the code that you find in the link :

```
private window: any;
 constructor(options: VisualConstructorOptions) {
this.window = window;
var items = new this.window.vis.DataSet([
```

**Comment by mmaitre314** [comment]
Thanks! Amazingly, that did the trick. I am still not hitting your access-denied problem. I haven't tried packaging the visual yet though, and I have an issue with Edge where the graph does not show up.

**Comment by knom** [comment]
THIS is big! Please solve this OR at least put it prominently into the DOCS!!
I struggled because of this issue for hours!

**Comment by helen508light** [comment]
outdated
